### ISSUE TITLE
Create a 404 page for invalid URLs

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1000]
Please create a 404 page for invalid URLs.

The page must centre align the FightPandemics logo.
The page must contain the link to redirect to Homepage and support email.
This must work on mobile and web both for all the invalid URLs

**Comment by nr431207** [comment]
@ppagarawal is there a specific design for this?

**Comment by ppagarawal** [comment]
There is but in Figma. Unfortunately, my laptop is in trouble now. @vikjoshi @Yu-Alexa-Zhao can either of you please help here?

**Comment by OzkanAbdullahoglu** [comment]
Hi @ppagarawal, I couldn't find any design in Figma which is related to 404 page.  Maybe It is updating?

**Comment by ppagarawal** [comment]
Thanks for raising this @OzkanAbdullahoglu Let me check this with @Yu-Alexa-Zhao and get back.

**Comment by nadinejuraschek** [comment]
Any news on the design? @ppagarawal

**Comment by yu-zhao-xyz** [comment]
Yes we have an updated design. Let me export to Zeplin in about an hour? Sorry about the delay.

**Comment by yu-zhao-xyz** [comment]
Hi @nadinejuraschek , the desktop version of 404 page is here: https://zpl.io/bJJMeDK, the mobile version is here: https://zpl.io/bJJMeDK
