### ISSUE TITLE
blank page error undefined error - getInitialsFromFullName edge case with multiple spaces

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1012]
@idjevm there must be some edge case bug introduced from #1005. I'm having a hard time pinpointing it can only recreate in staging.

When you scroll to what is currently `api/posts?limit=5&skip=15` for unathenticated (no geo sort) I get undefined error (blank page) that debugger indicates comes from `.map((n) => n[0].toUpperCase())` in:

It's from "Nivethetha  Sankar " specifically - there are 2 spaces between Nivethetha  & Sankar, so the map function tries to do something like `""[0]` which throws the error

`split(/\s+/)` instead of `split(" ")` might work but there are other options

**Comment by idjevm** [comment]
Makes total sense! Thank you so much! I def did not test that one out. And yeah I thought of using a regex instead lol~ making a fix asap~ Thank you
