### ISSUE TITLE
Feed-> Add comment -> Login-In -> Lost track of the FEED on which user wanted to comment

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1017]
1. Open "https://staging.fightpandemics.work/"
2. Click on Request help -> Medical -> Share my location -> Enter email -> Click on Submit
3. From the FEEDs displayed, user select specific feed as per his/her requirement
4. On the selected Post click on 'Comment' icon

You will observe that user is directed to LOGIN screen.
5. Login using valid email/pwd

Issue#: User land on FP home page rather than the Post/Feed, he wanted to comment on. So the user completely lost the FEED on which he was about to comment before Login.

Ideally, user should land on previous selected FEED.

Refer below GIF.

https://share.getcloudapp.com/jkuQAOdD

**Comment by pthoma14** [comment]
@rabbi08 thank you for catching and logging this issue. 

@ppagarawal I believe this issue should be tagged for MVP launch instead of Soft Launch. Thoughts?

**Comment by ppagarawal** [comment]
@pthoma14 You're correct 
@rabbi08 This is a good bug. 👍 

@silenceway @idjevm Can either of you help with it? What do you think about the timelines?

**Comment by silenceway** [comment]
This can be reviewed with the like button, too: Like -> Login -> Home (not feed). But it depends in https://github.com/FightPandemics/FightPandemics/pull/834 merge.
The like button saves to storage to allow the like after the login, it can be applied something like this to comment.
But I cannot work on this issue now. If nobody can, I will do it at the weekend. (I can review the PR if somebody did it).
