### ISSUE TITLE
EDIT my POST -> Click on Back button -> Lands on FEEDs page, rather than previously navigated page.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1018]
1. Open "https://staging.fightpandemics.work/"
2. Login using valid email/pwd
3. Navigate Profile -> My Profile
4. EDIT any comment  and after "EDIT or comment" on any Post, click on 'BACK' button

Issue: You will observe that user lands on 'FEED' home page rather that 'My Profile' page from where I navigated.

So actually, BACK button should navigate to the previous page that user navigated, i.e. preserving the history of the user, to user "BACK" button feature.

Refer attached GIF
https://share.getcloudapp.com/X6uoK5NY

**Comment by rabbi08** [comment]
@BMariscal @idjevm 
while validating this issue, it is not working in STG, hence reopening.
PR# 1067
https://share.getcloudapp.com/NQugBgWx

**Comment by BMariscal** [comment]
@rabbi08  it is working on staging when tested in Firefox but not on Chrome. Interesting. Can you check if it's working for you on Firefox?

**Comment by rabbi08** [comment]
@BMariscal 
I tested in FF, and its not working in FF too including chrome & safari

Please refer below GIF from FF:
https://share.getcloudapp.com/GGuodppd

**Comment by BMariscal** [comment]
thanks @rabbi08  

I'll use the Window.history object instead since it seems document.referrer doesn't always work.

Thanks for letting me know!

**Comment by rabbi08** [comment]
@BMariscal 
This issue have been observed again in STG. Hence reopening this same issue, let me know if I should log new one or we should track from here.

Add Post -> https://share.getcloudapp.com/xQuL97BZ
EDIT post -> https://share.getcloudapp.com/kpubyDpP

When user click on 'Back' button, user should be re-directed to previous page visited before.

**Comment by rabbi08** [comment]
Closing this issue and opening new one #1398
