### ISSUE TITLE
Add underline to Privacy Policy and Terms&Conditions to show that it is a clickable link

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#1020]
Lets add an underline to the Privacy Policy and Terms & Conditions links on the sign up ages for Create User Profile and Create organization profile. We should only underline the highlighted parts from the image below

![image](https://user-images.githubusercontent.com/41554004/86546366-5e7b0780-bee9-11ea-9d33-02526f28fc50.png)

**Comment by morrme** [comment]
@vikjoshi I'd like to help Should this be done on the component or inline?

**Comment by Sridevi2014** [comment]
@vikjoshi I am working on this task

**Comment by Sridevi2014** [comment]
added an underline to the Privacy Policy and Terms & Conditions links on the sign up ages for Create User Profile and Create organization profile.

I didn't create pull request. I will talk with JV then I will create pull request.

Just I have attached screen shots
![screencapture-localhost-3000-create-organization-profile-1594020762938](https://user-images.githubusercontent.com/28641604/86568112-fef51a00-bf31-11ea-8349-36e3e81746aa.png)


![screencapture-localhost-3000-create-profile-1594020883532](https://user-images.githubusercontent.com/28641604/86568118-0288a100-bf32-11ea-8047-e87125ad50bd.png)

**Comment by idjevm** [comment]
👀 Seems good however, I wam wondering why does the left side show like that 👀

**Comment by vikjoshi** [comment]
@Sridevi2014 @idjevm , this looks great across both profile types and mobile web and desktop. Thank you!
