### ISSUE TITLE
[Mobile iOS] Feed | Like functionality doesn't work.

### ISSUE THREAD

**Issue by gkjain82** [FightPandemics/FightPandemics#1029]
Steps to Reproduce:

Goto: staging.fightpandemics.work
Log in as an authorized user
Click on the Hamburger icon and select "Feed " 
Select like button for any post.
The like functionality button doesn't work.

Expected Result:
The user should be able to like any post successfully.

Actual Result:
The user is not able to like any post.
![Video 07-06-2020 11 47](https://user-images.githubusercontent.com/62069057/86614785-84ec8180-bf81-11ea-8a63-7f721839d099.gif)

**Comment by joshmorel** [comment]
Yeah this is a WIP - I think this affects all platforms... #834 . I think it's almost done @silenceway ?

**Comment by silenceway** [comment]
@joshmorel  That PR is waiting for review and merge some days ago.

**Comment by doheekim93** [comment]
@silenceway I'm closing this ticket since the PR has been merged! Please reopen it if the issue hasn't been solved. Thanks!
