### ISSUE TITLE
Feed - When adding a post the box "Organization' is spelled "Organisation" with s. *** We need to update with S everywhere on Mobile****

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#1035]
When adding a post on Feed, the box "Organization' is spelled "Organisation" with s.

Steps to Reproduce:

Pre-Requisite: Be signed in

1 - Click on the 3 lines on the top right of the page
2 - Click on Feed
3 - Click on Plus icon

Current Result: Organisation 
Expected: Organization (as per Figma)

![image](https://user-images.githubusercontent.com/67716598/86623851-1acedf00-bf77-11ea-84c0-df379c3b2651.png)

**Comment by BMariscal** [comment]
Hello @dabartlett We are using British English in the app so `Organisation ` is correct.

**Comment by dabartlett** [comment]
Hi @BMariscal, on that case we would need to change it in other locations such as below to be the same:
![image](https://user-images.githubusercontent.com/67716598/86627082-8d8e8900-bf7c-11ea-9250-2b6fcc8757a4.png)

**Comment by BMariscal** [comment]
https://fightpandemics.slack.com/archives/C010P7A17V3/p1591063767149200?thread_ts=1591062823.148900&cid=C010P7A17V3

**Comment by BMariscal** [comment]
> Hi @BMariscal, on that case we would need to change it in other locations such as below to be the same:
> ![image](https://user-images.githubusercontent.com/67716598/86627082-8d8e8900-bf7c-11ea-9250-2b6fcc8757a4.png)

Yes! correct

**Comment by manualzuru** [comment]
@dabartlett, @BMariscal is right. We are using British English and it should be with S everywhere.

@Yu-Alexa-Zhao can you please create a design ticket so we update all our designs with "S"?

**Comment by dabartlett** [comment]
Examples - this is from "Create Organisation": https://staging.fightpandemics.work/create-organization-profile

![image](https://user-images.githubusercontent.com/67716598/86811243-8924a780-c032-11ea-9e7b-6f5fa8cac95a.png)
