### ISSUE TITLE
Organization Profile linkedin not saving

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1039]
Organization LinkedIn not being sent to B/E on Organization Profile form:

![image](https://user-images.githubusercontent.com/10546720/86630307-a73ec900-bf9a-11ea-8c5f-23d7cfcf436d.png)
 
Maybe has to do with?
`Warning: [antd: Checkbox] `value` is not a valid prop, do you mean `checked`?`

**Comment by nr431207** [comment]
@joshmorel @idjevm  the `formData` thats being sent to the backend does have the correct data in it, and the request body on the server side also receives the correct data, I traced it a bit deeper and it looks like upon get request of server from db, the result doesnt even have the key `linkedin` in the urls object, isnt it supposed to at least have the key `linkedin: ' '` when it is empty?

**Comment by joshmorel** [comment]
I'm wondering if it has to something to do with key name case in F/E config vs everywhere else?. linkedin vs linkedIn  w capital I

**Comment by nr431207** [comment]
> I'm wondering if it has to something to do with key name case in F/E config vs everywhere else?. linkedin vs linkedIn w capital I
aah that was it! thank you so much! took me hours to trace and check everything lol

**Comment by idjevm** [comment]
Yeah lol looks like the schema on the backend expects `linkedin` and not `linkedIn`. Good catch haha
