### ISSUE TITLE
Edit Profile: Add a "username" placeholder for social media URLs

### ISSUE THREAD

**Issue by hellynyc** [FightPandemics/FightPandemics#1057]
Adding a grayed out "username" placeholder for social media URLs could help users understand how to edit the fields better.

![Screenshot_20200707-023450](https://user-images.githubusercontent.com/52841932/86736679-b6a52d00-c001-11ea-8853-d68a135fcb21.jpg)

**Comment by emtay** [comment]
Closing issue as this as we're actually going to remove the social media URLs with another issue.

@tejasm2 an idea from this story for your story is that there can be a greyed out URL instead of a hard URL so that people pasting in the link from Facebook and LInkedIn can overwrite it.
