### ISSUE TITLE
[Mobile Android] Profile | Website icon (for personal website) is missing 

### ISSUE THREAD

**Issue by hellynyc** [FightPandemics/FightPandemics#1058]
Device/OS/Browser: OnePlus 7 Pro / OS10 / Chrome

Steps to Reproduce:
1. Log in as a user on [staging.fightpandemics.work](staging.fightpandemics.work)
2. Go to Profile page
3. Click on edit, and fill out Personal Website field, and click "Save Changes"

Expected Result: User returns to Profile page and sees website icon for personal website

Actual Result: User sees a smiley face for personal website

![Screenshot_20200707-021328](https://user-images.githubusercontent.com/52841932/86739525-f1a86000-c003-11ea-95aa-ea62b085ec7a.jpg)

**Comment by idjevm** [comment]
This is a duplicate from #1043 and has been resolved already. Please check on staging (make sure you are in incognito/private or clean your cache and cookies).
