### ISSUE TITLE
[Mobile] About us | missing sponsor logos

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1060]
env: staging

**Seen on Chrome v.81**

Steps:
1. Open About us page
2. Go to the Our supporters sections. Logos are missing:
![Screenshot_2020-07-07-20-35-32-461_com android chrome](https://user-images.githubusercontent.com/21987083/86827164-f3b90000-c091-11ea-9b89-6f0d174c2f11.jpg)

**Comment by idjevm** [comment]
@galeza I think it is not that they are missing, but that they have not loaded yet. Can you please re test, and maybe wait for a bit? I think we have to find a solution to reduce the size of this page as it is quite heavy with all the pics and logos.

**Comment by rabbi08** [comment]
@ppagarawal @galeza 
Unable to reproduce the issue on iPhone n andriod devices:

![image](https://user-images.githubusercontent.com/67168400/86828980-e421c300-c061-11ea-8742-af7a2ac67558.png)

**Comment by galeza** [comment]
Hi @idjevm 
I refresh a page but still nothing.
I have an impression that they are loaded.
I'm using chrome://inspect/#devices and remote debugging:


![icons](https://user-images.githubusercontent.com/21987083/86834431-1dc2f000-c09b-11ea-8f58-90fb293b612d.gif)

**Comment by idjevm** [comment]
It might be an issue with this environment, @rabbi08, @sheeba1, @galeza, @hellynyc, @nivetheatha can you all go to https://staging.fightpandemics.work/about-us from your phones please? I think this is only on this environment.

**Comment by hellynyc** [comment]
@idjevm The sponsor logos load fine in staging on my androids (OnePlus 7 Pro & Google Pixel), both running OS10.

**Comment by galeza** [comment]
@idjevm 
No it's not environment. When I use my tablet samsung galaxy tab I see all icons.

**Comment by galeza** [comment]
![Screenshot_20200707-231448](https://user-images.githubusercontent.com/21987083/86844119-dabb4980-c0a7-11ea-8960-8484262382ba.png)

**Comment by idjevm** [comment]
Looks like this works fine in all devices @galeza, I think it is an issue only from this emulator or the tool you are using to test. Let's wait for @sheeba1, @nivetheatha, @rabbi08  to test out on their devices, and then we should decide whether to explore or just close this issue.

**Comment by galeza** [comment]
@idjevm 
No, I test on a device.
It is a problem with a chrome browser. With 81 icons are not visible. I upgraded to version 83 and it works

**Comment by galeza** [comment]
![Screenshot_2020-07-07-23-28-50-698_com android chrome](https://user-images.githubusercontent.com/21987083/86845383-b6f90300-c0a9-11ea-884b-e3cb6f1d9b63.jpg)
![Screenshot_2020-07-07-23-28-43-994_com google android gms](https://user-images.githubusercontent.com/21987083/86845386-b7919980-c0a9-11ea-8ce2-5cd10ea14973.jpg)

**Comment by idjevm** [comment]
True! OMFG great catch! Just tested on my reg browser on my phone and they didn't load :O I will have to check why is that though !

**Comment by nivetheatha** [comment]
@idjevm I can able to see the logos.Mine is Samsung Galaxy 
![Screenshot_20200707-182409_Chrome](https://user-images.githubusercontent.com/41587211/86850467-5228b300-c07f-11ea-81b3-6591397b9df0.jpg)

**Comment by sheeba1** [comment]
@idjevm , working fine for me  iphone XR
![image](https://user-images.githubusercontent.com/65972693/86867122-1bef3180-c087-11ea-9718-4ea478f75b66.png)

**Comment by rabbi08** [comment]
Working fine on iPhone 10, 11, ZTE Blade Max(Andriod), Mac with Chrome (Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by galeza** [comment]
@rabbi08 
It was seen for Chrome v.81

**Comment by CamilaArias** [comment]
@galeza is this still an issue with the new version of the about us in prod?

**Comment by galeza** [comment]
@CamilaArias I'm closing this issue.
