### ISSUE TITLE
Not able to view the selected  post in feed by unsigned user [Mobile-Android]

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1074]
Steps to create:
-Go to Staging environment.
-Select Request help/Offer help.
-Select show me the posting from anywhere.
-Skip email id
-Select any post from the feed.
![Screenshot_20200708-114148_Chrome](https://user-images.githubusercontent.com/41587211/86941576-18ed5300-c112-11ea-9c6e-c160e97e956a.jpg)

**Comment by nivetheatha** [comment]
We can able to see the selected post from feed when we are logged in.

**Comment by nivetheatha** [comment]
Only old organization posts are not displaying. Other posts working fine.

**Comment by idjevm** [comment]
Yup this was affected by #1068. @BMariscal should we move the contents on the db from`organization` to `organisation`? or should we just have people create new orgs/posts?
