### ISSUE TITLE
Posts are not displayed after creation if the confirmation modal is closed

### ISSUE THREAD

**Issue by nr431207** [FightPandemics/FightPandemics#1085]
#### Steps to recreate:
1) go to Feed/Help Board or Profile page or Org page
2) create a post
3) close the modal instead of clicking the `view post`
4) the post is not in the list of posts
5) refresh the page
6) the post is now in the list

#### Expected behavior:
post should be visible when the user closes the modal

#### Current Behavior: 

![FightPandemics (2)](https://user-images.githubusercontent.com/37174253/86960033-c745c800-c113-11ea-991a-385bcddfe02e.gif)

**Comment by nr431207** [comment]
@ppagarawal FYI

**Comment by pooji02** [comment]
This issue also happens when after post creation -> go back to the profile who created the post-> under activity doesn't display the new post created , only after refreshing the post is visible in the activity feed. 
I believe this issue is a known one @idjevm

**Comment by nr431207** [comment]
@pooji02 yes thats correct, is basically happens anywhere the post gets created  👍
