### ISSUE TITLE
Send User ID to google tag manager (to use in analytics)

### ISSUE THREAD

**Issue by lelecanfora** [FightPandemics/FightPandemics#1088]
To enrich Google Analytics we'd like to send user IDs for logged in users, via google tag manager.

We're currently using this module for GTM: https://www.npmjs.com/package/react-gtm-module

Please add the userId (when available) to the data layer for GTM to ingest as described in the module example.

The end result is that we can retrieve the User ID from the data layer in GTM and send it to GA (or other scripts)

**Comment by idjevm** [comment]
Thanks for logging this issue @lelecanfora, but please add info and the right labels to it -> this might help -> https://github.com/FightPandemics/FightPandemics/wiki/How-to-%22Properly%22-create-a-ticket-%7C-new-issue-on-the-FightPandemics-repo

**Comment by lelecanfora** [comment]
> Thanks for logging this issue @lelecanfora, but please add info and the right labels to it -> this might help -> https://github.com/FightPandemics/FightPandemics/wiki/How-to-%22Properly%22-create-a-ticket-%7C-new-issue-on-the-FightPandemics-repo

Done, thanks

**Comment by doheekim93** [comment]
Hey @indirabhowmick, can we get this implemented for the soft launch?

**Comment by idjevm** [comment]
Hey @lelecanfora this has been completed. Please verify on staging! We set the `userId` on the dataLayer as follows. 
![image](https://user-images.githubusercontent.com/25408660/87614322-aa922d00-c6dd-11ea-94d4-f9339eb9529d.png)
