### ISSUE TITLE
Get AppStore & PlayStore icons/links working properly 

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1089]
@vikjoshi - we require a design for icons to complete this fully.

Once that is done we can update the icons here.

* [x] Also `appleStore` should be `appStore` in the form - it's not updating B/E otherwise. (this specific issue is resolved with #1099 )

![image](https://user-images.githubusercontent.com/10546720/86963064-ece1ca00-c131-11ea-99a1-2f014742c197.png)

Affects also post page - see #1038

**Comment by joshmorel** [comment]
@vikjoshi @manualzuru @Yu-Alexa-Zhao  Or maybe we should use official badges instead???

They wouldn't look good inline with other social icons but maybe on another line?

https://lh3.googleusercontent.com/cjsqrWQKJQp9RFO7-hJ9AfpKzbUb_Y84vXfjlP0iRHBvladwAfXih984olktDhPnFqyZ0nu9A5jvFwOEQPXzv7hr3ce3QVsLN8kQ2Ao=s0

https://developer.apple.com/app-store/marketing/guidelines/images/badge-example-preferred.png

**Comment by tejasm2** [comment]
As a user,  
When, I have entered the Google Playstore or Apple Playstore link in the organization profile info,  
Then I should see the Google Playstore icon or Apple Playstore icon on my Organization profile.
Google Playstore icon: https://zpl.io/beRoykP  
Apple Playstore icon: https://zpl.io/brwWGMD

@joshmorel @idjevm

**Comment by doheekim93** [comment]
Updated playstore icons can be found here: [https://zpl.io/brwWGMD](https://zpl.io/brwWGMD)
