### ISSUE TITLE
Unsigned user not able to view the long posts on the feed redirects to sign in page

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1102]
Steps to create:
1.Click on view help board.
2.If user wants to access the long post(so he has to click on view more).
3.It redirects to sign in page.
![Screenshot_20200709-120241_Chrome](https://user-images.githubusercontent.com/41587211/87093200-d2c7ea80-c20a-11ea-97ef-c379e0776b1e.jpg)
![Screenshot_20200709-120248_Chrome](https://user-images.githubusercontent.com/41587211/87093226-dc515280-c20a-11ea-8bb4-c474a99919d5.jpg)

**Comment by idjevm** [comment]
This is not an issue. This is an expected behaviour. They can have a preview of the post but they cannot interact, view completely, or comment on it without joining / signing in. @manualzuru can explain this better though 🙏

**Comment by nivetheatha** [comment]
@idjevm oh ok thanks for explaining.
