### ISSUE TITLE
My pofile|Create a Post|Like button doesnt work [Desktop]

### ISSUE THREAD

**Issue by natasoz27** [FightPandemics/FightPandemics#1104]
Environment:
OS X Yosemite/ Firefox
Steps to reproduce:
1. Navigate to sign in page
https://staging.fightpandemics.work/auth/login
2. Sign in
3. Navigate to your profile
4. Create a new individual post
5. Click on View you post
6. Click on like button
Expected result: 
Heart icon should change the color, and number of likes should change
Actual result: nothing changed 
![Screen Shot 2020-07-09 at 8 13 10 PM](https://user-images.githubusercontent.com/65917628/87103093-05311200-c222-11ea-91a2-21adedf8c1d1.png)

**Comment by idjevm** [comment]
This is a duplicate from #914. Please if you have any other thoughts, add them there. Also there is a PR already open #834  to try to resolve this issue.
