### ISSUE TITLE
[Mobile] The "+" icon on feed is very small in mobile version.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1107]
The "+" icon on the feed is very tiny in the mobile version.

![Create post icon small](https://user-images.githubusercontent.com/66698276/87121194-dfe2e900-c29f-11ea-951a-38e500974cc2.gif)

**Comment by nadinejuraschek** [comment]
I'll work on this once I get the .env variables. I currently can't see the feed :)
