### ISSUE TITLE
Help Board [Mobile - IOS] Location filter is not displaying address options to select after a zip code, Address or City is entered

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#1119]
Location filter is not displaying address options to select after a zip code, Address or City is entered

Steps to Reproduce:

1 - Using mobile Iphone 6s (works fine on developer tool), navigate to staging
2 - Request or Offer Help> select arrow to pass steps 1 2 and skip 3
3 - On Help Board click on location filter + icon
4 - Enter a zip code or address or City

Current Result: address options does not display to select and continue the process
Expected Result; address options should display

iphone 6s
![image](https://user-images.githubusercontent.com/67716598/87203012-9225ab00-c2b6-11ea-8b91-22c31ee52fa5.png)

Developer Tool:
![image](https://user-images.githubusercontent.com/67716598/87203079-bc776880-c2b6-11ea-9665-e3275b7445c7.png)

**Comment by joshmorel** [comment]
@dabartlett what browser are you using? If it works on dev tools but not your phone it might be a JS feature not supported by the browser.

**Comment by dabartlett** [comment]
Tested with iphone 6 after upgrading to version 13 and it works as well. thank you

![image](https://user-images.githubusercontent.com/67716598/87695719-b238ec80-c744-11ea-95c9-ea717d722ff2.png)
