### ISSUE TITLE
Organisation names with long names is displayed/extends beyond the space allocated  [DESKTOP] [MOBILE]

### ISSUE THREAD

**Issue by pooji02** [FightPandemics/FightPandemics#1120]
**Environment** : https://staging.fightpandemics.work/

**Steps to reproduce**
1. Create an organisation whose name is more than 25 characters

2. After successful creation of organisation profile -> go to org profile ->Click on Create a post - > click Organisation 
                                                            OR
Help Board - > Post Creation ->continue posting as : Organisation 

3.  Here it lists all the organizations so far created . 

**Actual Results:**
The name is displayed beyond the button layer. Affects both Desktop and Mobile.
**Expected Results:**
It's doesn't look visually appealing. The names when long should adjust accordingly within the button. Shouldn't overflow or there should be text limit to the organisation name.

**Screenshot 1  : DESKTOP** 

![image](https://user-images.githubusercontent.com/5065427/87201433-93fa6900-c2cc-11ea-8aa4-78c39b05a73c.png)

**Screenshot 2 : MOBILE** 

![image](https://user-images.githubusercontent.com/5065427/87201620-f7849680-c2cc-11ea-8db6-dbc6a5d9104c.png)

**Comment by nr431207** [comment]
@ppagarawal @idjevm do you guys know if there should be a count limit for org names?

**Comment by ppagarawal** [comment]
@vikjoshi Can you please help here?
