### ISSUE TITLE
FEEDBACK: Error message need to be specific when AGE field is NULL

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1125]
1. Open "https://staging.fightpandemics.work"
2. Click on EMAIL icon on homepage, to provide FEEDBACK
3. Provide Ratings -> Enter details in Feedback form -> Do NOT enter age or select anything 
4. Click on 'Submit FeedBACK' button

Issue: You will observe that error is displayed as :
Could not submit feedback, reason: body.age should be integer
<img width="1280" alt="Screen Shot 2020-07-11 at 12 50 03 PM" src="https://user-images.githubusercontent.com/67168400/87229586-29523780-c377-11ea-875c-b7bf672f1a9a.png">

Refer attached GIF.
https://share.getcloudapp.com/4gujG8nd

**Comment by rabbi08** [comment]
This issue is displayed on Mac but is not displayed on iPhone, hence it don't initialize the radio buttons present in the FEEDBACK pop up i.e. previously selected options, remains selected when user clicks on FEEDBACK option again.

**Comment by omarzoghayyer** [comment]
I didnt see the issue on mac/chrome.

**Comment by rabbi08** [comment]
@omarzoghayyer 
I too can't reproduce the error, but that's the reason that the previously selected radio button is selected by default the next time too. Will look into this little more and will update also, will close it in case

**Comment by sheeba1** [comment]
On Windows-chrome I was notable to reproduce this error. Also observed , once i click any radio button it remains selected , for my next feedback attempt.

**Comment by rabbi08** [comment]
@JamesonRudolph 
unable to reproduce currently, hence closing this one as 'Unable to reproducible'. Will log again If I got the same observation again.

Thanks.
