### ISSUE TITLE
FEEDBACK- The 'Thank you!' message needs to be more appropriate

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1126]
1. Open "https://staging.fightpandemics.work"
2. Click on EMAIL icon on homepage, to provide FEEDBACK
3. Provide Ratings -> Enter details in Feedback form -> enter valid age & select option
4. Click on 'Submit FeedBACK' button, 'Thank You!' message is displayed in the pop up.

Issue#: You will observe that the 'Thank You!' statement contains statement "help us help you and others'

Ideally, this feedback is for FP so it should be like "help us". It can be something like below:

Your input means a lot and helps us improve our services during and after the COVID-19 pandemic.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/67168400/87229660-ff4d4500-c377-11ea-9ecb-aff398141d94.png">

**Comment by rabbi08** [comment]
Also, as a suggestion the FP logo in 'Thank You!' pop up window should be clickable and lands on FP home page.

**Comment by pooji02** [comment]
As I am testing the feedback feature can you let me know what was the agreed final text to be displayed on clicking submit feedback

**Comment by rabbi08** [comment]
> As I am testing the feedback feature can you let me know what was the agreed final text to be displayed on clicking submit feedback

This issue is fixed in "rc/v1.1" not in STG. It is working as it was before.
