### ISSUE TITLE
"Check your inbox" heading out of alignment after signing up for an account [DESKTOP]

### ISSUE THREAD

**Issue by jessica-lau** [FightPandemics/FightPandemics#1129]
Environment: https://staging.fightpandemics.work/

Steps to reproduce:
1.  Go to https://staging.fightpandemics.work/
2. Click "Join Now" and enter info in email, password, and confirm password fields. Click "Join Now".
3. User will be redirected with a "Check your inbox message".

Actual results:
The "Check your inbox" heading is aligned above the message towards the right.

Expected result:
The "Check your inbox" heading should be centered above the message.

![image](https://user-images.githubusercontent.com/56090896/87232462-4560d380-c38d-11ea-940d-6d4745677ffa.png)

**Comment by omarzoghayyer** [comment]
Hi @jessica-lau  - I am unable to reproduce the issue. Can I ask what browser or environment are you using? 

<img width="1440" alt="Screen Shot 2020-07-13 at 9 02 54 PM" src="https://user-images.githubusercontent.com/49251966/87382619-3aa06d00-c54c-11ea-8534-94d851c780ac.png">

**Comment by jessica-lau** [comment]
Hi @omarzoghayyer I was using the staging environment on Chrome v83.0 on Windows10. However, I just rechecked this issue by doing another sign up process and everything seems to be looking good now.

**Comment by jessica-lau** [comment]
This issue can be closed.
