### ISSUE TITLE
Feed filter "offer or request help" not working [Mobile]

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1137]
It is adding this to `filter={"offer or request help"%3A["Offer Help"]}` instead of `objective=request` or `objective=offer` as in Desktop sidebar. The result is no filter is applied (both are sent back). 

Filter from onboarding does work however.

FYI @ppagarawal @pthoma14  . Not sure with code freeze how we are deciding what should be done as hotfix or not and how to label.

**Comment by pthoma14** [comment]
@joshmorel great point. 
1. Maybe we can first define what a hotfix would be vs. not. 
2. Then we could potentially use "hotfix" as a tag.

**Comment by idjevm** [comment]
👀 Ohh damn, was this perhaps introduced by one of my changes? 🤔 Can I take a look at this one @joshmorel ?

**Comment by idjevm** [comment]
This has been resolved.
