### ISSUE TITLE
GTM ID's not showing up

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1147]
**How to set up GTM debugging on Local: [https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255)

The following IDs have already been assigned to the correct components. Issue is that GTM does **not** pick up on these IDs.

### 1. Filter Categories (url path: /feed)

**Issue:** `Location`, `Providers`, and `Type` IDs do not show up on GTM when clicked on.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "Location" text and + Button <br>(including clickable white space) | HB_LO |
| "Providers" text and + Button <br>(including clickable white space) | HB_PV |
| "Type" text and + Button <br>(including clickable white space) | HB_TP |

<img width="700" alt="Screen Shot 2020-07-13 at 5 03 41 PM" src="https://user-images.githubusercontent.com/66695502/87358840-3ebc9280-c52c-11ea-8056-6adf348e7984.png">

### 2. View More button (url path: /feed)

**Issue:** `View More` IDs do not show up on GTM when clicked on.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "View More" text | HB_VM_postnumber |

<img width="700" alt="Screen Shot 2020-07-13 at 6 00 23 PM" src="https://user-images.githubusercontent.com/66695502/87362112-56e3e000-c533-11ea-8deb-1bc9c0cbf497.png">

### 3. Create a Post (on help board page, on individual profile page, and on organisation profile page)

**Issue:** GTM does **not** show the assigned IDs when clicking on the **red** shaded areas (text and icon), but it _does_ show the IDs when clicking on the green shaded areas.

| Element on page | JSX 'id' attribute |
| --- | --- |
| Individual Button | HB_CP1_IN |
| Organisation Button | HB_CP1_ORG |

<img width="700" alt="Screen Shot 2020-07-13 at 5 04 33 PM" src="https://user-images.githubusercontent.com/66695502/87360248-50ec0000-c52f-11ea-8f57-708ea69281ba.png">

### 4. url path: /offer-help

**Issue:** GTM does **not** show the assigned IDs when clicking on the **red** shaded areas (text), but it _does_ show the IDs when clicking on the green shaded areas.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "As a Volunteer" Button | OFS1_VO |
| "As a Donor/Investor" Button | OFS1_DI |
| "As an organisation" Button | OFS1_ORG |

<img width="700" alt="Screen Shot 2020-07-13 at 5 41 10 PM" src="https://user-images.githubusercontent.com/66695502/87361191-4b8fb500-c531-11ea-8d14-f6944c88c557.png">

### 5. Post page: View Less button

**Issue:** The `View Less` button on posts has the same ID as the `View More` button. The `View Less` button does **not** need an ID assigned to it.

<img width="700" alt="Screen Shot 2020-07-13 at 6 00 36 PM" src="https://user-images.githubusercontent.com/66695502/87362278-d1146480-c533-11ea-9ee4-be58425e42a6.png">

### 6. LinkedIn ID change to _LN
sign in page: /auth/login
Change Linkedin ID to: SI_LN

sign up page: /auth/signup
Change LinkedIn ID to: SU_LN

**Comment by idjevm** [comment]
Weird, it did not automatically close, so closing this manually.
