### ISSUE TITLE
Individual user profile create page- 'Privacy Policy/Terms and Conditions' doesn't open first time.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1152]
1. Open "staging.fightpandemics.work"
2. Sign up as new user say 'Linkedin User'
3. On User profile creation page:
- Click 'Privacy Policy' OR
- Click 'Terms and Conditions' 

Issue: You will observe that FP home page OPEN in new TAB rather than privacy policy page, when user clicks on either 'Privacy Policy' or 'Terms and Conditions' initially. The second clicked options and later works as expected.

Please note this issue works fine for Organisation Profile page.

Refer below GIF for more detail:

https://share.getcloudapp.com/JruLYj5z

Below is image from iPhone:
![image](https://user-images.githubusercontent.com/67168400/87386404-6af90300-c56e-11ea-9630-2cba396b2c71.png)

@indirabhowmick: As this is individual user profile I am marking it as Release-1 issue, please feel to update if you want.

**Comment by eyturner** [comment]
I'd like to take a crack at this one if no one has assigned themselves yet!

**Comment by indirabhowmick** [comment]
@eyturner - that would be awesome. Thanks so much. Please let me know once you have fixed the bug, I can test it in Staging

**Comment by rabbi08** [comment]
@eyturner @indirabhowmick @idjevm 
On User Create Profile Page -> Earlier when user click on 'Privacy Policy' it loads, home page but now it turn BLANK. It looks it is generating error, while adding new user profile:
"Create user failed, reason: No Authorization was found in request.cookies"

In Cookies: Failed to load resource: the server responded with a status of 401 ()


Error displayed if user click 'Privacy Policy' before Create User button [with same data]->
https://share.getcloudapp.com/P8ue45Gw

Error is NOT displayed if user click 'Privacy Policy' before Create User button [with same data]->
https://share.getcloudapp.com/geuwNbpD

**Comment by idjevm** [comment]
This has been resolved with #1228
