### ISSUE TITLE
User Friendly message should be displayed -> if the shared post is Deleted and viewed -> after sharing.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1155]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/pwd
3. Share own post using 'Share'

Test data - https://staging.fightpandemics.work/post/5f0d4323632a6c00124017c4 [link of shared post]

The post will shared successfully i.e. can be viewed from other phone or browser or so.

4. Now, delete the above shared post:

Issue: The shared link will not work and will be stuck in 'Loading' mode only.

Expected Result: User friendly message should be displayed that, the post is no longer available.

Note: This issue will come when the visibility of the POST expires as the post will be deleted as per the functionality by the shared link can be accessed for that respective post.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/67168400/87389318-8961fd00-c574-11ea-86c1-853320c22b64.png">

**Comment by joshmorel** [comment]
I'm not sure if we should have a specific message or redirect to 404. Thoughts @ppagarawal ?

**Comment by ppagarawal** [comment]
> I'm not sure if we should have a specific message or redirect to 404. Thoughts @ppagarawal ? 

For such scenarios, we need to let the user know that the post has been deleted. This will be different from 404 message. Please update the user with a message "This post has been deleted. 
Check our help board for more posts"
Embed a link on the helpboard to the helpboard. 


@Yu-Alexa-Zhao it'll be good to create a new page design for such use cases.
