### ISSUE TITLE
The FEEDBACK-END screen does not disappear after 3 seconds [DESKTOP] [ MOBILE]

### ISSUE THREAD

**Issue by pooji02** [FightPandemics/FightPandemics#1157]
**Environment:**  https://staging.fightpandemics.work/

**Expected  Results:**  System visualizes **FEEDBACK-END** screen which disappears after 3 seconds.

**Actual Results:** The FEEDBACK-END screen does not disappear after 3 seconds 

**Screenshots :** 

**MOBILE**
![image](https://user-images.githubusercontent.com/5065427/87433686-9eac4b00-c5b7-11ea-8929-82272c888dab.png)

**DESKTOP**
![image](https://user-images.githubusercontent.com/5065427/87433851-cc918f80-c5b7-11ea-95cd-a4a4c5a202f0.png)

**EXPECTED**
![image](https://user-images.githubusercontent.com/5065427/87434309-4d508b80-c5b8-11ea-947c-a3d2764685c7.png)

**Comment by pthoma14** [comment]
Thank you @pooji02, I'll review this issue for MVP-Release 1
