### ISSUE TITLE
Social links in the footer don't link out correctly 

### ISSUE THREAD

**Issue by elisechant** [FightPandemics/FightPandemics#116]
# What happened

Clicking Facebook, Instagram, etc links in the footer at the website https://fightpandemics.com/, don't link out correctly to the associated social domains. Rather they link to https://fightpandemics.com/#. 

# Expected 

Clicking Twitter icon should link to https://twitter.com/FightPandemics rather than https://fightpandemics.com/#, and so on.

**Comment by nadinejuraschek** [comment]
I should be able to fix that!

**Comment by nadinejuraschek** [comment]
Solved! 
Links for facebook, instagram, and twitter work now. I disabled Google+ and RSS, because I don't think we have accounts for those?
