### ISSUE TITLE
[Mobile-Android]Copyright on the footer should be center aligned

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1166]
Tested using: Samsung galaxy s8, Google chrome.
Environment:Staging
Actual result:
Copyright present in the footer of all the pages are left aligned.
Expected result:
Copyright should be center aligned .
![Screenshot_20200714-125337_Chrome](https://user-images.githubusercontent.com/41587211/87466717-c1a12400-c5e4-11ea-8468-e9bb0cc7a7ee.jpg)

**Comment by idjevm** [comment]
This  is actually resolved already on `rc/v1.1` branch.

**Comment by nivetheatha** [comment]
@idjevm But the links on footer is still left aligned .In the desktop version entire footer is center aligned.
![FP_webversion_footer links are center aligned1 (1)](https://user-images.githubusercontent.com/41587211/87476396-51020380-c5f4-11ea-8e0f-a4fd56fd738f.JPG)

**Comment by idjevm** [comment]
Yeah but staging is not deployed on the latest version, this was merged recently, I think yesterday with #1114
