### ISSUE TITLE
User Feedback UI

### ISSUE THREAD

**Issue by Valrud** [FightPandemics/FightPandemics#117]
**Priority**: High

**Requirements**: https://www.notion.so/fightpandemics/User-Feedback-UI-645a5edc39c44d91843d3b6e56f2eff8 

**Description**: User can give feedback over a user feedback functionality included in the hamburger menu (mobile) / top menu bar (desktop). 

**Tasks**:
- Frontend: the creation of  UI

Please contact Valentin Rudloff if there are any questions related to the requirements

**Comment by indirabhowmick** [comment]
@DanielAlexander84 

- [ ] Can you please include the styling changes for Desktop in the same PR?
Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A802

- [ ]  Designs need to be pixel perfect

**Comment by DanielAlexander84** [comment]
I can do that, but am not 100% sure which changes are meant with that. When I click on the link it leads to only the logo.

**Comment by indirabhowmick** [comment]
@DanielAlexander84 : My bad.
Here is the link:https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

**Comment by pthoma14** [comment]
@DanielAlexander84 what is your current status for User Feedback Frontend?

**Comment by DanielAlexander84** [comment]
@pthoma14 I am still working on it. I have pretty limited hours during the week, so most of my work is done on the weekend. I currently have the first two modal pops ups designed and spent Sunday working on getting the data handling working with Redux. My plan is to hopefully get a PR up on the weekend.

**Comment by vikjoshi** [comment]
@pthoma14 @DanielAlexander84 , I'm writing the E2E test for the feedback UI. @DanielAlexander84 , will your implementation cover both desktop webapp and mobile webapp?

**Comment by DanielAlexander84** [comment]
@vikjoshi I was planning to cover the design for both the web and mobile webapp. And you do not need to be logged in in order to submit feedback. For "users" that are not logged in, only the IP will be logged.
