### ISSUE TITLE
on My Profile ,  Post is deleted without asking for confirmation.

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1170]
Issue: on My Profile ,  Post is deleted without asking for confirmation.

Steps
1.Login to https://staging.fightpandemics.work/
2.Go to Profile->My Profile  and a Create a Post as Individual/Organization.
3.From My Profile choose the post to be deleted
4.Click on ellipsis and select delete.
Result: Post is deleted without asking for confirmation.
Expected: A confirmation dialog box should be displayed as shown below:

image
![image](https://user-images.githubusercontent.com/65972693/87477084-5eab8f00-c5dc-11ea-9867-5f1834a7680b.png)

**Comment by idjevm** [comment]
This is actually resolved in the `rc/v1.1` branch that we might merge very very very soon to master with a lot of little changes minor ones that will take effect once we merge iit to master.
