### ISSUE TITLE
Onboarding User -> Add comment -> Login using 'Social Media' option -> BACK button from Post lands on FP SIGN in page

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1172]
1. Open "https://staging.fightpandemics.work"
2. As Onboarding User-> Request Help -> Medical -> Share location -> skip 

All the FEEDs on help board are displayed.
3. Click on any FEED to add comment

User will be directed to SIGN In as expected.
Now, Sign in as Facebook user or through any social media option.

4, After successful login add comment and click on BACK button or icon.

Issue: You will observe that, User lands on SIGN In page rather than Help board page.
Please note this scenario works fine/as expected if onboarding user login using email/pwd option.

Refer below GIF
https://share.getcloudapp.com/NQugmy2w

and below is GIF when user logs in using email/pwd, it is working as expected:
https://share.getcloudapp.com/8Lu7ER2k

**Comment by OzkanAbdullahoglu** [comment]
also, same error was reproducing when "view more" clicked.
