### ISSUE TITLE
Loosing Post description text (after 123 characters ) if a post is edited and posted, when the Post Description is in 'view More ' mode. 

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1177]
Loosing Post description text (after 123 characters ) if a post is edited and posted, when the Post Description is in 'view More ' mode. 

1.Log into staging
2. Create a post with post description >123 characters, so that 'View More' option will be displayed. Ex description is given below.
".abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdabcd6dggViewMoreWillHappen"

3.Go to this  post on Help Board  
4.Click on View More and it goes to post details page 
5. Click "on view Less' then the 3dots appear at the end
6.Click on Ellipses->Edit
7. change the tag/title of the post and click on post
8. The post is saved with dots at the end and thereby losing rest of the post description
9. The post details page does not reflect it immediately but Help Board displays the post with missing data
![image](https://user-images.githubusercontent.com/65972693/87572334-3aa18980-c680-11ea-8c9d-c0d62cd9df38.png)

I have video recording, will send it over slack

**Comment by rabbi08** [comment]
Verified the fix in STG, it is working fine.  Post is retained after EDIT as well. Refer below GIF.

https://share.getcloudapp.com/Z4uyYJvP
https://share.getcloudapp.com/L1uQp4Pd
