### ISSUE TITLE
NO Icon for "Google playstore & iTunes links" displayed for Organisation

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1181]
1. Open "https://staging.fightpandemics.work"
2. login using valid email/address and Navigate to Profile -> Org_name -> EDIT profile
3. APPEND following test data for both Google playstore and apple iTunes links:

https://play.google.com/store/apps/developer?id=Mutual+Aid
https://itunes.apple.com/store/apps/developer?id=Mutual+Aid

You will observe that user is able to successfully add the links for the Organisation 
Issue: But on the Organisation profile, you will observe that NO icons are displayed for google and apple store links. they are displayed like 'BLANK BOXES'.

Refer below screenshot.
<img width="1129" alt="Screen Shot 2020-07-16 at 1 43 26 AM" src="https://user-images.githubusercontent.com/67168400/87632662-d0ccc280-c707-11ea-983d-cc6fae646aa5.png">

Please this issue is reported now as now I can add URLs with special characters for google and apple links.

**Comment by rabbi08** [comment]
Please note that links are working too i.e. if u click on boxes user is directed to the sample company app page. Thanks

**Comment by jyclam** [comment]
Thanks Rabbi! But this is a duplicate issue, see #1089
