### ISSUE TITLE
Update Sourced by FP avatar url

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1185]
The current URL to SendGrid is broken (I think the logo is deleted). We can use the GitHub logo instead like we do in Auth0.

![image](https://user-images.githubusercontent.com/10546720/87700528-74e45700-c764-11ea-8290-89062e21e5b9.png)

@vikjoshi @pthoma14 FYI this is very easy and shouldn't impact E2E testing at all. So I'm going to target `master` (Soft Launch).

**Comment by pthoma14** [comment]
@joshmorel sounds good. Thank you

**Comment by joshmorel** [comment]
Resolved by #1189
