### ISSUE TITLE
Create user error - no authorizations cookies [only in prod?] [requires reproduction]

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1186]
After trying to create user - but it doesn't consistently happen....

Never occurred in staging or review branches. I think it is F/E but unsure.

![image](https://user-images.githubusercontent.com/10546720/87701648-52ebd400-c766-11ea-90a5-231381b61a24.png)

This might only affect testers (those creating a user, signing out, then creating another user - not that it shouldn't be fixed). A fix to this #782 _might_ solve whatever is happening here (I think I know an easy way...).

**Comment by dabartlett** [comment]
I saw this message once, but after I cleared cache I could not reproduce it again.

**Comment by joshmorel** [comment]
I will close this as I think it's resolved but there is a new different edge case error: #1217
