### ISSUE TITLE
Any user can "attempt" to EDIT/DELTE post of other users but don't happen in the end

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1188]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/pwd
3. Navigate to 'Home Board' page
4. Filter the posts as per 'Provider -> Individual and type= Medical Supplies' to view less post, and click on any User Profile say'TT -Test Test' to view its profile

Issue: You will observe that under the 'Activity' of the user, the post are displayed and 'ellipse' are displayed for the post of that other respective user, and are clickable. You can perform all the actions of EDIT/DELTE the post.

Issue here is that any user can ATTEMPT to edit/delete, but safe at the end because even if all the actions are performed successfully the other users Post is not edited or deleted from the system.

Refer attached GIF:
https://share.getcloudapp.com/xQuD8mkv

![image](https://user-images.githubusercontent.com/67168400/87711069-c7c60a80-c774-11ea-99da-44fa83034e2f.png)

Please note this issue exist in PROD and STG both.

**Comment by joshmorel** [comment]
Thanks @rabbi08 . We should disable the menu if they aren't the author, or don't own the organization who authored the post.

**Comment by idjevm** [comment]
@joshmorel  I agree, that's exactly what I was telling @manualzuru on the call !

**Comment by jyclam** [comment]
I'm not seeing this at the tip of master but I do see it on staging. Tried viewing Individual profiles and also Organisation profile.

**Comment by idjevm** [comment]
@jyclam You have to be logged in, else it will not display..

**Comment by jyclam** [comment]
Yeah, I was logged in on two separate individual accounts looking at each others' individual profile and organisation profile.

@rabbi08 any idea what other configuration I should try?

**Comment by rabbi08** [comment]
> Yeah, I was logged in on two separate individual accounts looking at each others' individual profile and organisation profile.
> 
> @rabbi08 any idea what other configuration I should try?

@jyclam 
This issue exist for Individual profile i.e. if I click to view the profile of an individual user profile from his/her post, but this is working fine for Organisation post. I have attached GIF, showing the difference.

Please let me know if this is helpful :
https://share.getcloudapp.com/L1upA2Xj

**Comment by idjevm** [comment]
This should've been resolved by #1221

**Comment by rabbi08** [comment]
Verified in STG, this is working fine. Thanks.

Refer attached GIF.

https://share.getcloudapp.com/wbuWlKmx
