### ISSUE TITLE
[backend] Look into automatically adding additionalProperties: false to all fluent schemas

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#119]
See Robin's comment:

Only disadvantage is that it's a risk to forget this in the schema. For me this is ok but would be nice if we can set it as a default without risking to forget it in the schema's.
@mannykary Can you also add this in the readme?

_Originally posted by @robinv85 in https://github.com/FightPandemics/FightPandemics/pull/105_

**Comment by mushketyk** [comment]
Would it be a good idea to create a function like this:

```js
function strictSchema() {
  return S.object()
    .additionalProperties(false)
}
```

it can then be used everywhere where we define objects' schemas.

**Comment by robinv85** [comment]
@mushketyk yes something like that is what I had in mind
Furhtermore it can probably be automatically added to all the request schema's, to the `body` , `params` etc. if those are present? We might be able to find some standard plugin for that, I think @mannykary tried one but it wasn't working well

**Comment by mannykary** [comment]
@mushketyk Nice, thanks for tackling this! Would you mind updating the resume to mention this function? There is already a note to use `additionalProperties(false)` so we would just need to update the note to use the `strictSchema`.

**Comment by robinv85** [comment]
@mannykary I've also just thought about that, I'm adding fastify-sensible and will update the readme about backend so I can also change this in the process
