### ISSUE TITLE
Edit Organisation profile - Adding a word such as "edit or test" next to Link to "App Store and Google Play" causes to add a broken icon

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#1195]
Edit Organisation profile - Adding a word such as "edit or test" next to Link to "App Store and Google Play" causes to add a broken icon

Steps to Reproduce:

Pre-Requisite - user is logged in and Oganisation profile exists

1) On https://fightpandemics.com/ navigate to 3 lines at the top of the page> click on exiting organisation
2) on Profile page, click on "pencil" from the top right of the page> Edit Profile
3) Add a word such as 'edit or test" next to "Link to Apple Store and Link to Google Play") 
4) Save changes

Current Results: Logo at the top of the page breaks
Expected Results: Perhaps it shoud not show anything if incorrectly edited or if user should not edit, make those fileds not editable (check with Design or Product team)

![image](https://user-images.githubusercontent.com/67716598/87747653-c9112a80-c7a8-11ea-8602-33c96c35a562.png)
![image](https://user-images.githubusercontent.com/67716598/87747783-0f668980-c7a9-11ea-8a3b-0bb4f5e91286.png)

**Comment by idjevm** [comment]
Yeah the issue is that there's not icon for those 2 right now. So you can add pretty much anythin, including the actual url and it will be the same

**Comment by idjevm** [comment]
@vikjoshi Do we have icons or can we have the design team make some for us?

**Comment by dabartlett** [comment]
Will message the design team on it.

**Comment by vikjoshi** [comment]
Thanks @dabartlett . FYI @idjevm , not critical for soft launch so going to put the MVP-Release 1 tag on it

**Comment by rabbi08** [comment]
similar issues:

#1089, #1181

**Comment by galeza** [comment]
Close as duplicate #1089
