### ISSUE TITLE
Help Board - Location Filter is not displaying only location selected  *** will add details tomorrow****

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#1196]
Help Board - Location Filter is not displaying only location selected 

![image](https://user-images.githubusercontent.com/67716598/87748547-08d91180-c7ab-11ea-94f0-46a2caeb7d8d.png)

![image](https://user-images.githubusercontent.com/67716598/87748504-e47d3500-c7aa-11ea-870f-8202023a97d0.png)

**Comment by idjevm** [comment]
Thanks for logging this issue @dabartlett, but this is not an issue, there just aren't any posts besides yours in Vegas. The next close ones are Irvine and Anaheim, which are both in California.

**Comment by idjevm** [comment]
Also, the way it works is that it will display all posts of the location you selected, if there are no posts, then it will display any other posts that are near to that location, and if not, then it will display posts that are worldwide.
