### ISSUE TITLE
[Desktop][Mobile] Organisation Profile | Improve error message when location is empty

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1198]
env: https://staging.fightpandemics.work/

Steps:
1. Log in
2. Go to Profile - Add Organisation
3. Add name, email, leave location empty.
Add other details.
4. Press Create Profile button

Error message is not user friendly: Creating organisation failed, reason: body.location should have required property 'address', body.location should have required property 'coordinates'

Could we change this?

![Screen Shot 2020-07-17 at 11 32 20](https://user-images.githubusercontent.com/21987083/87779523-336bae80-c82d-11ea-9ebe-8e899cbe131b.jpg)

**Comment by idjevm** [comment]
Wait, are you able to submit the form without having the address??

**Comment by galeza** [comment]
@idjevm 

No, you can't submit without location. You have an error. It's just about the message that is not user friendly.

Another question - how application should work when the checkbox "We are a global organisation" is selected? Should we enter location? Currently it's required. You select checkbox and you have to enter location.

**Comment by joshmorel** [comment]
> Another question - how application should work when the checkbox "We are a global organisation" is selected? Should we enter location? Currently it's required. You select checkbox and you have to enter location.


@galeza I had asked about this before. The understanding I got that it was more marketing list related - so we can identify potential partners. So it's not related to any functionality currently. But you can ask more about that in Slack #mvp_organizationprofile channel.

**Comment by vikjoshi** [comment]
Thanks @galeza for identifying. Lets move this into MVP- Release 1 for now

**Comment by OzkanAbdullahoglu** [comment]
this is kinda duplicate of #1204 and I have already opened a PR #1219.

**Comment by galeza** [comment]
Closing
