### ISSUE TITLE
GTM ID's changed/not working as intended on prod

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1202]
**How to set up GTM debugging on Local: [https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255)

The following IDs are not working as they were on staging previously. **Please make sure the id attributes are working the same way for the mobile version as well!!**

### 1. Nav Bar: Feedback Button

**Issue:** GTM does **not** show the assigned ID when clicking on the **red** shaded area (icon), but it _does_ show the IDs when clicking on the green shaded area.

| Element on page | JSX 'id' attribute |
| --- | --- |
| Feedback Button | NAV_FDB |

<kbd>
    <img width="544" alt="Screen Shot 2020-07-17 at 10 08 10 AM" src="https://user-images.githubusercontent.com/66695502/87802793-52f7dc80-c817-11ea-9867-1a667efafa73.png">
</kbd>

### 2. url path: /need-help#Step2 AND /offer-help#Step2

**Issue:** `Show me postings from anywhere` IDs on both Request Help and Offer Help Step 2 changed. We want the IDs to be RES2_SA and OFS2_SA, **not** RES3_SA and OFS3_SA. Please fix these with the correct IDs:

| Element on page | JSX 'id' attribute |
| --- | --- |
| "Show me postings from anywhere" Button <br>(/need-help#Step2) | RES2_SA |
| "Show me postings from anywhere" Button <br>(/offer-help#Step2) | OFS2_SA |

### 3. Filter Categories (url path: /feed)

**Issue:** GTM does **not** show the assigned ID when clicking on the **red** shaded areas (icon), but it _does_ show the IDs when clicking on the green shaded areas.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "Filter" text and Filter Icon <br>(including clickable white space) | HB_FI |
| "Location" text and '+' Icon <br>(including clickable white space) | HB_LO |
| "Providers" text and '+' Icon <br>(including clickable white space) | HB_PV |
| "Type" text and '+' Icon <br>(including clickable white space) | HB_TP |

<kbd>
    <img width="274" alt="Screen Shot 2020-07-17 at 10 33 07 AM" src="https://user-images.githubusercontent.com/66695502/87805002-49bc3f00-c81a-11ea-8cd0-c1f5986cf0e3.png">
</kbd>
<kbd>
    <img width="272" alt="Screen Shot 2020-07-17 at 10 33 33 AM" src="https://user-images.githubusercontent.com/66695502/87805010-4cb72f80-c81a-11ea-8547-d1108f36be1a.png">
</kbd>

\
**Acceptance Criteria**: Please make sure that all fixes are working by testing _locally_. The GTM tags should be firing correctly as shown on the notion page (the link the setup local debugging is on the top of this ticket).

**Comment by jyclam** [comment]
Seeing an issue not documented, clicking on `Show me postings from anywhere` in addition to the correct triggers, it also triggers wrong tag **RES3_SA**
![Screen Shot 2020-07-17 at 4 57 26 PM](https://user-images.githubusercontent.com/26049767/87839292-07612500-c84f-11ea-8c85-4bdd2d96afef.png)
![Screen Shot 2020-07-17 at 4 57 35 PM](https://user-images.githubusercontent.com/26049767/87839293-07f9bb80-c84f-11ea-9649-bd231434ad55.png)
![Screen Shot 2020-07-17 at 4 57 46 PM](https://user-images.githubusercontent.com/26049767/87839289-05976180-c84f-11ea-85d7-024dd1908755.png)
![Screen Shot 2020-07-17 at 4 57 54 PM](https://user-images.githubusercontent.com/26049767/87839296-08925200-c84f-11ea-83ad-1c3c1fb26295.png)

**Comment by idjevm** [comment]
This issue was resolved by #1214
