### ISSUE TITLE
Unsigned user not redirected to post page clicked on

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1203]
Environment:Staging
1.As a unsigned user click on help board.
2.Click on long post(see more).Directs user to sign in page.
3.User logs in by entering valid username ,valid password.
Expected Result:
User has to land on the particular long post.
Actual Result:
User lands on home page.

**Comment by joshmorel** [comment]
Thanks @nivetheatha . This could be solved with similar to how we are redirecting when an unsigned user clicks comment.

**Comment by joshmorel** [comment]
@nivetheatha perhaps a more specific issue title would be helpful - "Unsigned user not redirected to post page clicked on" ?

**Comment by nivetheatha** [comment]
@joshmorel will rename it.
