### ISSUE TITLE
'Like','comments' labels should be removed for mobile posts

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1206]
'Like','comments' labels should be removed for mobile posts.

@ppagarawal Please comment if we need to remove 'share' label too for mobile posts

**Comment by ppagarawal** [comment]
I think that the design also needs to change a bit to match for the overlap between icon and the post boundary

![image](https://user-images.githubusercontent.com/6276256/87817386-7a39c280-c886-11ea-8dfa-2e990964e7c9.png)

**Comment by ppagarawal** [comment]
Note that the share button will be the three dots not the one on the Figma image

**Comment by OzkanAbdullahoglu** [comment]
just posts? or in feeds too ?

**Comment by sheeba1** [comment]
@ppagarawal  @OzkanAbdullahoglu  Anywhere the posts are displayed,ex:  feed,profile,post detail page etc.

**Comment by ppagarawal** [comment]
@OzkanAbdullahoglu Please refer to the designs in Zepelin for this and feel free to reach out here in case you need any confirmation

**Comment by OzkanAbdullahoglu** [comment]
@ppagarawal  @sheeba1  thank you both. I ll look and get back to you.
