### ISSUE TITLE
Org Users in Production cannot use the same email for sign up as their individual user email

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#1207]
In staging, we allow users to sign up for **1** organization with the same email as their individual user email. In production, we do not allow for this behavior. 

@galeza - please confirm that you are still seeing this behavior in prod vs staging

Ideally, production should reflect staging. Thoughts? @idjevm @joshmorel

**Comment by rabbi08** [comment]
I have tested the just now and yes:
In STG ->  Org Profile can be created once with the same email as of Individual user.

Test data used in STG and PROD: test.rajbir.qa@gmail.com

In PROD -> Unable to create the Org with the email of the individual user.
![image](https://user-images.githubusercontent.com/67168400/87818831-41273100-c839-11ea-8603-1aceaf16fc9d.png)

**Comment by idjevm** [comment]
Yeah Ideally we want production to reflect staging, but I think right now we should focus on production since we have already deployed, and then figure out staging once soft launch is done.

**Comment by joshmorel** [comment]
So the index was missing and there were many duplicates in staging :shrug: . I resolved that by tweaking duplicate org emails and added the index manually so both environments should disallow this:

![image](https://user-images.githubusercontent.com/10546720/87854597-07aa0080-c8e1-11ea-8c26-42b758526396.png)

I guess we should close this.

**Comment by vikjoshi** [comment]
Closing this
