### ISSUE TITLE
Onboarding - Need Help - Medical Help - UI Testing defects

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#122]
Issues identified in the flow:
https://www.notion.so/fightpandemics/Onboarding-Need-Help-Medical-Help-UI-Testing-defects-228519f361354bb9b08de05f2358f2ae

**Comment by luxumbra** [comment]
I have just pushed a branch, 664a7ff,  which has a slight refactor of the Need help wizard, so it now uses the additional styled components in `components/StepWizard/` I created in a previous chunk of work (now merged). If someone wants to take on this branch to attend to the issues in this ticket, that'd be cool. I'm not sure if that's best practice?
