### ISSUE TITLE
[desktop][mobile] Multiple orgs are not being displayed properly, when trying to create post as an Organisation. (edge case))

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1227]
The organization list should be scrollable, when trying to create a post as an Organization.

Currently, when we have many organizations,  they arent displayed properly.

**Note:** This is an edge case.

Check this out:
![Multiple orgs](https://user-images.githubusercontent.com/66698276/87938378-1eed1780-cab4-11ea-8254-dc6667799cd9.gif)

**Comment by jyclam** [comment]
I think this is a duplicate of #1210 which was fixed in rc1.1 by #1216.

**Comment by tejasm2** [comment]
Thanks @jyclam , closing the ticket.
