### ISSUE TITLE
Can't complete profile after opening new tab (privacy, terms & conditions) 

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1228]
This is because opening a new tab (or any start-up of the app) queries `/users/current` to authenticate and fetch the JWT cookie.  But because the user isn't created yet it clears the authentication cookie created in the 1st tab after sign-up before complete-profile.

@vikjoshi @pthoma14 @indirabhowmick  FYI

Looks like @rabbi08 was the only one to e2e test sign-up INCLUDING opening the privacy/terms+conditions tab.

This whole thing needs to be refactored as part of this #1164 - but I need to implement a hotfix for soft launch.

**Comment by idjevm** [comment]
Should've been resolved this by now!
