### ISSUE TITLE
Set up Cloudfront/S3 CDN on AWS

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1239]
https://www.learnetto.com/blog/cloudfront-s3

Ideally this should be done using Terraform: https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html

Our Terraform infrastructure code lives in https://github.com/FightPandemics/infrastructure

**Comment by git-satya** [comment]
Working on CDN recently. If no one has started on this, then I can take this request.

**Comment by git-satya** [comment]
@joshmorel ,  I will start on this request.

**Comment by mannykary** [comment]
This is required for avatar profile image upload. We will be saving upload avatar images to S3, and save the Cloudfront distribution URL for these images in MongoDB (this will be part of another ticket).

**Comment by mannykary** [comment]
Resolved in this [PR](https://github.com/FightPandemics/infrastructure/pull/9) in infrastructure repo.
