### ISSUE TITLE
Remove the additional text on homepage

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1242]
A text "FightPandemics" in white colour has been found on the homepage of the product. Please remove this to ensure clean content.

![image](https://user-images.githubusercontent.com/6276256/88040103-0ccbb180-cb66-11ea-94fc-4ccf5a9cee6e.png)

**Comment by idjevm** [comment]
We cannot remove it, we just need to change the logic to not show this on mobile. This is the text that shows on the desktop, on top of the text.
