### ISSUE TITLE
[Desktop][Mobile] POST | View more comments button

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1243]
env: staging

Steps:
1. Go to Help Board
2. Create post with ex. 10 comments
3. Click on a post

First 5 comments is displayed and button Show more comments is displayed. I click Show more comments button and next 5 comments is displayed. There's no more comments but button Show more comments is still shown.

![Screen Shot 2020-07-21 at 11 39 12](https://user-images.githubusercontent.com/21987083/88047259-a472d500-cb51-11ea-91c6-97f7f28bb1cb.png)
![Screen Shot 2020-07-21 at 12 56 11](https://user-images.githubusercontent.com/21987083/88047288-b0f72d80-cb51-11ea-822e-c229d85ede0d.png)

**Comment by galeza** [comment]
@ppagarawal 
Please prioritise

**Comment by galeza** [comment]
@ppagarawal @rabbi08 
Comment from @rabbi08 :

suggestion: if we can change the button to "show less comments" after all the comments are displayed, rather than nothing? So that user can again view the default newer comments only?

Refer attached GIF:
https://share.getcloudapp.com/E0uzk7zB

**Comment by pemika-me** [comment]
Hi all @ppagarawal @galeza  @rabbi08 @sheeba1 

As per my understanding, if a post with > 5 comments already displayed all of them, when the user click to show less comment, only the latest 5 comments will be left for display, is that correct? 

But what if there is **exactly** 5 comments in a post, and as per all details in this ticket - should it show the "show less comments" button at the bottom of all comments also? And then how many comments will be left for display after the user clicked on the show less comments button for this case?

**Comment by rabbi08** [comment]
> et - should it show the "show less comments" button at the bottom of all comments also? And then how many comments will be left for display after the user clicked on the show less comments button for this case?

@pemika-me 
As per my understanding, NO additional buttons for 'More/Less'  should be displayed, if comments are <5 and 'Show more is displayed when comments are >=5. This is also currently the default behavior. 

Please share your thoughts/observations if any.

**Comment by pemika-me** [comment]
@rabbi08 Thank you for your clarification, that's totally reasonable! :) I just would like to confirm for commenting a test script - comments part.

**Comment by pemika-me** [comment]
@rabbi08 Sorry, but I read it again, shouldn't it be 'Show more' is displayed when comments are >5, while no any additional buttons in case of <=5? (Because all 5 comments are already showing up)

**Comment by Elohina** [comment]
@pemika-me are you working on this issue?

**Comment by pemika-me** [comment]
@Elohina No, I am not an engineer.

**Comment by rabbi08** [comment]
> @rabbi08 Sorry, but I read it again, shouldn't it be 'Show more' is displayed when comments are >5, while no any additional buttons in case of <=5? (Because all 5 comments are already showing up)

@pemika-me 
Sorry for late reply, nice observation. Yeah, agree with your comments. 'Show more' button should be displayed if number of comments >5. If the number of comments are <= 5, No button should be displayed.

**Comment by rabbi08** [comment]
Verified in STG, working fine. Refer below GIF.

https://share.getcloudapp.com/7Ku8mB1R
