### ISSUE TITLE
Fit the screen on varying screen sizes to an acceptable limit

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1244]
As a user, I want to have seamless user experience on the mobile so that I have less efforts in interacting with the mobile.

Eg: Make the product homepage, onboarding and post view accessible in a single screen and avoid scrolling unless the content is too long(in post). 

Assigning to @Yu-Alexa-Zhao as well to get her comments wherever needed.

Sample:
Actual Image:
![File (1)](https://user-images.githubusercontent.com/6276256/88059038-eae02800-cb81-11ea-8b00-f4cb6e6f2c96.jpg)

Desired result:
![File](https://user-images.githubusercontent.com/6276256/88058927-c71ce200-cb81-11ea-8541-7f17c66bdb6e.jpg)

**Comment by cweave** [comment]
Solving #1242 should provide enough space to fix this.
