### ISSUE TITLE
Separate posts with horizontal rule

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1246]
As a user I want to have clear distinction between different posts on Help Board so that I they are readable.

Currently, there is no separation between different posts on helpboard.

**Comment by OzkanAbdullahoglu** [comment]
Hi @ppagarawal, in Zepplin I found out this one [feed-help-m](https://zpl.io/boqZxkW), How is it look to you?

**Comment by ppagarawal** [comment]
@OzkanAbdullahoglu the changes you have in the pull request is good. May I know what exactly do you mean to change here in the image you've attached?

**Comment by OzkanAbdullahoglu** [comment]
> @OzkanAbdullahoglu the changes you have in the pull request is good. May I know what exactly do you mean to change here in the image you've attached?

I meant I tried to make similar changes in PR up to Zepplin. Glad to hear that you like it :)
