### ISSUE TITLE
Fix the shivering elements across the platform

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1248]
The text elements when hovered over distort the other elements. Please fix them to have stability and not distort other elements or introduce a scroll bar on the page
Please check this in the following pages/features
- [ ] filter with location
- [ ] header
- [ ] visibility of posts in the post modal window
- [ ] onboarding pages
- [ ] Individual profile
- [ ] Create org profile
- [ ] Sign in page
- [ ] Join now page

**Comment by phuclb** [comment]
Hi @ppagarawal, I think I can take this task, but I need time because it occurs in many pages.

**Comment by ppagarawal** [comment]
Sure @phuclb . I recommend that you go step by step and ship the first 2 checkboxes first and get it merged. Then proceed with the next. I can create additional tickets to breakdown the work. Let me know if you need more tickets.

**Comment by phuclb** [comment]
Hi @ppagarawal,

Filters' Location & Header are updated.
Please check it out and let me know your feedback.

If they are ok, we can continue with others.
Thanks.

**Comment by ppagarawal** [comment]
> Hi @ppagarawal,
> 
> Filters' Location & Header are updated.
> Please check it out and let me know your feedback.
> 
> If they are ok, we can continue with others.
> Thanks.

Please share the link to the vm you are making chages to @phuclb 

Cc:@idjevm @rabbi08

**Comment by phuclb** [comment]
Hi @ppagarawal,

All pages are updated.
Please check it again.

Phuc.
