### ISSUE TITLE
[Mobile-Android]Not identifying GPS Location.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1253]
Environment
https://rcv11.fightpandemics.xyz/
Device used: Samsung Galaxy
Browser:Google chrome
Steps to create:
1.Click on Request Help.
2.Click "I have a symptoms of covid-19".
3.Click on share my location.
![Screenshot_20200722-155308_Chrome](https://user-images.githubusercontent.com/41587211/88222809-7fa35e00-cc34-11ea-8826-7b74ade60bb8.jpg)

**Comment by joshmorel** [comment]
Hi @nivetheatha are you able to use geolocation on other sites? 

The other thing - can you click the lock and share a screenshot. Maybe you blocked Location at some earlier point. It should say "Location - Allowed".

We discussed this one before #985 but no I can maybe use BrowserStack to see if it is device/browser specific.

What specific galaxy are you using?

**Comment by nivetheatha** [comment]
@joshmorel  yes am able to use geo location on other sites.It works well on the earlier staging environment (https://staging.fightpandemics.work/).
I am using Samsung Galaxy s8.

**Comment by nivetheatha** [comment]
@joshmorel #985 it works well on Google chrome. But now it's not working on Google chrome as well.

**Comment by joshmorel** [comment]
@nivetheatha if it works on staging but not production I'm wondering if you blocked it earlier. It's hard to tell. You need to click on the lock icon next to the URL.

If it says "Location - Blocked" like below that would explain it.

![image](https://user-images.githubusercontent.com/10546720/88225174-17567b80-cc38-11ea-86e7-cb043cfc9f51.png)

If not then I'm definitely puzzled on this one.

**Comment by nivetheatha** [comment]
@joshmorel yes you are right my mobile blocked the link from accessing gps.Now its working.Thanks.

**Comment by joshmorel** [comment]
Thanks @nivetheatha . We can display more specific error messages (such as permission denied) to make it clearer to the user. I can add a new issue.
