### ISSUE TITLE
[post moderation] Set up prod MongoDB cluster to expose posts endpoint

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1257]
https://www.mongodb.com/blog/post/creating-a-data-enabled-api-in-10-minutes-with-mongodb-stitch

Create the Stitch endpoint to expose the posts view (we only need to the post ID and the post content, and maybe the timestamp)

**Comment by joshmorel** [comment]
This part is mostly done (developing in my own cluster) - I just need to finish the google sheets (.gs) code which consumes it.

I think it's best to save the realm files (new name for AtlasDB product which includes stitch) files as well as .gs code in a different repo (maybe `mongodb-realm-apps` ?). I would envision adding this #1310 and any similar items. Thoughts @mannykary?

**Comment by mannykary** [comment]
@joshmorel Yes, I think a different repo would be best for this as it's independent of the web app.

**Comment by joshmorel** [comment]
Closing as we have a 1st iteration - new issues should be added in https://github.com/FightPandemics/FightPandemics-RealmApps
