### ISSUE TITLE
[post moderation] Set up Google Sheet to call Mongo Stitch posts endpoint

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1258]
Depends on #1257 

Create a Google Sheets script that can be run on demand to call this endpoint to populate the Google Sheet with all the posts returned. Then post moderators can sift through the posts and flag any inappropriate posts. The flagged post IDs can then be passed on to a lead engineer to delete in the MongoDB database.

See https://www.mongodb.com/blog/post/stitching-sheets-using-mongodb-stitch-to-create-an-api-for-data-in-google-sheets for an example. It will need to be modified so that it is just fetching the data from the endpoint, rather than mutating the data.

**Comment by joshmorel** [comment]
I will work on this using my own mongodb atlas cluster. Some familiarity with mongo & our data model is useful here so not necessarily good for a new user. Once this is done I will get a review then we can replicate the realm/stitch settings to the prod cluster (issue #1257).

**Comment by joshmorel** [comment]
Closing as we have a 1st iteration - new issues should be added in https://github.com/FightPandemics/FightPandemics-RealmApps
