### ISSUE TITLE
[Mobile-Android]New user not able to see their profile for the first time.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1262]
Environment: https://rcv11.fightpandemics.xyz/
Device used: Samsung galaxy s8
Browser: Google chrome
Steps to create:
1.New user sign up with valid user name,valid password.
2.Confirms mail id.
3.Signin with the same mail id,password.
4.Create your profile by providing all valid details.
5.Goto profile.
![Screenshot_20200722-153451_Chrome](https://user-images.githubusercontent.com/41587211/88314490-fdbe3e00-cce2-11ea-91d8-558e3179be87.jpg)

**Comment by nivetheatha** [comment]
This happens only for the new user.If we logged out and log in again ,then the bug doesnt exist.

**Comment by joshmorel** [comment]
Weird I thought we fixed this. Maybe there was a regression or maybe not entirely.  I will assign myself to fix

**Comment by idjevm** [comment]
@nivetheatha Could you do the same on https://staging.fightpandemics.work ? I am curious if it is still there.

**Comment by joshmorel** [comment]
@idjevm (cc @nivetheatha)  - it's mobile-only. We didn't fix the nav link for `AuthenticatedMenu` (mobile only). I have a fix very soon

**Comment by nivetheatha** [comment]
@joshmorel it exists in iphone too..Not sure about web version.
@idjevm  I will check in staging as well.

**Comment by joshmorel** [comment]
@nivetheatha don't worry I was able to recreate the issue. I just check that it is resolved here on any mobile device or dev tools mobile view: https://hotfixmobile-profile-id-undefined.fightpandemics.xyz/

**Comment by nivetheatha** [comment]
@idjevm it works well in staging. Bug doesn't exist.
