### ISSUE TITLE
User able to signup again with same emailid by using facebook,linkedin,google.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1266]
Environment: https://rcv11.fightpandemics.xyz/
Device used: Samsung galaxy s8
Browser: Google chrome
Steps to create:
1.Signup with a mail id(ex:abc@gmail.com).
2.The user have a facebook account with the same email id abc@gmail.com.
3.If the user tries to signup with facebook account again.
Expected Result:
It should not allow user to create new account with same email id.
Actual Result:
It allows user to create different accounts with facebook and manual creation with same email id.
But it doesnt allow to create a profile.(It idetifies the match in emailid only at profile creation page)
![Screenshot_20200723-164037_Chrome](https://user-images.githubusercontent.com/41587211/88336793-9b296a00-cd03-11ea-8ad9-13d0ba97eb7f.jpg)

**Comment by joshmorel** [comment]
Thanks @nivetheatha. Email is supposed to be unique so this is expected.

There are 2 things we can do long term and short for this:

1. Long term: Account linking #781 - more on this here https://auth0.com/docs/users/concepts/overview-user-account-linking
2. Short term: Check if the email exists before sign-up so they get an error message earlier.

Thoughts @indirabhowmick @vikjoshi ? We definitely should do 1 but should we do 2 in the interim?

@adisen have you made any progress on that issue?

**Comment by adisen** [comment]
Yeah. 
https://github.com/FightPandemics/FightPandemics/issues/781

**Comment by manualzuru** [comment]
@robinv85 said that he wanted to tackle this.

**Comment by adisen** [comment]
Okay. Awesome

Regards,
Israel Adetunji
https://adisen.me

**Comment by robvenn** [comment]
Hey @manualzuru @adisen I was going to look at some other things first (like avatar upload) but was waiting for some more feedback and am currently busy with other things
For this feature are you working on #781 backend @adisen or does this also still need to be done? I suppose we probably have to add some API call to "confirm" the merging of the social accounts as well (so the functional requirements haven't been clearly defined yet).

**Comment by adisen** [comment]
Yea I'm working on Backend end, I've seen in the documentation that we can sort of like prompt the user to link the accounts when it finds that a similar email is already registered

**Comment by ddveloper** [comment]
I am working on the backend right now #781 , we can do front-end in parallel if anyone wants to work on the front end at the same time.

**Comment by ddveloper** [comment]
I am working on p_Notifications and won't touch this issue for a while, unassign myself for now (so others can take)
