### ISSUE TITLE
Implement Lazy Loading on the Frontend

### ISSUE THREAD

**Issue by dfrancks** [FightPandemics/FightPandemics#127]
In https://github.com/FightPandemics/FightPandemics/issues/126, we'll implement pagination on the backend - this is to implement the lazy loading on the frontend.

The idea is that we'll only load 5 posts at a time, and will automatically load the next page when the user scrolls down a certain amount in their feed. 

Check out `backend/lib/endpoints/schema/posts.js` for the BE schema:
```
const getPostsSchema = {
  querystring: S.object()
    .prop("authorId", S.string())
    .prop("skip", S.integer())
    .prop("limit", S.integer()),
};```

**Comment by silenceway** [comment]
Hi @robinv85.
Are you working on this? It seems related to https://github.com/FightPandemics/FightPandemics/issues/179 and I`m working in API integration.

**Comment by robinv85** [comment]
Ah yes I was waiting for the Posts backend PR to be merged, it just got merged an hour ago or so, but feel free to take this over if you're working on the feed @silenceway

**Comment by robinv85** [comment]
Hey @silenceway if you are working on this also with #179 maybe assign this to you or close it and mention in the other ticket? Or it might be done yet since I see that ticket is closed...

**Comment by silenceway** [comment]
In https://github.com/FightPandemics/FightPandemics/issues/179 it was only implemented the call, pagination is missing because it was covered in this ticket. So, it's pending.

**Comment by manualzuru** [comment]
@robinv85 @silenceway shouldn't this be in New instead then?

**Comment by robinv85** [comment]
Not sure but if I understand correctly @silenceway is working on this so that's why I asked if he can assign himself to the ticket so we know he is working on it... it's probably included in the scope of the other ticket as well
