### ISSUE TITLE
Center align header right/left navlinks [desktop]

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1276]
Currently the links on the right are lower than the left (logo):

![image](https://user-images.githubusercontent.com/10546720/88484115-618e7400-cf3a-11ea-963d-8e359f335f06.png)

Should this be fixed? It would look better

The design is currently not also center aligned:

![image](https://user-images.githubusercontent.com/10546720/88486669-6d376600-cf4d-11ea-8273-7f4c39a346a6.png)
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed0372bafc298bac6778361

@Yu-Alexa-Zhao - this came up in here #1268 . Thoughts? @tejasm2 I think it would look better to have the left (logo) and right nav links center aligned. But this would actually be different than the current design. 

It's hard to notice on a large view but at medium size (e.g. half-monitor) it is noticeable and looks a bit wrong.

**Comment by tejasm2** [comment]
Yes totally agreed @joshmorel, we should have it center aligned. May be @Yu-Alexa-Zhao can suggest here.

**Comment by yu-zhao-xyz** [comment]
Yes it could be centered!

**Comment by kterry1** [comment]
@joshmorel @tejasm2 @Yu-Alexa-Zhao This is a pretty easy fix. Just add `align-items: normal` to the **.am-navbar-right** class. I'd fix it myself, but I can only find the class using dev-tools. I can't seem to find it in the source code. I just finished onboarding today, so I'll do some more digging and see if I can find it.

**Comment by phuclb** [comment]
Hi @kterry1, please consider the border when hovering menu item, the border-bottom should reach to end of header block

**Comment by idjevm** [comment]
I have a solution locally already so I will be submitting this soon.
