### ISSUE TITLE
Address is displayed twice for an Individual and Organisation in their profile.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1277]
1. Open "https://rcv11.fightpandemics.xyz"
2. Navigate to HelpBoard
3. 'Click on Profile icon of an Org to view the its details

Issue: You will observe  that the address for an organisation is displayed.

Refer below screenshot.

<img width="1440" alt="Screen Shot 2020-07-26 at 6 21 50 PM" src="https://user-images.githubusercontent.com/67168400/88491024-a41d7400-cf6d-11ea-8a91-81b7e0ac7e9e.png">

<img width="1440" alt="Screen Shot 2020-07-26 at 6 28 56 PM" src="https://user-images.githubusercontent.com/67168400/88491070-18f0ae00-cf6e-11ea-8247-8f1e6c44c840.png">

**Comment by rabbi08** [comment]
Please note this is regression, this issue does not exist in STG. i.e. staging.fightpandemics.work

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67168400/88491106-8e5c7e80-cf6e-11ea-8e07-dde6b47022fd.png">

**Comment by OzkanAbdullahoglu** [comment]
This is about #1250. @cweave
