### ISSUE TITLE
Fix incorrect PRIMARY constant & "Join Now" font color

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1279]
As discussed in #1268

"Join Now" button should use the same color `#425af2"` as our design system's primary color 
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed038667f1f399a291b343e 

This could be addressed in one of two ways - **1)** just update the rule(s) to use `#425af2`.

Or **2)** refactor our `client/src/constants/colors.js` constants file and usage. We have `PRIMARY` set as `"6A7EFC"` and `ROYAL_BLUE` set as `#425AF2`. The latter is mostly used as the primary color despite the former's existence. It is is used in a few places including "Join Now" button, even though it is not in our design system color palette at all:

![image](https://user-images.githubusercontent.com/10546720/88555059-492f5f80-cff5-11ea-9723-c3a1fb7b5f07.png)

2 is ideal, but needs to be done careful so as to not break what already exists. Best to just delete this line https://github.com/FightPandemics/FightPandemics/blob/ef8ad0872d26783c74f2fafb6dc870854a43cbf2/client/src/constants/colors.js#L1 - and use replace usage of `PRIMARY` as `ROYAL_BLUE` wherever it is defined.

**Comment by kterry1** [comment]
@joshmorel   Looks like a simple fix but I'll review and let you know if I have any questions.
