### ISSUE TITLE
f_Internationalisation: Integrate language translation data to our platform

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1286]
Use react-i18n to integrate translated data from Lokalise to our platform!

**Comment by tr1503** [comment]
For integrating translated data from Lokalise to our platform, we need to finish the following stuff:

- [x] Install the package react-i18n and its associated packages
- [x] Initialise react-i18n and add translate function to every displayed word
- [x] Find all missing words that don't have in Lokalise data and add them to Lokalise
- [x] Design and create the button for switching the language

**Comment by jyclam** [comment]
Hey @CeesWang, do you remember the context around this bit of code? https://github.com/FightPandemics/FightPandemics/blob/bd6529ef50e1825f35f95996b214ce82b6b6a4e1/client/src/components/Feed/FilterBox.js#L30-L36

Just want to confirm that it's safe to remove this `fromWhom` to `providers` conversion.

**Comment by CeesWang** [comment]
Changes have been made and I'm not 100% if it's safe to be removed. Might
have to look where the method is potentially being called.
