### ISSUE TITLE
Meta image is not displaying in Twitter

### ISSUE THREAD

**Issue by idjevm** [FightPandemics/FightPandemics#1290]
We need to fix this for twitter: 
![image](https://user-images.githubusercontent.com/25408660/88831948-0f4d8d00-d19e-11ea-9e17-24de499138da.png)

Follow the convo here: 
https://fightpandemics.slack.com/archives/C015BC1EMMG/p1595966724089300

**Comment by phuclb** [comment]
Hi @idjevm, do we need to use absolute path for twitter image?
Here is reference: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

**Comment by joshmorel** [comment]
This has been resolved maybe with #1378 ?
