### ISSUE TITLE
'Share' post is not working for telegram

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1297]
Issue: 'Share' post is not working for telegram. Post details/link is not shared for telegram.

Steps:
Have telegram installed on your dektop.
1.Click on share button for a feature and choose telegram .
2. It goes to message 'Open Telegram...' message opening telegram
3. Then it stays on 'Choose recipient'

Issue: Post details/link is not shared for telegram.

**Comment by jyclam** [comment]
It seems to work for me, did you choose a recipient in your contact list on the left? 

I've also double check our implementation and also the implementation on the module we're using (`react-share`) and it seems to be correct. 

![Screen Shot 2020-07-29 at 4 34 57 PM](https://user-images.githubusercontent.com/26049767/88864259-9fe59680-d1b9-11ea-9edb-3b0e061fac01.png)

**Comment by sheeba1** [comment]
@jyclam , I was able to make it work. Thanks John! for the suggestion to choose recipient.
 I had only one user and I was hoping to see the shared link to be pasted on the chat window.
