### ISSUE TITLE
Overlapping issue in the POST with address and Post TAGs.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1302]
PR#1182: Still doesn't work on iPhone 11 Pro max and now reproducible in Mac- safari too.

Please note- I have cleared my cache. 
Devices tested on- Mac, iPhone 11 Pro max, ZTE Blade Max(Andriod)

This issue exist on Mac-Safari but not in Chrome

iPhone 11 Pro max: Safari

ZTE Blade Max(Andriod): Working fine

1. Open "staging.fightpandemics.work'
2. Navigate to 'Help Board'

Issue: The Address -> City overlaps the post TAGs.

Please note that I have tried to change the address and re check the view of the new post with new address, the issue still exist.

Few of the posts have overlap of the cities with the post TAGs as shown in below screenshot:

<img width="1017" alt="Screen Shot 2020-07-30 at 2 24 23 PM" src="https://user-images.githubusercontent.com/67168400/88960065-f366eb80-d270-11ea-8ca7-98b8fcbf13e1.png">

![image](https://user-images.githubusercontent.com/67168400/88959245-af271b80-d26f-11ea-96fd-e952fb120b23.png)

**Comment by jyclam** [comment]
The [PR](https://github.com/FightPandemics/FightPandemics/pull/1182) that fixed this isn't in staging / production yet. I've tested Safari locally just now and it's fine but I suspect that the iPhone bug still remains as that wasn't addressed yet.

**Comment by phuclb** [comment]
Hi @rabbi08, I'm working on this issue.

**Comment by manualzuru** [comment]
@jyclam @rabbi08 @phuclb Is this solved?

**Comment by phuclb** [comment]
Hi @manualzuru, this issue is fixed, applied and closed.
