### ISSUE TITLE
[Mobile-Android]Menu adds on space depends on the number of post in the page.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1308]
Environment:https://staging.fightpandemics.work/
Browser:Google Chrome
Mobile:Samsung Galaxy
Steps to create:
1.Login with valid username,password.
2.Goto HelpBoard.
3.Scroll down to the middle post of the page.
4.Open Menu.
Expected Result:
Able to see all items in the menu .(The list has to be freezed it should look the same way when we open from top of the page or bottom of the page)
Actual Result:
The menu looks blank and we need to scroll up to see the items on the menu.
![Screenshot_20200730-184619_Chrome](https://user-images.githubusercontent.com/41587211/89051297-0a194b00-d322-11ea-85b9-56be52e19607.jpg)

**Comment by phuclb** [comment]
Hi @Joeu, adding 'position: fixed' to the block 'am-drawer-sidebar', it will work.
Hope it helps.

**Comment by Joeu** [comment]
Thanks for the tip, @phuclb ! I'm opening a PR.

**Comment by Joeu** [comment]
![Screenshot from 2020-08-05 08-22-27](https://user-images.githubusercontent.com/1004896/89409008-bcbd2500-d6f7-11ea-9ad2-fd8b259dbce4.png)

**Comment by phuclb** [comment]
You're welcome @Joeu :)
