### ISSUE TITLE
[Accessibility] Create standards for accessibility or use a third party

### ISSUE THREAD

**Issue by kterry1** [FightPandemics/FightPandemics#1309]
### We currently don't have any accessibility standards for our Product, Design, or Front End Engineering Team to follow. Although I don't have a lot of experience with accessibility, I've done a bit of research and it actually looks like it would be easier to just use a third party company that uses AI to add accessibility. 
---
### Here is a website I found that would do just that: https://accessibe.com/ and it would cover WCAG 2.1, Section 508, ADA Title III, and EAA/EN 301549. 

It's not free though, at **49/month**, so we may want to see if someone can reach out to them on whether they would provide a service for us at no cost. 

Any other ideas are welcome. This was created more to just get the conversation started.

**Comment by phuclb** [comment]
Hi @kterry1,

From my experience, to make a site accessible, we have many things to do and to follow, strictly. For example, meaningful tags for specific cases with role attribute and other things to do.

Maybe a third party can help us, it's real good, but it also affects too much to the way we are going together.

My suggestion is finding a team or a person can help us to review our current site, to find out what should do to improve accessibility.

My question is: 
Should we consider to apply accessibility this time or not?

Thanks.

**Comment by kterry1** [comment]
Thanks @phuclb! We are currently setup with a trial account for accessibe.com.
Could we set up out staging environment with the trial account? 
This might require a more senior person here to approve this: @idjevm or @joshmorel 

You can reach out to Yegor from hr for the credentials.

**Comment by kterry1** [comment]
@robinv85 Any thoughts on this? Not that we have an accessibe account, should we start implementing it or do we not want to use a third party?
