### ISSUE TITLE
User friendly message should be displayed if the email update for an Org is successful or NOT.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1311]
1. Open "https://staging.fightpandemics.work/"
2. Login using valid email/pwd
3. Navigate to Profile -> Org_name[Already added]
4. Click on EDIT icon to edit account information
5. Update the 'Organisation email" to existing email in the system, say for e.g. try with the individual user email ID and click on 'Save Changes' button.

Issue#: You will observe that nothing will happen and only the focus moves to the top of the screen and revert the changes.
Refer below GIF.
https://share.getcloudapp.com/2NuyK5X1

6. Now update the email with valid unique email ID and click on 'Save Changes' 
You will observe that email for the Org is updated and user is directed to Org Profile page.

Expected behavior: Ideally, user should get user friendly message if the email update is successfully or unsuccessful.

**Comment by manualzuru** [comment]
We should also confirm the email right @rabbi08?

**Comment by rabbi08** [comment]
> We should also confirm the email right @rabbi08?

Yeah, valid email address, which should be confirmed while be added/updated for an Org just like we do for individual profiles.

**Comment by soniaroh** [comment]
@rabbi08 two questions regarding this one:
1. in regards to displaying a user friendly error, do we want this message to show an error under the email input filed ? 
2. in regards to success message, do we want an alert to show? are we still redirecting the users back to org page?

**Comment by rabbi08** [comment]
> * isplaying a user friendly error, do we want this message to show an error under the email input filed ?
> * in regards to success message, do we want an alert to show? are we still redirecting t

@nr431207 Below are the answers for the qs raised above:

1. No, the message should be displayed on the top after user update email and clicks on 'Save Changes' button.
To keep consistency throughout the application, let's display the error message in same way as we have unique email error messages on 'Create profile' page.

Please note that currently in FP we are displaying email address validation under the email input field, for e.g. refer below screenshot:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/67168400/89371253-d9823a00-d6b0-11ea-88dd-8af9c6c6a1c2.png">


2. It will be great if we can display "Email successfully updated" message but 
here I wanna highlight what @manualzuru suggested above that- 

-> we need to confirm the email after email is updated, as we do for individual user email. So, after user update valid email address ->send email verification -> User will confirm the email and then email should be updated for an organisation.
-> "Email successfully updated" message should be displayed after updated email is verified.

Please let me know if answer your question or if any other query. 
Thanks

**Comment by soniaroh** [comment]
@rabbi08 does the user actually need to `confirm` the changed and verified email address for an org before it gets updated?  Im not sure if Im following.

**Comment by soniaroh** [comment]
@rabbi08 ok I think I understand it now, youre talking about the email verification that is sent to the user's provided email address along with a link to confirm the account, right?

**Comment by rabbi08** [comment]
> @rabbi08 ok I think I understand it now, youre talking about the email verification that is sent to the user's provided email address along with a link to confirm the account, right?

Yes, we need to verify email, which user is trying to update.

**Comment by soniaroh** [comment]
@rabbi08 I looked into this further, and what we have in place for email verification is designed for new user signup, so our backend is currently expecting password along with other data to perform verification through Auth and we are dealing with different set of data in org profile edit page. In that case I will need some backend help on this if we are trying to implement the email confirmation portion. But if we want to proceed without that piece, I can implement the user friendly messages.

**Comment by rabbi08** [comment]
> @rabbi08 I looked into this further, and what we have in place for email verification is designed for new user signup, so our backend is currently expecting password along with other data to perform verification through Auth and we are dealing with different set of data in org profile edit page. In that case I will need some backend help on this if we are trying to implement the email confirmation portion. But if we want to proceed without that piece, I can implement the user friendly messages.

@nr431207 Agree. Currently this email verification process is only working for Individual profile creation only. 

I will suggest that's lets currently work with only error handling part for successful and unsuccessful email Update during Org ->EDIT process. 

And then we can add email verification for Organisation profile while 'Creating and  updating Organisation' i.e. we have to verify the email while Org is added and then we have to verify the email when Org email is updated during EDIT process. 
We can have separate ticket for Org email verification process.

@manualzuru great if you can add your thoughts/input on the same.

Thanks

**Comment by ppagarawal** [comment]
@idjevm @nr431207 

Please display the message for any updates made in the fields. 

Rest looks good
