### ISSUE TITLE
[Desktop][Mobile] Display Playstore and Apple store icon on Organization profile.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1324]
As a user, 
When, I have entered the Google Playstore or Apple Playstore link in the organization profile info,
Then I should see the Google Playstore icon or Apple Playstore icon on my Organization profile.

Google Playstore icon: https://zpl.io/beRoykP
Apple Playstore icon: https://zpl.io/brwWGMD

Related to [#1089](https://github.com/FightPandemics/FightPandemics/issues/1089) issue.

**Comment by idjevm** [comment]
This is a duplicate. Let's add the context to 1089...
