### ISSUE TITLE
Selector displaying value instead of text from options 

### ISSUE THREAD

**Issue by jyclam** [FightPandemics/FightPandemics#1335]
![Screen Shot 2020-08-06 at 5 27 24 PM](https://user-images.githubusercontent.com/26049767/89595728-23cafe80-d80a-11ea-9615-c4337e17e6a5.png)
![Screen Shot 2020-08-06 at 5 27 28 PM](https://user-images.githubusercontent.com/26049767/89595733-24fc2b80-d80a-11ea-94de-a13f0fec889d.png)

https://github.com/FightPandemics/FightPandemics/blob/bd6529ef50/client/src/assets/data/createPostSettings.js#L2-L10

Relevant conversation[ here ](https://github.com/FightPandemics/FightPandemics/pull/1131/commits/c42488ae2c1a65e9ab1552d1503b617b5d516e54
)regarding whether we want "In my City" vs "City", etc. Regardless of the decision there this bug needs to be fixed for localization. 

@doheekim93 Can you reach out to relevant parties and get a definitive answer? The actual text can be part of localization PR. This ticket is specifically to address the component render `value` instead of `text`.

**Comment by doheekim93** [comment]
Spoke with design team:
We will adjust the wording from "The post will be visible to" to "The post will be visible to people" and go with "In my..."

**Comment by jyclam** [comment]
@doheekim93 
In changing the text of the drop down, the flow of the modal gets changed sometimes. I can reduce the  spacing between `The post will be visible to` and the drop down menus to make it fit. Is this an acceptable fix?

![Screen Shot 2020-08-06 at 6 41 50 PM](https://user-images.githubusercontent.com/26049767/89599569-cc7e5b80-d814-11ea-9ae7-82d5ab9617ff.png)
![Screen Shot 2020-08-06 at 6 42 17 PM](https://user-images.githubusercontent.com/26049767/89599567-cb4d2e80-d814-11ea-8a69-f01cea20299b.png)

**Comment by doheekim93** [comment]
@jyclam oops just saw this -- yes, the fix looks fine!

**Comment by rabbi08** [comment]
Verified in STG, values are displayed as shown on below image:
![image](https://user-images.githubusercontent.com/67168400/95545632-76709480-09cc-11eb-9338-2c3bbad4a870.png)
