### ISSUE TITLE
[Add Feature] Change Password Option in the Edit Profile section 

### ISSUE THREAD

**Issue by DevonLattrell** [FightPandemics/FightPandemics#1339]
Part of the Feature Ratings from July. 

See below for wireframe of feature. Created a simple tab in the edit portfolio called `Security Information`. This is a similar format to change passwords as other large Social Feeds (Instagram, Snapchat, and Facebook) 

Requirements:
1. User must enter their old password correctly in order to meet the requirements to update the new password.
2. The password input will have to hide the characters inputted by representing ********* upon typing.
3. New Password and confirmation password must match.
4. Forgot your password Link will follow the same format as the Forgot your password link on login page. You will have to verify your email and a link to change password will be provided in that email. 

![Password Reset in Edit Profile](https://user-images.githubusercontent.com/68662812/89661656-f1201500-d8a0-11ea-951e-7623f854ee5f.PNG)

**Comment by Joeu** [comment]
@DevonLattrell , is the backend already supporting this feature?

**Comment by DevonLattrell** [comment]
@Joeu that is a great question. The Forgot Password link is already supported. @joshmorel do you know if this would be already supported by the backend or with Auth0? Thanks!

**Comment by dhruvdpatel** [comment]
@joshmorel can you please get this verified? Thanks.

**Comment by joshmorel** [comment]
@Joeu @DevonLattrell @dhruvdpatel 

Apologies for the late response. We could use the forgot password route but the user  would need to change via their email.

If we want a form we need another backend route.

**Comment by DevonLattrell** [comment]
Ok - so for this specific feature we will have to build this up on the backend, as this is the currently not supported.  @Joeu @joshmorel @dhruvdpatel
