### ISSUE TITLE
[Desktop][Mobile] Need to update the design of "Request Help" and "Offer Help" buttons on the Landing page.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1342]
Need to update the designs of "Request Help" and "Offer Help" buttons on the Landing page. 

The new updated designs without hover: https://zpl.io/V4Wzp0M
The new updated designs when user hovers: https://zpl.io/VqoL73G

**Comment by Joeu** [comment]
@tejasm2 , can you export the icons in this zeplin link or maybe are they available elsewhere?

**Comment by tejasm2** [comment]
Hey @Joeu , I think the link I shared has the designs from zeplin. Are asking about something else?

**Comment by Joeu** [comment]
Hi, when I click on the knife icon, the .svg files are not available for download.
![Screenshot from 2020-08-08 10-09-26](https://user-images.githubusercontent.com/1004896/89711239-589c9a00-d95f-11ea-9204-a6bc3dd7b299.png)

Am I doing something wrong?

**Comment by tejasm2** [comment]
Hey @Yu-Alexa-Zhao can you please help here.

**Comment by yu-zhao-xyz** [comment]
Updated the Zeplin:
request/filled: zpl.io/25WxMoJ
request/hollow: zpl.io/V10Dm5Q
offer/filled: https://zpl.io/2EM1z98
offer/hollow: https://zpl.io/VqonGn7

**Comment by tejasm2** [comment]
Thanks a lot @Yu-Alexa-Zhao

**Comment by Joeu** [comment]
@tejasm2 , the updated designs were removed, do you know which styleguide should I use now?

**Comment by Joeu** [comment]
Also the unselected color is _lighter_ now than in the previous icons.

![Screenshot from 2020-08-11 08-02-11](https://user-images.githubusercontent.com/1004896/89890137-3d24cf80-dba9-11ea-8044-c7966e8e3e19.png)

**Comment by tejasm2** [comment]
This is strange. Can you please check this @Yu-Alexa-Zhao ?

**Comment by yu-zhao-xyz** [comment]
This is weird. The only difference between old vs. new designs is the illustrations used. I think replacing the illustrations would be sufficient. In the image shown above, the border and background color should be the primary color. 
Example of new design: 
![image](https://user-images.githubusercontent.com/44085699/89904586-1e2d3a00-dbb7-11ea-97f3-1c64f541bde1.png)

**Comment by Joeu** [comment]
Yep, you folks are correct, I've mistaken the filled/hollow naming for selected/unselected. My bad! haha!
Just the Request help icon is cut on the top and right edges, @Yu-Alexa-Zhao .

![Screenshot from 2020-08-11 13-56-38](https://user-images.githubusercontent.com/1004896/89926028-a8d36080-dbda-11ea-8d05-0b2d18c57840.png)

**Comment by yu-zhao-xyz** [comment]
Yes I think this is great, thank you! The difference in color is due to screenshotting I believe?  @Joeu

**Comment by Joeu** [comment]
Yes, it is, @Yu-Alexa-Zhao .

**Comment by tejasm2** [comment]
Hey @Joeu , we now have the correct design icons for this, can you please check them if you have not checked yet.

**Comment by Joeu** [comment]
![Screenshot from 2020-08-20 08-01-45](https://user-images.githubusercontent.com/1004896/90765748-d8f8be80-e2c0-11ea-8fed-35aa14a533c2.png)
![Screenshot from 2020-08-20 08-03-14](https://user-images.githubusercontent.com/1004896/90765751-da29eb80-e2c0-11ea-9dbc-946b2db4df27.png)


Folks, I've created another PR (and closed the previous) to avoid a bunch of conflicts regarding some deleted files.

**Comment by rabbi08** [comment]
Tested in STG, the designs are updated. Refer below screenshot. Thanks

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/67168400/91335649-b114c980-e79e-11ea-928a-063e708d2a57.png">

**Comment by manualzuru** [comment]
@rabbi08 im seeing it like this on mobile production. @Joeu please take a look ![image](https://user-images.githubusercontent.com/35108827/91672134-a9ea1480-eb2c-11ea-8d0d-b6dd615d0de7.png)
