### ISSUE TITLE
created an Organization with an email in invalid format

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1365]
Issue: I was able to create an Organization with an email  in invalid format ex:sheebag@com(refer figure 2 )
Steps: sign into staging.fightpandemics.work and navigate to 'Help Board''
2. click 'Create Post' and Choose 'Organization'
3. Click create new org
4. Enter the required fields and email as  abc@com
5.click 'Create Profile'. Organization is created

Expected behaviour: A validation message 'Invalid email' should be displayed (Refer figure1)if the email is invalid and the user should not be able to create an Organization with invalid email .

figure 1
![image](https://user-images.githubusercontent.com/65972693/89979830-7ac73e00-dc25-11ea-9c6a-7d1cbf2d2563.png)

figure 2
![image](https://user-images.githubusercontent.com/65972693/89980061-ef01e180-dc25-11ea-94e9-7203fbc54e29.png)

**Comment by AshBha243** [comment]
@sheeba1 : Hi Sheeba! I am newly joined to FP. When I login and got to create post, it create user profile and not the organization profile.
How to create organization profile?
Thanks

**Comment by sheeba1** [comment]
@AshBha243  , Hello ,When you click on create post, choose 'Organisation'.Click  ' create new one'. You just need to follow steps in the description above. 

Please let me know if you come across any issues. thx!

**Comment by emtay** [comment]
@sheeba1  @AshBha243 
While touching the email field for Organizations, can you also remove the 30 character limit? We found it with user testing and it's a problem if users have longer than 30 character emails which can be more likely with organizations than individuals.

**Comment by sheeba1** [comment]
@emtay , it should be ok as long as PM suggests /ok with it. What is the new limit.? 
@AshBha243 , Whats your thoughts? Any design constraints?

**Comment by AshBha243** [comment]
@sheeba1 @emtay I shall reach out to PM

**Comment by AshBha243** [comment]
@dhruvdpatel Hi! can we  change the character limit for email address of organization? if yes what would be?

**Comment by emtay** [comment]
@AshBha243 @sheeba1 @dhruvdpatel how about 200 characters to be safe? the design shouldn't need to change.

**Comment by sheeba1** [comment]
I think 200 is a bit high.

**Comment by AshBha243** [comment]
are you sure for email, 200 chars will be needed..looks on higher side

**Comment by emtay** [comment]
yea, i just figured it could be high because we don't really need a constraint since we have the validation. is there a database concern?

i found this on a simple google search for email length: 
To help the confused rookies like me, the answer to "What is the maximum length of a valid email address?" is 254 characters.
If your application uses an email, just set your field to accept 254 characters or less and you are good to go.
You can run a bunch of tests on an email to see if it is valid here. http://isemail.info/

https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address#:~:text=%22There%20is%20a%20length%20limit,total%20length%20of%20320%20characters.

**Comment by sheeba1** [comment]
@emtay  Can you please open another ticket for increasing field length as it might need approval and more validations etc. 

@AshBha243 If this  ticket is fixed , proceed with review

**Comment by emtay** [comment]
@sheeba1 good call. i've created a new one: https://github.com/FightPandemics/FightPandemics/issues/1437

**Comment by sheeba1** [comment]
Tested Org email validation by adding new orgs and editing email
