### ISSUE TITLE
[Desktop][Mobile] Need to display a general error message if there are no relevant posts available.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1367]
As a user,
When I filter the posts as per "Location", "Type" and "Providers" and if no relevant posts exists as per my filters,
Then I should be displayed the following message: "Sorry, there are currently no relevant posts available. Please try using different tags or create your own post."

![image](https://user-images.githubusercontent.com/66698276/90018722-0050f980-dccb-11ea-8081-969921c4c554.png)

**NOTE:** This error message should be displayed irrespective of whether the user is logged in or not.

**Comment by kterry1** [comment]
@tejasm2 @dhruvdpatel What do you think about something basic like this? 
![image](https://user-images.githubusercontent.com/40950641/90998556-645ca300-e592-11ea-944b-c056efb22e51.png)

**Comment by dhruvdpatel** [comment]
Hi @kterry1 here is the message we want to implement when there are no search results available:

“Sorry, there are currently no relevant posts available. Please try using a different filter search or create a post.” where Create a post should be highlighted, clickable and opens a “Create a post” action.

**Comment by kterry1** [comment]
@dhruvdpatel Thanks! Any specific look or is the red text enough?

**Comment by dhruvdpatel** [comment]
@kterry1 red text should be enough. Thank you.

**Comment by kterry1** [comment]
@dhruvdpatel Here is what I have so far.
I'll work on highlighting **Create a Post** and push up the code. 
![gif](https://p35.f2.n0.cdn.getcloudapp.com/items/4gu9Z05J/Screen%20Recording%202020-08-24%20at%2011.14.38.26%20PM.gif)

**Comment by kterry1** [comment]
Thanks @idjevm. It looks like Prettier wasn't formatting the doc. I made the fix but before I push the new commit up, can we get a design team member to provide another hightlight recommendation? @dhruvdpatel are you able to chime in here since you created #1420.

**Comment by rabbi08** [comment]
Tested in STG, it is working fine, refer below screenshot. Thanks

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/67168400/91335206-14522c00-e79e-11ea-9bba-76991616ea45.png">
