### ISSUE TITLE
Not able to logout if user has more than 10 organisation.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1369]
Environement: Staging
Device used:Dell (Windows os)
Browser:Google Chrome
Steps to create:
1.Login with valid user name and password.
2.Create 10 Organisation under the profile.
3.Click on profile.
Expected Result:
Able to see all the item in the list/Able to scroll to access all the item in the list.
Actual Result:
Not able to access logout in the menu.Not able to scroll as well.
![Logout](https://user-images.githubusercontent.com/41587211/90065065-b57ab600-dcb9-11ea-8ac4-cffc0e5c6a63.JPG)

**Comment by joshmorel** [comment]
Good find @nivetheatha . I think putting Logout then Feedback then Add Organisation and finally the org list would be best.

Alternatively we could have a manage organizations button if there are more than X (5?) orgs. But we'd need a page or section on the user's profile to manage orgs.

**Comment by Serhazor** [comment]
I can work on putting the log out button on the top as you suggested, but maybe adding the sliding out list of organisations as sub menu would be a better option?

**Comment by sheeba1** [comment]
Tested on staging and working fine
