### ISSUE TITLE
Customize the authentication page which grants profile access

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#1374]
Customize the auth0 page with Facebook integration to show that the user is providing Facebook profile access to FightPandemics and not auth0.

Acceptance criteria
- [ ] Change the text from auth0 to FightPandemics
- [ ] Change the Auth0 logo to Fightpandemics logo

![image](https://user-images.githubusercontent.com/6276256/90210211-fe8e4f80-de0a-11ea-80dd-d3d04343884a.png)

**Comment by joshmorel** [comment]
We've updated (in Auth0 not code base).

**Comment by ppagarawal** [comment]
Great!
