### ISSUE TITLE
Add visible Timestamp to posts on Feed 

### ISSUE THREAD

**Issue by DevonLattrell** [FightPandemics/FightPandemics#1389]
We currently store a timestamp for post creation and last update on posts. We currently do not show this on the posts themselves. As users move through their feed they will want to know how relevant the post is and how new it is. 

We are current discussing on issue #1303 the sort by feature, but in order for clarity on the feed, even with the sort by feature, it will be crucial to show the timestamp. 

Below is the wireframe that we discussed on #mvp_feed 

![Time stamp](https://user-images.githubusercontent.com/68662812/90409276-f63a4c80-e076-11ea-99b1-3120cce5f682.PNG)

The details of showing the timestamp would be to reference how long the post has been on the feed:
55 mins ago, 5 hours ago, 4 days ago (format)

Once the post is older than 7 days we would show the date it was posted:
August 1, 2020 (format)

**Comment by emtay** [comment]
@dhruvdpatel @tejasm2 - just fyi on this issue per our conversation. will want the designs for the "duration" indicator that the user selected when creating the post to account for this.

**Comment by tejasm2** [comment]
> @dhruvdpatel @tejasm2 - just fyi on this issue per our conversation. will want the designs for the "duration" indicator that the user selected when creating the post to account for this.

Yes, mentioned regarding this in issue #930 . I think showing the timestamp and the duration label on posts should work. FYI @Yu-Alexa-Zhao
