### ISSUE TITLE
Show text that message that IE11 is not support

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1390]
See issue #1304 for discussion. Due to current usage of libraries without polyfills, use of modern style rules & mechanism for secure persistent login we do not support IE11.

It would be a significant effort to implement and maintain such browser support so a decision to do so would require prioritization against other desired features.

We should display a message - "To ensure a secure and pleasant experience this app requires a modern browser. Please come back with the latest version of Edge, Chrome, or Firefox." We should probably include links that will take them to the right page (by language) in case the visitor does not speak English.

**Comment by ashminbhandari** [comment]
![sc_invalid_browser](https://user-images.githubusercontent.com/22779514/90706524-ec713e80-e25a-11ea-8330-fcbab4bfb8fc.PNG)

Hey Josh, this is what I came up with. I basically worked on the index.html file to check for the browser and wrote the above HTML to the DOM if the browser was IE 11 or lower. How do you suppose I should add language support?

**Comment by ashminbhandari** [comment]
![fightpandemics_invalid_browser](https://user-images.githubusercontent.com/22779514/90712830-7f18da00-e269-11ea-90ec-cbfb6432b81e.PNG)

The above screenshot is from an old laptop running IE11. The links should automatically adapt to the browser language setting based on my tests.

**Comment by joshmorel** [comment]
Wow this is great thanks @ashminbhandari 

I'm wondering if we need to include Safari, however. I'd assume all of the people who might visit with IE would be running Windows so I think Chrome/Firefox/Edge is sufficient. Thoughts?

**Comment by ashminbhandari** [comment]
Yes, that makes sense because this page is only shown for those using IE. I will make changes and proceed accordingly.
