### ISSUE TITLE
Notifications for Web App [Desktop-Mobile] - Send notification to post author when a comment is added

### ISSUE THREAD

**Issue by nfranklin9** [FightPandemics/FightPandemics#1406]
As a commentor/author of a post, I want to receive a notification on every comment posted, as well as when a post or comment is edited.

Current Scenario: When someone comments on my post, I don't know right away because I'm not sent an email or notification.

Expected results: As soon as someone comments on my post or edits it, I should be sent a notification to alert me.

**Acceptance Criteria:**

-  All the users receive notification
-  The notification is triggered for posting, commenting, editing posts, editing comments
-  The notification must have standard template with the message "New comment on your post"
-  The notification must contain a link to the post
- Note this is only for logged in users.

User notification settings:
- Mute notifications
    - Email: 24 hours / 1 week / 1 month / Forever
    - App: 24 hours / 1 week / 1 month / Forever
- Change frequency of notifications to weekly/monthly/yearly
- Turn on/off email notifications

These Settings could be accessed through:
- Notification email (have a link that takes users to change settings) on the FightPandemics platform
- Settings tab on the profile page on FightPandemics website

### Flow 1 - Comment Notifications for Individual post

When a User comments on a post → show a web app notification to the author of the post → Click on the link in the notification →  User gets redirected to the post for which the notification was generated

### Flow 2 - Comment Notifications for Organization post

When a User comments on a post → show a web app notification to all the members of the Organization of the post → Click on the link in the notification →  Member gets redirected to the post for which the notification was generated

### Flow 3 - Engagement notification

Click on the notification → User is sent to the post for which the notification was generated → New comments are highlighted for user to easily find them

**Starting point**
Justin Collier said "Either way [in app notifications or just email notifications], the easiest way to drive it is just have the backend push all notifications into an AWS SNS queue. Then any number of people can make other dispatch services for mobile push notifications, web push notifications, email, sms, or any other channel from there."
"Usually we model the notification object like this:
```
"notification": {
  "id": UUID,
  "subject": String,
  "message": String,
  "recipient": UserObject,
  "email": Boolean,
  "sms": Boolean,
  "push": Boolean,
  "web": Boolean,
  "is_sent": Boolean,
  "is_read": Boolean,
  "timestamp": DateTime,
}
```
Steps:
Backend creates a new notification on trigger
Publish whole object to SNS queue
Update is_sent value on successful publish
Then other services are responsible for updating the object with is_read once the user has been confirmed to have seen it via either Twilio, Sendgrid, or via the web or mobile clients."
"We can make lambda functions to handle all of the dispatch options. The User model should be validated to include the necessary fields like a verified phone number and email before those dispatch options are available."

Initial UX Design: https://fightpandemics.slack.com/archives/C018ZNAD62Y/p1598344009136700

**Comment by CamilaArias** [comment]
"New comments are highlighted for user to easily find them" this is a "Nice To Have". Please remove to avoid confusion :)

**Comment by emtay** [comment]
@nfranklin9 @CamilaArias per slack, we'd remove 'yearly' right? can we add 'daily' as an option?

Also, do users really want a notification if someone edited their comment? Maybe we can leave that out for now?

**Comment by tejasm2** [comment]
> @nfranklin9 @CamilaArias per slack, we'd remove 'yearly' right? can we add 'daily' as an option?
> 
> Also, do users really want a notification if someone edited their comment? Maybe we can leave that out for now?

Yes I agree with @emtay  on notifying user when a comment is edited for now. Also wont "daily" option be same as forever, and if it means a user needs to mute notifications for a given day..then we have the "24 hrs" option

**Comment by emtay** [comment]
@tejasm2  there is the frequency setting of getting the email and the duration of the muting.

Mute notifications
Email: 24 hours / 1 week / 1 month / Forever
App: 24 hours / 1 week / 1 month / Forever
> not sure if this should just be 1 week/ 1 month/ forever (and not 24 hours)

Change frequency of notifications to weekly/monthly/yearly. 

> this is what i thought should be daily/weekly/monthly

Turn on/off email notifications
