### ISSUE TITLE
Organisation name not updated in menu after update 

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1409]
Org name is not updated in menu list after editing.

![org-name-not-updated](https://user-images.githubusercontent.com/10546720/90931840-76401980-e3cb-11ea-8336-f87f8e46ffb8.gif)

That is until page refresh. This is a React state management issue.

This can be resolved by re-implementing changes in this commit for `EditOrganisationAccount.js` file 33ec75c

**Comment by kterry1** [comment]
Just fixed this. I'll push up the changes in a bit.
