### ISSUE TITLE
Remove Email Sign-up Question 3 from Initial Flows

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1422]
As a user, I don't want to provide my email when I'm just starting to engage with the platform.

Remove email signup page as it is a barrier for entry for users and they're prompted to login as soon as they interact with the posts.

![image](https://user-images.githubusercontent.com/43509421/91143346-39904e80-e667-11ea-9033-cfff4b235ef4.png)

As part of this story, please also update first two onboarding pages to say "Question 1/2"  and "Question 2/2" and on the Location question (2/2), we should change the "Next" to "Submit"
![image](https://user-images.githubusercontent.com/43509421/92409084-4778b180-f0f4-11ea-91f2-65c1bfcd430a.png)

(We can look to leverage email signup functionality we built on a separate part of the site when we know what we're going to use the emails, but that will be a future story)

**Comment by galeza** [comment]
Hi @emtay 
I have a question about this issue. @jessica-lau is going to write automated tests for this page. Please let us know how Question3 page will be changed?

**Comment by jessica-lau** [comment]
@galeza thanks for mentioning me in this. Yes, @emtay if you could please keep me in the loop on how Q3 will be changed that would be great. Thanks!

**Comment by emtay** [comment]
@galeza @jessica-lau it's going to be removed. so just question 1 (type) and question 2 (location) and then help board results

**Comment by galeza** [comment]
@emtay 
Thanks for clarification!

**Comment by jessica-lau** [comment]
@emtay Thanks!

**Comment by galeza** [comment]
Hi @emtay 
I have a question about Q3 screen removal. Are we going to modify Question 2 screen as a result of Question 3 removal?
We have a Next button thats open Q3 screen and a link "Show me postings from anywhere" that opens currently Q3 screen. They will open Help Board? Or maybe we will remove one of them?

**Comment by emtay** [comment]
@galeza good callout we can change "Next" to "Submit". i'll update the story

**Comment by kterry1** [comment]
@emtay Did you still want a submit button when adding the location or clicking "Show postings from anywhere" automatically moves the user to the next step, which in this case is the feed? If you are alright with how the below looks, I'll push up the code. 
![url](https://p35.f2.n0.cdn.getcloudapp.com/items/wbu7pWvz/Screen%20Recording%202020-09-13%20at%2001.05.58.56%20PM.gif?source=viewer&v=8309421bd272522b1c3ad1433864c1be)

CC @galeza

**Comment by emtay** [comment]
@kterry1 I think that looks good and more streamlined!

@manualzuru @doheekim93 @dhruvdpatel @tejasm2 @CamilaArias - thoughts on kevin's post above?

**Comment by galeza** [comment]
@kterry1 
I like your idea. It looks good and I agree that it is more streamlined.

**Comment by tejasm2** [comment]
Yes this looks good @kterry1
