### ISSUE TITLE
Open port on mongo docker container

### ISSUE THREAD

**Issue by lmpeixoto** [FightPandemics/FightPandemics#1424]
The objective of this issue is to open a port on mongo docker container to connect with the host machine and use with Compass or Robo 3t.

**Comment by joshmorel** [comment]
Not sure why you closed this but this will address - #1456. Was it opened for this issue or something else (testing?) @galeza ?

**Comment by sheeba1** [comment]
testing before prod release.
docker-compose.yml entry below:

version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: fightpandemics
    restart: always
    ports:
      - "27017:27017"
    networks:
      - fp_network
