### ISSUE TITLE
Notification Backend and DB [Desktop][Mobile] - for creating notifications

### ISSUE THREAD

**Issue by nfranklin9** [FightPandemics/FightPandemics#1426]
As a commentor/author of a post, I want to receive a notification for every comment posted, as well as when a post or comment is edited.

Current Scenario: When someone comments on my post, I don't know right away because I'm not sent an email or notification.

Expected results: As soon as someone comments on my post or edits it, I should be sent a notification to alert me.

This ticket is to create the database, middleware & queue for creating notifications and managing them on the queue.
middleware would be in node.js, queue would be SNS

Environment: node.js middleware, AWS SNS for queue
Expected results: Create notifications and manage them in the SNS queue
Actual results: Does not exist

**Comment by mannykary** [comment]
Based on our meeting today, here is our updated plan for the backend:
* We agreed to not use Mongo Atlas for the MVP as it would add unnecessary overhead for CI/CD, and we already have it set up for AWS/Lambda
* We will add a “trigger” to the existing web backend which will create a notification when a like or comment is created
* Lambda will run on a cron job to query for new notifications, and then group the notifications to send an email
* We need to refine the model and make it simpler, as mentioned by Josh above
* We need to sync up with Zayd to see how the web notifications will be implemented, and also share the tweaked model to see if we need to add or modify it to make it work with web notifications
* HTML template provided by Cami above will be used by the Lambda to build the email
* Lambda will send the email through SES
* We need an algorithm for grouping notifications for daily, weekly, and bi-weekly emails

I recommend that tasks be broken up as follows:

1. Refine/finalize Notification data model
2. Add logic to web backend to create a new notification on new like/comment
3. Add a Cloudwatch rule to Terraform to run the Lambda every 5 minutes
4. Create basic code in Lambda to query notifications and send an email for any unread notifications
5. Come up with algorithm for grouping notifications for digest emails, and add this logic to the Lambda
6. Finalize HTML templates for the notification emails

Web notifications is covered in #1428 and #1531. We need to meet with Zayd to discuss this implementation

Unsubscribe from notifications is covered in #1507. We will need to generate unsubscribe links in the Notification Lambda, and add a new unsubscribe page to the web frontend (with corresponding logic in the web backend to toggle the user's notification preferences).
