### ISSUE TITLE
Web Notification front end [Desktop]

### ISSUE THREAD

**Issue by nfranklin9** [FightPandemics/FightPandemics#1428]
As a commentor/author of a post, I want to receive a notification for every comment posted, as well as when a post or comment is edited.
Current Scenario: When someone comments on my post, I don't know right away because I'm not sent an email or notification.

Expected results: As soon as someone comments on my post or likes/shares it, I should see a web notification to alert me, (similar to notifications on facebook or reddit)

Initial design: https://fightpandemics.slack.com/archives/C018ZNAD62Y/p1598344009136700 

![image](https://user-images.githubusercontent.com/43509421/91257348-82efa500-e71e-11ea-8b61-bb4f8496851a.png)

**Comment by ddveloper** [comment]
The changes have been merged into PR #1677 , I'm going to close this thread
