### ISSUE TITLE
Symptoms checker (Desktop) - Question 2 page (SC-Q2-soe) should have "Back" & 'Next" button options.

### ISSUE THREAD

**Issue by Akhila2406** [FightPandemics/FightPandemics#1431]
**Link to the webpage:**
https://staging.fightpandemics.work/symptoms-check#Step2

**Description:**
Question 2 page of symptom checker for myself doesn't have the option to move to next or previous page. Should have "Back" & "Next" button options. Think it is hidden behind the options displayed on the page.

![sc-1](https://user-images.githubusercontent.com/69996947/91234788-e52db300-e6e8-11ea-83d2-a5d919c62903.png)
![sc-2](https://user-images.githubusercontent.com/69996947/91234803-ea8afd80-e6e8-11ea-8069-d877253bd7f1.png)

**Comment by kterry1** [comment]
This is a duplicate.
Closing out.
https://github.com/FightPandemics/FightPandemics/issues/1340
