### ISSUE TITLE
Messaging: Add "Message" Button to Post

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1433]
As a user, I want to send a message to the Author of a Post in order to connect with them to figure out how to help or how to get help without other users seeing my message.

This story is to add the message button on the post within the Help Board and to check for authentication when clicked.

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=10956%3A15744 

![image](https://user-images.githubusercontent.com/43509421/91274151-1f23a700-e733-11ea-937f-851c5a73068c.png)

Users trying to click on this button need to be logged in.
If users are not logged in, they should be redirected to login.

AC:
Given user is looking at a post on the help board,
Then they will see the "Message" icon

Given user clicks on the "Message" icon and is logged in
Then user can proceed to the message submission page (future story)

Given user clicks on the "Message" icon and is not logged in,
Then user will be redirected to log in.

**Comment by manualzuru** [comment]
@xreic should we move this to "In Progress"?

**Comment by xreic** [comment]
> @xreic should we move this to "In Progress"?

Thank you for pointing it out @manualzuru !
I'll do so immediately.

**Comment by manualzuru** [comment]
No worries, I just want to make sure that we have a clean board so new engineers don't need to expend time figuring out if a feature/issue is being worked on or not
