### ISSUE TITLE
Messaging: [Desktop] [Mobile] Create "Inbox" for Private messages and Indicate Read/Unread

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1435]
As a user, 
I want to be able to find all my active messages in one place so that I can read them and reply to them efficiently.

This story is for the Left Side "inbox" and read vs. unread messages:
1. All private messages that user is a part of is on left side.
2. Each message should display the user avatar, name of the user, title of the post through which the user messaged (upto 15 chars max), and the last message sent or received (light grey and upto 15 chars max).
3. Unread messages are indicated with a blue dot. If the message is "read/opened" by the user the blue dot should disappear. 
4. Messages are sorted by most recent (first) and oldest (last at bottom).
5. Timestamp is displayed for most recent message sent (by either sender).
6. The current opened or read message should be indicated by highlighting it with transparent light blue (as per designs)
7. The total number of unread conversations from users should be indicated and should change or decrease as a particular message is read or opened.
8. Add a "question mark" icon as shown in designs.

![DM 2](https://user-images.githubusercontent.com/66698276/91733067-b8850a00-ebc6-11ea-8f3e-ed7d38bb6703.png)

Design Desktop (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87532

Design Mobile (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87652

Zeplin link: Will be added soon

AC
Given user has a message
When they come to message inbox
Then they will see the message in their left hand inbox with a blue dot to indicate not read.

Given user comes to message inbox without a new message
When they come to message inbox
Then they will see their messages in their left hand inbox and no messages will have blue dot because all are read.

**Comment by kterry1** [comment]
@emtay Do you know where the github ticket is for the rest of that design that isn't squared in red? It easier to build it out all together, so I wanted to make sure someone else wasn't working on the other part as well.

**Comment by emtay** [comment]
@kterry1 yep this one! https://github.com/FightPandemics/FightPandemics/issues/1453

**Comment by kterry1** [comment]
@emtay Thanks!!
