### ISSUE TITLE
Email Validation: Extend email to more than 64 (max supported by Auth0) characters and consolidate email validation

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1437]
As a user, I want email validation to be consistent across my individual and organization profiles and for email length to be 200 characters so that I can be sure my email will fit.

Within this story, all email validation should be in one configuration so that we ensure consistency.

Email validations should be:

Empty field: “Email is required”
Not a valid email address: “Email is invalid”
Over 200 chars: “Email must not exceed 200 characters”
Invalid domain: “Email domain is invalid”

![image](https://user-images.githubusercontent.com/43509421/91332588-46a16080-e781-11ea-8642-c46bb0f15ea0.png)

AC Character limit:
Given user is adding their email to create an individual profile
When their email is less than 200 characters
Then the system should accept the email and process the profile creation.

Given user is adding their email to create an organization profile
When their email is less than 200 characters
Then the system should accept the email and process the profile creation.

Given user is adding their email to create an individual or organization profile
When their email is longer than 200 characters
Then the system should given an error that there is a max of 200 characters and email is not valid.

Note we considered allowing same email address between indiv and org, but will keep those unique. so one more constraint is that the email is unique across other users (any type of user), so this should continue:
Error for signing up with same email:
![image](https://user-images.githubusercontent.com/43509421/91332728-79e3ef80-e781-11ea-8b5c-ae0db7a9f1bc.png)

**Comment by sheeba1** [comment]
For Sign-up, 200 character email is giving "Internal server error" as below:

email used: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh@gmail.com



![image](https://user-images.githubusercontent.com/65972693/94050868-afcdc100-fd8b-11ea-8025-823449d4950c.png)

**Comment by idjevm** [comment]
Hey @emtay, reopening this since it looks like Auth0 only supports emails that are less than 64 chars. @paulms1 could you make the quick update or should I go ahead and open a PR for this one? Let me know if not I will go ahead and submit a PR.

**Comment by sheeba1** [comment]
Tested Create and Edit Org -worked fine .

**Comment by rabbi08** [comment]
Closed by mistake, reopening.

**Comment by sheeba1** [comment]
any new PR? @emtay , Please confirm you are aware of the changes. Thanks!

**Comment by joshmorel** [comment]
I think we should update details here or just create a new one @paulms1 @emtay @rabbi08 @idjevm.

Let's use the same email validator function FE/BE that should work with Auth0 given recent error @sheeba1 found .

local is 64 max, domain is 255 max overall but each part separated by . is max 63. So testing this sounds complicated... Let's use our existing regex but with following lengths check.  Not sure approach here in splitting as addition `@` are allowed if in quotes. Here is a regex which finds a way to split on local & domain part. Then we can check local for max 64, domain for max 65 (63 + '.' + 1 tld) for nice even 130 (w '@') and be happy with it. https://github.com/auth0/lock/blob/4aaefa4a9ed00423e665e0743a7b0a952c6a267d/src/field/email.js#L7

But this function once provided by Auth0 is deprecated so maybe it's no longer valid?

We could save ourselves a headache... Max 60 chars overall (or 64 inline with title). Long emails may cause UI issues elsewhere maybe? If they have a real long email they can use another email.

**Comment by joshmorel** [comment]
Resolved by #1566

**Comment by rabbi08** [comment]
STG: User is able to create account with email containing 64 or less characters but not more: PASS

Individual Profile:
User can enter 64 chars without space to create email ID with 64 chars, if the char exceed, 'error shows up as 'Email is invalid' as shown in below screenshot.
Email used:
Valid email:    test123456789012345678901234567890124567890123456767890000000000@gmail.com

![image](https://user-images.githubusercontent.com/67168400/95484211-2d81f700-095e-11eb-9d31-cac873725f5f.png)

Invalid email: test1123456789012345678901234567890124567890123456767890000000000@gmail.com

![image](https://user-images.githubusercontent.com/67168400/95484067-01ff0c80-095e-11eb-9487-ee03cd83660b.png)

Organization Profile:
User is able to create Org account with email of 64 chars, if the char for the email exceed error is displayed as 'Email address id invalid' as shown in below screenshot.

Valid email:   Orgemailwith64chars123456789012345678901234567890123456789012345@gmail.com
![image](https://user-images.githubusercontent.com/67168400/95485208-6a022280-095f-11eb-9562-b8156a43040f.png)


Invalid email: Orgemailwith64chars1234567890123456789012345678901234567890123456@gmail.com

![image](https://user-images.githubusercontent.com/67168400/95485075-3aebb100-095f-11eb-8ab8-80be67cb9ef0.png)
