### ISSUE TITLE
Messaging [Desktop][Mobile]: Create Inbox for messaging with user. (Part 2 of #1435)

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1453]
**New Version:** 

As a user,
Given that I am on the HelpBoard,
When I click on the message icon on a particular post, send a message & view the message,
Then the message should be displayed in a chat with the author of that post, attached with the post information (Title & Description) as a reference (as shown in the designs). 

Note: If the user clicks on that referred post in the chat, then that post should be opened in a new tab.

Designs Desktop: https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5f57f31ce2f04b425e445a2d
Designs Mobile: https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5f4db259d00e160dbd987d0c

FYI: @emtay @kterry1 

---
**Old Version:**

As a user, 
Given that I am on the main messaging screen,
When I select a particular conversation from a user,
Then I should be able to see any previous messages with that user and should be able to send a message to that particular user. 

Design components from top to bottom:
 
1. Display text : User Avatar and User name.
2. Title of the post and Description (max up to 1 line, ~25 words) of the post with an arrow to expand the post.
3. When the post is expanded the type of post ("Offer" help or "Request" help) should also be visible along with timestamp of post (X hours/mins ago- same as with post time stamp) and the entire post should be visible.
4. Messages shared between two users (Received messages should be on left and sent messages on right). The newest messages should be at the bottom and the oldest messages at the top. Each message should display the timestamp when the message was sent below that message.
5. Textbox to enter the message (the box expands its height upto 3 lines max as content increases and after that a scroll should appear)
6. Send button icon.

![dm](https://user-images.githubusercontent.com/66698276/91725563-8bcbf500-ebbc-11ea-9bc5-71d721f755d0.png)

![DM 3](https://user-images.githubusercontent.com/66698276/91725573-91293f80-ebbc-11ea-9103-6f39d3da9a07.png)

Designs Desktop (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87532

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A88538

Design Mobile (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87716

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A88665

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A89153

Acceptance Criteria:

1. The send button remains disabled (light blue) until a character is typed in the textbox. When a character is typed in the textbox the send button icon is highlighted (dark blue).

**Comment by manualzuru** [comment]
@tejasm2 can we add the new designs?

**Comment by emtay** [comment]
@kterry1 @tejasm2 just realized we don't have a design for error if not sent on this design. i'll double check figma and then will ping kelly/yu if not there.
