### ISSUE TITLE
Messaging [Desptop][Mobile]: Display the number of unread messages along with message icon on menu bar. 

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1454]
As a user,
I should be able to see the number of unread messages along with message icon on the menu bar. 

Note: As I open/read a message, the number should be updated accordingly.

![DM menubar](https://user-images.githubusercontent.com/66698276/91557660-810e2780-e952-11ea-95d0-847d4219f998.png)

Design Desktop (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87412
Design Mobile (Figma): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17065%3A87652

**Comment by manualzuru** [comment]
@tejasm2 Where is the notification icon? If the notifications for message work, then the normal notifications should as well work as it's basically the same feature

**Comment by tejasm2** [comment]
> @tejasm2 Where is the notification icon? If the notifications for message work, then the normal notifications should as well work as it's basically the same feature

Yes Manu, will update the design with the notifications icon.
