### ISSUE TITLE
Messaging [Desktop][Mobile]: Create a confirmation modal window pop up when a message is sent via posts.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1457]
As a user, 
Given that I am on the "Send a message" modal window,
When I click on the "Send" button,
Then I should see a pop up modal window, which indicates a confirmation of sent message with "Your message was successfully sent" message and two buttons: "View Message" & "Done"
_When_ I click on the "View Message" button,
_Then_ I should be redirected to that particular message.
or
_When_ I click on the "Done" button,
_Then_ I should be redirected back to that particular Post (through which I sent the message) in helpboard.

![helpboard-pop-up-B](https://user-images.githubusercontent.com/66698276/91729601-6f32bb80-ebc2-11ea-9c73-b5776aed6793.png)

![Sent](https://user-images.githubusercontent.com/66698276/91729721-9c7f6980-ebc2-11ea-85aa-38bc768500c5.png)

Design Desktop (Figma):  https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=16797%3A84572

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=16797%3A85212

**Comment by CamilaArias** [comment]
Hey @tejasm2 small thing, we're capitalizing the first letter of each word in CTAs (View Message).

I think one detail that might be missing is what would it look like with a long post title and 2 or more tags?
Are the tags really needed?
Maybe just to identify the post we could do we with:

Author - title of post (multiline if needs be)
Short description

If the tags are needed, maybe they can be in a line below the title?

**Comment by tejasm2** [comment]
> Hey @tejasm2 small thing, we're capitalizing the first letter of each word in CTAs (View Message).
> 
> I think one detail that might be missing is what would it look like with a long post title and 2 or more tags?
> Are the tags really needed?
> Maybe just to identify the post we could do we with:
> 
> Author - title of post (multiline if needs be)
> Short description
> 
> If the tags are needed, maybe they can be in a line below the title?

Yes @CamilaArias , the designs are updated will add those here soon

**Comment by manualzuru** [comment]
@tejasm2 do we also need a message when the message (post as we are leveraging the post feature) doesn't get sent?
