### ISSUE TITLE
Make drawer draghandle not visible

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1459]
### The issue

Handler of the drawer menu on the right-hand side is visible and looks like a bug, it doesn't provide useful information to the user either, as the hamburger icon already indicates how to access the menu.

![image](https://user-images.githubusercontent.com/25089562/91616306-cc790380-e95b-11ea-8623-2bcd75a93cd8.png)

### Suggestion to fix
Remove background colour
```
.am-drawer-draghandle {
    z-index: 1;
    position: absolute;
    background-color: rgba(50,50,50,.1);
}
```

**Comment by LincolnNowell** [comment]
if add a media query to the webkit-scrollbar that changes the width to zero it might work

`::-webkit-scrollbar{
  width: 5px;
  background-color: ${WHITE};
  @media screen and (max-width: ${mq.phone.wide.maxWidth}) {
    width: 0px;
  }
}`

**Comment by LincolnNowell** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/45523380/92971373-f3e4cb80-f445-11ea-8344-b1de96eb3727.png)

**Comment by CamilaArias** [comment]
Hey @LincolnNowell I think that's for the scrollbar and not the drawer menu handle? I might be wrong

**Comment by kterry1** [comment]
@CamilaArias I'll push up the fix for this in a bit.
