### ISSUE TITLE
Add Expiration Date to Posts

### ISSUE THREAD

**Issue by dfrancks** [FightPandemics/FightPandemics#146]
We need to add `expireAt` to the Post model and the Post endpoints.

In a future ticket, we will add filtering on the backend to filter out expired posts before serving them to the FE.

When editing the post, the `expireAt` should be referenced from the time the person is editing the post, not the original time of posting.

**Comment by robinv85** [comment]
I think the backend will apply filters based on query params that are sent by the frontend? Well that makes more sense to me anyway... maybe I didn't understand the requirements exactly, haven't looked at the designs for the feed in detail yet.

**Comment by dfrancks** [comment]
That makes sense, thanks Robin. Updated the ticket

**Comment by Naraujo13** [comment]
When creating the post, we set the expireAt (I suggest that name to keep the consistency with createdAt and updatedAt timestamps) at X time after the current date and then filtering it by the fronted params should be easy at the backend as @robinv85 said.

What is still not clear to me about this feature @dfrancks is when editing, what is the reference date? If the user edits a post and sets to expire "1 week", should we set it to 1 week from the date he is editing or 1 week from the date the post is created?

**Comment by dfrancks** [comment]
I think one week from editing makes more sense. I'll update the ticket.

**Comment by dfrancks** [comment]
I think one week from editing makes more sense. I'll update the ticket.

**Comment by robinv85** [comment]
@Naraujo13 this is also implemented on your posts PR right?

**Comment by Naraujo13** [comment]
> @Naraujo13 this is also implemented on your posts PR right?

Yes, I've added the `expireAt` at both posts endpoints, this should be solved with the posts migration.

**Comment by manualzuru** [comment]
@Naraujo13 should we close this ticket?

**Comment by Naraujo13** [comment]
It's not done yet, but I will assign this issue to me and link it with the PR for Posts migration since it is being done there. 
It is currently being reviewed.

**Comment by indirabhowmick** [comment]
@Naraujo13 - Can we please move to Done so that PM's can do UAT?

**Comment by Naraujo13** [comment]
Sure, I moved it to QA thinking that was the state  for that
