### ISSUE TITLE
Show border on posts in My Activity [Firefox]

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1461]
UPDATE: This seems to be happening on Firefox, but not on Chrome. I guess it has to do with those resolutions? I've no idea on this. It might affect other browsers?

### The Issue

On desktop, post cards in the Help Board have a border, this helps separate them visually. On My Activity, border is missing.

This:
```
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx)
html:not([data-scale]) .am-card:not(.am-card-full) {
    position: relative;
    border: none;
}
```
is overriding this:
```
@media screen and (min-width: 768px)
.dUrmQP.am-card {
    border: 0.05rem solid rgba(0, 0, 0, 0.5);
    border-radius: 0.2rem;
    padding: 2rem 2.4rem;
}
```
However, this also affects the individual post view, which should *not* have a border. So we can't just change that.

When looking at the Help Board posts we see they have a border because this is overriding the two above:
```
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx)
body .feed-posts .dUrmQP.am-card {
    border: 0.05rem solid rgba(0, 0, 0, 0.5);
}
```

**Comment by joshmorel** [comment]
@CamilaArias I can't see this at all. Screenshots?

**Comment by CamilaArias** [comment]
@joshmorel I checked again and the borders are there now, maybe someone fixed it or something changed, I don't know... Closing this.
