### ISSUE TITLE
Improve Create Account experience Indiv/Org

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1462]
### First Issue
_Mainly on mobile_

User hasn't selected an address, and nothing says it's mandatory (and because it doesn't look like it is, they don't choose one, because they might not want to give an address).
They only need to agree to Privacy Policy and T&C for the "Create Profile" button to become active. They click it and it turns white. Nothing happens, no feedback.

![image](https://user-images.githubusercontent.com/25089562/91627241-84260980-e98c-11ea-958b-b46acce650d7.png)

Button turns light-blue again when clicked, now inactive.
Unless they scroll up, they won't see the error message below address selection.

### Second Issue
_Mobile/desktop_

User is trying to sign up with an email that's already in use.
After realising they have to enter an address (issue 1), they click "Create Profile". Nothing happens again. No feedback again. The button is now outlined and whenever it's clicked again it says "Creating Profile..." for a second.

![image](https://user-images.githubusercontent.com/25089562/91627406-7e7cf380-e98d-11ea-909a-982b258a7147.png)

Only if they scroll up, they'll see the error message, at the top of the screen, saying their email needs to be unique. No prompts to do anything. Also, instead of checking for both address value an email uniqueness, we check one first and then the other, we should at least tell them everything that's wrong, especially when email being wrong is more important than not selecting an address.

### Suggestions

Add a required * hint for address to minimize friction. We do it for other fields so it's odd we don't do it for this.

Display any errors on top of the "Create Profile" button, which is where the user is looking. Feedback is important and needs to be instantly visible.

--- This will be a different ticket---
When we retrieve the email from the account they're trying to sign up with, check that is unique.
- If it is -> create account
- If it's not, tell them there's an account with that email -> sign in

Don't let them go through a process deemed to fail. Also if we do this, we don't need to show an error for expecting unique email because that situation would no longer be possible.

**Comment by cjohlmacher** [comment]
**Status Update:**

For First Issue: 

I've pushed to feature/1462 two things to resolve the issue:  
1.  Added text "Required" to the Address field.
2.  Create Profile button is disabled if the Address field is not filled in.

-----
Still need to address email issue for organizations and also the suggestion:
"Display any errors on top of the "Create Profile" button, which is where the user is looking. Feedback is important and needs to be instantly visible."

I can work on this tomorrow (9/7), but I just wanted to push up the changes for address field now.

**Comment by CamilaArias** [comment]
@cjohlmacher I'm going to create another ticket for the email issue, as it's going to need design as well! But thanks for getting started on the other stuff!

**Comment by cjohlmacher** [comment]
Okay.

With regards to the issue of "Display any errors on top of the "Create Profile" button, which is where the user is looking. Feedback is important and needs to be instantly visible.",  I pushed up new changes which duplicate the error message that appears if there is an issue when trying to add the user/organization to the server.  

Originally this message appeared just at the top of the page.  Now it appears at both the top of the page and directly above the Create Profile button.  This is fine on mobile, but maybe looks a little odd on a large screen since both errors appear:

![ErrorMessages_LargeScreen](https://user-images.githubusercontent.com/55671489/92519910-9e9f8480-f1cf-11ea-9d4c-9666ed813bdf.PNG)

Alternately, I could just have the error message appear above the Create Profile button and remove it from the top of the page.  

Any thoughts on that before I create a pull request?

**Comment by CamilaArias** [comment]
@cjohlmacher I think it's fine to keep just above the create profile button!

**Comment by cjohlmacher** [comment]
Okay, pull request created with the error only appearing above the create profile button.  Thanks for the input!

**Comment by rabbi08** [comment]
This issue is no longer valid as the the 'Type' and 'Industry' dropdown' are fixed via #1465 . hence, closing this issue as od now, please open a new issue, if this issue is observed again. Thanks
