### ISSUE TITLE
[Profile] Change text "I Need Help/I want to offer help" for their icons

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1463]
SVG for I want to offer help [here](https://fightpandemics.com/static/media/offer-help-unselected.aca98093.svg)

![image](https://user-images.githubusercontent.com/25089562/91627923-7c1c9880-e991-11ea-94a4-8f6755078c80.png)

For I need help [here](https://fightpandemics.com/static/media/request-help-unselected.c4adb941.svg)

![image](https://user-images.githubusercontent.com/25089562/91627940-9e161b00-e991-11ea-974d-ad6939b2a3f2.png)

**Comment by geobde** [comment]
@CamilaArias can you provide a direct link

**Comment by CamilaArias** [comment]
Hey @geobde they're in the hyperlinks, but here they go again:
https://fightpandemics.com/static/media/offer-help-unselected.aca98093.svg
https://fightpandemics.com/static/media/request-help-unselected.c4adb941.svg

**Comment by manualzuru** [comment]
This apply for both, org profile and individual profile and it should have an alt text. Like: "Requesting Help" "Offering Help"

**Comment by AshBha243** [comment]
@CamilaArias hi! Is this a still pending issue? I could see the Offer help and Need help images on the staging page.

**Comment by CamilaArias** [comment]
@AshBha243 I'm so sorry I never saw this, I need to figure out how to de-clutter my notifications! Where did you see the images? Looking right now and it's just text.
On Individual profile
![image](https://user-images.githubusercontent.com/25089562/94303063-a1c2a080-ff43-11ea-8ec1-ef377b84bdce.png)

**Comment by CamilaArias** [comment]
This will be implemented on the new profile design.
