### ISSUE TITLE
Improve Create Post Experience

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1464]
### Issue

User has set their address at country level (one very valid reason could be not giving much detail for privacy).
They want to create a post for either offering or requesting help, and they choose City/State for visibility.

The post shows only the country, and is displayed at country level, therefore not working like the user intended to.
Remember, we never tell them that the posts will be based on what they've set as their address.

_This happened in the MAG interview with Vlad and caused confusion, he picked city level visibility, his address is "Playa del Rey, CA, US", neither of those are cities_

We might have to put neighbourhood as an option, or put neighbourhood and city together and call it "local" visibility?

### Suggestions

- Show the user the actual location they will be posting at, at city/state/country level depending on what they choose
- Give them an option to change this address before posting
- If they select the post's visibility to be at a lower level of what they've chosen for their address, give them an error so they're aware the results won't be what they expect. Prompt them to continue at [higher level they'd chosen], or change their address.

- In the future: we might want them to be able to select a different location to make posts in, without requiring them to change their Account address.

**Comment by emtay** [comment]
@CamilaArias great callout. how about adding 'location' field and pre-populating based on user location but it is editable to be another city or state. (is it weird for user of one country to choose another country as location?) 

good call on error out if location=country and display is city or state, etc.

**Comment by CamilaArias** [comment]
I'm going to move this back to a Notion page.
