### ISSUE TITLE
[Mobile UI bug] Org Account drop-down causes page to stretch up to the limits of the screen

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1465]
### The Issue
If user edits organisation's type or industry:
Depending on the length of the option chosen, drop-down width is adjusted, causing the entire screen to be stretched beyond the space it should be within, and therefore length of divider lines and button's padding are stretched out and left-aligned elements are placed in the limit of the screen.

### Steps to reproduce
On mobile, go to organisation's account information.
Choose a long length option on the drop-down menus.

Short option
![Screenshot_20200829-030005](https://user-images.githubusercontent.com/25089562/91630284-64034400-e9a6-11ea-92df-67c6786c6016.png)

Long option
![Screenshot_20200829-030016](https://user-images.githubusercontent.com/25089562/91630289-71203300-e9a6-11ea-9c58-ac5e7ade5161.png)

It'd be great if we can fix this behaviour, and also we could have the drop-downs be a bit longer (within the limits of alignments) so longer options can be read a bit better.

Note this isn't a problem when creating the account, only when editing the settings.

**Comment by rabbi08** [comment]
Verified in STG on mobile, its working fine in both create and edit ORG page, refer below screenshot:

![FightPandemics (13)](https://user-images.githubusercontent.com/67168400/95503172-f66d0f00-0978-11eb-8001-aec5ff82420a.png)
![FightPandemics (12)](https://user-images.githubusercontent.com/67168400/95503174-f705a580-0978-11eb-9f6b-879ef98f1453.png)
