### ISSUE TITLE
Missing Facebook, Instagram and GitHub options and icons in Org Profile

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1467]
As an organisation I would like to display our Facebook, GitHub and Instagram links on our profile.

We need to add these options along the already present Twitter and LinkedIn links. Bear in mind Facebook doesn't use usernames, so this option should allow the user to paste the entire link, because usually people don't know what the link to their profile is, so they check, copy and paste the whole thing.

When there's a username in the Instagram URL field, or a valid link on the Facebook field, their respective icons should appear on the profile and redirect the user to those links, as the other icons do.

Icons can be found on [Figma](https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ#38722920) in **Design System / IOS Mobile** (filled, not circled ones).
![Screenshot_20200829-041448~2](https://user-images.githubusercontent.com/25089562/91631200-420dbf80-e9ae-11ea-97ed-603dce33783a.png)

**Comment by manualzuru** [comment]
Instagram icon looks completely different in comparison to the rest @CamilaArias

**Comment by rabbi08** [comment]
Verified in STG and it is working fine.

![image](https://user-images.githubusercontent.com/67168400/92657856-80b34c00-f2c3-11ea-8084-e4c0e7f66cc8.png)

**Comment by sheeba1** [comment]
Tested on both desktop and IOS device . Looking good
![image](https://user-images.githubusercontent.com/65972693/92658195-01b21980-f2ab-11ea-8f85-3bd6bd408fec.png)
