### ISSUE TITLE
[Mobile UI bug] Long addresses break screen

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1468]
### The Issue
Long addresses wouldn't be super rare, and atm they cause the address field to stretch out of the screen pushing elements outwards and practically breaking the screen.

### Example to reproduce
Type "Santiago del Estero" and select first option.
![Screenshot_20200829-050856](https://user-images.githubusercontent.com/25089562/91632440-f7447580-e9b6-11ea-9e29-7a7c766ed968.png)

Similar problem to [this one](https://github.com/FightPandemics/FightPandemics/issues/1465) 

Note this isn't a problem when creating the account, only when editing the settings.

**Comment by CamilaArias** [comment]
Another P2 because it really breaks the screen and makes some options unaccessible. Feel free to change if it should be less prioritised.

**Comment by manualzuru** [comment]
P2 is fine

**Comment by emtay** [comment]
@CamilaArias just so i'm clear- issue is on edit when addresses are super long. then user gets stuck to the right and it breaks the rest of the page?

what's the solution you're wanting? 
1- don't mess up other elements
2-have the cursor of address line be scrolled to the far right?

**Comment by CamilaArias** [comment]
@emtay It's not getting stuck to the right but the fact that the length of the address seems to dictate the width of the container of the page. The solution is making it work like when you create the account, which works fine, so I guessed someone who looks at the code would be able to find out why that is. I can add this to the ticket too.

**Comment by cjohlmacher** [comment]
Hi, can you check to see if this is still an issue in the latest build in staging?  
I think the changes for feature 1466 would have also addressed the issue here. 
Ref: [Pull Request 1488](https://github.com/FightPandemics/FightPandemics/pull/1488)
Ref:  [Build for Pull Request 1488](https://feature1466.fightpandemics.xyz)

**Comment by emtay** [comment]
@CamilaArias is it better now after Chris' fix?

**Comment by CamilaArias** [comment]
@emtay @cjohlmacher it's better now! Thanks :)

**Comment by rabbi08** [comment]
Verified in STG on iphone 11 pro max, working fine, refer below screenshot.

https://share.getcloudapp.com/Qwu0yogB
https://share.getcloudapp.com/jkuZjp9g
https://share.getcloudapp.com/rRu7dD4e
https://share.getcloudapp.com/DOuxLE54

But if user click on "View profile" of any Organisation say, "Sourced By FightPandemics(Other)" 
You will observe that there is delay in the post loading, which leads to UI distortion. Refer below screenshot.
https://share.getcloudapp.com/lluYeAyZ

But I suppose we can have new separate bug for this and verify and validate/close this one.
@CamilaArias @joshmorel @emtay @manualzuru please confirm

**Comment by joshmorel** [comment]
Hi @rabbi08 yeah that loading issue is related to the fact we don't have pagination for activity. There's an WIP pr hope to resolve soon - #1274 - that will resolve it.
