### ISSUE TITLE
[UI Bug] Blue outline left on comment's delete button after cancel deleting a comment

### ISSUE THREAD

**Issue by pemika-me** [FightPandemics/FightPandemics#1473]
### Issue
When the user clicks on the "Delete" button at the bottom of a comment they created and the confirm modal window popped up - if they click to cancel the deleting request, the modal window will disappear but left BLUE outline on the comment's "Delete" button. 

**Desktop:** will show blue outline text box for Delete button for a while, then it will disappear by itself.
**Mobile Web:** will show blue outline text box for Delete button until the user click on anywhere else

### Steps to reproduce
1. Access any post as a logged-in user, write a new comment
2. Click on "Delete" button at the bottom of the comment
3. Modal window pops up and ask for delete confirmation, click "Cancel" button
4. Observe the result that happens to the comment's "Delete" button.

### Expected behavior
No blue outline left after click to cancel comment deleting

![Screenshot_20200830-174757](https://user-images.githubusercontent.com/69309354/91657582-4dff9b80-eaec-11ea-8709-f954032924a7.png)

**Comment by manualzuru** [comment]
Also, when the outline appears, it shouldn't be that blue but our main color.

**Comment by cjohlmacher** [comment]
I looked into this issue and will push proposed change to branch feature/1473 when I get access.  Thanks.

**Comment by sheeba1** [comment]
tested on staging for both desktop and IOS
