### ISSUE TITLE
User Feedback Backend 

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#148]
Backend: the creation of a database for collecting feedback that lists user (if registered and logged in) or IP-address together with location based on IP address and answers to feedback questions

Requirements:
https://www.notion.so/fightpandemics/User-Feedback-UI-645a5edc39c44d91843d3b6e56f2eff8
Please contact Valentin Rudloff if there are any questions related to the requirements.

**Comment by DanielAlexander84** [comment]
I would like to do this in addition to the frontend [issue](https://github.com/FightPandemics/FightPandemics/issues/117) associated with it to get to know the project better. If anyone has an issue with this or I am taking too long, please let me know. 😄

**Comment by indirabhowmick** [comment]
@DanielAlexander84 awesome. Thanks for volunteering. I think for this you have to create the API to post the user feedback. The table has already been created to store data and should be present in the data model. I will create another ticket to connect the front end with back end - API connectivity. Any questions related to the data model, please contact Nicholas.

**Comment by Naraujo13** [comment]
Hi @DanielAlexander84, if you need any help with the data model, please reach out.

[Here](https://github.com/FightPandemics/DataModel/blob/master/v2/scripts/Mongoose_Script/feedbacks.js) is the definition of the feedback model, already in mongoose, so you can use it to save some time and focus on the endpoints.

**Comment by DanielAlexander84** [comment]
Thank you both for the info. I plan on working on this during the weekend when I will have more free time. 😄
