### ISSUE TITLE
Create Footnote for Mobile and Desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#149]
- [ ] Create Footnote for Mobile and Desktop

- [ ] All the UI's need to include the Footnote

Requirements:
https://www.notion.so/fightpandemics/Footnote-24895e52864547a5be0c365fcccc3595

**Comment by PriyalPatney** [comment]
> * [x]  Create Footnote for Mobile and Desktop
> * [x]  All the UI's need to include the Footnote
> 
> Requirements:
> https://www.notion.so/fightpandemics/Footnote-24895e52864547a5be0c365fcccc3595
