### ISSUE TITLE
To retain the filter values when user clicks back from an individual post

### ISSUE THREAD

**Issue by pemika-me** [FightPandemics/FightPandemics#1498]
### Issue
When the user clicks on back button from any individual post to go back to the Help Board, found all filters was cleared and lead the user to the top of Help Board.

### Steps to reproduce
1. Log in (to be able to access a post), and go to Help Board
2. Select at least one filter, then scroll down the page for a while
3. Click to access any post there
4. Once redirect to the post, click back button at the bottom of any individual post (or :arrow_left: of the browser) to go back to the Help Board page
5. Observe the result, you will see that all filters the user selected are cleared, also lead the user to the top of the Help Board page

### Expected behavior
When a user clicks on back button at the bottom of any individual post (or :arrow_left: of the browser), all filters should be remained as last selected. Also land the user to where they last left off on the Help Board.

**Comment by joshmorel** [comment]
Thanks @pemika-me - definitely something we need for users when going from feed > post/profile > feed.

@OzkanAbdullahoglu I know you had looked into how Twitter handles list data from pagination perspective is there anything else that points to a resolution for this one?

In any case let's get the new pagination fixed and merged then someone can work on this one.

**Comment by OzkanAbdullahoglu** [comment]
@joshmorel In twitter when you chose a trend and then when you go back to the feed, filters resets , and also It looks like same in advanced search too, actually all filtering activities handling with searching. Neither I analysed deeply, nor I am a great fan of twitter, but it seems like technically they desire to show off more posts in numbers.
It is a decision though after we merge new pagination, It can be done as It is requested.

**Comment by pemika-me** [comment]
Hi team, I am the ticket's author and just decided to leave FP. Please contact PM or engineer lead in case you would need some info or review related to this ticket. Thanks. 😊

**Comment by OzkanAbdullahoglu** [comment]
@pemika-me thanks for your help until now.:)
@joshmorel  I think resetting filters is a better practice then keep them. After new pagination, this logic is still persisted.
