### ISSUE TITLE
Turn a URL within text (Post, Comment, future- message) into hyperlinks

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1499]
As a user, when I enter a URL in a post or comment, I expect those to become hyperlinks so that users can easily click on them and have it open a new tab.

This will require recognizing text as URL based on www. or https://www. etc.
Form into hyperlink and upon click, open to a new tab (not go to website in current tab because we want to keep FightPandemics tab open).

Note, we're not validating the URLs, so users may have added incorrect URL.

Here is our FightPandemics URL where it is not a hyperlink:
![image](https://user-images.githubusercontent.com/43509421/92409494-b1de2180-f0f5-11ea-9441-211427425308.png)

AC:

Given user adds www.(URL) or http:// or https:// to a post,
When post is submitted,
Then www.URL becomes a hyperlink that opens to a new tab upon click.

Given user adds www.(URL) or http:// or https:// to comment,
When comment is submitted,
Then www.URL becomes a hyperlink that opens to a new tab upon click.

Given user adds short URL without www.(URL) or http:// or https:// to post or comment, (like fightpandemics.com)
When post or comment is submitted,
Then it will not be hyperlink and instead will remain as text.

**Comment by haoxianZ** [comment]
Hi, I was working on this since it was assigned through slack, please take a look of the pull request of this branch. Sorry for not assigning myself here.

**Comment by ashminbhandari** [comment]
Ah, got it. Thanks for LMK.
