### ISSUE TITLE
[Mobile-android]Long Address cause the page stretch up to the limits of the screen and the content not fully visible to the user.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1503]
Environment: fightpandemics.com
Device:Samsung Galaxy s8
Browser:Google Chrome.
Steps to create:
1.Login with valid username,password.
2.Choose Request help/offer help.
3.Choose Medical/Other Help.
4.Provide address that is long.(ex:Type 19020 choose the option Avenue of americas,19020....)
5.It moves to Email address page.Click on back arrow.
The page is stretched up due to the long address and the user not able to view all the content in the page.
![Screenshot_20200906-195604_Chrome](https://user-images.githubusercontent.com/41587211/92529340-58125000-f1f8-11ea-96a3-f1dda953ab38.jpg)

**Comment by joshmorel** [comment]
Thanks @nivetheatha I think I have someone to work on this. I would do exactly what google itself does

![Screenshot_20200908-175034_Maps](https://user-images.githubusercontent.com/10546720/92531238-e3d9ab80-f1fb-11ea-9383-387806a9069d.jpg)

**Comment by joshmorel** [comment]
@nivetheatha actually nvm it's fixed in staging should be in prod soon. https://github.com/FightPandemics/FightPandemics/issues/1468

**Comment by nivetheatha** [comment]
@joshmorel thanks for letting me know. Will close this issue.
