### ISSUE TITLE
Notifications: Email Notification Unsubscribe link

### ISSUE THREAD

**Issue by nfranklin9** [FightPandemics/FightPandemics#1507]
I receive email notifications when users interact with my post. I need a link at the bottom of these emails to "Unsubscribe" me from these emails and access the Notification Settings page to change my email preferences. The "Unsubscribe" link may either link directly to the Notification Settings page, or unsubscribe the user in some other way (and a different link goes to the Notification Settings page).
Notification settings page: https://github.com/FightPandemics/FightPandemics/issues/1427

Acceptance Criteria:

- [ ] The Unsubscribe link is included in all Notification emails

- [ ] The Unsubscribe link is shared with other FightPandemics components that send emails (Messaging, Signup, etc)

- [ ] The Unsubscribe link allows users to stop receiving email notifications.

This unsubscribe button will call the backend to process the unsubscribe and update mongodb user to set them to opted out (or maybe keep track of opt outs in a separate model, with a reference to user)
https://fightpandemics.slack.com/archives/C018ZNAD62Y/p1599171215043400

I think it’s actually required that the unsubscribe page be accessible directly from the email per CAN-SPAM requirements. The CAN-SPAM Act requires that every email sent must contain a way to unsubscribe from that email list. In addition to offering the opt-out option, it must be easy to find and uncomplicated to do.

-The account update via web form should be relatively simple but we also need something that can be done securely from a link in the email
-We should include a token in the unsubscribe URL that the backend can validate
-We also need a special backend route for unsubscribing from email notifications via email - we'd need to authenticate with some other kind of token then what we use for auth. https://fightpandemics.slack.com/archives/C018ZNAD62Y/p1598202665129800
-We may need a backend route and store settings in the backend

**Comment by ddveloper** [comment]
I assume the unsubscribe link will be generated by Lambda, right @mannykary , after the user click on the link, will it send a request to the backend directly? what token are we going to use?
