### ISSUE TITLE
E2E Cypress test - Test "Login fail alert appears when incorrect email & password are entered and submitted by user" fails 

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1513]
Env: Dev

Test "Login fail alert appears when incorrect email & password are entered and submitted by user" fails when it runs multiple times.
Expected error message: Login failed, reason: Wrong email or password. 
Actual error message: Login failed. Maximum number of sign in attempts exceeded.

```
 User signs into account
cypress-e2e          |          Login fail alert appears when incorrect email & password are entered and submitted by user:
cypress-e2e          |      AssertionError: Timed out retrying: Expected to find content: 'Login failed, reason: Wrong email or password.' within the element: <span.ant-alert-message> but never did.
cypress-e2e          |       at Context.eval (http://client:3000/__cypress/tests?p=cypress/integration/e2eTests/signin/signIn.spec.js:256:22)
```

![FightPandemics Sign In Page -- User signs into account -- Login fail alert appears when incorrect email   password are entered and submitted by user (failed)](https://user-images.githubusercontent.com/21987083/92908667-bd4b8880-f426-11ea-8388-128ce8d9659d.png)

**Comment by jessica-lau** [comment]
@galeza I believe the number of times a user can enter the same wrong password/email combination to see the "Wrong email or password" error is up to 10 times. Starting the 11th time, when the user enters the same wrong password/email the error changes to "Maximum number .... was exceeded". With that being said, I did run the test continuously for 25+ times and didn't encounter the test failing (I'm running it on the staging url and not localhost url). 

I made a change to the sign in test in PR# [1500](https://github.com/FightPandemics/FightPandemics/pull/1500) to see if it will fix this error for you. Can you please run it and see if you still encounter the error? I ran it again after I made this change and it's working successfully for me:

![image](https://user-images.githubusercontent.com/56090896/93023093-9aea7400-f5ba-11ea-8ad7-e1eb3409f183.png)

![image](https://user-images.githubusercontent.com/56090896/93023110-accc1700-f5ba-11ea-98f1-ff8bb755bf7d.png)

**Comment by galeza** [comment]
Hi @jessica-lau 

I run branch feature/cypress-test-feedback-modal several times. 
1. I haven't seen any issues related to Footer
2. But the test Sign In Login fail alert appears when incorrect email & password are entered and submitted by user fails each time.
```
cypress-e2e          |   1) FightPandemics Sign In Page
cypress-e2e          |        User signs into account
cypress-e2e          |          Login fail alert appears when incorrect email & password are entered and submitted by user:
cypress-e2e          |      AssertionError: Timed out retrying: Expected to find content: 'Login failed, reason: Wrong email or password.' within the element: <span.ant-alert-message> but never did.
cypress-e2e          |       at Context.eval (http://client:3000/__cypress/tests?p=cypress/integration/e2eTests/signin/signIn.spec.js:261:22)
```

**Comment by jessica-lau** [comment]
@galeza just added the random email generator code, like how you did for the mocha backend test. Please refer to PR#1500. Let's see if you still encounter the error. :)
