### ISSUE TITLE
Messages: Backend Services

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1521]
As a product team, we need new API services to support messages so that we can manage:

1. Conversation/message thread creation

> thread_id (id)
> thread_createdAt (date time)
> thread_updatedAt (date time)
> thread_status ( )
> thread_participants (array)
> > participant_id (id)
> > participant_name (name)
> > participant_type (org vs. indiv)
> > participant_newMessages (boolean)

2. Message creation
> message_id (id)
> message_createdAt (date time)
> message_updatedAt (date time)
> message_content (text)
> message_threadId
> message_status*
> message_author
> > author_id
> > author_name
> > author_type
> > author_location

> message_postRef
> > post_id
> > post_objective
> > post_title
> > post_content
> > post_author

3. Update "Read" status after message was opened/read
> message_status*

**AC**

- Final contract
- Demo conversation creation
- Demo message creation with post
- Demo message creation without post
- Demo read status update

**Comment by WillHiggs** [comment]
How could I build this?

**Comment by emtay** [comment]
@WillHiggs we're evaluating Socket.io instead of Rest API. Meeting Tuesday 12 pm PT/9 pm CEST to review demo from this story: https://github.com/FightPandemics/FightPandemics/issues/1542

Please join us!
