### ISSUE TITLE
NavLink on NearestHospital page not working

### ISSUE THREAD

**Issue by cjohlmacher** [FightPandemics/FightPandemics#1527]
The NavLink on the /nearest-hospital page is not working with console warning: 

"The component Styled(Drawer) with the id of "sc-pRsKx" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component."

StyledDrawer needs to be moved out of the functional component so that the component renders properly.

**Comment by joshmorel** [comment]
This also will fix the fact that there is no smooth animation in the slider as these examples.

Current state you see it is abrupt unlike examples: https://ant.design/components/drawer/

![drawer-abrupt](https://user-images.githubusercontent.com/10546720/93215696-c2fde280-f734-11ea-8fb8-9c8090092334.gif)

**Comment by rabbi08** [comment]
Verified in STG, the drawer is rendering smoothly no grey sliding area is observed on the phone:
Devices tested on : iphone 11 pro max
Simulation:
Google Pixel 3A
https://share.getcloudapp.com/8LurjAL8

iPhone XR
https://share.getcloudapp.com/P8uyE4jw
