### ISSUE TITLE
[Mobile] Onboarding offer or request help filter not applied

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1530]
Noted #1526 along with another issue with a different cause

This affects all mobile viewports (dev tools, iOS, Android) since offer/request help filters are handled different for mobile vs desktop view. 
All environments: staging/production/etc

**Steps:**

1. Visit https://staging.fightpandemics.work/ or https://fightpandemics.com/ (with mobile device or in dev tools mobile view)
2. Click "Request Help"
3. Click "Medical"
4. Click "Show me postings from anywhere"
5. Click "Skip"
6. Check filters

**Result:**

Filter applied on Type but not "Offer or Request Help"

**Expected:**

"Request Help" filter should be applied.

![offer-add-help](https://user-images.githubusercontent.com/10546720/93236456-dcab2400-f74c-11ea-82c2-47e4a3835831.gif)

**Comment by leon-i** [comment]
Hi, I believe I found a fix for this.
