### ISSUE TITLE
Add "We are here to offer" section in Create Organization and Edit Organization Account screens.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#1538]
As a user,
When I am on the "Create Organization" or "Edit Organization account" page,
Then I should be able to see a section "We are here to offer:" along with "We are here to request:" section with the following options:

- Donations

- Volunteers

- Staff

- Information

- Resources/Tools

- Others

These options would be same for both "We are here to offer:" and "We are here to request:" sections. (Note: As per the current implementation "What are you looking for?" question becomes "We are here to request:')

When a user selects "Other" option, then a text box appears where the user can enter text (max upto 60 chars, if it exceeds 60 chars then an error message should be shown "Maximum limit 60 chars")

Figma link (Desktop): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=19559%3A97078
Figma link (Mobile): https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=19735%3A97620

Designs:
![create-org-profile](https://user-images.githubusercontent.com/66698276/93667088-d1cff680-faa0-11ea-960a-a4044f3083e1.png)

![create-org-profile (1)](https://user-images.githubusercontent.com/66698276/93667096-dc8a8b80-faa0-11ea-83df-2cfabe1d5570.png)

**Comment by joshmorel** [comment]
@tejasm2 is there a separate BE ticket for this or should it all be done together. As you can see this requires a backend & data model changes. https://github.com/FightPandemics/FightPandemics/blob/872629d9b75c8251a16d9c2afdf8c6c070e070b2/backend/lib/models/OrganisationUser.js#L13

If the later I'd add the appropriate labels. And @Elohina are you comfortable taking this on - shouldn't be too hard BE wise I don't think. If not maybe it's best to tackle as one issue with two contributors (@tejasm2  could ask in Slack).

**Comment by Elohina** [comment]
@joshmorel I think that I can work on all together. I took a look at what needs to be done in the back end and I could see that I just need to change the organization's model and the schema in order to add the new needs.

**Comment by tejasm2** [comment]
Ohh yes @joshmorel , this needs a backend ticket. Thanks for the call out. @Elohina do you need a separate backend ticket for the same?

**Comment by Elohina** [comment]
No, I think it is ok how it is @tejasm2

**Comment by rabbi08** [comment]
As per the recent updated for 'Organization profile' page, 'we are here section' does not exist. Please see below screenshot.
For both Add/Edit Org Profile page, user is given an option as:
 "What are you looking for"

in place of 'We are here section"

Hence, this issue is no longer valid, so closing this one. Please feel free to reopen or log a new ticket if this issue have been observed again. Thanks.

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/67168400/103487261-14101000-4dd2-11eb-9f3c-403b7bd6d57a.png">
