### ISSUE TITLE
Create Organisation Profile Type and Industry Dropdowns are too narrow

### ISSUE THREAD

**Issue by jyclam** [FightPandemics/FightPandemics#1554]
## Currently: 
![Screen Shot 2020-09-25 at 1 41 27 PM](https://user-images.githubusercontent.com/26049767/94314820-2c9c9e80-ff36-11ea-9ecf-b3f4c4d936e3.png)

**Comment by rabbi08** [comment]
Verified in STG  for 'Create Org" as working fine but it is NOT for EDIT org profile, Refer attached GIF:

![image](https://user-images.githubusercontent.com/67168400/95546937-d1f05180-09cf-11eb-8392-f63a6ab1fd6e.png)

adding new bug to fix this issue for EDIT Org page too #1621 

![image](https://user-images.githubusercontent.com/67168400/95547010-fd733c00-09cf-11eb-89e4-a737c86b56be.png)
