### ISSUE TITLE
User(logged IN/NOT) is unable to LIKE a post from the profile of an Individual/Organisation  who posted the post

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1561]
Scenario 1:
staging - User is not signed in
1. Go to Help board 
2. Go to the Individual profile  OR Org profile -for a particular post.
3. Click on the 'like '  button of a post listed under activity.
Expected: Clicking on 'like' should redirect user to login page.
Actual: 'Like' is not clickable from profile page

Scenario 2:
staging - User is logged in.
1. Go to Help board 
2. Go to the Individual profile  OR Org profile -for a particular post.
3. Click on the 'like '  button of a post listed under activity.
Expected:  'like' should be clickable
Actual: 'Like' is not clickable from profile page

**Comment by leon-i** [comment]
Hi, I'd like to grab this issue, so I've assigned myself
