### ISSUE TITLE
There is no warning message when file is over 5MB for Profile Photo

### ISSUE THREAD

**Issue by Monica0843** [FightPandemics/FightPandemics#1562]
When choosing a supported profile photo type but size is over 5MB, there is no warning message or anything alike. 
Steps:
1. Sign in and click Profile - My Profile on the right top corner 
2. Hover over the camera icon and click when it turns to a hand pointer 
3. Choose a file of supported type (e.g., .jpeg) but size over 5MB and click Open/Choose(depends on the OS) 

Expected Result: A warning message telling User that file cannot be over 5MB (or something alike) 
Actual Result: The window just get dismissed without anything
Reproducible environment - MacOS - Chrome, Windows 10 - Chrome 
Not reproducible environment - MacOS + Safari

**Comment by kannan1001** [comment]
In addition to this issue, the user is not able to remove profile picture/photo
Steps to reproduce:

        1.Sign in and Select Profile - My Profile
        2.click on camera icon and choose a supported file  which you wanted to upload and click on open
        3.Click on submit
Once the profile picture is uploaded the user is able to change the picture but not remove the picture.
As a user if I wish to remove my picture I should be able to remove it , not only change the picture.

**Comment by joshmorel** [comment]
I'm pretty this is resolved as part of #1548 PR - now in staging soon in prod. If mistaken please reopen (screenshot & file size would help).
