### ISSUE TITLE
Project Management for FP

### ISSUE THREAD

**Issue by mvijays** [FightPandemics/FightPandemics#1570]
Mock auth back end component for local development.

This would be similar in purpose to #882 .

By mocking the Auth component we would decrease new dev onboarding friction while also reducing the need to widely share the dev auth account secret.

Back end, Devops, P4

**Comment by joshmorel** [comment]
Hi @mvijays . What's this issue been created for? It's the same text as #1495 but with a different title...

**Comment by mvijays** [comment]
Hi Josh,

Let me research a bit on that and get back to you.

Regards
Vijay

**Comment by mvijays** [comment]
Same issue as #1495 and a duplicate.
