### ISSUE TITLE
Adjust screen for Navbar

### ISSUE THREAD

**Issue by mvijays** [FightPandemics/FightPandemics#1572]
The Issue

Navbar looks fine on Desktop, but on smaller screens, padding-left is 15px on the left-navbar when it should be 23px as per Zeplin, and there's no space above the entire navbar. It just doesn't look good having the logo touching the top of the screen, no space in-between.

Suggestion to Fix

Adjust padding-left on left-navbar
If we can't keep the same height value for some reason then maybe:

Add padding-top on navbar
Add the same amount in margin-top of the "Help Board" bar-tab which is below
(idk if this is the tidy way to do this, but yeah)

Edit: Same space for the top should be in the bottom!

Front end, front end clean up, mobile 

P4 level

**Comment by mvijays** [comment]
Ok thanks, I will close #1572 if it is my request that I opened.

Regards
Vijay

**Comment by rabbi08** [comment]
Verified in STG as working fine. Refer below screenshot.
https://share.getcloudapp.com/7Ku8mdEb
![image](https://user-images.githubusercontent.com/67168400/95521916-bf0e5a80-0998-11eb-81c8-f2a939b62969.png)
