### ISSUE TITLE
Localisation: Change globe icon and change location of icon

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1574]
1. Update the globe svg icon in the nav bar with the new [blue svg icon](https://zpl.io/2ZeQ6e4) for **Desktop**
2. Update the globe svg icon in the menu with the [white svg icon](https://zpl.io/br4wk8L) for **Mobile**

3. Change location of the globe icon to be on the right side of the Feedback icon in the nav bar for **Desktop**

**Current:**
<img width="528" alt="Screen Shot 2020-10-02 at 4 43 06 PM" src="https://user-images.githubusercontent.com/66695502/94972262-7f45ff80-04ce-11eb-8860-713c84db180a.png">

**New:**
Link to Zeplin design - [zpl.io/VKeqQP7](zpl.io/VKeqQP7)
<img width="735" alt="Screen Shot 2020-10-02 at 4 43 34 PM" src="https://user-images.githubusercontent.com/66695502/94972273-853be080-04ce-11eb-8406-4402ad2ce2b1.png">

**Comment by idjevm** [comment]
This has been resolved by #1590

**Comment by rabbi08** [comment]
Verified in STG as working fine, Refer below screenshot.
![globeicon](https://user-images.githubusercontent.com/67168400/95523829-afdddb80-099d-11eb-9713-5d42dae743d3.png)
