### ISSUE TITLE
Localisation: Adding German translations to webapp

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1576]
Since we are adding a new language, please follow the instructions below to add German correctly to our codebase. We are using this ticket to test whether our instructions are clear enough :) 

Instructions:
> If you are adding a **new language**, you will have to edit `client/src/locales/index.js` and `client/src/locales/languages.js` . You will need to import the correct file in `index.js` and also add the language and ISO code to the `localization` and `MENU_MAP` objects.

**Comment by rabbi08** [comment]
In STG, able to view/select 'German' language in the frontend. Refer below image:

![image](https://user-images.githubusercontent.com/67168400/95522592-7bb4eb80-099a-11eb-9990-95a4b136c8b1.png)
