### ISSUE TITLE
Localisation: en_US.json has references to "organisation" instead of "organization"

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1582]
I first noticed this in the navbar:
![image](https://user-images.githubusercontent.com/4285073/95030168-a03f5980-0662-11eb-95a5-cc5a13427442.png)

Looking at the locale JSON file for [en_US](https://github.com/FightPandemics/FightPandemics/blob/staging/client/src/locales/translations/en_US.json), I noticed that "organization" is being spelled as "organisation" in some places. This should be corrected to "organization" with a z.

**Comment by guvarallo** [comment]
Hi @mannykary you are right, in en_GB is ok to use with 's', but en_US is strictly with 'z'. Are you on it? If not I can fix it.

**Comment by mannykary** [comment]
@guvarallo no, you can go ahead and pick up this ticket.

**Comment by rabbi08** [comment]
Verified in STG, it is working fine, Refer below GIF:

For American English "Organization' is displayed whereas, for British English "Organisation" is displayed.
https://share.getcloudapp.com/X6udorBk
