### ISSUE TITLE
Add accessibility features on website

### ISSUE THREAD

**Issue by mvijays** [FightPandemics/FightPandemics#1585]
Accessibility features on website (e.g. tabIndex, keyboard support)

User experience; P4

**Comment by joshmorel** [comment]
This was done with accessibe integration around a month ago - you can see on prod.

![image](https://user-images.githubusercontent.com/10546720/95684578-aa141000-0bc0-11eb-87e4-b251d1ee68ce.png)

If you have questions about it ask @kterry1 in Slack.

**Comment by mvijays** [comment]
Ok thanks !
