### ISSUE TITLE
Privacy settings

### ISSUE THREAD

**Issue by mvijays** [FightPandemics/FightPandemics#1588]
Privacy setting (example allow user to share or hide location in profile)

Feature

Grow of User experience

**Comment by joshmorel** [comment]
Hi @mvijays is this linked to a feature in Notion? Are there any designs? For a developer to work on this we need more details.

For example - https://github.com/FightPandemics/FightPandemics/issues/1499

**Comment by mvijays** [comment]
Hi Josh,

This is linked to a profile anybody creates in Notion. In the profile,
there is notification and settings option with a wheel symbol. But users
must be able to turn off or on  certain specific options like location etc.
and be able to manage profiles.

Regards
Vijay Suryavanshi

**Comment by skrithiga** [comment]
@mvijays We are not finalized on the requirements for this feature yet and this could branch out to privacy settings and visibility settings for posts, profile information etc. Until specs are reviewed/approved in Notion for features, we should not be creating tickets in github.

**Comment by mvijays** [comment]
Ok sounds good. I have closed the ticket for this already.

Regards
Vijay

**Comment by mvijays** [comment]
1588 ticket is closed because this will branch out into small requirements per Krithiga.
