### ISSUE TITLE
Visibility of the post based on the distance of searched location.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1592]
Environment-Staging
Tested on Samsung Galaxy S8
Browser-Google chrome
Steps to create:
1.Create a post (Ex. Created  post on Request help ,Offer help each in location Bensalem,Pa,USA ).
2.Goto help board and search the same location.(ex: search as Bensalem, PA then post is visible in the help board.)
3.Search Nearby location Ex: Bristol,Pa (6 miles from Bensalem,Pa).
Expected Result:
Posts should be sorted based on the distance of searched location.
Actual Result:
Post created  is not visible in the help board. Even posts from Princeton(23 miles from bensalem) is visible.

![GIF-201005_163354](https://user-images.githubusercontent.com/41587211/95129521-1f976080-0729-11eb-92a3-768d9ad0f917.gif)
![Screenshot_20201005-153041_Chrome](https://user-images.githubusercontent.com/41587211/95129531-23c37e00-0729-11eb-8d41-8ec7bdc150fc.jpg)
![Screenshot_20201005-152924_Chrome](https://user-images.githubusercontent.com/41587211/95129561-2f16a980-0729-11eb-89ac-44fbf2bf1347.jpg)

**Comment by rabbi08** [comment]
@nivetheatha 
Please check the location "visibility" of the post when it is created. If the visibility is set as "city" then the post only be visible when that particular city is selected. Mostly the post's visibility depends on the location visibility selected while post creation. Thanks

**Comment by nivetheatha** [comment]
@rabbi08 Thanks for letting me know. Yes I didn't check the visibility option in the post.
