### ISSUE TITLE
Sign Up/Sign In Backend Server Validation Messages and Status Codes

### ISSUE THREAD

**Issue by jessica-lau** [FightPandemics/FightPandemics#1594]
When running backend tests on staging regarding signup/sign in there are:

1. return of some validation messages from the server that need to be rephrased 
2. incorrect HTTP status code/error being returned from server

The below tests are based on the valid email format (64max)@+(63max)+‘.’+(tld) within the max char limit of 254 implemented by Auth0.

**Scenario 1: _**Sign Up**_**
When I enter more than 64 characters before '@' for the email, the error message returns 500 internal server error when it should return an "Email address is invalid" related message (400 Bad Request status code) .

![image](https://user-images.githubusercontent.com/56090896/95108647-89077700-0709-11eb-8b1c-24ad39fe8706.png)

**Scenario 2: **_Sign Up & Sign In_****
Password fields left empty on signup/sign in triggers 500 internal server error when it should return a 400 Bad Request code with message "Password is required".

![image](https://user-images.githubusercontent.com/56090896/95112750-59f40400-070f-11eb-9a4b-ee6f054507b9.png)

**Scenario 3: **_Sign Up & Sign In_****
There are a couple of tests pertaining to when an invalid email format is entered and the server returns an error message of 'body.email should match format "email"'. Such messages in this format should be rephrased to "Email address is invalid" or “Email address is required” instead. Below are some examples:

Domain exceeding 63 characters on signup/sign in -
![image](https://user-images.githubusercontent.com/56090896/95109793-139ca600-070b-11eb-8cc1-d11779765e01.png)

Email field left empty on signup/sign in -
![image](https://user-images.githubusercontent.com/56090896/95110090-81e16880-070b-11eb-9dee-c14a8af18d95.png)

Unspecified email domain on signup/sign in -
![image](https://user-images.githubusercontent.com/56090896/95110365-e4d2ff80-070b-11eb-83df-c4c69b0b0f80.png)

**Scenario 4:** 

While keeping the local part and domain part of an email within their character limits then using an invalid tld (ones that don't exist on the [tld list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)), I received two different outcomes.

- 62 char for local + @ + 5 char for domain + . + 125 char for tld = 194 total. Received error message "body.email should match format \"email\"

![image](https://user-images.githubusercontent.com/56090896/95116623-4f3c6d80-0715-11eb-951d-2c790a45ed9b.png)

- 62 char for local + @ + 5 char for domain + . + 4 char for tld = 73 total. Received no error message.

![image](https://user-images.githubusercontent.com/56090896/95116662-5c595c80-0715-11eb-9cef-5ef7ad3995d5.png)

**Scenario 5:** 

After running the login test continuously 10+ times, the two tests in the screenshot failed because they're expecting a 429 status error (too many requests) instead of a 401 status error (unauthorized). The message we expect the server to return is 401 unauthorized user. Apparently, the 429 error appears due to rate limits being set to protect the server from intentional abuse. X-RateLimit-* headers can be set with information about the limits. How can we set this and what limits can we use?

https://blog.bearer.sh/error-429-too-many-requests-what-to-do-when-youve-been-rate-limited/

![image](https://user-images.githubusercontent.com/56090896/95122979-48b2f380-071f-11eb-9342-a710f94c9bef.png)

**Comment by jessica-lau** [comment]
@galeza I'm adding you to keep you in the loop. This is regarding issues with the backend tests for signup/sign in we've come across and discussed on Slack. Please let me know if I'm missing anything.

**Comment by ddveloper** [comment]
I'd like to start working on the error code part for now and see what we conclude on the rate limitation.

**Comment by galeza** [comment]
@ddveloper 

The goal should be: use the same **validator/lib/isEMai**l function in backend (the same validations as for the frontend)

**Comment by ddveloper** [comment]
Thanks @galeza 

I made 3 changes based on the frontend validation code, plan to test them soon with Jessica's script
please have a look and let me know if the changes make sense.

- [add required packages for email validation](https://github.com/ddveloper/FightPandemics/commit/3662687c71c776e2c3207fc047d2528d40468fdc)
- [use same email validation code from front-end](https://github.com/ddveloper/FightPandemics/commit/37304ef56e82eb25773dac3bad6347b01c324507)
- [update endpoint for sign up to validate email and password](https://github.com/ddveloper/FightPandemics/commit/6cf651835ef90f124bc8e195502c90ff7a0acb41)

Note: the isValidEmail also is used as userSchema's email validator

**Comment by galeza** [comment]
Hi @ddveloper

You can create draft PR and we will ask other developers for a review :)

**Comment by ddveloper** [comment]
created one draft PR while it didn't pass the check "Post Review Build URL", error message: "403 - Resource not accessible by integration", I will need some help to understand this error ...

**Comment by galeza** [comment]
Hi @ddveloper 
I think that you use a fork?
Please see links:
https://fightpandemics.slack.com/archives/C010V0DDHLN/p1589775520305100?thread_ts=1589768215.304500&cid=C010V0DDHLN
https://github.com/FightPandemics/FightPandemics/#review-branches

**Comment by ddveloper** [comment]
Draft PR #1598 is created for code review, (I need to run Jessica's tests before merging)

**Comment by ddveloper** [comment]
tested with Mocha integration tests, #1598 has the latest code
- scenario 1-4 should be resolved (except the error message is in a different format, translation keys are used currently)
- for scenario 5, I guess the rate limit comes from [Auth0 Rate Limit Policy](https://auth0.com/docs/policies/rate-limit-policy), not sure how to get around it, @mannykary @joshmorel
