### ISSUE TITLE
Localisation - incorrect language name

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1604]
env staging

Please correct Polish language name. It should be Polski. (not Polski**e**)

![Screen Shot 2020-10-07 at 13 46 10](https://user-images.githubusercontent.com/21987083/95326841-7de84e80-08a3-11eb-9a6a-8b292dc6c5c0.png)

**Comment by rabbi08** [comment]
Verified in STG the spellings are correct, refer below screenshot.

![FightPandemics (14)](https://user-images.githubusercontent.com/67168400/95522164-5b386180-0999-11eb-89b3-fcec5897a1a0.png)
