### ISSUE TITLE
Localisation: Add ID attribute to Language Selection

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1611]
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Globe icon | NAV_LS |
| 2. | Chinese Traditional | NAV_LS_ZH_TW |
| 3. | English (American) | NAV_LS_EN_US |
| 4. | English (British) | NAV_LS_EN_GB |
| 5. | Polish | NAV_LS_PL |
| 6. | Peninsular Spanish | NAV_LS_ES_ES |
| 7. | German | NAV_LS_DE |

German is not shown in the images below, but it is already added to the platform, so we need to assign the ID!

**Desktop Ver:**

<img width="600" alt="Screen Shot 2020-10-07 at 3 08 17 PM" src="https://user-images.githubusercontent.com/66695502/95387022-c9a3f380-08b5-11eb-9ea2-ebb869020a93.png">

<img width="417" alt="Screen Shot 2020-10-07 at 3 36 08 PM" src="https://user-images.githubusercontent.com/66695502/95387082-de808700-08b5-11eb-904a-824d441ec0be.png">

\
**Mobile Ver:** 
<p float="left">
  <img src="https://user-images.githubusercontent.com/66695502/95387149-f1935700-08b5-11eb-8d25-56f59c91d9b6.png" width="200" />
  <img src="https://user-images.githubusercontent.com/66695502/95387163-f48e4780-08b5-11eb-8d59-cba58f225017.png" width="200" /> 
</p>

**Comment by joshmorel** [comment]
Resolved by #1612
