### ISSUE TITLE
Changes introduced by Lokalise - English language

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1623]
env: staging

Tests set language to Eng-US

Some tests fail. @doheekim93 Please decide - should we change tests in the below scenarios or open an issue to correct application?:

1. Feedback modal window:
    a. **expected**: What is your age? - question mark was removed.  **Actual: What is your age**
    b.**expected**: Submit Feedback - button name was changed.  **Actual: Submit**

2. Recover Password
    a. **expected**: Recover Password - screen H1 title. **Actual: Forgot Password**

3. Sign In screen:
    a. **expected**: Forgot Password? - link to the next screen. question mark was removed. **Actual: Forgot Password**
![Screen Shot 2020-10-09 at 14 52 33](https://user-images.githubusercontent.com/21987083/95585290-5201d000-0a3f-11eb-9a6b-0a7df0d1cfa5.png)
![Screen Shot 2020-10-09 at 14 53 07](https://user-images.githubusercontent.com/21987083/95585303-575f1a80-0a3f-11eb-989c-b9e53006d130.png)
![Screen Shot 2020-10-09 at 14 52 50](https://user-images.githubusercontent.com/21987083/95585311-59c17480-0a3f-11eb-978c-ad1637aebc6e.png)

**Comment by galeza** [comment]
@jessica-lau FYI

**Comment by galeza** [comment]
@TimeaKovacs86 FYI

**Comment by jessica-lau** [comment]
@doheekim93 just a side note - I think it would make sense to have punctuation as we already do in the original tests, especially for questions and sentences so that it maintains consistency and clarity.

**Comment by joshmorel** [comment]
I think we should change these back cc @jyclam to not break tests. And I agree having punctuation there makes sense.

> Recover Password
> a. expected: Recover Password - screen H1 title. Actual: Forgot Password

For this one I think the wording is actual wrong (you aren't recovering a password but setting a new one) but not a big deal and if that is to change it should be another issue/PR.

**Comment by rabbi08** [comment]
Agree with @galeza @jessica-lau we should keep the links and button names same as before else the existing e2e test will fail and needed to be updated. Also having proper punctuation will improve the language on the webpage. Thanks

**Comment by joshmorel** [comment]
@doheekim93 @rabbi08 I fixed most but with the `forgotPassword` we were using hte same key for both the link and title:

Before:

```
    "forgotPassword": "Forgot Password",
``` 

We would need to add a key and therefore translate all the other existing languages. We can't just tack a "?" onto the link as that's not how many languages are written.

I kind of want to change "recover" to "forgot" now because it's semantically incorrect but I'll resist.
