### ISSUE TITLE
Create a script that parses and imports posts data into database

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#163]
Currently we have data from Airtable that we want to migrate over to MongoDB.

We want a script that parses the data from Airtable and structures the data to fit our current models. The script should also insert the parsed data into our MongoDB database.

**Comment by joshmorel** [comment]
We are both seeding data initially then importing additional data post go-live. All posts will be assigned to "Sourced by FightPandemics".

**Comment by joshmorel** [comment]
Dependencies to Complete (all PRs under review): Primary #401, Also #414 #373

Once dependencies merged additional development time to complete: **1 day (~3/4h)**; plus pull request review & approval

Total effort to date including analysis, discussion & coding: ~20h
