### ISSUE TITLE
Web Notifications Backend

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#1637]
The scope of this ticket is to integrate socket.io with web notifications. As discussed in the meeting on 10/11, this will involve taking the existing socket.io Fastify plugin that is in the direct messages branch `feature/message-modal/1457` and updating it to support notifications. We also need to create the notifications in the database.

**Comment by mannykary** [comment]
@Zaydme I created the branch `feature/1637-notifications-web-backend`. I was about to merge in the notification lambda code into this branch, but realized that web notifications does not depend on any of that code, so right now this is an exact copy of `feature/message-modal/1457`. I think you might need the code that is in the `feature/notification-drop-down/1531`, so you will probably have to merge that in.

**Comment by Latha-AP** [comment]
on this staging link for web notifications:
https://feature1637-notifications-web-backend.fightpandemics.xyz/
1. we could create the post. 
2. we could like the post: **Web notification shown.**
3. **we could n't comment on the post!**
4. 2 times, today I could able to comment on own post, but not on other. 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/72217779/96402731-7e2df700-118b-11eb-8ec0-5e2fe7a81516.gif)

![comment notification disabled](https://user-images.githubusercontent.com/72217779/96420735-b5f86700-11aa-11eb-940d-7c1ca68cae3e.png)


****

**Comment by claudiang1357** [comment]
I was in a post to attempt updating post comment (stay for quite some time - probably expired?), error was displayed as per screenshot -> Error message is overlapped with Help Board button.
![Overlapping Error](https://user-images.githubusercontent.com/72559826/96641113-3675af80-12f2-11eb-9302-baa87e414bc2.png)

**Comment by Zaydme** [comment]
@Latha-FP [this](https://github.com/FightPandemics/FightPandemics/issues/1637#issuecomment-711550797) was fixed

**Comment by shrutigupta1981** [comment]
I think second 2 is not required?
https://files.slack.com/files-pri/T010BHVS3EF-F01CWAC3K9C/image.png

**Comment by shrutigupta1981** [comment]
Should we have scroll as notification nos increases?
https://files.slack.com/files-pri/T010BHVS3EF-F01D890UQ2W/image.png

**Comment by shrutigupta1981** [comment]
Scenario: I created a post and left comment on it. I received comment from another user saying interested. I replied back to that comment. I myself shouldn't get notification in such a case? Right? No notification should be generated.
https://files.slack.com/files-pri/T010BHVS3EF-F01CNBE2MFH/image.png

**Comment by Zaydme** [comment]
@shrutigupta1981 this [bug](https://github.com/FightPandemics/FightPandemics/issues/1637#issuecomment-715574308) was fixed. you don't get notifications by interacting with your own post.

**Comment by shrutigupta1981** [comment]
Not getting notifications for self. Closing the issue.Checked.

**Comment by Zaydme** [comment]
Please keep this issue https://github.com/FightPandemics/FightPandemics/issues/1637 open for future feedback and bug reports

**Comment by Latha-AP** [comment]
To my surprise no notifications are shown on org. profile. Am I missing something here.

I used this feature link to test
https://feature1637-notifications-web-backend.fightpandemics.xyz/feed.

![org profile](https://user-images.githubusercontent.com/72217779/97132089-264f3d00-1703-11eb-89de-710ccfbaf042.png)

![org profile2](https://user-images.githubusercontent.com/72217779/97132094-28190080-1703-11eb-8128-2570b7c15d1e.png)

**Comment by Zaydme** [comment]
@Latha-FP notifications are working for individuals only as of now, but soon they should work for organizations too, along with the messaging feature.

**Comment by Latha-AP** [comment]
no Email notifications are working for me. I got earlier for likes .


![Screenshot 2020-10-26 100202](https://user-images.githubusercontent.com/72217779/97204246-1a02c880-1773-11eb-98f2-79401c801696.png)
![Screenshot 2020-10-26 100253](https://user-images.githubusercontent.com/72217779/97204247-1a9b5f00-1773-11eb-9580-8b96341a84e3.png)
![Screenshot 2020-10-26 100411](https://user-images.githubusercontent.com/72217779/97204249-1a9b5f00-1773-11eb-9d39-9169b008e6c3.png)
