### ISSUE TITLE
Localisation: GTM IDs not firing

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1643]
Please make sure that the ID include all elements in component!

The following IDs have already been assigned to the correct components. Issue is that GTM does not pick up on these IDs.

| Component on page | JSX 'id' attribute |
| --- | --- |
| Chinese Traditional | NAV_LS_ZH_TW |
| English (US) | NAV_LS_EN_US |
| English (UK) | NAV_LS_EN_UK | 
| German | NAV_LS_DE |
| Polish | NAV_LS_PL |
| Spanish (Peninsular) | NAV_LS_ES_ES |

Desktop:
<img width="423" alt="Screen Shot 2020-10-12 at 1 31 59 PM" src="https://user-images.githubusercontent.com/66695502/95779362-84a20780-0c8f-11eb-9988-9aa01aa18cd8.png">

Mobile:
<img width="311" alt="Screen Shot 2020-10-12 at 1 34 45 PM" src="https://user-images.githubusercontent.com/66695502/95779570-e2365400-0c8f-11eb-857d-00ccf61c77ec.png">

**Comment by Zaydme** [comment]
@tr1503 this is issue is being worked on, please check PR #1647

**Comment by idjevm** [comment]
Closing this manually as I verified them locally. Feel free to reopen them after testing on staging if the problem persist. It works locally.

**Comment by rabbi08** [comment]
Verified in STG, Refer the IDs in below screenshot.

![languageIDs](https://user-images.githubusercontent.com/67168400/95931270-a639e680-0d96-11eb-94b3-62646c9ca896.png)
