### ISSUE TITLE
GTM ID not showing up

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1644]
**How to set up GTM debugging on Local: [https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255)

The following IDs have already been assigned to the correct components. Issue is that GTM does **not** pick up on these IDs.

### 1. Onboarding Flow

**Issue:** `Enter address, zip code, or city` ID does not show up on GTM when clicked on.

| Component on page | JSX 'id' attribute | url path |
| --- | --- | ---|
| "Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | RES2_EAZ | /need-help#Step2 |
| "Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | OFS2_EAZ | /offer-help#Step2 |

<img width="700" alt="Screen Shot 2020-10-12 at 5 25 28 PM" src="https://user-images.githubusercontent.com/66695502/95795576-4f59e180-0cb0-11eb-8e90-5ba0cf8449d3.png">

### 2. Help Board (url path: /feed)

**Issue:** `Enter address, zip code, or city` ID does not show up on GTM when clicked on.

| Component on page | JSX 'id' attribute |
| --- | --- |
| Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | HB_LO_EAZ |

<img width="1440" alt="Screen Shot 2020-10-12 at 5 27 57 PM" src="https://user-images.githubusercontent.com/66695502/95795655-80d2ad00-0cb0-11eb-88a4-274071613820.png">

**Comment by idjevm** [comment]
Closing this manually as I verified them locally. Feel free to reopen them after testing on staging if the problem persist. It works locally.

**Comment by rabbi08** [comment]
@idjevm @Zaydme @doheekim93 
Verified in STG,   GTM IDs are being fired as expected. refer below screenshot. Thanks
Filter post as per location:
![FilterlocGTM-I](https://user-images.githubusercontent.com/67168400/95926572-a2a06280-0d8a-11eb-97df-e20789a9ccc8.png)

GTM IDs for Request/Offer help:

![location-GTM](https://user-images.githubusercontent.com/67168400/95926574-a2a06280-0d8a-11eb-8a9b-2b2172b9efd5.png)
