### ISSUE TITLE
Frontend changes needed for the mobile Symptoms Checker page

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#165]
- Need to update all styles and text based on the latest designs on Figma.
- Designs need to be more pixel perfect.

Mobile Design: 
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=11%3A2

**Comment by manualzuru** [comment]
@jherkyesse do you have any update?

**Comment by jherkyesse** [comment]
> @jherkyesse do you have any update?

update on branch [frontend#165/sc-page-change](https://github.com/FightPandemics/FightPandemics/tree/frontend%23165/sc-page-change)

**Comment by snowiesuet** [comment]
I think this and #315 are similar.

**Comment by anniegiang** [comment]
@snowiesuet Ah you're right, I closed that one since it's similar to this one.
