### ISSUE TITLE
Localisation: Language dropdown menu needs to be anchored to the language change button

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#1658]
The dropdown menu for language select in **mobile** needs to be anchored to the language change button (i.e. the globe icon).

Issue:
The dropdown menu moves when user scrolls. 
<img width="300" src="https://user-images.githubusercontent.com/66695502/96156118-57936600-0ed6-11eb-87d7-3cecf698ff5b.gif">

**Comment by mathigayathri2001** [comment]
@doheekim93  during analysis I found out this issue is resolved after implementing the enhancement '#1448 - Add search bar on help board with a search button',

**Comment by doheekim93** [comment]
Hey @mathigayathri2001 -- I checked the PR (#1695) that is linked to #1448, but I don't see the fix on the build URL. Could you double check please? Thank you!!

**Comment by Zaydme** [comment]
yeah #1448 aka (#1695) doesn't change that, but what it does is adding "Help Board" to that sidebar, and because of that, we moved the language switch icon to the up a bit, but it won't fix this issue for all screen sizes.

**Comment by Zaydme** [comment]
This was fixed with #1767 (act as organization) as it changes the entire drawer menu for mobile.
