### ISSUE TITLE
[Mobile-Android]During commting the post user press newline key it acts as Enter instead of creating new line. 

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1672]
Device used : Samsung Galaxy s8
Environment:staging 
Browser:Google chrome 
1.Login with valid user name and password. 
2.Go to help board.
3.Comment on any post and click newline key in mobile keyboard. 
Expected result 
It has to create new line
Actual Result
It acts as enter key.
![GIF-201019_145135](https://user-images.githubusercontent.com/41587211/96503309-0e6a4b80-1221-11eb-83fa-f6096bcc4183.gif)

**Comment by nivetheatha** [comment]
Environment production 
It works the same way as staging.

**Comment by joshmorel** [comment]
Thanks @nivetheatha . We had this similar #1497 but the PR didn't resolve the issue and I don't think anyone else in the discussion is currently actively involved in FP. I will get a new person to start. 

My suggestion on resolution:

* Enter is always newline - mobile or desktop
* Ctrl+Enter can submit (applicable to desktop only)

**Comment by joshmorel** [comment]
I'm assigning myself so no one else does until the new dev I asked in Slack responds.

**Comment by BMariscal** [comment]
I can do this one.
