### ISSUE TITLE
Desktop: The search textbox need to be aligned with post and other UI issues.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1685]
1. Open STG environment, and navigate to Help Board
2. You will see that the search textbox is not aligned on the page, It should be aligned with the post section. Refer below screenshot.

![search-align](https://user-images.githubusercontent.com/67168400/96670987-c46f8b80-132e-11eb-9409-61c65cf1d9dd.png)

Also, the text for 'HELP' for the Organization needs to be updated as per the application i.e. 'Requesting Help' and 'Offering Help'. refer below screenshot.

![Search terms](https://user-images.githubusercontent.com/67168400/96671090-0ef10800-132f-11eb-9e62-957798cd7998.png)

**Comment by Zaydme** [comment]
fixed in https://github.com/FightPandemics/FightPandemics/pull/1693
