### ISSUE TITLE
Mobile: Search functionality is not user friendly

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1686]
1. Open the STG url on mobile, and navigate to the help Board
2. Enter the search text in the search textbox.

Issue: You will observe that nothing will happen, nor any user message is displayed to select the 'TABs' to perform the search.
Here either it should work as like in desktop, by entering the text and selecting the TAB or user need to be notified to select the TAB before entering the search text.

Refer below GIF.
![ezgif com-gif-maker (22)](https://user-images.githubusercontent.com/67168400/96672376-1fef4880-1332-11eb-9aeb-e0cda0508b00.gif)

**Comment by ddveloper** [comment]
the [hotfix/search-function-issue](https://github.com/FightPandemics/FightPandemics/commits/hotfix/search-function-issue) has a workaround for this issue, could be a start point to work from

**Comment by Zaydme** [comment]
fixed in https://github.com/FightPandemics/FightPandemics/pull/1693
