### ISSUE TITLE
Home Page for Desktop version

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#169]
- [ ] Update current Home page styling for desktop. 
Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ] Designs need to be pixel perfect

**Comment by manualzuru** [comment]
@TenNga please give us an update?

**Comment by indirabhowmick** [comment]
@TenNga What is the status of this issue? Please provide an update

**Comment by TenNga** [comment]
Navigation still needs progress and someone else is working on the footer, I am trying to use the existing code for desktop but its kind of hard for me to figure out fast, otherwise I might need to write a new nav for desktop (not optimal way).

**Comment by indirabhowmick** [comment]
@anniegiang - Please refer to the previous comment from Kevin. Can you help?

**Comment by anniegiang** [comment]
I'm sorta confused, I think this was already implemented? I'm aware there are just finishing touches that need to be made from PR #300. Otherwise was there a PR linked to this? If so please link on the right side.
