### ISSUE TITLE
[Mobile-Android]If we provide Search filter+Filter by options together leads to blank page.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1690]
Environment -- staging
Device used -- Sansung Galaxy s8
Browser -- Google chrome 
Steps to create:
1.Go to help board. 
2.Give filter in search field .(ex person as nivethetha)
3.Give filter by (ex location as sanfrancisco ca.
4.Enter apply  filter.
5.Goto search box and enter again.
Expected result:
Both filter has to apply in the search results 
Actual Results:
Leads to a blank page.
![GIF-201021_100341](https://user-images.githubusercontent.com/41587211/96744092-ad628500-1392-11eb-8ec6-6b73d7a7de35.gif)

**Comment by adorapham** [comment]
@nivetheatha , it seems the mode for the search keyword is not on.  for number 5 , can you click on this search icon 
![image](https://user-images.githubusercontent.com/70918430/96747000-a3ce2280-137c-11eb-8b64-c464ce3e38b2.png)
**Update** after reading the comment from nivetheatha and try to execute : it has blank page in display after applying the filter and click on search icon.  This happens also with Galaxy J7 max/Android 7.0/Firefox

**Comment by nivetheatha** [comment]
@adorapham I tried to click on search icon for 5.It still leads to blank page.

**Comment by Zaydme** [comment]
fixed in https://github.com/FightPandemics/FightPandemics/pull/1693
