### ISSUE TITLE
Search functionality for International languages is not working as expected and we should NOT limit the letters in a word to search

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1691]
1. Login into STG and navigate to Help Board
2. Change language to German and search for text , help i.e. 'Hilfe' in German language 

Issue: You will observe that search is performed differently when the text is entered as single word or if it is entered as part of multiple words. refer below screenshot.

![search-german-1](https://user-images.githubusercontent.com/67168400/96747991-f87e9700-1396-11eb-99e7-bba5194264fe.png)

**Expected Result: We should remove the condition on the number of the letters in a word to perform search**

While searching for Chinese post, the search is not performed word wise, please see the screenshot below:

![search-chinese](https://user-images.githubusercontent.com/67168400/96748104-1cda7380-1397-11eb-9638-3b76266a80e8.png)

Also as per @ddveloper for chinese search:
It's actually not that frequent to search one character in Chinese, the most common I would say is 2 characters plus.
https://docs.acquia.com/acquia-search/language/non-latin/ for reference

**Comment by Zaydme** [comment]
> Also as per @ddveloper for chinese search:
It's actually not that frequent to search one character in Chinese, the most common I would say is 2 characters plus.
https://docs.acquia.com/acquia-search/language/non-latin/ for reference

Amazing, 2 characters should be good then
