### ISSUE TITLE
Search icon still performs the search with the current validation message for keywords

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1694]
1-click on Help Board and type less than 4 letters word then press enter
2- see the validation message display with Min. 4 characters 
3- click on search icon 
4- Expect the search should not perform but still see the search is executed.
![searchIcon](https://user-images.githubusercontent.com/70918430/96770302-219e2800-1395-11eb-8486-ffa9933ec121.gif)

**Comment by adorapham** [comment]
#1695-change the requirement keyword length from 4 to 1 so this might not be valid.

**Comment by adorapham** [comment]
@Zaydme please review this one to see it is invalid

**Comment by Zaydme** [comment]
This is outdated, please check https://github.com/FightPandemics/FightPandemics/pull/1695
