### ISSUE TITLE
Create Post Module: Post visibility dropdown - order to be reversed 

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1696]
Expected: Create Post Module: Post visibility dropdown - order to be reversed- for a day, for a week, for a month, forever

Actual: Create Post Module: Post visibility dropdown - order - forever, for a month, for a week, for a day

**Comment by shrutigupta1981** [comment]
I checked on Staging and it still not reflected. Pls have a look
![image](https://user-images.githubusercontent.com/72843352/97052360-b3449b80-1535-11eb-8a35-dfbe8aa618da.png)

**Comment by shrutigupta1981** [comment]
It's not fixed.

**Comment by galeza** [comment]
@shrutigupta1981 NOT on staging but we have a Build URL: https://feature1696.fightpandemics.xyz. It was not merged.
Please add your comments in the PR

**Comment by shrutigupta1981** [comment]
I didn't add it to PR as it's not related so opened a separate issue. Checked on the mentioned URL. Working fine there
