### ISSUE TITLE
Create Post: Unselection of Tags is to be more intuitive 

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1698]
Please refer to the Video to understand the issue.
https://hippolms-storage.s3-accelerate.amazonaws.com/wiz/videos/thumbnails/v2/J0SdkzPi0Dun4ireMhYseaKkjwXSW8ykXI1DY49xnyM_play.jpg?_=1603316550

**Comment by mathigayathri2001** [comment]
@shrutigupta1981 above video is  not working . Can you please provide the correct link

**Comment by shrutigupta1981** [comment]
Pls, refer slack. I shared a video there as here the format is not supported

**Comment by mathigayathri2001** [comment]
> Pls, refer slack. I shared a video there as here the format is not supported

Thanks @shrutigupta1981 . I will check

**Comment by mathigayathri2001** [comment]
> Pls, refer slack. I shared a video there as here the format is not supported

Thanks @shrutigupta1981 . I will check

**Comment by shrutigupta1981** [comment]
Were you able to access the video?

**Comment by shrutigupta1981** [comment]
[Tagsremovalnotintuitive.zip](https://github.com/FightPandemics/FightPandemics/files/5468126/Tagsremovalnotintuitive.zip)
