### ISSUE TITLE
Login Page for Desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#170]
- [ ]  Update current Login page styling for desktop.
 Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ]  Designs need to be pixel perfect

**Comment by indirabhowmick** [comment]
@Chimaobi-Johnson @CeesWang Login and Signup pages are different. 
Please refer to the design in FIGMA

**Comment by CeesWang** [comment]
@indirabhowmick The only difference is the picture and certain text based on the condition whether the user is logging in or signing up. This however is rendered conditionally in the same component. Which would mean that we are working in the same component trying to accomplish the same thing. Please let me know if this is not the case.

**Comment by indirabhowmick** [comment]
@CeesWang I agree. Thanks!
