### ISSUE TITLE
 HB Feed search result should retain the highlight searched keyword when navigating back from the post page 

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1701]
1-Navigate to Help Board Feed page and enter keyword , click on search icon
2-See the result of posts that contains at least one keyword
3-Click on the post that has [view more](url) link since the post is too long and the keyword might be hidden.
4-The post page for the Post is on display.
5-**Right here,  It is nice to see the keyword is highlight on this post.**
6-After viewing the post , click on  [<- Back](url) to go back the previous search result.
7- **Expect to see search result still retains the highlight keywords, so the user can continue to review the rest of the posts.** 
Otherwise, they might need to perform the same search to see the highlight keyword match

please see the GIF.
![Result_keyword_hightligh](https://user-images.githubusercontent.com/70918430/96818910-4b783e80-13d7-11eb-84af-d4bed0781a1a.gif)

**Comment by adorapham** [comment]
@Zaydme - can you please review this one.

**Comment by Zaydme** [comment]
The feed state is not preserved, this includes pagination, filters and search. We are planing to change this behavior in a future feature. (using query strings?)
cc @joshmorel
