### ISSUE TITLE
Update Sign-up page styling for desktop.

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#171]
- [ ] Update current Sign-up page styling for desktop.
Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027
 
- [ ]  Designs need to be pixel perfect

**Comment by Chimaobi-Johnson** [comment]
@CeesWang i think this is the same issue as issue #170 Login Page for Desktop which am currently working on.

**Comment by CeesWang** [comment]
@Chimaobi-Johnson It is exactly the same. I didn't know there there was a duplicate issue. How far are you in ?
