### ISSUE TITLE
Health board search- Icon search has no response when clicking on it

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1714]
SC1
1-navigate to feed page
2-enter keywords and click on search icon 
**3-see no response ,  so we need to press on enter key**
![searchIconNotResponseSC1](https://user-images.githubusercontent.com/70918430/97223407-f3ea2200-178c-11eb-82c0-c8a34e890ea3.gif)

SC2
1-navigate to feed page and enter one character keyword
2-see validation message -min. 2 characters
3-enter 3 characters keywords and click on search icon
4- **see no response** , press enter key and see the result
5- click on X icon to clear the search
6- enter new keywords 3 characters 
**7-click on Search icon , and see no response**

![searchIconNotResponse](https://user-images.githubusercontent.com/70918430/97223390-edf44100-178c-11eb-98bc-c8d9dbeb3e8d.gif)

**Comment by adorapham** [comment]
@Zaydme , please review this one.

**Comment by Zaydme** [comment]
@adorapham thank you, this will be fixed soon.

**Comment by Zaydme** [comment]
Fixed in https://github.com/FightPandemics/FightPandemics/pull/1695

**Comment by adorapham** [comment]
Verify both issues are passed after the fix #1695
SC1
![sc1_passed](https://user-images.githubusercontent.com/70918430/97229490-b2aa4000-1795-11eb-8b26-eccf7b62e0cf.gif)

SC2
![sc2_passed](https://user-images.githubusercontent.com/70918430/97229554-c5bd1000-1795-11eb-97cd-f5e69489b8e5.gif)
