### ISSUE TITLE
Create Post - Update Styling for Desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#172]
- [ ] Update current Create Post page styling for desktop.
Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ]  Designs need to be pixel perfect

![Screen Shot 2020-05-18 at 6 19 13 PM](https://user-images.githubusercontent.com/42228386/82274100-1baea180-9934-11ea-8cde-aa21d9f1af31.png)

**Comment by limaneto** [comment]
I will send the PR related to this task today, then it will be missing only some fixes that might come from code review @MohamedEl1
