### ISSUE TITLE
Use query params for filters/search

### ISSUE THREAD

**Issue by Zaydme** [FightPandemics/FightPandemics#1723]
Using query parameters instead of React state to store filters & search, this will give the user share-able URLs, and help preserve the state when navigating back to feed.
example: `/feed/searchQuery=Face+Mask&searchCategory=1&objective=2&filter=eW91dHUuYmUvZFF3NHc5V2dYY1E=`

**Comment by Latha-AP** [comment]
User opted for not sharing the location.
but while searching it is allowing to show the address and showing results accordingly

![search1](https://user-images.githubusercontent.com/72217779/98040749-a9445780-1dd5-11eb-9e18-a28ae80a4509.png)

![Screenshot 2020-11-03 130635](https://user-images.githubusercontent.com/72217779/98040745-a8abc100-1dd5-11eb-9c48-6d1dba4e35db.png)
