### ISSUE TITLE
Like functionality is not working for searched output for People tab

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1725]
Staging env - Tested on Android 9 Mobile and Windows 10 laptop on Chrome Browser

https://www.hippovideo.io/video/view/6758057

**Comment by shrutigupta1981** [comment]
Please the video if the above link is not working
[ezyzip.zip](https://github.com/FightPandemics/FightPandemics/files/5467877/ezyzip.zip)

**Comment by shrutigupta1981** [comment]
Steps 1. Put any keyword and search
         2. Goto people tab
         3. See any person  posts
         4. Like the post

**Comment by shrutigupta1981** [comment]
[LikenotworkingforPeoplesearchedresult2.zip](https://github.com/FightPandemics/FightPandemics/files/5468134/LikenotworkingforPeoplesearchedresult2.zip)

**Comment by shrutigupta1981** [comment]
Hi, Its not about like button count issue. Its the User not able to like the posts itself. #1754 needs recheck as its not fixed. Please confirm if I am correct!

**Comment by mathigayathri2001** [comment]
> Hi, Its not about like button count issue. Its the User not able to like the posts itself. #1754 needs recheck as its not fixed. Please confirm if I am correct!
Hi , Please refer enclosed GIF ,the earlier like button is not working correctly  before. After the fix like button fuctionality is working fine also user able to like the post itseslf. Once you review the GIF , if you still have clarification please let me know
![Recording-_2](https://user-images.githubusercontent.com/60233461/98060966-e8e06300-1e18-11eb-89ee-fb99dd0b4542.gif)

**Comment by Zaydme** [comment]
## this is NOT an issue :rotating_light: 
What you are seeing in the "People" (and "Organizations") tab is **NOT** a post, it's a user card, a mini version of a user profile showing their name and their "about" section.
![image (1)](https://user-images.githubusercontent.com/46847212/98601884-918a3900-22d7-11eb-809a-1cc882e30f28.png)
#### think of it like this:
![image](https://user-images.githubusercontent.com/46847212/98601577-29d3ee00-22d7-11eb-8f09-8aa502841415.png)

**Comment by rabbi08** [comment]
> ## this is NOT an issue 🚨
> What you are seeing in the "People" (and "Organizations") tab is **NOT** a post, it's a user card, a mini version of a user profile showing their name and their "about" section.
> ![image (1)](https://user-images.githubusercontent.com/46847212/98601884-918a3900-22d7-11eb-809a-1cc882e30f28.png)
> 
> #### think of it like this:
> ![image](https://user-images.githubusercontent.com/46847212/98601577-29d3ee00-22d7-11eb-8f09-8aa502841415.png)

Actually @Zaydme 
the issue is when you navigate to user post from 'People' then on that post user is not able to click 'Like' but can comment.
see this GIF

The user is able to like his own post but not other users.
![test1](https://user-images.githubusercontent.com/67168400/98602999-5b38c380-22af-11eb-9f0b-0b86572b759a.gif)

**Comment by Zaydme** [comment]
Ayyy :joy:
Thanks for the clarification @rabbi08
