### ISSUE TITLE
[Mobile-Android]Question no 2 from inial flow is not enabled in the filter 

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1765]
Environment--Staging
Browser-Google chrome 
Device used--Samsung Galaxy s8
1.click Request help.
2.click medical. 
3.provide location/show posts from anywhere 
4.check filter 
Expected result:
All the details got from the user should be enabled in the filter. 
Actual result:
Medical supplies is not enabled in the type.
![GIF-201105_151341](https://user-images.githubusercontent.com/41587211/98292432-b3538b00-1f7a-11eb-940a-2cca6b7cb64a.gif)

**Comment by nivetheatha** [comment]
Environment-production
Issue exists in production as well.

**Comment by joshmorel** [comment]
Thanks @nivetheatha 

I've checked and it seems this will be resolved by #1728
