### ISSUE TITLE
Update styling for Create Org Profile for Desktop

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#177]
- [ ] Update current Create Org Profile page styling for desktop.

Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ]  Designs need to be pixel perfect

**Comment by Chimaobi-Johnson** [comment]
There seems to be no current Create Org Profile page, do you mean the Organization Profile itself?
