### ISSUE TITLE
Unsigned user clicks on create post then after login it leads to home page instead of create post page.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1781]
Environment : staging 
Device used:Samsung Galaxy s8
Browser:Google chrome 
1.As a  unsigned user go to help board. 
2.click on plus symbol to create post.
3.Redirected to login page.
4.provide valid user name and password and click sign in. 
Expected result:
It lands on post creation page.
Actual result:
It lands on home page.

**Comment by nivetheatha** [comment]
Environment production 
It works the same way as staging.

**Comment by joshmorel** [comment]
@nivetheatha we reviewed the code and it seems to have fully resolve the issue so went ahead and merged. If you can confirm in staging that would be great.

**Comment by nivetheatha** [comment]
@joshmorel sure will do.
