### ISSUE TITLE
About Us - The label for 'contact us email' need to be in sync for all languages.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1788]
1. Login into 'staging.fightpandemics.work' and navigate to 'About Us' page.
2. Scroll down on 'about Us' page to view the 'contact email'

Issue: You will observe that for en_US i.e. American English, the label for 'contact Us' email is 'Contact us at:' but for all the other languages it is 'Or contact us at:'
To keep the label in sync we need to update 'en_US language context. Also, currently in PROD we have 'Or contact us at:' it is so because we have given user the option to either contact us through '#com..' or contact us through email.

Refer below screenshot.
![image](https://user-images.githubusercontent.com/67168400/98848579-ef299d00-241f-11eb-83eb-635cd1a4bea6.png)

**Comment by galeza** [comment]
@tejasm2 @rabbi08 
If you want to change EN-US version, let me know and I'll trigger PR from Lokalise.

**Comment by rabbi08** [comment]
> @tejasm2 @rabbi08
> If you want to change EN-US version, let me know and I'll trigger PR from Lokalise.

Yeah we can trigger PR to fix this.

**Comment by galeza** [comment]
@rabbi08 

We need to change href attribute! We still have here admin@fightpandemics email. So when users clicks on contact links in the email he has admin@fightpandemics:
![Screen Shot 2020-11-13 at 13 06 24](https://user-images.githubusercontent.com/21987083/99070844-4c088d00-25b1-11eb-9bc9-36c26f4074b3.png)

It's on Prod. Please prioritise.

**Comment by galeza** [comment]
@Jameel139
This issue will trigger a change in the Lokalise Key - we will change EN-US text.

**Comment by ddveloper** [comment]
@galeza if we merge #1811 , there will be one `en_US` value change, i.e. `Contact us at: ` to `Or contact us at: ` (while all the translations may stay the same)
![image](https://user-images.githubusercontent.com/44758313/99102392-ddb4d200-2592-11eb-97ac-be643f0c5f67.png)

**Comment by galeza** [comment]
@rabbi08 
May I close this issue? PR was merged?

**Comment by rabbi08** [comment]
yeah @galeza 
closed. thanks
