### ISSUE TITLE
About Us- The linked pages like privacy policy, should have focus on the top of the page not the end when load.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1790]
1. Login into 'fightpandemics.com' and navigate to 'About Us' page
2. Navigate to the bottom of the page and click on 'Privacy Policy' link

Issue: You will observe that privacy page open but the user application focus is on the bottom of the privacy policy.
So with 'terms and condition, cookie policy, FAQ or 'About Us' page itself'
Refer below GIF.

Expected Result: after user click to view other linked pages, the focus should be on the top of the page.
![ezgif com-gif-maker (50)](https://user-images.githubusercontent.com/67168400/98883015-94ae3200-245b-11eb-9270-0a5f5188e570.gif)

**Comment by galeza** [comment]
@rabbi08 
FYI I think that similar issue was reported here: https://github.com/FightPandemics/FightPandemics/issues/1372 
There is also a PR open: #1571 It's still open however it was accepted by several people.

**Comment by rabbi08** [comment]
> @rabbi08
> FYI I think that similar issue was reported here: #1372
> There is also a PR open: #1571 It's still open however it was accepted by several people.

Looks like @sujatha-m was working on #1571 
@sujatha-m Can you please pick this as well and fix both issues as they are of similar nature. Thanks

**Comment by sujatha-m** [comment]
> > @rabbi08
> > FYI I think that similar issue was reported here: #1372
> > There is also a PR open: #1571 It's still open however it was accepted by several people.
> 
> Looks like @sujatha-m was working on #1571
> @sujatha-m Can you please pick this as well and fix both issues as they are of similar nature. Thanks

Sure Rajbir

**Comment by rabbi08** [comment]
Closed with #1851
