### ISSUE TITLE
Notification -> The Mobile Browser daily digest mail ->edit notification preferences and unsubscribe text is very light

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1791]
![Screenshot_20201111-182647](https://user-images.githubusercontent.com/72843352/98889798-76dad000-244f-11eb-920a-b92cf668e959.jpg)
 Attaching to compare with Laptop Gmail Browser appearance
![image](https://user-images.githubusercontent.com/72843352/98889886-a689d800-244f-11eb-80b6-543d196092d4.png)

**Comment by shrutigupta1981** [comment]
URL : https://featurenotifications.fightpandemics.xyz/
Issue in Mobile- Browser only

Steps:
1. Login to URL and click on Help Board
2. Search the Post and like, share, comment 
3. Login into mail of User whose post has been liked, shared and commented
4. See for daily digest mail 


**Actual Result: The text is almost invisible in Mobile but clearly visible in Laptop Browser**

**Expected Result: The text should be visible both in Mobile as well as Laptop Browser**

**Comment by Zaydme** [comment]
@shrutigupta1981 please reopen this ticket if the issue persists after retesting.

**Comment by shrutigupta1981** [comment]
**Tested**

![Screenshot_20201113-004407 (2)](https://user-images.githubusercontent.com/72843352/99048640-ac181880-254a-11eb-99e2-bbfc69fa3388.jpg)
