### ISSUE TITLE
Notification-> The message when clicked on Cancel button given at Unsubscribe Screen should be more user friendly

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1792]
![Screenshot_20201111-181901](https://user-images.githubusercontent.com/72843352/98890334-96262d00-2450-11eb-8fb9-a3e919f81d8a.jpg)

**Comment by ddveloper** [comment]
any suggestions? how about "Notification update is canceled"?

**Comment by shrutigupta1981** [comment]
Please contact @CamilaArias or @nfranklin9

**Comment by shrutigupta1981** [comment]
URL : https://featurenotifications.fightpandemics.xyz/

1. Login to Mailbox to check email notifications
2. Click on Edit Notifications Preferences or Unsubscribe link
3. Now, click on Cancel button

**Actual Result: Operation is canceled**

**Expected Result: More User friendly**

**Comment by shrutigupta1981** [comment]
Cami Arias  3 hours ago
"No changes will be made to your notification preferences." for the cancel button
:+1:
1

**Comment by Zaydme** [comment]
@shrutigupta1981 this issue was fixed, please retest, if there was any problem feel free to reopen this ticket.

**Comment by shrutigupta1981** [comment]
**Tested** 
![image](https://user-images.githubusercontent.com/72843352/99046548-c13f7800-2547-11eb-8e53-f1b835677e53.png)
