### ISSUE TITLE
Notification-> The Web App notifications doesnt has scroll so not able to see all notifications after certain number

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1794]
![image](https://user-images.githubusercontent.com/72843352/98892328-f74fff80-2454-11eb-9a44-13e4f160e2b7.png)

**Comment by shrutigupta1981** [comment]
URL : https://featurenotifications.fightpandemics.xyz/ 
Issue in Web App only

Steps:
Login to URL and and click on bell Icon

**Actual Result: Web App doesn't has scroll button for Notifications**

**Expected Result: Web App should have scroll button to navigate and click on any of the notifications****

**Comment by Zaydme** [comment]
@shrutigupta1981 this was fixed, please check and confirm.

**Comment by shrutigupta1981** [comment]
Tested and scroll there now 👍 

![image](https://user-images.githubusercontent.com/72843352/99041761-5b032700-2540-11eb-809f-89dedb846b8e.png)
