### ISSUE TITLE
Notification-> The Organisation doesnt has Notification preferences in its profile like Individual has. Both need to have their own notification preferences.

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1796]
Individual has
![image (6)](https://user-images.githubusercontent.com/72843352/98896650-56664200-245e-11eb-8d6c-cf7b223b124d.png)

Organisation hasn't
![image (7)](https://user-images.githubusercontent.com/72843352/98896715-7eee3c00-245e-11eb-8b11-aab81f7510c8.png)

**Comment by shrutigupta1981** [comment]
URL : https://featurenotifications.fightpandemics.xyz/

Steps:

1. Login as an Individual
2. Click on Profile and My Profile
3. Click on Edit button
4. Notice the Edit Notification option given
5. Now, again click on Profile, Organisation, Organisation added 
6. Click on Edit button

**Actual Result: No Edit Notification  option given**

**Expected Result: Edit Notification option should be given so that Organisation can set its own preferences**

**Comment by Zaydme** [comment]
Same solution as #1797

**Comment by ddveloper** [comment]
added preference for organisations
![image](https://user-images.githubusercontent.com/44758313/98996554-e4d2d600-24e7-11eb-9de5-54f194fe063e.png)

**Comment by ddveloper** [comment]
note: notification check values are cleared if you toggle the switch to be `off`, this will be fixed after #1799 complete

**Comment by shrutigupta1981** [comment]
**Tested** 

![image](https://user-images.githubusercontent.com/72843352/99042022-d82e9c00-2540-11eb-837f-f5e7338462c8.png)
 
**Preferences:**

![image](https://user-images.githubusercontent.com/72843352/99042045-e54b8b00-2540-11eb-9135-3872b76eb763.png)
