### ISSUE TITLE
Notification-> Organisation get email notifications though it doesnt has any notification preferences. Ideally it shouldnt have got any email notification only 

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1797]
URL: https://featurenotifications.fightpandemics.xyz/
1. Individual logins and find the Organization posts through Help Board
2. He shares, likes, comments the posts
3. That Organisation checks his mailbox to see if any notifications there for him

**Actual Result: Organisation receives emails in his mailbox**

**Expected result: Organisation shouldnt get any email notifications as he doesnt has any notification preferences nor functionality**

![image (8)](https://user-images.githubusercontent.com/72843352/98896957-1c497000-245f-11eb-8350-53b2f8e54939.png)

**Comment by shrutigupta1981** [comment]
**Post URL** 
https://featurenotifications.fightpandemics.xyz/post/5fac863a7c7e6d0011bb5974

**Comment by Zaydme** [comment]
I think all we need to do is add the notifications preferences link to the organization profile.
cc @ddveloper

**Comment by ddveloper** [comment]
@Zaydme  will do

**Comment by ddveloper** [comment]
didn't think about the Organisation before, need a little more work to reuse the Notification page, and update the unsubscribe page, will do it tomorrow

**Comment by ddveloper** [comment]
see #1796 for the added notification preference for organisations

**Comment by shrutigupta1981** [comment]
My point is when we didnt add any notification preferences for Organisation than how mail triggered?

**Comment by shrutigupta1981** [comment]
Shruti Gupta  1 hour ago
@Shruti Gupta the reason organisation got email is because they have default preference setting, which are all @Dawei Zhang In front end, where are the email notifications settings for Organisation? No where than emails shouldnt have triggered right? When Email notification settings doesn't exist for Organisation than how emails triggered?



New

Dawei Zhang  < 1 minute ago
@Shruti Gupta it was in the backend, when the organisation got created, it's created with the default value of trues, and our email services look up the value then decide to send out emails.
now new preference settings is created to reflect them in F/E
