### ISSUE TITLE
Notification-> Email notifications disabled and than enabled again. User has to manually check each option. Lets just not clear the checks.

### ISSUE THREAD

**Issue by shrutigupta1981** [FightPandemics/FightPandemics#1799]
When I disable Email notifications, Is it possible to show disabled view but checked not removed so that once I enable it, all checks remain intact and I as user dont have to do that exercise manually?

**Disabled View**
![image](https://user-images.githubusercontent.com/72843352/98897819-23717d80-2461-11eb-88dd-27a847e2cdcc.png)

**Enabled view**
![image](https://user-images.githubusercontent.com/72843352/98897874-35532080-2461-11eb-82b6-b83448921d3a.png)

**Comment by shrutigupta1981** [comment]
Dawei Zhang  29 minutes ago
yes Shruti, that's doable

**Comment by shrutigupta1981** [comment]
URL: https://featurenotifications.fightpandemics.xyz/

Steps:
1. Login and click on Profile
2. Click on My Profile
3. Click on Edit button
4. Click on Edit Notification
5. Toggle off Email Notification
6. Toggle on Email Notification again

**Actual Result: The Email Notifications preferences checks also gets cleared when Email Notification is disabled**

**Expected Result: The Email Notifications preferences checks shouldnt get cleared though should remain in disabled mode so that when User turns it on again, he doesnt has to manually check 5-8 times to set preferences once again**

**Comment by ddveloper** [comment]
use localStorage for now to remember the values, fixed in PR #1801 
![image](https://user-images.githubusercontent.com/44758313/98922914-e2409400-2487-11eb-8faa-a74d491ba966.png)
![image](https://user-images.githubusercontent.com/44758313/98923021-fdab9f00-2487-11eb-9c02-ea243edd29eb.png)

**Comment by shrutigupta1981** [comment]
Tested. Working for Individual. Email Settings are not getting off for Organisation. 

Steps:
1. Go to Organisation
2. CLick on Edit button
3. Toggle off the Email Notifications
4.CLick on Save Changes button
5. Again, click on Edit button
6. Email Notification Settings On only

**Actual Result: Email Notification Settings are on for Organisation**
**Expected Result: Email Notification Settings should be off**

**Comment by ddveloper** [comment]
yes @shrutigupta1981 , when I fixed the individual settings, the organisations' preference was not ready, now I can fix the organisation part

**Comment by ddveloper** [comment]
![image](https://user-images.githubusercontent.com/44758313/99050133-960b5780-254c-11eb-9152-f20bd02e7c18.png)
#1809 fixed this

**Comment by shrutigupta1981** [comment]
Working fine now. Tested.
