### ISSUE TITLE
Connect API for Liking and Unliking a Post

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#180]
- Logged in
  - [ ] Make a `PUT` request to `/api/:postId/likes/:userId` if a user HAS NOT liked a post.
  - [ ] Make a `DELETE` request to `/api/:postId/likes/:userId` if a user HAS liked a post.
- Not logged in
  - Redirect to login/sign up

More reference:
https://www.notion.so/fightpandemics/Feed-653658508c4649869787c48f3e4eee13

Contact @anniegiang for questions about how the frontend of the Feed was built.

**Comment by Naraujo13** [comment]
@limaneto Backend endpoints merged at #284
