### ISSUE TITLE
Set Maximum Character Limit User is Allowed to Enter in Feedback Responses

### ISSUE THREAD

**Issue by jessica-lau** [FightPandemics/FightPandemics#1806]
**Environment:** https://staging.fightpandemics.work/

**Steps to reproduce:**

- Click the feedback icon on the top right of the homepage when user is not signed in.

- Answer question on screen 1. When user reaches screen 2, enter as many characters in the response fields as the user wants. When user reaches screen 3, enter as many numbers in the age response field as the user wants. Submit feedback.

**Actual results:**

When user is on screen 2, he/she can enter as many characters in the response fields with no character limit.
When user is on screen 3, he/she can enter as many numbers in the response field with no integer limit.
Feedback can be submitted successfully.

**Expected Results:**

A max character limit should be set for the response fields on screen 2 (e.g. 1000 character limit).
A max 3 number limit (assuming there are people over age 99) should be set for the age response field on screen 3.

![image](https://user-images.githubusercontent.com/56090896/99011334-dd2c2500-2519-11eb-9fcb-c56342cd379d.png)

![image](https://user-images.githubusercontent.com/56090896/99011297-ca195500-2519-11eb-9ba0-f20356a41cc6.png)

**Comment by CamilaArias** [comment]
@speed-o-soundSonic 1000 char for text responses and 3 digits for age is good :)
