### ISSUE TITLE
Backend API Validation Not Returning Correct Status Code and Message

### ISSUE THREAD

**Issue by jessica-lau** [FightPandemics/FightPandemics#1807]
**Path:** https://staging.fightpandemics.work/api/feedback

**1.** Incorrect status code and message are being returned on the backend when a zero, negative integer or large integer is the value for "age". The correct status code should be a 400 Bad Request with an error message of something like "body.age should be positive integer".

![image](https://user-images.githubusercontent.com/56090896/99012307-12397700-251c-11eb-9e8a-b459d378e1a5.png)

![image](https://user-images.githubusercontent.com/56090896/99020326-4c127980-252c-11eb-991d-29ec8f65015e.png)

Also, in the database age is saved in double instead of Int32.

![image](https://user-images.githubusercontent.com/56090896/99014485-c210e380-2520-11eb-977f-75f6fcafbbbf.png)

**2.** Incorrect status code and message are being returned on the backend when a negative integer is the value for "rating". The correct status code should be a 400 Bad Request with an error message of something like "body.rating should be positive integer".

![image](https://user-images.githubusercontent.com/56090896/99012526-9f7ccb80-251c-11eb-8ccd-8ff8ad16d25c.png)

**Comment by jontkoh** [comment]
Just wanted to confirm as to why the data type is being seen as double. 

<img width="693" alt="feedback-obj-screenshot" src="https://user-images.githubusercontent.com/54458111/99899087-57b41d80-2c5b-11eb-8a66-e2b7f258e372.png">
<img width="445" alt="age-dataType-screenshot" src="https://user-images.githubusercontent.com/54458111/99899091-5da9fe80-2c5b-11eb-8fb8-eeb05700d0a3.png">

These are screenshots of mongo inside my docker container of my local env, and it's reading them as integers.

**Comment by jessica-lau** [comment]
Hi @galeza you had screenshot the age data type in the feedback form last time. Can you please confirm if you're still seeing the data type as double instead of int as I'm not sure where you got the screenshot from :) Maybe the data type changed since then? 

![image](https://user-images.githubusercontent.com/56090896/99920504-f2f7d200-2cf1-11eb-9cf3-b07b753a9b43.png)

Right now, I'm seeing the same thing as @jontkoh in my docker container in local - the age data type is an integer.

![image](https://user-images.githubusercontent.com/56090896/99920539-4538f300-2cf2-11eb-8418-9e0f21c6822b.png)

Thanks!

**Comment by galeza** [comment]
Hi,

For dev environment I use MongoDB Compass - and to connect to the DB. From docker-compose: port 27017 is exposed.
DM is more info is necessary how to connect to the local/dev DB.

For staging I use Robo 3T.
![Screen Shot 2020-11-23 at 15 40 06](https://user-images.githubusercontent.com/21987083/99975561-af10d580-2da2-11eb-9709-37d4d8f5c4fa.jpg)

There is no limitation for age, no validation - you can enter on UI or send in the Postman value like 7.777777777777777e+57 
![Screen Shot 2020-11-23 at 15 44 59](https://user-images.githubusercontent.com/21987083/99975737-e5e6eb80-2da2-11eb-9865-1bc64b1c945f.png)


It's more about using incorrect values, lack of validations.

When you enter correct data, in the DB you have int:
![Screen Shot 2020-11-23 at 15 40 22](https://user-images.githubusercontent.com/21987083/99975497-99031500-2da2-11eb-8c58-25ba58b44008.jpg)
