### ISSUE TITLE
Connect API for Commenting a Post

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#181]
Comment on a post (logged-in)
- [ ] Make a `POST` request to `/api/:postId/comments`, sending along the required data in the request body to the server. 

If not logged in, redirect the user to login/sign up.

More reference:
https://www.notion.so/fightpandemics/Feed-653658508c4649869787c48f3e4eee13

Contact @anniegiang for questions about how the frontend of the Feed was built.

**Comment by jyclam** [comment]
@anniegiang Can I be granted access for the FightPandemics notion page?
