### ISSUE TITLE
Connect API for Post CRUD operations

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#182]
A not logged-in user is redirected to login/signup.

A logged-in user can:

1. Create a Post 
   - [x] Make a `POST` request to `/api/posts/`, sending along the required data in the request body to the server.

2. Access any post (no auth required)
   - [x] Make a `GET` request to `/api/posts/:postId`.

3. Edit a post that they authored 
   - [ ] Make a `PATCH` request to `/api/posts/:postId`, sending along the required data in the request body to the server.

4. Delete a post that they authored
   - [x] Make a `DELETE` request to `/api/posts/:postId`.

More reference:
https://www.notion.so/fightpandemics/Feed-653658508c4649869787c48f3e4eee13

Contact @anniegiang for questions about how the frontend of the Feed was built.

**Comment by Naraujo13** [comment]
Backend endpoints merged at #284

**Comment by Naraujo13** [comment]
> A not logged-in user is redirected to login/signup.
> 
> A logged-in user can:
> 
> 1. Create a Post
>    
>    * [ ]  Make a `POST` request to `/api/posts/`, sending along the required data in the request body to the server.
> 2. Access any post (no auth required)
>    
>    * [ ]  Make a `GET` request to `/api/posts/:postId`.
> 3. Edit a post that they authored
>    
>    * [ ]  Make a `PATCH` request to `/api/posts/:postId`, sending along the required data in the request body to the server.
> 4. Delete a post that they authored
>    
>    * [ ]  Make a `DELETE` request to `/api/posts/:postId`.
> 
> More reference:
> https://www.notion.so/fightpandemics/Feed-653658508c4649869787c48f3e4eee13
> 
> Contact @anniegiang for questions about how the frontend of the Feed was built.

One quick thing, I think `/posts` doesn't require auth, but `/post/:postId` does (unauthenticated users can't access the post screen to see comments).

**Comment by robinv85** [comment]
@joshmorel @anniegiang any idea about progress, anyone working on this?

**Comment by anniegiang** [comment]
@robinv85  @joshmorel I think this issue is related to PR #402 by @silenceway  ?

@limaneto was working on the frontend too
