### ISSUE TITLE
Notification: web notifications dates need internationalization.

### ISSUE THREAD

**Issue by Zaydme** [FightPandemics/FightPandemics#1824]
The receive date of the web notifications is displaying non-user-friendly English-only dates. will need to be made more readable and internationalized.

steps:
- switch language to something other than English.
- open the web notifications dropdown.

expected results:
- The notifications dates should be translated.

Actual results:
- Shows English only dates.

![image](https://user-images.githubusercontent.com/46847212/99185623-5d859c80-274b-11eb-96e6-5e1433c03813.png)

**Comment by shrutigupta1981** [comment]
Please mention actual and expected results clearly @Zaydme

**Comment by Zaydme** [comment]
@shrutigupta1981 Sorry about that, I updated the comment above.

**Comment by shrutigupta1981** [comment]
np @Zaydme . Now I Understood . WIll check

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/99325770-d9571600-282b-11eb-97ed-4c1e18dcecf7.png)

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/99325954-2dfa9100-282c-11eb-89c6-3719315326b6.png)
