### ISSUE TITLE
Organisation user cannot unsubscribe, return "Not Found"

### ISSUE THREAD

**Issue by ddveloper** [FightPandemics/FightPandemics#1832]
Right now if trying to unsubscribe an organisation user, the page will show below "Not Found" error.

![image](https://user-images.githubusercontent.com/44758313/99198205-e00e5c00-274b-11eb-8afb-f8b3c5b67d79.png)

**Comment by shrutigupta1981** [comment]
On and Off both working 
![Screenshot_20201116-184313](https://user-images.githubusercontent.com/72843352/99341491-d6195580-283e-11eb-87bb-1c554527f8a5.jpg)
![Screenshot_20201116-184342](https://user-images.githubusercontent.com/72843352/99341511-ddd8fa00-283e-11eb-8827-7cd30b8b1e6d.jpg)
![Screenshot_20201116-184038](https://user-images.githubusercontent.com/72843352/99341522-e4677180-283e-11eb-9239-070338813017.jpg)
