### ISSUE TITLE
Not all user infor are necessary for the searching function, close them

### ISSUE THREAD

**Issue by ddveloper** [FightPandemics/FightPandemics#1835]
Osaigbovo and Igor discovered we have some unnecessary user information open to query

Line 139-150, should only allow necessary fields.

https://github.com/FightPandemics/FightPandemics/blob/a04509b01caa80c0bfe7c4916ed1179c3ddc3862/backend/lib/endpoints/users.js#L139

**Comment by Zaydme** [comment]
@ddveloper As the one who worked on the search feature I can confirm that all of those projected values are required and used in the components/Feed/User.js cards.

I see that #1836 removed "about", "location", "urls", "objective" and "needs", but those are used in the front end and displayed to the end user, you can see all of them here: 
![img](https://i.ibb.co/ZMHdD2r/Screenshot-20201121-004344-Chrome.png)

(objective and needs are used to display "offering/requesting help")

**Comment by ddveloper** [comment]
Thanks @Zaydme I was wrong about that, the main goal is to remove the coordinates for privacy reason, please help to review again

**Comment by Zaydme** [comment]
@ddveloper please check line 146. There is a condition that if the user decided to hide their location when creating their account `hide.location: true`, their location is not being projected in the search results, and it returns null in that case. so there is no location/emails leaks.
