### ISSUE TITLE
Add filters to /posts endpoint 

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#184]
In the `/feed` page, a user can filter posts based on the following filters:
1. Location (will use Google Maps API)
   - Related to Issue #64 
2. From Whom
3. Type
4. Need or give help

After a user selects filters, the Feed will make a `GET` request  to `/api/posts` that: 
 - [ ] Accepts queries of filter values.
 - [ ] Queries into database based on filter values.
 - [ ] Return to the client filtered posts that are paginated (10 posts) and lazy loaded on the client.

More reference:
https://www.notion.so/fightpandemics/Feed-653658508c4649869787c48f3e4eee13

Contact @anniegiang for questions about how the frontend of the Feed was built.

**Comment by robinv85** [comment]
So I guess title of the endpoint can change to "add filter parameters to posts API" or something like that instead of creating a new endpoint, I don't think that's necessary.

**Comment by anniegiang** [comment]
@robinv85 Yea I agree, will update the issue.
