### ISSUE TITLE
Edit & Delete commen's UI should be an ellipsis instead of individual buttons

### ISSUE THREAD

**Issue by skrithiga** [FightPandemics/FightPandemics#1841]
Currently, the comment section in a post has edit & delete as buttons.
![image](https://user-images.githubusercontent.com/5383010/99438033-3f51a500-28e1-11eb-93f5-d29910dbcca2.png)

It needs to be an ellipsis with the edit and delete as a menu bar.
![image](https://user-images.githubusercontent.com/5383010/99437988-2f39c580-28e1-11eb-93a5-19b1ce21844a.png)

**Comment by mathigayathri2001** [comment]
Hi @skrithiga, please review the enclosed screenshot. I tried by best, but found limitation to move the ellipsis top right side. Now, it is available on bottom. But, the functionality behind both the option edit/delete working fine. Please let me know whether I can go ahead with this change. In case, if you require to move the ellipsis on top right, then I may need some help from someone in #engieering team.
![Untitled1](https://user-images.githubusercontent.com/60233461/100405176-10e66f00-3031-11eb-8df8-b24fd290b723.png)

**Comment by skrithiga** [comment]
The positioning looks weird having it at the bottom. Can you also check in mobile view? 
@tejasm2 Any frontend engineer who can help?

**Comment by mathigayathri2001** [comment]
> The positioning looks weird having it at the bottom. Can you also check in mobile view?
> @tejasm2 Any frontend engineer who can help?

Hi @skrithiga  Please review the attached screen shot, Now, its moved to the top left, hope it is ok.
![Untitled3](https://user-images.githubusercontent.com/60233461/100464012-cbf72280-309a-11eb-8f53-54035ea5c4b7.png)
