### ISSUE TITLE
Able to create post for  organization when in individual profile account and vice versa. 

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1849]
Environment- staging
Browser -Google chrome 
Device used-Samsung Galaxy s8
1.login with valid user name and password 
2.click on switch account. 
3.click on any organization profile. 
4.click on create post as individual. 
Expected result 
It should not allow user to create post for individual when they are in organization account.
Actual result
It allows to create post for individual when they are in organization account and vice versa. 
![GIF-201117_193538](https://user-images.githubusercontent.com/41587211/99467821-2ced6080-290d-11eb-8d90-9053743ad10a.gif)

**Comment by rabbi08** [comment]
Related to PR #1843 
 But need to analyze, because after user clicks on 'Create Post' option as Indivi or Profile is there. to restrict user we need to remove this feature. So need some discussion.

**Comment by Zaydme** [comment]
This and #1843 should be one fix.
