### ISSUE TITLE
Issue for Vietnamese translation

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1852]
this is to keep track i need to check when the fixed data coming .  No coding involving

**Comment by adorapham** [comment]
![image](https://user-images.githubusercontent.com/70918430/99483881-0b43a780-2914-11eb-9846-2872fd5bb04c.png)


![image](https://user-images.githubusercontent.com/70918430/99483969-38905580-2914-11eb-9a4f-1baf6140366f.png)


![image](https://user-images.githubusercontent.com/70918430/99484060-70979880-2914-11eb-8743-6f18b37c5562.png)

**Comment by Zaydme** [comment]
@adorapham you corrected these on lokalize, so you are just waiting for the new translation to be imported into the website?

@Zaydme , yes I did correct and also translate all new keys, just wait for new translation to be imported into the website.

**Comment by adorapham** [comment]
8-check cookies-policy page , mixed english and vietnamese
![image](https://user-images.githubusercontent.com/70918430/99918185-1a3aa900-2cca-11eb-81cd-46615ed96a1b.png)

**Comment by adorapham** [comment]
1-fixed
![image](https://user-images.githubusercontent.com/70918430/100154448-6b79a280-2e5a-11eb-98dd-4bf7416e2784.png)

2-fixed
![image](https://user-images.githubusercontent.com/70918430/100154543-99f77d80-2e5a-11eb-8caf-2ab4ba719ab4.png)

3 and 4- fixed
![image](https://user-images.githubusercontent.com/70918430/100155222-bb0c9e00-2e5b-11eb-8755-0ed625c32529.png)

5-fixed
![image](https://user-images.githubusercontent.com/70918430/100155312-eabba600-2e5b-11eb-93eb-a5bdcdddd196.png)

6-fixed
![image](https://user-images.githubusercontent.com/70918430/100155507-41c17b00-2e5c-11eb-8cec-227c202f2aa3.png)

7-fixed
![image](https://user-images.githubusercontent.com/70918430/100155790-b72d4b80-2e5c-11eb-9fdf-6bb9db554c24.png)

8-fixed
![image](https://user-images.githubusercontent.com/70918430/100155864-d7f5a100-2e5c-11eb-81b3-073f3bf982c3.png)
