### ISSUE TITLE
Font for Polish language - About Us page

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1853]
Please correct fonts for Polish language like in this PR: #1603 - Add medium and bold Poppins font #1669
It was done for Help Board. Could we implement it also for About Us Page? 

![Screen Shot 2020-11-18 at 14 10 34](https://user-images.githubusercontent.com/21987083/99534587-eef14a80-29a7-11eb-84f3-50bed172cd06.png)

Home Page:
![Screen Shot 2020-11-18 at 14 11 53](https://user-images.githubusercontent.com/21987083/99534658-0b8d8280-29a8-11eb-8095-5120f2272d40.png)

**Comment by galeza** [comment]
The same issue for the Turkish language:
![Screen Shot 2020-11-18 at 19 22 42](https://user-images.githubusercontent.com/21987083/99571420-920b8980-29d3-11eb-89ba-d47aa0a20a55.png)
![Screen Shot 2020-11-18 at 19 21 44](https://user-images.githubusercontent.com/21987083/99571462-9e8fe200-29d3-11eb-848a-4b4e474c267f.png)

**Comment by CamilaArias** [comment]
@aleksarad if you have any questions about how this was solved in the Help Board reach out to @doheekim93

**Comment by aleksarad** [comment]
@CamilaArias thank you :)

**Comment by CamilaArias** [comment]
@Zaydme we still need to fix the same thing for Vietnamese
