### ISSUE TITLE
Switch Profile - Add new user selection pop up for user switch profile option

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1854]
when user click on ‘switch profile’ then pop up should come to ask them if they want to be on same page.., 

"Do you want to be on same page?"
“yes or no.” . 

They will choose yes, if they want to stay in same page where they are like either in Helpboard , about us or any page. else if user choose 'No', then they will be navigated back to their respective Profile page.

**Comment by joshmorel** [comment]
We did discuss this before... cc @camba95 staying on the same page is okay, it is just imperative that if you stay on the same page you do a window.reload or else the data will be wrong for the selected user (whether it is post related, messaging related, whatever).
