### ISSUE TITLE
Avatar -> The user's names initials logo is not displayed when user add comments, but after avatar is uploaded it works fine

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1860]
1. Open 'Fightpandemics.com'
2. Select a profile with no avatar uploaded, should have 'user initials' as user profile logo.
3. Select any post and add comment

Issue: You will observe that user's profile logo as initials, is missing for the comments. refer below screenshot.

![image](https://user-images.githubusercontent.com/67168400/99607634-2b3d9e80-29da-11eb-8c00-18ebc993518a.png)

Please note this issue exist in STG too.

**Comment by ddveloper** [comment]
not sure initials is a better solution, imagine many users all share the same initials when they don't have pictures uploaded.
while on the other hand, many users share the same grey icons currently ( I cannot tell which is a better one )
any advice? @CamilaArias @nfranklin9
