### ISSUE TITLE
Messaging - QA Feedback

### ISSUE THREAD

**Issue by Zaydme** [FightPandemics/FightPandemics#1865]
Please make sure you are testing on the messaging branch review build: 
https://featuremessage-modal1457.fightpandemics.xyz/inbox

Testing scope: 
- User OR Org must be able to message other Users/Orgs from:
-- Post page.
-- Post in Feed.
-- Post in profile page.
-- Message button on the profile page.
-- Message button on the "Poeple" search tab.
-- Message button on the "Organizationz" search tab.
- Messages sent from a post must have an embed post in them.

- User should not be able to contact themself.
- User should not be able to contact their owner Orgs.
- Org should not be able to contact itself.
- Org should not be able to contact owner 
- Org should not be able to contact Orgs owned by its owner.

- In the inbox, Users and Orgs should be able to:
-- Send/Edit/delete messages.
-- the recipient must see all of this in real time.
-- The online status must update in real time.
-- The blue unread indicator must appear in real time when you receive a message on a conversation you are not currently active on.

- The following actions need to be tested for both users and orgs: 
-- Blocking a user/org.
-- Unblocking a user/org
-- Accepting a message request.
-- Ignoring a message request.
-- Archiving a conversation.
-- Unarchiving a conversation.
-- The blocked user must see themselves getting blocked in real time, and they shouldn't be able to send messages anymore.
-- same for Unblocking.

- The inbox icon in the header:
-- Must show the number of unread conversation + requests. Not total messages.
-- should update in real time in all pages.
-- should not increase if the new message was received from the conversation you are currently active on (open in the inbox).
-- Should decrease when you read a conversation.
-- Should be independent for each org/user while switching.

- when the user updates their avatar or name:
-- The conversation name and avatar must be updated (after refresh). 

Advanced test cases:
- on a connection loss (internet cut), after the connection is back, the messages received when the connection was lost must get loaded, the user should be able to resume messaging seamlessly.

**Comment by nivetheatha** [comment]
Tested on Samsung Galaxy s8,Google chrome 
1.Go to messenger .
2.click on ... and choose archive from the menu.
3.Go to message settings.
4. click on unarchive and click on back button. 
Expected result 
It moves to previous page.
Actual result
It lands on Blank page.
![GIF-201119_155432](https://user-images.githubusercontent.com/41587211/99724139-313a8a80-2a81-11eb-8f7a-901f7a6ed48a.gif)

**Comment by nivetheatha** [comment]
Unarchive button from the message setting is not fit into the screen. 
![Screenshot_20201119-160045_Chrome](https://user-images.githubusercontent.com/41587211/99724455-a1491080-2a81-11eb-8578-c80aed1724d2.jpg)

**Comment by nivetheatha** [comment]
1.Go to messenger.
2.Delete any message.
3.click on the deleted message and choose edit.
It leads to a blank page.
![GIF-201119_170454](https://user-images.githubusercontent.com/41587211/99732698-f1c66b00-2a8d-11eb-9d8c-eb57ab411081.gif)

**Comment by jessica-lau** [comment]
**On Desktop (chrome):** 
1.  Mouse cursor should change to the pointer or default style when user hovers over the scrollbar in the message modal. The right corners of the message textbox are cut off when the scrollbar appears.

![Screen Recording 2020-11-19 at 05 27 32 29 PM](https://user-images.githubusercontent.com/56090896/99732549-af049300-2a8d-11eb-9266-69feb1e1bc19.gif)

2. Don't see option to unarchive a conversation in the Message Settings after archiving it. Conversation card also stretches to the end of the right side of the page.

![Screen Recording 2020-11-19 at 05 55 46 13 PM](https://user-images.githubusercontent.com/56090896/99734272-816d1900-2a90-11eb-93dd-aab41719d7d9.gif)

**Comment by Bhavaninalla** [comment]
Tested on Android mobile
1.Click on messenger icon
2.Click on user and send a message.
I am not able to see the last message 
![ezgif-7-22ad5e899adc](https://user-images.githubusercontent.com/72236992/99750340-0b1ee580-2a95-11eb-9fec-85f45f0d2fae.gif)

**Comment by Bhavaninalla** [comment]
Tested on desktop
1 sign in
2.click on user profile
3. click on " Add on link "
 I observed when i click that add on link button  it redirects to Amazon page 
![ezgif-7-c5c3aaff481a](https://user-images.githubusercontent.com/72236992/99751987-45d64d00-2a98-11eb-91cb-015753033c48.gif)

**Comment by sheeba1** [comment]
I received a message from oct 14, for one of my posts. I deleted the post.then when I click on it I get the following page. Help board comes in middle. (chrome/windows 10)

![image](https://user-images.githubusercontent.com/65972693/99821011-56251100-2b06-11eb-8269-df0b59f5c1ad.png)

**Comment by rabbi08** [comment]
@Zaydme 
1 Wrong count of Unread messages is displayed for 'Inbox' icon, please see below screenshot.
![image](https://user-images.githubusercontent.com/67168400/99822444-39e29d80-2b21-11eb-97d0-5294f59a1f2a.png)

2. Only on Desktop: Email received from FP, is not in readable form in user's personal inbox: The email received is having extra large icon of FP. The email is displayed for a sec and then the icon replace the screen. After user zoom in and scroll, the image is too big and text is too small.  Refer below GIF 

![ezgif com-gif-maker (62)](https://user-images.githubusercontent.com/67168400/99823678-a90cc180-2b22-11eb-9e58-cba5dc183bf9.gif)

3. In my personal inbox -> click on 'View Inbox' link, you will observe that user is directed to FP inbox login page -> 
Issue: this page is not having update link i.e. no 'profile logo or Profile Switch' options. Refer below GIF
![ezgif com-video-to-gif 29](https://user-images.githubusercontent.com/67168400/99824579-e45bc000-2b23-11eb-8ede-023710b07931.gif)

4. The 'Cancel' & 'Done' button should have BLUE background when hover on, like we have on 'Clear Filter'

**Comment by Zaydme** [comment]
@Bhavaninalla this https://github.com/FightPandemics/FightPandemics/issues/1865#issuecomment-730811875 is normal behavior, because you have set "Website" to amazon on your profile settings.
![image](https://user-images.githubusercontent.com/46847212/99832503-e85a0300-2b60-11eb-8eda-85d3ad8fcf6c.png)

**Comment by nivetheatha** [comment]
Tested on Samsung Galaxy s8
1.login with valid user name and password 
2.Go to profile.
3.Edit profile information. 
4.click on save.
Observation:
1.Edited name is not reflected in the menu.
2.Avatar is not in the menu.
3.If we sign out it leads to a blank page. 
![GIF-201120_160129](https://user-images.githubusercontent.com/41587211/99850492-76c38a00-2b4b-11eb-86c1-bc55e41d3ec8.gif)

**Comment by adorapham** [comment]
Testing on Window10 , chrome , laptop, will update all testing flows that I perform
**Flow 1**  - Post Help Board page 
User should not be able to contact themself. (**passed**)/Org should not be able to contact itself. (**passed**) Individual can send message to Individual with post (**passed**)/Must show the number of unread conversation + requests. (**passed**)-Need to test more for every cases/should update in real time in all pages(**passed**) - need to test more for every cases/Should decrease when you read a conversation (**passed**)  need to test more for every cases/The blue unread indicator must appear in real time when you receive a message on a conversation you are not currently active on (**passed**)  need to test more for every cases.  **Note** : for this flow, i start with Vietnamese language but when i click on switch account , it set back to english, i think the reason might be switch account is not translated to multiple language yet.  If it is incorrect, that can be a defect.
![flow1](https://user-images.githubusercontent.com/70918430/99865719-93b68800-2b60-11eb-85ff-e73cc069b00d.gif)
**Flow 2**-Post Help Board page 
Org should not be able to contact owner (**passed**)/Org should not be able to contact Orgs owned by its owner(**passed**) User should not be able to contact their owner Orgs(**passed**)
big file so i have to zip and put here 
[ezyzip.zip](https://github.com/FightPandemics/FightPandemics/files/5577077/ezyzip.zip)

**Comment by adorapham** [comment]
**issue 1**  it might not in this scope , if you want me to put on existing defect or create a new one, please let me know
Switch Account- Profile page is not matching with account when using the switch account feature. It should behave like inbox page.
1-login in as individual - VP who has three organizations 1-Nature Food 2-Hoa Phat 3-Heineken Viet
And navigate to inbox
2-switch account to  Nature Food  and select Yes to stay on the current page - see inbox of Nature Food 
3-switch account to Hoa Phat and select  Yes to say on the current page, see inbox of Hoa Phat 
4-navigate to View Profile page see Hoa Phat organization profile (passed until this point)
5-click on Switch account Nature Food and Yes for staying on the current page 
6- see on the top ant-avatar ant-avatar-circle sc-gzcbGf hNajDo ant-dropdown-trigger 
    <span class="ant-avatar-string" style="transform: scale(1) translateX(-50%);">NN</span> has correct NN
but the profile page is still keep Hoa Phat , it should refresh with NN profile page instead like the inbox 
7-switch to Heineken, see the top avatar updated to Heineken viet but the profile page still keep Hoa Phat=>it should refresh with Heineken page
8-switch back to individual VP and see VP on the top Avatar but the profile page still keep Hoa Phat.  Expect VP profile in on display
![issue1SwitchAccount](https://user-images.githubusercontent.com/70918430/99867693-77224c00-2b70-11eb-98da-013942ae6c9f.gif)
**Issue 2**: flow 2 the logic is passed but we see the loading icon at the bottom keep loading
ezyzip.zip

**Comment by rabbi08** [comment]
> **issue 1**  it might not in this scope , if you want me to put on existing defect or create a new one, please let me know
> 
> Switch Account- Profile page is not matching with account when using the switch account feature. It should behave like inbox page.
> 
> 1-login in as individual - VP who has three organizations 1-Nature Food 2-Hoa Phat 3-Heineken Viet
> 
> And navigate to inbox
> 
> 2-switch account to  Nature Food  and select Yes to stay on the current page - see inbox of Nature Food 
> 
> 3-switch account to Hoa Phat and select  Yes to say on the current page, see inbox of Hoa Phat 
> 
> 4-navigate to View Profile page see Hoa Phat organization profile (passed until this point)
> 
> 5-click on Switch account Nature Food and Yes for staying on the current page 
> 
> 6- see on the top ant-avatar ant-avatar-circle sc-gzcbGf hNajDo ant-dropdown-trigger 
> 
>     <span class="ant-avatar-string" style="transform: scale(1) translateX(-50%);">NN</span> has correct NN
> 
> but the profile page is still keep Hoa Phat , it should refresh with NN profile page instead like the inbox 
> 
> 7-switch to Heineken, see the top avatar updated to Heineken viet but the profile page still keep Hoa Phat=>it should refresh with Heineken page
> 
> 8-switch back to individual VP and see VP on the top Avatar but the profile page still keep Hoa Phat.  Expect VP profile in on display
> 
> ![issue1SwitchAccount](https://user-images.githubusercontent.com/70918430/99867693-77224c00-2b70-11eb-98da-013942ae6c9f.gif)
> 
> 
> 
> 

@adorapham  
issue:1 this is intentional because as me and Zayd discussed that:
“Well maybe they want to comment on the other profile posts, or see how it looks to others.
Also if we did that, it will be very hard for them to find the first user profile, but now if they want the new selected user profile they can just click "go to my profile"

Hope that make sense. Thanks
@rabbi08 , @Zaydme ,  I  try to see how to apply on they want to comment on the other profile's posts or see how it looks to others. but since the profile page is no changed , the top avatar is changing, when you click on help board , you see the help board displaying the information of the top avatar, so if you want to go back to profile ,you need to click on view profile of the top avatar anyway.   The only way you can keep the not change profile post is using the back button and not very usual.  Within Individual profile and its organization , I think it should not be a problem. outside users who use our platform, they might think it is a defect. please check to see what other team members thinking.  I am fine with any decision but I just voice my thinking.  Please correct me if I am wrong.
per discussion in slack with Rajbir Kaur  , it works as design #1856

**Comment by Latha-AP** [comment]
1. User 2 messaged on post of User1
2. User1 blocked User2
3 User 2 tried to send another message , he got pop like this
**"Your message to testpandas staging001 concerning the "11/24" was not delivered.".**
4. User2 tried to message in message box, he will have a message in the textbox are like this
**"You've been blocked by testpandas staging001. You can no longer message them.".**

**About these messages, if user has same info at both the places could be better.
Also, the User2 should not be known that user 1 blocker him. We never see this  in any other social networking sites that some one blocked you! They simply can't communicate. If any time User1 can change his mind , their relationship would be smooth.**
![block message](https://user-images.githubusercontent.com/72217779/100155340-f6a76800-2e5b-11eb-9fc6-996830f9b1bb.gif)
