### ISSUE TITLE
Create a "report" button

### ISSUE THREAD

**Issue by kellgolden** [FightPandemics/FightPandemics#1875]
Context: As a Logged In User, when I am looking at a user's post, I want the option to report or hide their post. This story is to add an ellipsis button that will populate the option for the user to report or hide another user's post. Users trying to click on these buttons need to be logged into FP. If users are not logged in, and they click on either of these buttons, they should be redirected to FP's login page.

Designs: https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=88%3A2

<img width="658" alt="Screen Shot 2020-11-21 at 10 02 44 PM" src="https://user-images.githubusercontent.com/64812703/99892757-51677680-2c46-11eb-9282-99019bb7705c.png">

<img width="646" alt="Screen Shot 2020-11-21 at 10 02 52 PM" src="https://user-images.githubusercontent.com/64812703/99892759-55939400-2c46-11eb-9d31-4421788b72b0.png">

Acceptance Criteria:

Users can see and click on an ellipsis within a user's post, and report or hide that same post.

**Comment by nadinejuraschek** [comment]
@kellgolden Does this issue only include the "..." and "report post" buttons or all four buttons and their functionality?
Also, I can not open the design file or find the design for this on Zeplin.

**Comment by kellgolden** [comment]
In addition to adding the "..." and "report post", we also need the "hide post" option.

**Comment by kellgolden** [comment]
@Zaydme and @rabbi08, has this been through QA, yet?

**Comment by Zaydme** [comment]
@kellgolden This is not ready for the test now, will be on Friday
