### ISSUE TITLE
Location reverse geocode latitude < 0 results in error

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#1881]
Call to Auckland, NZ for example `location-reverse-geocode?lat=-36.8597592&lng=174.3238532` results in:

```
{
"statusCode": 400,
"error": "Bad Request",
"message": "querystring.lat should be >= 0"
}
```

This exludes the entire southern hemisphere.

https://github.com/FightPandemics/FightPandemics/blob/f8f3249d73c62b1c060da9694c1a1467fdd863c4/backend/lib/endpoints/schema/geo.js#L20

**Comment by aditilamkhede** [comment]
@joshmorel does this still needs a fix? or @jontkoh is working on it?

**Comment by joshmorel** [comment]
Go for it @aditilamkhede

**Comment by aditilamkhede** [comment]
@joshmorel, I have changed this(.prop("lat", S.number().minimum(0).maximum(90).required()) ) to .prop("lat", S.number().minimum(-90).maximum(90).required()) and that's the limit I guess. It seems t be working fine.
