### ISSUE TITLE
Unlogged user able to messenge from the profile. 

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1884]
Environment staging 
Browser Google chrome 
Device used-Samsung Galaxy s8
1.Go to help board. 
2.Click on the profile from the post shown.
3.click on message icon. 
Expected result 
Should not allow unlogged user to message. 
Actual result
It is allowing to message. But the message is not sent.
![GIF-201122_154046](https://user-images.githubusercontent.com/41587211/99916731-d059bf00-2cd9-11eb-8d1b-ae8df28b838a.gif)

**Comment by Zaydme** [comment]
@nivetheatha 
This is fixed in #1880
Please test it there.
