### ISSUE TITLE
Individual profile-> 'Edit Security' option is removed from Edit profile

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1892]
1. Open 'https://staging.fightpandemics.work/'
2. Login with valid username/pwd
3. Navigate to 'View Profile'-> Edit Profile

Issue: You will observe that user is NOT having the option to 'EDIT security'. Refer below screenshot.

![image](https://user-images.githubusercontent.com/67168400/99928763-86dc9480-2d18-11eb-9be1-71c9f33d6db4.png)

Please note this issue is WORKING FINE in PROD.

**Comment by adorapham** [comment]
@rabbi08 , it seem to me the Edit Security is only for Individual profile for its organization , we don't have the Edit security
for Individual Profile
![image](https://user-images.githubusercontent.com/70918430/99933356-ad4a0200-2d0f-11eb-82d8-2c46842a5c41.png)
for Organization Profile
![image](https://user-images.githubusercontent.com/70918430/99933403-d36fa200-2d0f-11eb-8032-2989ed621d61.png)

**Comment by rabbi08** [comment]
> @rabbi08 , it seem to me the Edit Security is only for Individual profile for its organization , we don't have the Edit security
> for Individual Profile
> ![image](https://user-images.githubusercontent.com/70918430/99933356-ad4a0200-2d0f-11eb-82d8-2c46842a5c41.png)
> for Organization Profile
> ![image](https://user-images.githubusercontent.com/70918430/99933403-d36fa200-2d0f-11eb-8032-2989ed621d61.png)

yes, this option is only available for individual profile. In my screenshot, its individual profile user.

**Comment by rabbi08** [comment]
@adorapham agree, I recheck with with email /pwd user and got this, thnx:

this issue exist for individual profile logged in using social media login #1895 
This works fine If I login using email/pwd but not working as Linkedin user.

nice @rabbi08  👍

**Comment by ddveloper** [comment]
Hi @rabbi08 for social account, there is no login user name / password, so I think not showing `Edit Security` make sense?

**Comment by rabbi08** [comment]
> Hi @rabbi08 for social account, there is no login user name / password, so I think not showing `Edit Security` make sense?

Yes, agree.
Thanks a lot @ddveloper

**Comment by rabbi08** [comment]
closing this issue as invalid for social accounts.
