### ISSUE TITLE
Avatar is not updated for social media logins

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1895]
1. Open 'https://staging.fightpandemics.work/'
2. Login through social media login and observe that profile avatar
3. Navigate to profile page and upload avatar. 
You will observe that avatar is succesfully uploaded displayed at all locations.

4. Now logout and login again 
Issue: You will observe that no avatar is displayed only user profile logo of initials is displayed. 

Refer below GIF
![ezgif com-gif-maker (69)](https://user-images.githubusercontent.com/67168400/99934218-5eaa6100-2d2b-11eb-9c36-191afdd97d76.gif)

Also, the avatar is displayed again properly after user view/switch profile .

**Comment by ddveloper** [comment]
hi @rabbi08 , please try PR #1896 , test link: https://feature1895-homePage-Avatar.fightpandemics.xyz
