### ISSUE TITLE
Notification- No notification received for 'Message' & 'Share' options

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1900]
1. Open 'https://staging.fightpandemics.work/'
2. Login as user-1 and select a post from user , who you can verify,
3. Now, Like/comment/Share/message on the post

4. Login as the user of the commented post.

Issue: You will observe that notification is received for 'Like and Comment' only but not for share and message option. Even though in preference it is checked.

Refer below screenshot
![image](https://user-images.githubusercontent.com/67168400/99998532-d197f400-2d8c-11eb-883a-3d7a595e583a.png)

Also, in my personal email-> I got email notification for like/comment/message.

**Comment by rabbi08** [comment]
For messages, the notification is on message icon : expected

**Comment by Zaydme** [comment]
@rabbi08 should we close this one?

**Comment by rabbi08** [comment]
No notification for Share/messages as per latest updates.
