### ISSUE TITLE
Mobile -> Notification-> The page title of the page 'Edit Notification' is NOT displayed correctly on mobile.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1901]
1. Open 'https://staging.fightpandemics.work/'
2. On MOBILE -> Login as valid user
3. Navigate to 'View Profile'-> 'Edit Notification'

Issue: You will observe that that the page title on mobile is 'EDIT profile' or 'Edit Org Profile' for ORG.
It should be 'Notification Preference' .

Refer below screenshot from mobile
![IMG_4022](https://user-images.githubusercontent.com/67168400/99999183-c5f8fd00-2d8d-11eb-9412-411b222bb4fa.PNG)

Below screenshot from Desktop
![image](https://user-images.githubusercontent.com/67168400/99999149-b8437780-2d8d-11eb-8f7c-b0c70a462edf.png)

Query: Why the the heading is 'Email Notification' Can it be more related to 'Notification Settings/preferences'

**Comment by rabbi08** [comment]
@ddveloper please update
- page title for mobile for should be 'Notification Preferences'
- The heading for 'Notification Settings' should be updated as <message icon> Notification Email Settings

Thanks.

Please see below screenshot.
![FightPandemics (18)](https://user-images.githubusercontent.com/67168400/100052898-e60bd900-2dec-11eb-9748-876d129bf5a6.png)

**Comment by ddveloper** [comment]
updated, @rabbi08 please also have a check for Account setting page and Profile setting page, those title along with Notification setting page are all updated together.
