### ISSUE TITLE
Create "Report Modal"

### ISSUE THREAD

**Issue by kellgolden** [FightPandemics/FightPandemics#1904]
User Story: As a Logged In User, after I report a post, I want to be notified that the post I reported, has been reported.

Designs: https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=88%3A2

<img width="679" alt="Screen Shot 2020-11-23 at 6 02 17 PM" src="https://user-images.githubusercontent.com/64812703/100025044-08cecb00-2db6-11eb-9705-06f28d6f36a6.png">

Success Story: Users are notified once they report a post.

Ensure that you set the base branch of your pull requests to feature/postmoderation.

**Comment by OzkanAbdullahoglu** [comment]
I think this should be closed if QA tests are finished
