### ISSUE TITLE
Message deleted is still counting toward the total message not read

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1905]
Here is flow
1-Person A search and see post of person B, then send the message to person B
2- Right after that, person A delete the sent message to person B
3-Person B login and see new message coming from person A with the note- This message was deleted and Do you want to accept the message request? you can't replay until you accept the request (Accept, Ignore,Block)

My expectation is if the person A send message to Person B, and delete right after that, if the person B is not reading it yet, we should delete the message for person B inbox.
![image](https://user-images.githubusercontent.com/70918430/100025299-5ab72700-2d9d-11eb-8f1a-9afae720795b.png)

**Comment by adorapham** [comment]
@Zaydme , @rabbi08 , please check to see if it is a valid defect

**Comment by Zaydme** [comment]
@adorapham this is expected behavior.
When a message is deleted, we keep "This message was delete." As a proof that there was something before, same applies for a message request, the recipient needs to know that there was a message sent to them, even if it was deleted.

**Comment by adorapham** [comment]
> @adorapham this is expected behavior.
> When a message is deleted, we keep "This message was delete." As a proof that there was something before, same applies for a message request, the recipient needs to know that there was a message sent to them, even if it was deleted.

@Zaydme , i know for the tracking record but it is strange to see deleted message with the question  do you accept , ignore or block .  @rabbi08 what do you think?

**Comment by Zaydme** [comment]
I think in the case you will go to the person's/org's profile, see if they are relevant for you. if yes, you can accept the request and ask why the messaged you in the first place, if now you block them so they stop being annoying lol. 
@Zaydme make sense
