### ISSUE TITLE
No account blocked but message is delivered from one person but not the other

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1906]
here is my observation, I have 3 accounts and check each account,  have no account is blocked
1-Vince Pham
2-Adora Pham
3-Hanh Nguyen
from post page
VP can send the msg to AP successfully
AP can't send the msg to VP with message- Your message to Vince Pham concerning the "offering help for testing post was not delivered" (note : I try many times with different message and get the same result ).  The strange is I  check the block account from AP but don't see any block account for VP or vice versa
AP can send the msg to HN successfully ( I check later not recording)
HN can send the msg to VP successfully 
![unableSendMessage](https://user-images.githubusercontent.com/70918430/100029547-6824df00-2da6-11eb-815e-3fe9b4ac0dd1.gif)

**Comment by adorapham** [comment]
@rabbi08 @Zaydme Please check this one.

**Comment by Zaydme** [comment]
@adorapham you have a waiting message request from VP, you can notice that on the request it says "You cannot send a message until you accept this request".
So you have to accept the message request from someone before you can message them.

**Comment by adorapham** [comment]
> @adorapham you have a waiting message request from VP, you can notice that on the request it says "You cannot send a message until you accept this request".
> So you have to accept the message request from someone before you can message them.

@Zaydme , Thank you , i am able to send now  sorry  since it is a learning process :)
