### ISSUE TITLE
Request help-->medical-->location  and choose people filter medical and offer help option is removed automatically. 

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#1907]
Environment staging
Browser Google chrome 
Devices used  Samsung Galaxy s8
1.choose request help.
2.choose medical.
3.provide location (ex bensalem pa)
4.select people and provide some value (ex people:nivethetha)
5.click enter.
Expected result 
From the shown result people with the name nivethetha should be shown. 
Actual result 
Offer help and medical applied in the filter removed automatically. 
![GIF-201123_203830](https://user-images.githubusercontent.com/41587211/100036175-b8fbfe00-2dcd-11eb-95d7-70ef5f755c5f.gif)

**Comment by Zaydme** [comment]
This is expected behavior, when searching for people, you can only user location filrer.
All other filters (medical supplies....) Will only work for posts.
Also help type, "offering/requesting help" will only work when you are searching for posts, not people or orgs.

**Comment by nivetheatha** [comment]
@Zaydme In that case I can close the issue.
