### ISSUE TITLE
Words/phases need to be translated to designed languages

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#1916]
1-Cancel from sending Post message
![image](https://user-images.githubusercontent.com/70918430/100167998-3b8bc880-2e75-11eb-979d-bf9ea37cf40e.png)

2-Offer/Request from inbox - post type 
![image](https://user-images.githubusercontent.com/70918430/100168047-55c5a680-2e75-11eb-8081-4bfc542fe031.png)

3- No more Notifications 
![image](https://user-images.githubusercontent.com/70918430/100168141-860d4500-2e75-11eb-84e1-942df4406ef1.png)

4-Edit Organization Notification
on/off instant Digest
![image](https://user-images.githubusercontent.com/70918430/100168288-d4badf00-2e75-11eb-9558-7f43bd1fe73d.png)
![image](https://user-images.githubusercontent.com/70918430/100168330-e4d2be80-2e75-11eb-94b3-99ea9958b3b1.png)

**Comment by adorapham** [comment]
checking on staging

1-fixed
![image](https://user-images.githubusercontent.com/70918430/100488605-04f7bd00-30c4-11eb-9f34-d327908c6549.png)

2-fixed
![image](https://user-images.githubusercontent.com/70918430/100488900-daa6ff00-30c5-11eb-9ecd-df3f03cd673d.png)



3-not fixed
![image](https://user-images.githubusercontent.com/70918430/100488631-2eb0e400-30c4-11eb-8800-c6a4a1a050a4.png)

4-might be fixed but the data is not translated
![image](https://user-images.githubusercontent.com/70918430/100488813-40df5200-30c5-11eb-8b42-9aba744cfd00.png)

**Comment by Zaydme** [comment]
3 is also not translated yet.
