### ISSUE TITLE
Desktop: Fix nav bar items behaviour and click area

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1928]
### Issue 
On Desktop, the language, feedback and profile icons in the nav bar have irregular and too small click areas which makes it hard to interact with. Also these icons do not behave as the rest when hovered on.

Correct:
![image](https://user-images.githubusercontent.com/25089562/100191701-5be87100-2ecf-11eb-9952-2be5f94f36e6.png)

Incorrect:
![image](https://user-images.githubusercontent.com/25089562/100191308-a74e4f80-2ece-11eb-9816-cd180b1e2793.png)
![image](https://user-images.githubusercontent.com/25089562/100191319-acab9a00-2ece-11eb-8a78-0fc09828d8e3.png)

### To Fix
Feedback, language and profile icons should have their click areas defined as the rest of the items like messaging and notifications do, and they should behave the same on hover.

**Comment by abideen11** [comment]
Correct me if I'm wrong-you want the feedback and profile icons to be bigger and want an underline to appear if the arrow hovers on top of it?

**Comment by aditilamkhede** [comment]
@CamilaArias let's talk about this, whenever you have chance.

**Comment by CamilaArias** [comment]
@abideen11 the icons should be the same size, the container that is clickable needs to be like those from messages and notifications icons, and yes the same underline should show up on hover :)
@aditilamkhede message me on Slack whenever :)

**Comment by chrislemus** [comment]
something like this? @CamilaArias 

![Screen Shot 2020-11-26 at 9 57 52 PM](https://user-images.githubusercontent.com/61127478/100405890-8d2d8200-3032-11eb-83ff-d12aa9f1e53b.png)

**Comment by CamilaArias** [comment]
Yup @chrislemus that's good!

**Comment by aditilamkhede** [comment]
@CamilaArias I have few questions, so these 2 are dropdown menus, that's why probably they didn't add hover style to it. But if it was indeed needed even if they are drop down menu then probably missed the implementation.
Or do you want to open menu itself on hover

@chrislemus let me know if you are already working on it. I will look into another issue.

**Comment by chrislemus** [comment]
@aditilamkhede Yes, I had already started working on it. My apologies for not asking to get assign to this issue, I'm fairly new and getting used to Github.
