### ISSUE TITLE
Modify Create Post button

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1930]
Should be [**-> This <-**](https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=145%3A328)  (link to Figma file). Inspect on Figma for specs.
![image](https://user-images.githubusercontent.com/25089562/100197654-5859e780-2ed9-11eb-8ab9-c4515318dfef.png)

Current:
![image](https://user-images.githubusercontent.com/25089562/100197554-39f3ec00-2ed9-11eb-9741-e59da52e01f4.png)

**Comment by rabbi08** [comment]
Closing this issue as this is fixed.

**Comment by ddveloper** [comment]
issue already fixed in staging
