### ISSUE TITLE
Reorder languages in the selector menu

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1940]
Items in the Language selector menu should be sorted alphabetically, as per the language's English name.
![image](https://user-images.githubusercontent.com/25089562/100293271-e7124700-2f61-11eb-8685-f3cc0d00246d.png)

Just need to sort the index in this file in the correct order, and add in the comment that new languages should be added alphabetically as well.
https://github.com/FightPandemics/FightPandemics/blob/staging/client/src/locales/index.js

**Comment by chrislemus** [comment]
submitted pull request
