### ISSUE TITLE
Mobile: Unable to 'Paste' text in the textbox while messaging

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1950]
1. Open FP app and login as valid user and navigate to Inbox
2. Select any user and tap in the textbox to have an option to Paste. 

Issue: You will observe that options as 'Select/Select all' are displayed but no Paste option.

**Comment by ddveloper** [comment]
my Android view seems fine, what's your device and browser @rabbi08 
![image](https://user-images.githubusercontent.com/44758313/100425051-5e6bd780-3043-11eb-8a13-74d151cf7aec.png)

**Comment by rabbi08** [comment]
> my Android view seems fine, what's your device and browser @rabbi08
> ![image](https://user-images.githubusercontent.com/44758313/100425051-5e6bd780-3043-11eb-8a13-74d151cf7aec.png)

iPhone 11 pro max

**Comment by emtay** [comment]
This is working for me on iphone 6s

**Comment by Zaydme** [comment]
Works for me on Android.
![IMG_20201127_235729.jpg](https://user-images.githubusercontent.com/46847212/100488116-2d9fa700-3104-11eb-9034-b567f48547c8.jpg)

**Comment by rabbi08** [comment]
This is working fine, may be it was more zoom in out the paste was not working. Tested again, it worked
Hence closing this issue. Thanks
