### ISSUE TITLE
Inbox-> The 'Online' status of the user is not showing the real time status

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1951]
1. Open 'FP' application and login as valid user
2. Navigate to Inbox, and for testing have another online user to communicate with (both as Individual and ORG)

Issue: You will observe that when user switch between Individual user and Org user the online status is not showing the real time update.

![image (1)](https://user-images.githubusercontent.com/67168400/100394674-02d22780-300c-11eb-8537-8c2f7db61c50.png)

**Comment by emtay** [comment]
@rabbi08 - little confused. the active status is turning off when user switch from indiv to org or it's staying on when it should turn off?

i believe it is only active when user is actually in inbox- correct @Zaydme 

cc @tejasm2

**Comment by Zaydme** [comment]
Yes, it should only be active for selected user.
But there is an issue with this behavior.
So sometimes the selected user appears to be offline even while chatting.
