### ISSUE TITLE
Navigation bar language submenu position

### ISSUE THREAD

**Issue by chrislemus** [FightPandemics/FightPandemics#1953]
Language submenu does not stick to Navbar and scrolls away with page scroll.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/61127478/100397636-bfca8100-3018-11eb-9124-ef1d530a38aa.gif)

**Comment by aditilamkhede** [comment]
Just to add to  this, it only happens when you first scroll the page a little bit and then click on language menu and scroll page again.

**Comment by ddveloper** [comment]
this is same as #2099 , which is fixed, so close this
