### ISSUE TITLE
Configure logger on the backend

### ISSUE THREAD

**Issue by mushketyk** [FightPandemics/FightPandemics#196]
Pino logger seems to be popular now: https://github.com/pinojs/pino

**Comment by robinv85** [comment]
@mushketyk Fastify comes with the Pino logger built-in by default https://www.fastify.io/docs/latest/Logging/
If you look at the code you can see there are aleady some places where we are logging things (you can just use `req.log.info()` inside handlers etc.) So I guess this can be closed unless you want to add some more specific logging.

Some things that I feel are missing here though, is the catch-all error handler just returns a 500 Internal Server Error and includes the error message, so this might work for development but for production I think this is risky, we should avoid to send every details about internal errors to the client and log it instead while returning a more generic error message... I also think that we could add some guidelines in the documentation about this.

**Comment by mushketyk** [comment]
@robinv85 Good points!

> the catch-all error handler just returns a 500 Internal Server Error and includes the error message

I'll create an issue to create a catch-all handler. I think the logic should be pretty straightforward: if this is a 5xx error we should return a generic error message in a response. If this is a 4xx error we should return an error message from an exception.

> We should probably log to a file so we can improve debugging capabilities, especially in production and then we also need to rotate the logfiles, maybe upload to AWS S3 periodically or when it gets to a certain size

I am not familiar with Heroku, but is there a way to get output from a process' stdout and ship to log storage?

**Comment by robinv85** [comment]
@mushketyk I've created an issue to propose adding the fastify-sensible plugin https://github.com/FightPandemics/FightPandemics/issues/210 
This would solve the catch-all error handler problem with a better default, and also add some other useful thigns.

Also we are working on the move to AWS so Heroku will probably not be used anymore.

We could also look at better configuration for the logger if the defaults aren't good enough (also think about development vs production, maybe we can add settings for that).

**Comment by mushketyk** [comment]
> Also we are working on the move to AWS so Heroku will probably not be used anymore.

We can configure Elasticsearch on AWS for logs, if we have a budget for this.

> We could also look at better configuration for the logger if the defaults aren't good enough

I like to make log output human-readable in dev, but then use JSON for staging/production, so that it could be parsed by CloudWatch logs/Elasticsearch.

**Comment by mushketyk** [comment]
I'll close this PR, as a duplicate
