### ISSUE TITLE
[Android] - Messages - Refresh private conversation

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1960]
env: Prod
platform: Android, chrome browser

steps:
1. LogIn
2. Go to your inbox
3. Open particular conversation
4. **Scroll up** to see earlier conversation/post 

actual results: user sees empty inbox screen, no Load more info, then ends up in the inbox but not on the conversation

![UploadMore](https://user-images.githubusercontent.com/21987083/100476092-fa99eb00-30e4-11eb-9e73-56007559d95c.gif)

**Comment by ddveloper** [comment]
@galeza it seems you triggered a page refresh by dragging down too much?

**Comment by galeza** [comment]
@ddveloper I think you're right. It's very easy to trigger page refresh on Android. 
However can we improve page refresh for Messaging inbox?

**Comment by ddveloper** [comment]
@galeza @rabbi08 , please have a check with this review build https://feature1960-inbox-scroll-up.fightpandemics.xyz
