### ISSUE TITLE
Navbar menu items overlap between 768px and 854px window width

### ISSUE THREAD

**Issue by chrislemus** [FightPandemics/FightPandemics#1973]
![Screen Shot 2020-11-28 at 9 07 08 PM](https://user-images.githubusercontent.com/61127478/100530310-571d0900-31be-11eb-88d3-a48ddf11cc7e.png)

**Comment by chrislemus** [comment]
@CamilaArias would you like to just switch to the mobile menu when content starts to overlap?

**Comment by tseringn** [comment]
This issue is not in our repo. I am closing this.
