### ISSUE TITLE
Add "Housing" label to types of Help

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#1975]
Need to add an additional type of help to the current ones: **Housing**.

**Acceptance Criteria:**

- Housing tag appears on filters.
- Housing tag appears on Create Post modal.
- Housing label appears on post card when added.
- Applying Housing filter displays posts with the Housing label in the help board.

EDIT: Adding more missing tags: Childcare, Translations, Volunteers, Staff (paid), Remote Work

**Comment by Zaydme** [comment]
Do we need to add something like "Remote" or "Remote work" too? since what was said in the eng/prod meeting yesterday.
@CamilaArias @rabbi08
