### ISSUE TITLE
Clean up: Export default named React Components

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#198]
Currently a few of our React components are exported as anonymous functions. To follow  [convention and best practices](https://twitter.com/dan_abramov/status/1255229440860262400), we want to export default React components with names. 

Things to keep in mind:
- Please also update import statements in components that use other components in order to prevent rendering issues.
- This will likely cause merge conflicts for those who worked on a component. If possible, please reach out them and let them know about the changes.

```
// no good :(

export default ({ prop1, prop2  }) => {
   // react code...
}
```

```
// good :)

const ReactComponent = ({ prop1, prop2 }) => {
   // react code...
} ;

export default ReactComponent; 
```

**Comment by robinv85** [comment]
Does that last example even work? As far as I know it should be either `export default function ...` or `export default class ...` ? See https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by anniegiang** [comment]
@robinv85 Ah for the last example I forgot to add `const`, in which case would work.

**Comment by anniegiang** [comment]
@robinv85 Also since we're sticking with Hooks I think it's best we stick with arrow functions and/or function statements and not use classes for our React components

**Comment by robinv85** [comment]
@anniegiang actually I think the default exports don't work with const, I tried before so I'm pretty sure :) 
https://stackoverflow.com/questions/36261225/why-is-export-default-const-invalid there's probably a logical explanation for it... so just saying that when using `const` with arrow functions and default exports it's probably needed to do it in 2 steps.

**Comment by anniegiang** [comment]
@robinv85 Ah my mistake, I'll remove the third example. I misread `export const ` as `export default const` when I was googling.

I'm also surprised how the the official React docs don't really talk about how to import/ export properly... or maybe I haven't searched deep enough in their docs
