### ISSUE TITLE
Icons in the share post modal looks too close to each other

### ISSUE THREAD

**Issue by tseringn** [FightPandemics/FightPandemics#1984]
# The icons on the share post modal looks to close to each other
- My suggestions are that if the width of the Modal is the same as that of Create Post Modal, then it will look better
- My second thought is the text input where the URL is displayed is looks like a plain HTML input, it would look better if we make it on liner input and copy-link button next to it.

Thank you!

<img width="774" alt="Screen Shot 2020-11-29 at 8 52 09 PM" src="https://user-images.githubusercontent.com/62776949/100560771-e2f96880-3284-11eb-9e54-a1ff30464d2d.png">

**Comment by CamilaArias** [comment]
Eileen Tong will work on design for this.

**Comment by tonge495** [comment]
Hey this is Eileen!

I attached a mockup of the updates.  Let me know if that works for everyone.
![Share Post](https://user-images.githubusercontent.com/9394413/101795487-f783ff00-3ad5-11eb-91c1-c3cf1676c21b.png)

**Comment by aleksarad** [comment]
Looks great to me 😊
One question I have is about the icons -- the icons we are currently using in the modal are imported from react-share, the icons in the mockup above are different. I styled the original icons to the FP blue which can be seen in the screenshot below.
Should I leave these older icons, or should they be replaced with the newer ones provided by Eileen?
If I need the newer ones, could someone please point me to where I can get them? Thank you!

<img width="1410" alt="Screen Shot 2020-12-15 at 4 07 40 PM" src="https://user-images.githubusercontent.com/52298236/102273074-c6e60000-3eef-11eb-9e3b-95dbd24b1fd1.png">

**Comment by CamilaArias** [comment]
Hey @aleksarad ! You can get the icons from here https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=515%3A12
Select the column of icons on the right, and with the right sidebar on the bottom you can click export and select the format :)
![image](https://user-images.githubusercontent.com/25089562/102277767-83978b80-3f07-11eb-8eab-ddd7d7f06f5d.png)
