### ISSUE TITLE
[Mobile Android] Post Comments counter

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#1987]
env- staging
Steps:
1. Open Help Board
2. Navigate to the Post with Comments
3. Click on a post
4. Number of comments displayed on Help Board on my example is 14, when you click on this post - post is displayed - number of comments displayed is 0 and after a second it displays correct number. Why do we have this latency? I don't see the same behaviour for Like counter. 
Expected behaviour - Correct number is displayed without switching from 0 to correct number.

![Nov-30-2020 12-34-40](https://user-images.githubusercontent.com/21987083/100605636-7e7fed00-3308-11eb-8eb9-131cb8861986.gif)

**Comment by CamilaArias** [comment]
I think this is just the time it takes to make the call to fetch comments. It happens in other places as well. We could look at something that only renders the page when everything is ready. Other platforms render a simplified version of the elements without text until they fetch the info.

**Comment by Zaydme** [comment]
Yeah, it just takes a moment to fetch comments, since they are stored separately from the post. while likes come already within the post itself.

**Comment by galeza** [comment]
> Yeah, it just takes a moment to fetch comments, since they are stored separately from the post. while likes come already within the post itself.

@Zaydme 
I see that PostMetaContainer uses `numComments={commentsCount}` and loadPost uses: `const endPoint = `/api/posts/${postId}${getActorQuery()}`;`
When I use GET /api/posts/{postId} I see that numComments is outside of Post. Why? 
Beside there is a Slack conversation: https://fightpandemics.slack.com/archives/C010V0DDHLN/p1606880831029600
that highlights inconsistency in the implementation.
@kumudchauhan Please confirm.
```
################### Post object returned in view a user's post workflow ############
{
_id: "5fbc99086058f2001d86c46c",
language: [ ],
types: [],
objective: "request",
title: "Random post title id 1499",
visibility: "city",
expireAt: null,
author: {},
createdAt: "2020-11-24T05:24:24.791Z",
updatedAt: "2020-11-24T05:24:24.791Z",
**commentsCount**: 1,
content: "Main content of request post. Post id 1499",
liked: false,
likesCount: 0,
elapsedTimeText: {}
},
###### Post object returned in a single post id workflow ##################
{
**numComments**: 1,
post: {
language: [ ],
likes: [ ],
types: [],
_id: "5fbc99086058f2001d86c46c",
content: "Main content of request post. Post id 1499",
objective: "request",
title: "Random post title id 1499",
visibility: "city",
expireAt: null,
author: {},
createdAt: "2020-11-24T05:24:24.791Z",
updatedAt: "2020-11-24T05:24:24.791Z",
__v: 0,
liked: false,
likesCount: 0,
elapsedTimeText: {}
}
} 
```
Why comments count is not stored within the post itself? Apparently it causes some issue also for frontend. Please correct me if I'm wrong.

**Comment by Zaydme** [comment]
Yes, looks like we need to do it the first way, within the post itself. First to make it work on the Frontend, second to make it easier for native mobile apps developers and ourselves, and finally for consistency.
so it will always be `commentsCount` within the post object.

**Comment by kumudchauhan** [comment]
Yes, I can confirm that number of comments are returned differently when you call posts API (All posts vs single post)
We should refactor the code that comments count should be the part of the post object as in the first example.
