### ISSUE TITLE
Configure an ESLint rule for alphabetization

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#199]
- [ ] Alphabetize imports

```
before
import Dog from "./Dog"
import Apple from "./Apple"

after
import Apple from "./Apple"
import Dog from "./Dog"

```

- [ ] Alphabetize object properties

```
before
const foo = {
   dog: "dog",
   apple: "apple"
}

after
const foo = {
   apple: "apple",
   dog: "dog"
}

```

**Comment by TenNga** [comment]
I'm a little confused as I'm not familiar with ESLint, does Alphabetize import and exports mean arrange import Alphabetically? 
Like changing the following:
2.  import Home from './Component/Home.js';
3.  import Call from './Component/Something.js';
to this:
2. import Call from './Component/Something.js';
3. import Home from './Component/Home.js';

**Comment by anniegiang** [comment]
@TenNga Just updated the issue with examples.

**Comment by joshmorel** [comment]
This seems to be resolved
