### ISSUE TITLE
While Scrolling up the messages, unable to view the entire post 

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#1991]
device :Iphone XR - chrome.

While Scrolling up the messages, unable to view the entire post  as below:

![postnotseen](https://user-images.githubusercontent.com/65972693/100644156-ccd4c200-32ef-11eb-94c1-47a1e257962e.jpg)

**Comment by ddveloper** [comment]
@sheeba1 this is related to #1960 and the PR #1992 should fix this, check https://feature1960-inbox-scroll-up.fightpandemics.xyz/ see if that works
