### ISSUE TITLE
Post Page -> Spacing is needed below 'Show more/Less Comments' button.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#1993]
1. Open FP web app and login as valid user
2. Open post having more than 5 comments to see 'Show more Comments' button.

Issue: You will observe that the button is displayed on the border of the post card. we should have spacing below button i.e. the button should move up or add more space to the post card.

Refer below screenshot.
<img width="755" alt="Screen Shot 2020-11-30 at 12 16 16 PM" src="https://user-images.githubusercontent.com/67168400/100647814-0a484800-330e-11eb-9135-00129b179c46.png">

**Comment by aditilamkhede** [comment]
@rabbi08 is this for any specific device? I tried on mac book and it seems to be fine. 
<img width="640" alt="Screen Shot 2020-11-30 at 11 21 43 AM" src="https://user-images.githubusercontent.com/22331887/100654225-5ab7a980-32fe-11eb-93e8-2243d2b3c7a0.png">

**Comment by rabbi08** [comment]
> @rabbi08 is this for any specific device? I tried on mac book and it seems to be fine.
> <img alt="Screen Shot 2020-11-30 at 11 21 43 AM" width="640" src="https://user-images.githubusercontent.com/22331887/100654225-5ab7a980-32fe-11eb-93e8-2243d2b3c7a0.png">

@aditilamkhede 
This issue exist on MacBook. Screen resolution: 13.3-inch (2560 × 1600)

**Comment by CamilaArias** [comment]
UI-wise this should be the same link button style as the "view more" in the post card.

**Comment by rabbi08** [comment]
@aditilamkhede @Zaydme 
This issue DOES NOT exist in PROD as of now. Please see below screenshot.
so we are introducing this issue, great if we have can quick fix around this.

<img width="1440" alt="Screen Shot 2020-11-30 at 11 57 13 PM" src="https://user-images.githubusercontent.com/67168400/100699050-f6313480-3367-11eb-9f0a-73389971128e.png">

**Comment by aditilamkhede** [comment]
@rabbi08 I see this issue now in staging. I wasn't able to see it earlier.

**Comment by aditilamkhede** [comment]
@Zaydme there was, padding-bottom: 0.2rem in .am-card class which is causing this issue, if there was no other use of this , which I don't see, as it just overrides the padding specified in the line above it. I will test more to see if there are any implications of removing this padding, then will push the code.

**Comment by rabbi08** [comment]
Closing this issue, as it is expected to be fixed with 'post-moderation' feature merge. Thanks
