### ISSUE TITLE
[Mobile]After edit accout details -->click on view my profile leads to failed loading page.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#2001]
Environment- staging
Device used  -Samsung Galaxy s8
Browser-Google chrome 
1.Sign in with valid user name, password. 
2.Go to profile.
3.Click on the pencil icon on right corner.
4.choose "Edit account" from the menu.
5.change name.
6.click on save changes.
7.click on view my profile from the side menu.
Result:
Failed loading.
If we go to help board and comes back to profile again still it shows failed loading page only.
![GIF-201130_175443](https://user-images.githubusercontent.com/41587211/100676160-54ddba80-3336-11eb-85b0-b7eb24a48f49.gif)

**Comment by rabbi08** [comment]
Please re-test in incognito mode, this might be build issue. Thanks

**Comment by nivetheatha** [comment]
@rabbi08 Retested and It still works the same in incognito mode.

**Comment by rabbi08** [comment]
@Zaydme 
This issue exist on mobile. Please see below GIF from iPhone.
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/67168400/100677872-f3b7e600-3339-11eb-9c63-8aed8bbf111b.gif)

**Comment by Zaydme** [comment]
@rabbi08 when the page show the error, can you please copy the current URL and post it here.

**Comment by rabbi08** [comment]
https://staging.fightpandemics.work/organisation/5f0d31f44f9daa1600e8bfdf

**Comment by aditilamkhede** [comment]
@Zaydme I looked at this issue and found the issue, so when we have hamburger menu irrespective of device, try to change profile and this issue occurs. 

Reason behind it is url ->" /organisation/5fbe143fc9c17e1100f72852" 
when clicking first time on view profile it redirects using correct url which is "/profile/5fbe143fc9c17e1100f72852"
But after you edit profile, it changes url to " /organisation/5fbe143fc9c17e1100f72852" . which it is unable to find and results in 404

so somehow in hamburger menu after first click it changes url to "organisation" from "profile".

**Comment by Zaydme** [comment]
Thanks @aditilamkhede 
Yeah we have been able to identify the issue.
It was just something that looks for `user.type` and if it was null it assumes it is an Individual, but after a recent PR, when you edit your account the user gets updated and gets the type of "Individual".
So it was a simple fix.
