### ISSUE TITLE
Post detail page- I am unable to edit from post details page. Cannot click on ellipsis

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#2002]
I am unable to edit from post details page. Cannot click on ellipsis

![image](https://user-images.githubusercontent.com/65972693/100681230-16d99a00-3328-11eb-98a0-adaa0660ada0.png)

**Comment by rabbi08** [comment]
@ddveloper @Zaydme 
This issue exist on Post detail page, user cannot click on 'ellipse'
