### ISSUE TITLE
When creating a post , then right after creating more than 5 comments, the show more comments or show less comments doen't work

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2005]
please see the below flow

1-Login as user
2-Navigate to Feed page
3-create a post
4-then on the post page, create 6 comments right away
5-click on show more comments or show less comments, the same last 5 comments on the display
6-user needs to click on page refresh icon in order to see the show less comments and show more comments are working
this is only for new post with new comments , for the existing post with already comments (adding or existing more than 5 comments  are working fine)
please see the screenshot
![showMoreShowLessComment](https://user-images.githubusercontent.com/70918430/100692590-07fee180-3340-11eb-87d3-f47115e84bf5.gif)

**Comment by rabbi08** [comment]
@adorapham 
so user is not able to view all the comments for their post?

**Comment by rabbi08** [comment]
The issue exist for newly added comments >5 condition, but if already there are post with more than 5 comments, this button works. Thanks

In case, if user re-visit the post the button works fine, its not working while adding and viewing. Please see below GIF.
![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/67168400/100695428-2e804500-335f-11eb-8358-6df2332286a7.gif)

**Comment by nivetheatha** [comment]
This issue exists in android mobile too.
#1719
