### ISSUE TITLE
Avatar -> blank pop up is displayed if user select 'jpg' file without preview

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2006]
1. Open FP web app and login using valid email/password
2. navigate to user profile and click on camera icon to upload a avatar
3. select some random image with no preview

Issue: You will observe that the pop up to select the picture is BLANK.
Refer below screenshot and GIF.

![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/67168400/100696593-e1ea3900-3361-11eb-92c5-d61fea1c93de.gif)
<img width="1440" alt="Screen Shot 2020-11-30 at 11 00 07 PM" src="https://user-images.githubusercontent.com/67168400/100696610-e9a9dd80-3361-11eb-8b41-477d985827be.png">

Please note this issue exist in PROD too. Thanks.

**Comment by poulomipal1319** [comment]
Hi @rabbi08,
Can you please confirm if the issue exists? I tried replicating the issue in my local as well as in prod. But was not able to replicate. I followed the below steps:
1. Clicked on  camera icon in Avatar.
2.Edit Avatar popup opened up.
3.Clicked on UploadNew and browsed a jpg image.
4.Was able to preview the image as well as submit it.
Could you please let me know if I am following the correct steps?

**Comment by linadinh2602** [comment]
I have been able to reproduce this problem locally. I believe the issue only happens on a larger image. I will add the fix soon
