### ISSUE TITLE
Post -> Unable to create or Edit post with a visibility of a 'week' 

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2008]
1. Open FP page and login using valid email/pwd
2. Click on  'Create post' to create new post -> enter all details and select time visibility = 'week' -> 'POST'
3. Click own 'edit' to view the post

Issue: You will observe that the post is created with Day visibility not week. Also when user try to edit with week, it change it to 'Day' hence unable to create/edit the post with 'Week' visibility.

Refer below GIF.
![ezgif com-video-to-gif-6](https://user-images.githubusercontent.com/67168400/100697863-1e6b6400-3365-11eb-8faa-9b7217a11f4d.gif)

This issue does not exist in PROD, though it is displayed incorrect like '7,week'- known, but user is able to create and edit post with week visibility.

**Comment by ddveloper** [comment]
@rabbi08 please check this review build on different setup before merge
https://feature2008-cannot-create-weeklypost.fightpandemics.xyz/
