### ISSUE TITLE
There is a mismatch in number of comments in actual post to the shared post.

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#2017]
Environment-staging 
Device used-Samsung Galaxy s8
Browser-Google chrome 
1.login with valid user name and password 
2.share your post to watsapp / email.
3.log out from the account.
4.click on the link from the watsapp/email.
Result:
There is a mismatch in number of comments from the actual post to the shared post. 
Always shared post comments shows as 0 irrespective of any number of comments the post has.
![20201201_113100](https://user-images.githubusercontent.com/41587211/100769007-818ee200-33c9-11eb-887d-42fa7474d9cf.jpg)

**Comment by Zaydme** [comment]
duplicate(?) of #1987

**Comment by nivetheatha** [comment]
@Zaydme #1987 is a loading issue. 
#2017 is a issue with showing number of comments from the shared link .

**Comment by Zaydme** [comment]
@nivetheatha both fixed in #2041 :+1:
