### ISSUE TITLE
[Desktop] Language dropdown opens off screen from bottom of page

### ISSUE THREAD

**Issue by CamilaArias** [FightPandemics/FightPandemics#2023]
From the bottom or close to bottom of the **about us** page, the language dropdown opens above the navbar, I assume because it's longer than what's between its anchor and the bottom of the page so it breaks. See the shadow of the dropdown in the screenshot below.
![image](https://user-images.githubusercontent.com/25089562/100840830-34585200-3455-11eb-924d-2719f2ae636d.png)

Making it scrollable if it's longer than the space below might fix it. Really needed as it'll be worse the more languages we add.

Note: on the home page opening the dropdown extends the height of the screen, which will still look bad as more languages are added.

**Comment by galeza** [comment]
@CamilaArias 
Is this somehow related to Navigation bar language submenu position #1953 ?
Could we fix those two issues in one PR?

**Comment by CamilaArias** [comment]
@galeza yeah we could have both solved in one :)

**Comment by ddveloper** [comment]
this is same as #2099 , which is fixed, so close this (@Juan-Moctezuma , let me know if you see the issue got fixed in the [staging build](https://staging.fightpandemics.work/about-us), please reopen this if the issue still exist 👍 )

**Comment by Juan-Moctezuma** [comment]
@ddveloper I went to the staging build (https://staging.fightpandemics.work/about-us) and so far so good!, the scroll bar bug doesn't seem to be there anymore
