### ISSUE TITLE
Clicking on FAQ in Kannada language display the blank page 

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2073]
both prod and stag
![image](https://user-images.githubusercontent.com/70918430/101866553-ed8dea80-3b2d-11eb-81be-437782f2dc15.png)

**Comment by adorapham** [comment]
@Zaydme - @Jameel139 , I log defect for the blank page FAQ as discussion on translation channel.

**Comment by adorapham** [comment]
@Juan-Moctezuma, I assign the defect to you per request.

**Comment by aditilamkhede** [comment]
@adorapham and @Juan-Moctezuma I found the issue and fix for this. Let me know if I can do this or can send you the details. It's really a small fix. Problem with json.
