### ISSUE TITLE
limit the "limit" query parameter

### ISSUE THREAD

**Issue by Zaydme** [FightPandemics/FightPandemics#2082]
limit the "limit" query parameter to a fixed number in all the requests using it, and add it as a global variable in the config file
![carbon](https://user-images.githubusercontent.com/46847212/101993142-9e27f580-3cb8-11eb-80f2-571eaab5860f.png)
because now someone can just access something like `http://localhost:3000/api/users?&limit=100000` and get all records

**Comment by ddveloper** [comment]
Sorry I forgot to create a PR, the changes were committed to the staging directly, here are they:
https://github.com/FightPandemics/FightPandemics/commit/86e30e34607381e69b8771186d2317af8c98c0a7
https://github.com/FightPandemics/FightPandemics/commit/c9d085cbaf8c7a5fe494512b1a4cd42cdac71168
https://github.com/FightPandemics/FightPandemics/commit/4576dd7b759f4dad88a66ea22066dde43f4d43d0
