### ISSUE TITLE
The user's existing avatar on their profile is not displayed after accounts get linked.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2096]
1. Login/signup using social media channel.
2. upload avatar for your profile and create a post.
The post will be added with selected profile avatar, as expected.

3. Then try to create to direct email/password on FP with same email address.
4. Login through direct email/address.

You will observe that accounts get linked as user try with same email address. as expected.

Issue: You will observe that, there is avatar on the profile, but there is avatar on the post created before with other login mode.
Please see below Screenshot.

<img width="1440" alt="Screen Shot 2020-12-16 at 12 37 29 PM" src="https://user-images.githubusercontent.com/67168400/102386131-b3dd3980-3f9c-11eb-847f-3a09b278b262.png">

Note: This issue exist after PR #1727

**Comment by ddveloper** [comment]
rabbi08 and I cannot reproduce currently, close for now, will see if we see it again later
