### ISSUE TITLE
Localisation: Language select menu scroll needs implementing

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#2099]
As reported by @rabbi08:

> As the language list is getting long in the dropdown, it scrolls the whole page, can we add scroll in the language menu dropdown, to scroll languages rather than page scrolling as in below GIF.
> ![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/67168400/102252772-7f9e4600-3ed4-11eb-80d5-55ae050c6e69.gif)

**Comment by aditilamkhede** [comment]
@rabbi08 and @doheekim93 how does this looks? any more suggestions?

https://user-images.githubusercontent.com/22331887/102676073-b2547280-4150-11eb-9827-2c59f9de52e8.mov

**Comment by rabbi08** [comment]
yes @aditilamkhede This looks good to me. Thanks

**Comment by doheekim93** [comment]
@aditilamkhede that looks good!!!

**Comment by aditilamkhede** [comment]
@rabbi08 and @doheekim93 I will finish up this today and let you know.

**Comment by aditilamkhede** [comment]
@rabbi08 @doheekim93 I am working on this. Mostly will check in before Monday. My laptop is little slow, so will let you know when done. Just wanted to keep everybody informed.
