### ISSUE TITLE
Detect disposable email domains during sign ups

### ISSUE THREAD

**Issue by dhruvdpatel** [FightPandemics/FightPandemics#2111]
**Goal**

Add an ability to recognize the disposable email domains when the user signs up on the FP Platform. 

Reference Github: https://github.com/ivolo/disposable-email-domains

**Comment by OzkanAbdullahoglu** [comment]
I looked at the docs of the referenced library, can be implemented but anyone has a better idea & alternative about this case? 
@mannykary @joshmorel @idjevm @Zaydme @ddveloper @manualzuru

**Comment by mannykary** [comment]
> I looked at the docs of the referenced library, can be implemented but anyone has a better idea & alternative about this case?
> @mannykary @joshmorel @idjevm @Zaydme @ddveloper @manualzuru

I think that library should work.
