### ISSUE TITLE
Posts should NOT be allowed to be  edited to 'Requesting Help' ,if its originally created for 'Offering Help'

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#2127]
Posts should NOT be allowed to be edited to 'Requesting Help' ,if its originally created for 'Offering Help' and Vice Versa.
. 
Steps: 1.Create a post using 'Create a New Post' from Help Board.

2. Choose 'Offering Help'. ENter details and Save
3. Now choose Edit and change to "Requesting Help" tab      and save

Expected:Posts should NOT be allowed to be edited to 'Requesting Help' ,if its originally created for 'Offering Help' and Vice Versa.
.

**Comment by kamarenmccord** [comment]
I don't have a way to verify the fix right now but it looks like if you remove this else claus on <strong>line 63</strong> in the client/src/componets/createpost/EditForm.js it will prevent the value from being overwritten. Then you would just have to find a way to remove the buttons from that header.

<code>
  const handleFormData = (field) => (e) => {
    if (e.target) {
      setFormData({ ...formData, [field]: e.target.value });
    } else { >>>>{* this else claus *} <<<<<
      const helpmap = { 1: "offer", 2: "request" };
      setFormData({ ...formData, [field]: helpmap[e] });
    }
</code>
