### ISSUE TITLE
Search: HelpBoard page turn blank after user search any text.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2131]
1. Login into STG and navigate to HelpBoard
2. search for text say 'New'

Issue: You will observe that the page turn blank after user user perform any search. 
refer below GIF. Thanks

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/67168400/104412103-a5515600-5539-11eb-9b9c-f67543a9d8c5.gif)

**Comment by ddveloper** [comment]
because the post title and body including hyperlink now (from #1515 ), the highlight function (based on text content) throw an error by calling `text.split()` in Post.js line 81
