### ISSUE TITLE
Filter: Search results, based on location(country), are not sorted as per time.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2141]
1. Login into STG/PROD "fightpandemics.com"
2. Navigate to Helpboard and apply location filter = 'United States' 

Issue: You will observe that 6 months old posts are displayed on the top for the selected location.
But when you keep scrolling, you will see recent post for the searched location.
So search results are as per location but they are not sorted as per time when they are posted. 

Expected Result: When user apply location filter -> the latest posts for the selected location should be displayed as per the age i.e. latest on top and so on.

See below screenshots/GIFs
<img width="1440" alt="Screen Shot 2021-01-13 at 7 47 18 PM" src="https://user-images.githubusercontent.com/67168400/104532489-57daf480-55de-11eb-900b-bbcc36cbf5d0.png">

<img width="1440" alt="Screen Shot 2021-01-13 at 7 52 06 PM" src="https://user-images.githubusercontent.com/67168400/104532492-58738b00-55de-11eb-9831-46d77e9ac8ce.png">

![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/67168400/104533022-8ad1b800-55df-11eb-8dda-e45ad6ba1c99.gif)

Please note, This issue is related to #2053 

**Some Exceptions need to be verified while fixing this issue:**
1. When we search on the base of country, this issue always exist, but when user expand the search location i.e. city/state/country, results are better. Please see this in GIF.

If I search 'United States' 'United Kingdom' 'Spain' 'Barcelona, Spain' the results are NOT accurate.

**Note: So, the locations are not matched properly when broader location is searched for.**

**Comment by ddveloper** [comment]
PR #2155 completed web view modification, mobile view is to be updated

**Comment by ddveloper** [comment]
the PR is ready to review, please see if anything to improve @rabbi08 @CamilaArias

**Comment by ddveloper** [comment]
will be covered by issue #2171 , close this one
