### ISSUE TITLE
After 5 reports on the user the view is blocked on 'Moderator dashboard' also.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#2159]
1. Open 'https://staging.fightpandemics.work'
2. Login as moderator, and navigate to moderator dashboard. 
3. On 'pending' TAB, click to view the post which is having 5 or more reports.

Issue: You will observe that, the view is blocked as more user's report this. But the view should be blocked for all users, working as expected, but in the moderator dashboard for the moderator, the view should not be blocked. As the moderator need to look into the post to take the further action(keep/remove) on the respective post.

Please see below screen recording.

https://user-images.githubusercontent.com/67168400/105077185-22109280-5a5a-11eb-9aca-43ab091b81dd.mov

**Comment by sankethbe** [comment]
@OzkanAbdullahoglu Can you please take a look?
