### ISSUE TITLE
Veriff Badge not working in staging

### ISSUE THREAD

**Issue by ddveloper** [FightPandemics/FightPandemics#2176]
When enabled in staging environment, the Veriff Badge is not functioning due to disconnected communication of the [Veriff webhook](https://developers.veriff.com/#webhooks-decision-post) and our [backend decision endpoint](https://github.com/FightPandemics/FightPandemics/blob/cd9b531b7c7ffc1c0c9a6f709836c0d3eb5b3098/backend/lib/endpoints/users.js#L710) , Veriff Console is showing 403 error when sending result to our staging backend
![image](https://user-images.githubusercontent.com/44758313/105810162-4ccd8000-5f5f-11eb-9a5d-b402d539ab59.png)

while testing in review build (and set the callback in Veriff to be review PR build link), it works, as shown below
![image](https://user-images.githubusercontent.com/44758313/105810345-9cac4700-5f5f-11eb-9ca2-588425f9bddb.png)

more details can be found at [slack channel](https://fightpandemics.slack.com/archives/C0113DAESF3/p1611566275005200), 
next steps: 1) talk to Veriff to get more details about the 403 responds, 2) check configuration differences in staging vs review, before finding the root cause, the Veriff Badge feature will be temporarily disabled

**Comment by ddveloper** [comment]
#2177 disabled the feature for now

**Comment by Zaydme** [comment]
@ddveloper
The test integration api and secret keys are only used in the review env, while staging and PROD are using the live integration keys. this might be related to this issue.

**Comment by ddveloper** [comment]
Thanks @Zaydme ,  the live key was set properly in AWS, I added debug log inside the preValidation function, not hit in staging after verification, got hit if sent using curl

**Comment by ddveloper** [comment]
it worked in both review build and production build, and released into production base, I will dig more for staging build and update here if find any thing new.
