### ISSUE TITLE
Organization profile - Backend

### ISSUE THREAD

**Issue by robinv85** [FightPandemics/FightPandemics#22]
- [x]  backend / API support to get organistion info

**Comment by PriyalPatney** [comment]
I’d like to write this API.

**Comment by pavanmt** [comment]
Will start working on API dev.

**Comment by MohamedEl1** [comment]
Sure

**Comment by pavanmt** [comment]
PR:
https://github.com/manualzuru/FightPandemics.com/pull/68

**Comment by mannykary** [comment]
@pavanmt Hope you don't mind me picking up this issue. I was asked by @robinv85 to work on implementing this in Node.js/Fastify, rather than Python/Flask as you had done. If you would like to work with me on this, let me know.
