### ISSUE TITLE
Add "confirm password" field to `/api/signup` 

### ISSUE THREAD

**Issue by robinv85** [FightPandemics/FightPandemics#220]
The `/api/signup` route should have an additional required field in the request body with the `confirmPassword` value to make sure that the user has entered their password exactly the same, twice, before creating a user in the Auth0 database.

**Comment by mushketyk** [comment]
I will look into it.

**Comment by mushketyk** [comment]
@robinv85 Sorry, I don't understand how this should work. Should this be a flag that frontend sets if a user entered a password twice exactly the same? If this is the case, a frontend can simply make a check and do not send a request if passwords a different.

**Comment by robinv85** [comment]
@mushketyk yeah the validation can happen client-side too, but adding it on the back-end makes it  certain that it works regardless of different clients making a request... i've seen this before, you might think it's overkill, to me it seems good to be more clear about splitting up /signup and /login as well.

**Comment by mushketyk** [comment]
@robinv85 Ok, I think there is a benefit in having this. Should be easy to implement
