### ISSUE TITLE
Resolve console warning in NrMap.js

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#221]
```
./src/pages/NrMap.js
  Line 90:32:   Expected to return a value in arrow function  array-callback-return
  Line 105:22:  Expected '===' and instead saw '=='           eqeqeq
  Line 123:28:  Expected to return a value in arrow function  array-callback-return
```

- [ ] Line 90:32:   Expected to return a value in arrow function  array-callback-return

- [x] Line 105:22:  Expected '===' and instead saw '=='           eqeqeq

- [ ] Line 123:28:  Expected to return a value in arrow function  array-callback-return

**Comment by nadinejuraschek** [comment]
@anniegiang This issue can be closed right?

**Comment by anniegiang** [comment]
> @anniegiang This issue can be closed right?

Not sure, I haven't been following that close to the project progress lately. The last time I checked the two checkboxes that aren't checked weren't fixed yet I think

**Comment by nadinejuraschek** [comment]
> > @anniegiang This issue can be closed right?
> 
> Not sure, I haven't been following that close to the project progress lately. The last time I checked the two checkboxes that aren't checked weren't fixed yet I think

NrMap was refactored since it was our last class component, so there are still warnings for NrMap, but different ones. I opened an issue for the new ones a few days ago: #449 

I'm closing this issue
