### ISSUE TITLE
Fix Ajv configuration without eslint warning

### ISSUE THREAD

**Issue by robinv85** [FightPandemics/FightPandemics#223]
ESLint marked the line `require("ajv")` because of the `no-extraneous-dependencies` rule
I've added an ignore rule for now to be able to commit changes, but this should be fixed.
Fastify includes Ajv by default and this was imported to adjust the configuration, 

This example was taken from possibly outdated documentation
https://www.fastify.io/docs/v2.10.x/Validation-and-Serialization/

There should now be a better way to just pass a configuration object, might require to upgrade fastify
https://www.fastify.io/docs/latest/Validation-and-Serialization/

**Comment by joshmorel** [comment]
This I think has been resolved maybe with #224 ?
