### ISSUE TITLE
No module google-map-react

### ISSUE THREAD

**Issue by AckslD** [FightPandemics/FightPandemics#2257]
When running `docker-compose up --build` and going to http://localhost:3000/  I get:
```
Failed to compile
./src/components/NearestHospital/FacilityMap.js
Module not found: Can't resolve 'google-map-react' in '/app/src/components/NearestHospital'
This error occurred during the build time and cannot be dismissed.
```

**Comment by aditilamkhede** [comment]
@AckslD this is not an issue. You have to rebuild images if you are on docker, on local you will have to install this module. ping me or on engineering channel on slack if you still need more help.
