### ISSUE TITLE
User Story 1.1 - Activity / Member tab background color

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2313]
<img width="946" alt="Screen Shot 2021-04-12 at 11 34 40 AM" src="https://user-images.githubusercontent.com/50638563/114454507-afbad480-9ba8-11eb-9c42-e0108fa78f47.png">

**Comment by adorapham** [comment]
**Activity**
font-size: 16px, current 14 px
line-height: normal , current 24 px
Activity is having the color #939393 when not in focus
#282828 when it is in focus.
**Members**
font-size: 16px, current 14 px
line-height: normal , current 24 px
Members  is to having the color #939393 when not in focus
#282828 when it is in focus.

https://user-images.githubusercontent.com/70918430/114655940-1374f880-9ca2-11eb-9b1b-d9d2cf04e7ed.mp4

**Comment by adorapham** [comment]
@xJamesScott  font weight/font-color are correct in both focus and not in focus for member and activity.
only font-size and line-height are incorrect.

**Activity**
font-size: 16px, current 14 px
line-height: normal , current 24 px
**Members**
font-size: 16px, current 14 px
line-height: normal , current 24 px


https://user-images.githubusercontent.com/70918430/116640095-e0c43480-a91e-11eb-8fc5-f259d1189819.mp4

**Comment by adorapham** [comment]
it looks fine now, use the recording from other defect 

https://user-images.githubusercontent.com/70918430/119876337-a1b4df00-bedc-11eb-8b97-e31635f09e0d.mp4
