### ISSUE TITLE
User Story 1.1 - Issue 2: The Org Name font size inconsistent

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2314]

**Comment by adorapham** [comment]
[Issue 2](https://www.notion.so/fightpandemics/Issue-2-The-Org-Name-font-size-inconsistent-Will-check-on-Issue-8-Duplicated-3c986f1e9aa1499984880eafafcff58b): see all the fonts are consistent across the pages but still not correct and will keep track under [issue 8](https://www.notion.so/fightpandemics/Issue-2-The-Org-Name-font-size-inconsistent-Will-check-on-Issue-8-Duplicated-3c986f1e9aa1499984880eafafcff58b)
