### ISSUE TITLE
User Story 1.1 - Issue 3: The “Apply” CTA button size

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2315]

**Comment by adorapham** [comment]
see update on [issue 3](https://www.notion.so/fightpandemics/Issue-3-The-Apply-CTA-button-size-204308dbe92749d6939e584cc411a926)

**Comment by adorapham** [comment]
@xJamesScott still see the issue not fixing, so i move it back.  Please let me know if you have any question.

**Comment by adorapham** [comment]
look ok , basing on discussion  we can close this defect
![image](https://user-images.githubusercontent.com/70918430/119746395-41269300-be45-11eb-8db7-8a00f27cb15d.png)
