### ISSUE TITLE
User Story 1.1 - Issue 5: The Org Initials in the circle is bigger than design

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2317]

**Comment by adorapham** [comment]
Still see some issues for eclipse and OP- [Issue 5](https://www.notion.so/fightpandemics/Issue-5-The-Org-Initials-in-the-circle-is-bigger-than-design-3cf19b81c9c34b82a80c382de9de7092)

**Comment by adorapham** [comment]
I see the built is matching with staging now . so I close this defect after confirming with Iris
Thank you @Adora Pham The initials are whatever is in prod right now - so if it's matching, closing the defect is the correct action :wink:

https://user-images.githubusercontent.com/70918430/116340816-a75fbd80-a794-11eb-8d97-5169e902393f.mp4
