### ISSUE TITLE
User Story 1.1 - Issue 6: Circle size for profile image is incorrect in specific browser size- will be resolved on Issue 5

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2318]

**Comment by adorapham** [comment]
[Issue 6 ](https://www.notion.so/fightpandemics/Issue-6-Circle-size-for-profile-image-is-incorrect-in-specific-browser-size-dba3c0a0ef664c05b9ed732181d5ee5c) can be resolved on[ issue 5](https://www.notion.so/fightpandemics/Issue-5-The-Org-Initials-in-the-circle-is-bigger-than-design-3cf19b81c9c34b82a80c382de9de7092)- close this one
