### ISSUE TITLE
Add Swagger documentation for the API

### ISSUE THREAD

**Issue by mushketyk** [FightPandemics/FightPandemics#232]
Add auto-generated Swagger documentation using [fastify-swagger](https://github.com/fastify/fastify-swagger).

**Comment by robinv85** [comment]
Hey @mushketyk we already have API documentation using [`fastify-oas`](https://www.npmjs.com/package/fastify-oas) which is based on fastif`y-swagger` but compaitble with Open API 3+ 
As mentioned in the readme, you can access this at http://localhost:8000/documentation

**Comment by mushketyk** [comment]
@robinv85 Sorry, my bad.
