### ISSUE TITLE
User Story 1.1 - Issue 8-The 'Location' text color is inconsistent in Org page and Org Post and organization and location properties different from design

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2320]

**Comment by adorapham** [comment]
Close after clarification  [issue 8](https://www.notion.so/fightpandemics/Issue-8-The-Location-text-color-is-inconsistent-in-Org-page-and-Org-Post-c957164a407d4d04b207eda402332a13)

**Comment by adorapham** [comment]
Close after clarification issue 8

**Comment by ruchimahajan78** [comment]
This issue has been resolved.
