### ISSUE TITLE
User Story 1.1 - Issue 9: Join Us should be displayed instead of Join {orgName}- Resolved but the attributes are not correct

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2321]

**Comment by adorapham** [comment]
see [issue 9](https://www.notion.so/fightpandemics/Issue-9-Join-Us-should-be-displayed-instead-of-Join-orgName-Resolved-but-the-attribute-is-not-co-67f72be043b847d896a1b4673716839d). see the Join Us in display but the attributes are incorrect

**Comment by xJamesScott** [comment]
If there are still issues, please add detail about attributes

**Comment by adorapham** [comment]
@xJamesScott , the information is on the notion , i copy and make it right here 

![image](https://user-images.githubusercontent.com/70918430/116177704-27205600-a6c9-11eb-923d-07e4c6a5e9f0.png)

**Comment by adorapham** [comment]
@xJamesScott ,  still see it not fixed except the height, per Zeplin
 font-family: Poppins;
  font-size: 16px;
  font-weight: 500;
are you able to include the border radius 46 px as rectangle property? 

https://user-images.githubusercontent.com/70918430/116454661-167cf680-a815-11eb-8329-ea37e945ecf2.mp4

**Comment by adorapham** [comment]
We agree to close it as long as it look fine
![image](https://user-images.githubusercontent.com/70918430/119746548-8f3b9680-be45-11eb-87cd-bf3a5bf75db9.png)
