### ISSUE TITLE
User Story 1.1 - Issue 10: User story 1.1:Join Us CTA button size in Org Page as duplicated for issue 9

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2322]

**Comment by adorapham** [comment]
I consider as duplicated for i[ssue 9](https://www.notion.so/fightpandemics/Issue-9-Join-Us-should-be-displayed-instead-of-Join-orgName-Resolved-but-the-attribute-is-not-co-67f72be043b847d896a1b4673716839d) which cover more issues , so close this one  related to [issue 10](https://www.notion.so/fightpandemics/Issue-10-User-story-1-1-Join-Us-CTA-button-size-in-Org-Page-Closed-as-duplicated-of-issue-9-b8a8db3f9ceb42f9a2dfa04173f0c7a7)
