### ISSUE TITLE
User Story 1.1 - Issue 11: User Story 1.1: Font Style difference in the text description of Volunteer Position.(Org Page)

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2323]

**Comment by adorapham** [comment]
Update more details on [issue 11](https://www.notion.so/fightpandemics/Issue-11-User-Story-1-1-Font-Style-difference-in-the-text-description-of-Volunteer-Position-Org-P-7582abe31c114179b1924ea17cdc10dd)

**Comment by adorapham** [comment]
see all issues are fixed except the width but it matches with the page. confirmation from Ruchi it is fine to close it and test with other browsers working fine.
![image](https://user-images.githubusercontent.com/70918430/116441236-204b2d80-a806-11eb-9321-0e46f403af99.png)


https://user-images.githubusercontent.com/70918430/116440265-28569d80-a805-11eb-90f3-fd1cbdc9b5b1.mp4

**Comment by adorapham** [comment]
confirmation from Ruchi it is fine to close it and test with other browsers working fine.
image
