### ISSUE TITLE
User Story 1.1 - Issue 1: Volunteer Position font issue

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2325]

**Comment by adorapham** [comment]
see font-family and font-size incorrect - see [issue 1](https://www.notion.so/fightpandemics/Issue-1-Volunteer-Position-font-issue-06e0244fe4984eb7a22aa3e5f37a5586)

**Comment by Selbinyyaz** [comment]
Hey @xJamesScott, I retested


 this on desktop (chrome and safari), still have the same issue. the font family is incorrect. you can see the video. it is not matching in Zeplin.


https://user-images.githubusercontent.com/62081140/117215245-97af2d00-adc3-11eb-8f6d-e1d2d9919bad.mp4

**Comment by adorapham** [comment]
it looks fine 
![image](https://user-images.githubusercontent.com/70918430/119875818-0e7ba980-bedc-11eb-8a22-515eaa255505.png)
