### ISSUE TITLE
User Story 2.1 - Issue 2: The Font Size "Application" in Pre-screening form too big

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2326]

**Comment by emanuelquerty** [comment]
Hi @xJamesScott! Can you provide a picture and the desired font size in the description?

**Comment by xJamesScott** [comment]
> Hi @xJamesScott! Can you provide a picture and the desired font size in the description?

Hi Emanuel! I created this ticket on behalf of a QA member, but I'm actually the engineer thats working on it.

**Comment by emanuelquerty** [comment]
@xJamesScott Thanks for letting me know

**Comment by emanuelquerty** [comment]
> > Hi @xJamesScott! Can you provide a picture and the desired font size in the description?
> 
> Hi Emanuel! I created this ticket on behalf of a QA member, but I'm actually the engineer thats working on it.

**Comment by adorapham** [comment]
@xJamesScott 
font-family should be Poppins-only 
line-height should be 20 px now it is 50.28 px- it seems the line-height is basing on the border out-side of the rectangle.  please let me know if it is fixable.

https://user-images.githubusercontent.com/70918430/116645039-c93e7900-a929-11eb-8aae-c606483857e8.mp4

**Comment by hiran11** [comment]
@xJamesScott  
2) If the input for the text field in the pre screening form can be defined in the sense. What are the input specifications

Does it allow all characters , symbols, numeric, Special characters ?

**Comment by adorapham** [comment]
it looks fine 
![image](https://user-images.githubusercontent.com/70918430/119875438-9b723300-bedb-11eb-8bdb-ca2914927e0b.png)
