### ISSUE TITLE
User Story 2.1 - Issue 1: User Story 2.1-pre-screening form: the CTA button Submit is bigger

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2327]

**Comment by adorapham** [comment]
-Adora work .  If you want , please pin me

**Comment by adorapham** [comment]
@xJamesScott [Issue 1](url)
nice to have   border-radius: 46px if we can for the rectangle-81
Submit - font-family should have Poppins only, Line-Hight should be 21.2 px instead of 20.0 px

https://user-images.githubusercontent.com/70918430/116644146-7d8ad000-a927-11eb-9ed0-76bd98bd9476.mp4

**Comment by adorapham** [comment]
We close it as it looks reasonable.
![image](https://user-images.githubusercontent.com/70918430/119748609-2571bb80-be4a-11eb-81b5-ad33c3fb8d8c.png)
