### ISSUE TITLE
User Story 3.1 - Issue 1: Which page to be displayed after clicking on Submit button? 

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2329]

**Comment by adorapham** [comment]
The user should see the 'application submitted' button as long as no action has been taken on the Application by the account owner/admin.
Once the form has been successfully submitted, the user should be directed back to the org profile page. At this stage user must see the CTA button disabled, and the CTA button text must display the sentence ' Application submitted'
