### ISSUE TITLE
User Story 3.1 - Issue 2: Text box must expand toward the bottom and more on application page

### ISSUE THREAD

**Issue by xJamesScott** [FightPandemics/FightPandemics#2330]

**Comment by adorapham** [comment]
Work as design

**Comment by adorapham** [comment]
[Issue 2](https://www.notion.so/fightpandemics/Issue-2-Text-box-must-expand-toward-the-bottom-and-more-on-application-page-6230df0d397a4f23a8508eb293969869)

https://user-images.githubusercontent.com/70918430/117067559-09fa1180-acdf-11eb-8dea-860387247880.mp4

**Comment by adorapham** [comment]
Closed with the above validation
