### ISSUE TITLE
 User Story 1.1 - Issue 13:  Switching account from Individual user to Org Owner Account and vice versa . #2332

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2332]
Device : Desktop 
Operation system : Windows 10 pro
Web Browser : Microsoft Edge , Chrome, Firefox 

https://user-images.githubusercontent.com/51660881/114615996-57510900-9c74-11eb-8a78-efdd07d21556.mp4

**Comment by xJamesScott** [comment]
@hiran11 @sarmahmili Please provide details or a link for the issue

**Comment by hiran11** [comment]
@xJamesScott 

Please refer to the link in notion 

https://www.notion.so/fightpandemics/Issue-13-User-Story-1-1-Switching-account-from-Individual-user-to-Org-Owner-Account-and-vice-versa-edab34b6d6f545eb8b5f5724e2c745eb

**Comment by xJamesScott** [comment]
@hiran11 Are you still having this issue?

**Comment by hiran11** [comment]
no Issue
