### ISSUE TITLE
User Story 1.1- Issue14: In Mobile view, Safari browser border and location issue

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2334]
In Mobile Safari browser, the the border of the org name is not defined as the Zeplin specs and also the message icon is there which is not in zeplin. Also the location seems to be positioned too close to the Org Name.
![IMG_8689](https://user-images.githubusercontent.com/80424272/114646397-2a6b1900-9ca9-11eb-9461-6170e0400889.PNG)

**Comment by xJamesScott** [comment]
The specs come from the profile designs shared between pages. As such, these concerns appear to fall outside of the scope of this Join Org project. Please confirm @IrisCGoncalves @ruchimahajan78 @sarmahmili

**Comment by sarmahmili** [comment]
@xJamesScott , I think testing on Safari is not in scope. Please confirm @IrisCGoncalves , @ruchimahajan78 .

**Comment by sarmahmili** [comment]
The build is matching with whats in Prod and Staging in terms of Border of the org name and message box. Also the spacing between location and org name also matching with prod and staging. Checked in Mobile safari, Firefox, Chrome browsers. After discussing with Iris I'm closing this ticket.
![image](https://user-images.githubusercontent.com/80424272/116454538-1806e880-a82e-11eb-8016-090d5162fa93.png)
