### ISSUE TITLE
User story 3.1- Issue 3 : The error message displayed is incorrect in the Application answer field #2336

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2336]
GIVEN the signed-in user is in the ‘Application’ page/screen WHEN they click/tap the ‘Submit’ button without responding to all fields THEN they must be presented with an error message next to the field that was left empty displaying the message ‘Mandatory Field’. Rather the error message displayed is "Required Field"

![image](https://user-images.githubusercontent.com/51660881/114751208-d9980680-9d22-11eb-8413-64bd2793484b.png)

**Comment by ruchimahajan78** [comment]
This issue can be closed. Leave it as 'Required field'. I will update the PRD. Thanks!

**Comment by hiran11** [comment]
@ruchimahajan78  Sure i will close this based on the comment given
