### ISSUE TITLE
User story 3.1 Issue 4-  The CTA button is displayed after application submission #2337

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2337]
@xJamesScott  
As per the User story 3.1 , the 3rd Acceptance criteria ,Once the form has been successfully submitted, the user should be directed back to the org profile page. At this stage user must see the CTA button disabled, and the CTA button text must display the sentence ' Application submitted'.

Either in Organization page nor in Application page the CTA button is not disabled after the submission of application.

![image](https://user-images.githubusercontent.com/51660881/114765524-40bdb700-9d33-11eb-8b12-e8fee325ba3b.png)

https://user-images.githubusercontent.com/51660881/114765558-4915f200-9d33-11eb-8b5c-5359f8964ee5.mp4

**Comment by AndersonNY** [comment]
@xJamesScott As you see on screenshot after you submit the application Cancel and Submit button doesn't seems correct on safari browser. Per zeplin should be space between two buttons.  <img width="1249" alt="'''" src="https://user-images.githubusercontent.com/56901619/114768939-841a2480-9d37-11eb-88c6-6ed9e4eef73c.png">

**Comment by ruchimahajan78** [comment]
This requirement was added after James implemented this story.  @xJamesScott can you please look into this. Thanks!

**Comment by xJamesScott** [comment]
This is a dependency on backend from US 8.1

**Comment by xJamesScott** [comment]
@hiran11 Fix released

**Comment by hiran11** [comment]
@xJamesScott 

The "Join Us " CTA button not disabled even after applying for an organization.

**Comment by hiran11** [comment]
Issue looks fixed  for submit button but CTA button is not disabled once applied.
