### ISSUE TITLE
User Story 1.1- Issue15: In Mobile Testing, Chrome browser The Org Name and Location Font Size Issue 

### ISSUE THREAD

**Issue by Selbinyyaz** [FightPandemics/FightPandemics#2340]
In Mobile Chrome browser, the Organization name font size is 16px in Zeplin where as in browser it is 19px.

![Screen Shot 2021-04-14 at 2 35 44 PM](https://user-images.githubusercontent.com/62081140/114793116-488b5480-9d4f-11eb-80ea-f4545fd2e88c.png)
It is 19px . 

![Screen Shot 2021-04-14 at 6 02 00 PM](https://user-images.githubusercontent.com/62081140/114792687-6d32fc80-9d4e-11eb-9a4c-a78f0b221131.png)

![Screen Shot 2021-04-14 at 6 30 00 PM](https://user-images.githubusercontent.com/62081140/114793185-753f6c00-9d4f-11eb-8860-5f6a1ffa1b13.png)

Also, The location font size is 10px in Zeplin where as in browser it is 14px.
![Screen Shot 2021-04-14 at 6 34 43 PM](https://user-images.githubusercontent.com/62081140/114793521-27773380-9d50-11eb-853f-294d2b165365.png)

![Screen Shot 2021-04-14 at 6 34 21 PM](https://user-images.githubusercontent.com/62081140/114793532-2c3be780-9d50-11eb-88fd-fe9f41447f60.png)

**Comment by xJamesScott** [comment]
Theses items can be ignored from the design. This page is intended to be consistent with the Profile page.

**Comment by Selbinyyaz** [comment]
The organization name and location font sizes are matching with prod and staging now. I close this defect after confirming with Ruchi. Thank you @xJamesScott
