### ISSUE TITLE
User Story 1.1- Issue15: In Mobile Testing, Chrome browser the "Org Description" text color Issue

### ISSUE THREAD

**Issue by Selbinyyaz** [FightPandemics/FightPandemics#2341]
In the Mobile Chrome browser, the organization description text color is lighter than in Zeplin. 

![Screen Shot 2021-04-14 at 6 59 06 PM](https://user-images.githubusercontent.com/62081140/114795295-d6693e80-9d53-11eb-85f4-01afc99667cd.png)
![Screen Shot 2021-04-14 at 6 52 42 PM](https://user-images.githubusercontent.com/62081140/114795327-e54ff100-9d53-11eb-9871-b73b6fe61072.png)
![Screen Shot 2021-04-14 at 7 02 34 PM](https://user-images.githubusercontent.com/62081140/114795378-01ec2900-9d54-11eb-82be-19f2ff8f1828.png)

**Comment by xJamesScott** [comment]
@Selbinyyaz Style is set by profile design, which is outside of the scope of this project

**Comment by Selbinyyaz** [comment]
The organization description text color is matching with prod so I close this defect after discussing Ruchi.
