### ISSUE TITLE
User Story 3.1: Application Submitted text is out of the box in Mobile device ,Android (Mozilla Firefox, 88.1.2)

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2356]
![Screenshot_20210503-161955_Firefox](https://user-images.githubusercontent.com/80424272/116934660-407a5280-ac33-11eb-82f9-2b28ab81355a.jpg)

**Comment by Selbinyyaz** [comment]
Hey @xJamesScott, The same issue has in chrome. 


https://user-images.githubusercontent.com/62081140/117371292-42d7e900-ae8d-11eb-8c09-8bc13717b786.mp4

**Comment by sarmahmili** [comment]
Seeing this issue as part of User Story 11.1 in mobile browsers (safari, chrome, Firefox).

**Comment by sarmahmili** [comment]
Retested in base branch and fix confirmed in mobile browsers (safari, firefox).
![image](https://user-images.githubusercontent.com/80424272/120034646-5af1e280-bfcb-11eb-8c48-bcaf488a9b0b.png)
