### ISSUE TITLE
User Story 6.1 : Issue 2 - Activity page should be the default page when navigating to Org Profile page

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2357]
As speaking with Ruchi , when the account owner or any 'member' is viewing the org profile, the default page will be the activity page

![image](https://user-images.githubusercontent.com/51660881/117301053-39785d80-ae48-11eb-96e5-71eba6cf751b.png)

![image](https://user-images.githubusercontent.com/51660881/117301120-4eed8780-ae48-11eb-9b0f-d75b360747c4.png)

https://user-images.githubusercontent.com/51660881/117300898-08982880-ae48-11eb-8288-d04bbe136436.mp4

**Comment by adorapham** [comment]
if you click on View My Profile for Org, it works but if you switch from org to org , or from org to indv, the page refresh and get two values: activity and Members, please see the screenshot. in this forget to record from org to indv but it fails the same as from org to org.

https://user-images.githubusercontent.com/70918430/118059294-0ef53b80-b345-11eb-9186-b2bde051c2ae.mp4

Testing on merged: Individual with one org account, still see the issue
![image](https://user-images.githubusercontent.com/70918430/119057575-8c423100-b981-11eb-80e7-9cca02dc8fd8.png)

**Comment by xJamesScott** [comment]
@adorapham This doesn't seem related to this User Story. I think this should be revisited after user stories are merged

**Comment by sarmahmili** [comment]
in the review Beta testing branch, the activity tab and posts are not visible initially. Its visible only after clicking on the members tab and then clicking on the Activity tab.

steps to replicate
sign in as user
click the org
by default "Activity tab " to be bold and should display posts by org rather
Post is displayed by clicking member tab first and then click Activity , posts are displayed

https://user-images.githubusercontent.com/80424272/121789527-b6fc5f80-cba4-11eb-9183-aea11eadab30.mov

**Comment by hiran11** [comment]
Issue is fixed
