### ISSUE TITLE
User Story 5.1- See Org Book Font Size Issue

### ISSUE THREAD

**Issue by Selbinyyaz** [FightPandemics/FightPandemics#2358]
Steps:
1. Click on the organization name
2. Should see the " See Org Book" link under the org description.

Actual result: the font size is 16 px in a chrome

Expected result: the font size is 14 px in Zeplin 

Environment:

- Browser: Chrome

- Device: Mobile

https://user-images.githubusercontent.com/62081140/117339591-86b6f800-ae65-11eb-858b-1d4f7eb4fa1b.mp4

**Comment by hiran11** [comment]
"See Org " Removed
