### ISSUE TITLE
User Story 6.1-Issue 4-in Desktop view, we expect to see Applicants (numberOfApplicants) - See All link and more

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2361]
For this one , we see few issues on desktop/mobile view-will confirm with BA and update 
1-should have total number of applicants in parentheses
2-should have See All  link (how many will be in display be default.  3 for mobile  and 4 for desktop view)
3-Put it back to mobile view , see See All link, click on see All link and when going to the end , see the up arrow, and click on up arrow to go to the top page to see the first few records. At that time, should the up arrow disappear?

https://user-images.githubusercontent.com/70918430/117372733-dd7cfb80-ae7e-11eb-98f0-13d2ae0324a8.mp4

**Comment by xJamesScott** [comment]
@adorapham There's no 'See All' link or number of applicants on mobile view in Zeplin
@xJamesScott - we can move fw without See All link and number of applicants on desktop

**Comment by adorapham** [comment]
I move back for enhancement for See All link and Applicants(number) for desktop view
![image](https://user-images.githubusercontent.com/70918430/118691678-29546c80-b7be-11eb-9aea-58e9ab82bb39.png)

**Comment by xJamesScott** [comment]
@adorapham Please check if this still exist

**Comment by adorapham** [comment]
@xJamesScott , it seems doesn't work .

https://user-images.githubusercontent.com/70918430/119766720-64176e00-be6a-11eb-98d2-fae978d1a0ea.mp4

**Comment by hiran11** [comment]
issue fixed
