### ISSUE TITLE
User Story 7.2 : the word "Reject" is incorrect.

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2368]
We get the same message whether we click on Reject or Accept button.
1. the Reject spellings should be corrected.
2. if we click on Reject button we should see 
![image](https://user-images.githubusercontent.com/80424272/119875192-7dfd9300-bef4-11eb-9cce-27c3ccde15a0.png)

3. If we click on Accept button we should see: 
![image](https://user-images.githubusercontent.com/80424272/119875361-ac7b6e00-bef4-11eb-839d-060e6b3ca9e4.png)

**Comment by sarmahmili** [comment]
![image](https://user-images.githubusercontent.com/80424272/117879007-6a0b2d80-b274-11eb-882a-2df010d6b45a.png)

**Comment by adorapham** [comment]
@linadinh2602 , please change the word SUBMIT to REJECT also.  I know the defect should include this
![image](https://user-images.githubusercontent.com/70918430/118993909-c1776080-b93a-11eb-83f9-6a10755ad4e9.png)

**Comment by sarmahmili** [comment]
The fix is confirmed for the word REJECT.
![image](https://user-images.githubusercontent.com/80424272/120006124-94642700-bfa6-11eb-87a8-80b7aefc24ba.png)

**Comment by sarmahmili** [comment]
@linadinh2602  as per requirement, can the string name be changed to Accept and Reject in the confirmation page as well? 

![image](https://user-images.githubusercontent.com/80424272/120018834-a9948200-bfb5-11eb-8eed-be9eb2104c94.png)

![image](https://user-images.githubusercontent.com/80424272/120018738-941f5800-bfb5-11eb-85c7-1ef4eebfaec4.png)

**Comment by sarmahmili** [comment]
Tested in build URL and fix is confirmed for the string name be changed to Accept and Reject in the confirmation page .
![image](https://user-images.githubusercontent.com/80424272/120385980-0d8cb280-c2f6-11eb-86a5-86e5d31a2a0d.png)
![image](https://user-images.githubusercontent.com/80424272/120386069-29905400-c2f6-11eb-858d-86ffcfa32a73.png)

**Comment by hiran11** [comment]
@linadinh2602 
Email is not generated when an applicant is rejected.
As per user story 7.2 Acceptance Criteria : Should they click/tap ‘Reject’ the user must be taken to a confirmation screen and the
applicant must receive a confirmation email reflecting this decision.

Email is not generated when an applicant is accepted.

As per User story 7.2 Acceptance Criteria : Should they click/tap ‘Accept’ the user must be taken to a confirmation screen and
the applicant must receive a confirmation email reflecting this decision.
