### ISSUE TITLE
User Story 6.1 Issue 5- don't see records display in the screen of mobile

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2373]
don't see records display in the screen of mobile
![image](https://user-images.githubusercontent.com/70918430/118026369-91fe9d80-b315-11eb-8e74-1f5477a025d6.png)

**Comment by xJamesScott** [comment]
@adorapham I've issued a fix for this. Please verify as soon as you can and approve the PR review so I can merge:

https://github.com/FightPandemics/FightPandemics/pull/2352

**Comment by adorapham** [comment]
verify and see the fix in and more discussion on the slack
https://app.slack.com/client/T010BHVS3EF/C01MWTZV64C/thread/C01MWTZV64C-1621289962.009700
![image](https://user-images.githubusercontent.com/70918430/118577355-1d759580-b73f-11eb-86bb-5cd2b035fbf5.png)
