### ISSUE TITLE
User Story 10.1 - In mobile view (firefox, Chrome & Safari) "Post Position" button text size is bigger.

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2374]

**Comment by sarmahmili** [comment]
In Mobile view (Mozilla Firefox), the text is going out of the border of the  "Post Position" button and overlapping  with the text from volunteer Position textbox/text area.
![image](https://user-images.githubusercontent.com/80424272/118043189-0b60b500-b343-11eb-947a-38519fba0163.png)

In Chrome the "Post Position" text is bigger for the Button siza.
![image](https://user-images.githubusercontent.com/80424272/118043307-34814580-b343-11eb-8817-023425be4dcc.png)

In Safari, the text from volunteer position is overflowing and the Post Position Button is small for the text.
![image](https://user-images.githubusercontent.com/80424272/118043483-6abec500-b343-11eb-8687-5406b1dec30d.png)

**Comment by ChunPingYang** [comment]
I already fix that, please test it.

**Comment by sarmahmili** [comment]
Retested in Mobile and fix is confirmed in Firefox, Safari and Chrome browsers.
In Firefox: 
![image](https://user-images.githubusercontent.com/80424272/118676870-c7016900-b7c9-11eb-9674-ba579ee2a1e6.png)

In Safari:
![image](https://user-images.githubusercontent.com/80424272/118677002-e26c7400-b7c9-11eb-9735-1f1534e2132c.png)
