### ISSUE TITLE
User Story 10.1-Issue 1 Volunteer Text Field description has text almost run out of the box and more

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2377]
[Issue 1-](https://www.notion.so/fightpandemics/Issue-1-Volunteer-Text-Field-description-has-text-almost-run-out-of-the-box-and-more-a4b20ab39c5c4fb780859250f63c0210)
**1.**The Org Admin can enter up to 501 instead of 500 characters in the text field on the 'Positions' page/screen

2. The Position text field description if entering the max of 500 characters, the last line seems almost out of the box.  So if we increase the height, Post Position btn should be move a bit down and might be increase a bit in distance from the textbox at the same time during  fixing this issue.
![image](https://user-images.githubusercontent.com/70918430/118176732-a78fc800-b3e6-11eb-9c74-fe43aa8df6d7.png)

**Comment by adorapham** [comment]
[https://www.notion.so/fightpandemics/Issue-1-Volunteer-Text-Field-description-has-text-almost-run-out-of-the-box-and-more-a4b20ab39c5c4fb780859250f63c0210](url)

**Comment by ChunPingYang** [comment]
I already fix that, please test.

**Comment by adorapham** [comment]
it works, TY
![image](https://user-images.githubusercontent.com/70918430/118690140-9b2bb680-b7bc-11eb-95f9-7d5582c6c3d3.png)
