### ISSUE TITLE
User Story 7.2-  the landing page should be the applicant page to see applicant profile is removed/accept

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2395]
I test on base line for reject applicant - I see the rejection function is working but the word is still wrong - (User Story 7.2 : the word "Reject" is incorrect. #2368).
1-GIVEN the user is in the ‘Applications’ page/screen WHEN he/she  clicks/taps  ‘Cancel’ the pop up message must disappear and restore the ‘Applications’ page/screen
2-Should they click/tap Reject’ the user must be taken to a confirmation screen and the applicant must receive a confirmation email reflecting this decision.
3-Should they click/tap 'Reject', the applicant's profile must be removed from the 'Applicants' page/screen.  i see it but the landing is still application page instead of Applicants page to see the applicant's profile is removed.  See the record on 
https://fightpandemics.slack.com/files/U01BMBU85G9/F022Q0XQWBY/reject_applicant.mp4?origin_team=T010BHVS3EF&origin_channel=C01MWTZV64C
since the file is too big
do the same for Accept , the landing page should be Applicants page , not Application page

**Comment by hiran11** [comment]
Issue fixed
