### ISSUE TITLE
User Store 6.1-7.1-8.1-the Applicants page display the same records of members page

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2396]
the Applicants page display the same records of members page when there is zero record of applicants and vice versa
1- Member page has zero record but show the same records as Applicants page
https://app.slack.com/client/T010BHVS3EF/C011V080R8E/files/F022TTRKZ8V

2-Applicants page has zero record but show the same records as Member page

https://user-images.githubusercontent.com/70918430/119430201-334a0400-bcc5-11eb-888a-345d54860f8c.mp4

**Comment by xJamesScott** [comment]
@adorapham Please check if this still exist

**Comment by adorapham** [comment]
@xJamesScott , it seems doesn't work - **old record** 

https://user-images.githubusercontent.com/70918430/119766720-64176e00-be6a-11eb-98d2-fae978d1a0ea.mp4

**new record** with applicants has records 

https://user-images.githubusercontent.com/70918430/119767243-5a423a80-be6b-11eb-8609-0e2f4a7d2cf7.mp4

**Comment by hiran11** [comment]
issue is fixed
