### ISSUE TITLE
User Store 1.1-non member should not be applied to same position /same organization many times 

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2399]
non member should not be able to apply to the same position of the same organization many times even this applicant has accept status and listed in members page. I think this one need more decision to find the best solution.

**here is what i observe - for example**  I provide a record but not necessary follow this flows but basing on that recording , i write this logic how the system currently work
1- Individual A (non member ) want to apply and submit the application in position Z for organization B  - we get record 11 in Applicants page of Organization B
2-Individual A (non member )  again apply and submit the application in position Z for organization B - we get record 22 in Applicants page of Organization B

**Account Owner of Organization B come to Applicants page**
1- first reject the record 11 of Individual A - first submission- so on Applicants page has only one record 22
2-second accept the record 22 of Individual A- second submission -so on Applicant page has zero record and Member has one record 22 of Individual A.  Individual A consider as a member but there is no role yet = So the system might consider as non-member

**back to Individual A login - search for Organization B**
-Individual A (member without any role yet- so consider as non-member) still able to apply the position Z for Organization B and we get record 33 in Applicant page for Organization B
so it seems the issues and how to make it work correctly.
https://app.slack.com/client/T010BHVS3EF/C010BHVT1MZ/files/F022X4NME85

**Comment by xJamesScott** [comment]
@adorapham issued a fix

**Comment by sarmahmili** [comment]
Tested in Beta branch (review) and noticed that the non member (DV) who applied for the Cinci Org can not see the Join Us CTA , when he tried to apply again.
![image](https://user-images.githubusercontent.com/80424272/121788305-43555500-cb9a-11eb-946c-a609c625fcab.png)
