### ISSUE TITLE
User Story 10.1 Issue 2 : Join Us CTA button is displayed when "Allow volunteers to join org" is turned off

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2402]
observations (desktop and mobile safari, chrome):
1. Join Us CTA button is displayed and enabled when org owner clicks on view org profile
2. Join Us CTA button is displayed when Allow volunteers to join org is turned off
![image](https://user-images.githubusercontent.com/80424272/119716035-ade46200-be32-11eb-9625-f69189b8d13d.png)

**Comment by xJamesScott** [comment]
@sarmahmili  Fix has been released, please check.

**Comment by sarmahmili** [comment]
Retested in base branch and fix confirmed.
![image](https://user-images.githubusercontent.com/80424272/119890947-6af3be80-bf06-11eb-9f81-26d3d02aa93e.png)
