### ISSUE TITLE
User Story 10.1 Issue 3 : Default description in Voluneer Position textbox is incorrect.

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2403]
Tested in Desktop and mobile (chrome, safari).
When the 'allow volunteers to join your organization' toggle is on and we tap on the Volunteer Position textbox, the default text is incorrect. 
![image](https://user-images.githubusercontent.com/80424272/119718523-ad00ff80-be35-11eb-95b9-b2cf6c34329d.png)
in desktop (chrome)
![image](https://user-images.githubusercontent.com/80424272/119718718-e76a9c80-be35-11eb-881c-54e60ab30bbe.png)
in mobile (firefox)
![image](https://user-images.githubusercontent.com/80424272/119719096-5e079a00-be36-11eb-9155-eef5a27188c8.png)

**Comment by ChunPingYang** [comment]
@sarmahmili Fix the bug

**Comment by sarmahmili** [comment]
Tested in base branch and fix confirmed.

in mobile (firefox)
![image](https://user-images.githubusercontent.com/80424272/120031415-c5545400-bfc6-11eb-81c8-1a2a4e2442ab.png)

in desktop (chrome)
![image](https://user-images.githubusercontent.com/80424272/120031572-f9c81000-bfc6-11eb-8edb-620dad9faf49.png)
