### ISSUE TITLE
User Story 1.1- signed user can apply only from individual profile

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2406]
Signed user can apply only from individual profile 
we find out the reason we have different avatar  because we apply the position from different account- for example- when we are in Individual Profile  (View Profile on the top left) , we have the record use the individual profile avatar.  But when we switch to Org account and apply for the position  (have Org Profile - View Profile on the top left),  see record use the Organization Profile avatar.  So i just wonder only Individual profile can apply for the position right. If you are in Organization profile , are you still able to apply . If yes, should record carry the Individual Profile avatar instead of Organization Profile avatar.  Or we have to force the user only apply when they are in individual profile? 
https://fightpandemics.slack.com/team/U01JXRL0SLA

**Comment by xJamesScott** [comment]
pushed this feature
