### ISSUE TITLE
USER STORY 6.1: Issue 6 Only 10 records Displayed in Applicant tab  

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2408]
@ChunPingYang @adroit22 

When logged in as owner of the organization and click the Applicant Tab only 10 Applicants are displayed even more applicants has submitted. 11th applicant is displayed only when action taken in 1st 10 records.  

[Recording #30.zip](https://github.com/FightPandemics/FightPandemics/files/6562442/Recording.30.zip)

In mobile version only 10 records are displayed in Applicant tab though more  applicants records  are present

**Comment by aditilamkhede** [comment]
@hiran11 isn't this autoscroll/infinite scroll behavior or see-all button?

**Comment by hiran11** [comment]
@aditilamkhede  yes aditi , in Desktop there is no "See all" or infinite scroll but in mob we have "See All " for applicant . Even if i click "See All " in mob  only 10 records will be displayed the 11th applicant wont be displayed .  In desktop at a time only 10 records is displayed by default .

**Comment by hiran11** [comment]
Issue looks fixed . "Load More " options is implemented.
