### ISSUE TITLE
User Story 6.1 and 8.1: when u create a new org, by default it shows 10000 members and  10000 applicants.

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2423]
Tested in base branch, when a new org is created, by default the Members and Applicants are shown as 10000. 
![image](https://user-images.githubusercontent.com/80424272/121085379-c4ce7100-c7af-11eb-8fe9-8cf4921865ee.png)

**Comment by sarmahmili** [comment]
1. when u search for a org (if the org have no members yet), by default it shows 10000 members.

![image](https://user-images.githubusercontent.com/80424272/121085852-65249580-c7b0-11eb-8877-8d3b7fc01f51.png)

2. After one applicant applies,  it shows 1 applicant and 10000 members.

![image](https://user-images.githubusercontent.com/80424272/121086546-4a065580-c7b1-11eb-8a2c-99171d465176.png)


3. after the org accept the applicant, it shows 1 member and 10000 applicant.

![image](https://user-images.githubusercontent.com/80424272/121086674-728e4f80-c7b1-11eb-8dbe-cc09167b55bd.png)

**Comment by hiran11** [comment]
@aditilamkhede @xJamesScott @adroit22 

In the mobile view  when signed in as Org owner the default value 10,000 is displayed in Applicant tab and Members tab when no member is added 

https://user-images.githubusercontent.com/51660881/121086891-bc773580-c7b1-11eb-8977-af59bb40e3ef.mp4

when  members  are added it displayes  number of applicants added as members and No applicant tab is displayed as 10,000 in Applicant tab 
![image](https://user-images.githubusercontent.com/51660881/121088853-57710f00-c7b4-11eb-9a32-2692dbe215c3.png)

**Comment by xJamesScott** [comment]
@hiran11 Pushed a bug fix

**Comment by hiran11** [comment]
Issue is fixed and looks good
