### ISSUE TITLE
User story 8.1 and 6.1 - Other org Appicants number and Member number displayed in individual org 

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2424]
@xJamesScott @aditilamkhede @adroit22 
 Steps to replicate error
When i try to login to my individual profile 
switch to my org profile 
Check the Applicant num (0)and Member number(0) 
click to other org B profile and check the  member num(20).
Switch to own org profile to see Applicant num and Mem num 
Org B profile Applicant num and Member num is displayed in my own org profile .

https://user-images.githubusercontent.com/51660881/121213418-32c87600-c84c-11eb-92f4-5b718d898a5e.mp4

**Comment by xJamesScott** [comment]
@hiran11 Pushed a bug fix

**Comment by hiran11** [comment]
issue fixed
