### ISSUE TITLE
Scrolling Issue in Safari browser.

### ISSUE THREAD

**Issue by sarmahmili** [FightPandemics/FightPandemics#2425]
Tested in base branch. It happens While trying to scroll to the bottom of the page.

https://user-images.githubusercontent.com/80424272/121216319-c9963200-c84e-11eb-9b5b-f156f0a98816.mov

**Comment by xJamesScott** [comment]
@sarmahmili What are the steps to reproduce?

**Comment by sarmahmili** [comment]
@xJamesScott , the steps to reproduce are as follows. I am seeing it in chrome, Edge and Safari desktop.

1. in the branch https://featurejoin-org.fightpandemics.xyz Sign in as org owner
2. Switch account to the organization
3. View Org profile
4. Click on Members tab
5. Scroll to the bottom of the page

**Comment by sarmahmili** [comment]
Tested in pre prod Beta branch and fix confirmed.
