### ISSUE TITLE
User Story 1.1 : "Applied Status :true"  is displayed in the Org description page 

### ISSUE THREAD

**Issue by hiran11** [FightPandemics/FightPandemics#2430]
@aditilamkhede @xJamesScott 

"Applied Status :true" is displayed in the org description page. 

![image](https://user-images.githubusercontent.com/51660881/121410605-c2dfeb80-c930-11eb-90f3-c387cf1cdd4b.png)

**Comment by xJamesScott** [comment]
pushed a fix

**Comment by hiran11** [comment]
issue fixed . LGTM
