### ISSUE TITLE
Permissions displaying on member profile when viewed by org

### ISSUE THREAD

**Issue by ruchimahajan78** [FightPandemics/FightPandemics#2439]
When clicking on the members name, it takes us to their profile page, which is currently displaying permissions on their profile. This needs to be removed, not only because the description is incorrect, but also because we are not supporting it anymore. (ref: user story 9.1).

Scenario: I am an org who clicked on one of the members name displayed under member's tab. it takes me to the profile page of this member which shows permissions.
Attached is the view  #
<img width="830" alt="Screen Shot 2021-06-11 at 2 13 29 PM" src="https://user-images.githubusercontent.com/77990810/121749529-a9b97500-cabf-11eb-86b1-a90ac25d75ba.png">

**Comment by xJamesScott** [comment]
@ruchimahajan78 Pushed a fix
