### ISSUE TITLE
Add validation for email on the need-help step 3 page

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#261]
environment : https://staging.fightpandemics.work/need-help#Step3

Steps: 
1. Select Need Help on the Main page
2. Go to step 3
3. enter one letter click Submit button

User should see validation for email

**Comment by anniegiang** [comment]
I removed @indirabhowmick as an assignee because she is a PM  and to not confuse other developers that this issue is taken.

**Comment by omarzoghayyer** [comment]
I'll work on this task.

**Comment by manualzuru** [comment]
@omarzoghayyer should we put this in progress?

**Comment by anniegiang** [comment]
There's a PR in review for this
