### ISSUE TITLE
Add validations while navigating between Give Help questions pages

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#263]
env: https://staging.fightpandemics.work/offer-help

steps:
1. From main menu select Give Help. Question 1 screen is open.
2. Do not select any checkbox
3. Click on next arrow.
Repeat for Question 2 and 3 pages.
4. On the Question 3 screen click submit

There should be error messages - select data

**Comment by anniegiang** [comment]
I removed @indirabhowmick as an assignee because she is a PM  and to not confuse other developers that this issue is taken.

**Comment by omarzoghayyer** [comment]
I tried the steps above, and I don't see any error messages after selecting the submit button.

**Comment by omarzoghayyer** [comment]
Ill work on this issue
