### ISSUE TITLE
Resolve required NODE_ENV

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#264]
When starting the app in the terminal:

<img width="1021" alt="Screen Shot 2020-05-06 at 9 00 05 AM" src="https://user-images.githubusercontent.com/42228386/81202658-c8277580-8f7b-11ea-810b-1fe90e827933.png">

**Comment by joshmorel** [comment]
I think we just need to tell everyone in the channel - about https://github.com/FightPandemics/FightPandemics/commit/fb51532d0e1722437aeda9fa61de7b8515a82ce4

Unless we want to make the default to `'dev'` here - https://github.com/FightPandemics/FightPandemics/blob/master/backend/config.js - (or is this risky)?

**Comment by anniegiang** [comment]
@joshmorel Ah, you're right. I forgot to implement the changes that Manny talked about. That should fix it. 

We shouldn't add a default `dev` as mentioned [here](https://github.com/FightPandemics/FightPandemics/pull/235/files/cd508b93aa373565cc61b8cbc00b8d57af43b43b#r419132281)
<img width="1424" alt="Screen Shot 2020-05-06 at 10 35 45 AM" src="https://user-images.githubusercontent.com/42228386/81209421-5d7b3780-8f85-11ea-9d99-8ee0e723cabe.png">
)
