### ISSUE TITLE
Integrate auth logic into Feed and Posts

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#271]
- [ ] Implement auth logic for liking/unliking posts.
- [ ] Implement auth logic for "View More".
- [ ] Implement auth logic for commenting posts.
- [ ] Implement auth logic for commenting comments.

For detailed requirements refer to:
https://www.notion.so/fightpandemics/a729bd46f001461393a0ad707161f299?v=16cb1b0a7a1c4d5ba0a1aea6184cf734&p=653658508c4649869787c48f3e4eee13

**Comment by limaneto** [comment]
Can I be responsible for the first item? 
Implement auth logic for liking/unliking posts.

**Comment by robinv85** [comment]
@limaneto is this  in progress? If yes, would be nice to drag it to the column on project tracker https://github.com/FightPandemics/FightPandemics/projects/1

**Comment by anniegiang** [comment]
duplicate of #179 - #183
