### ISSUE TITLE
fix close icon icon on cookies bar 

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#274]
flow
- go to https://staging.fightpandemics.work/
- will appear a cookies bar info on the bottom
- close icon is not very visible

<img width="1865" alt="Screenshot 2020-05-10 at 03 13 26" src="https://user-images.githubusercontent.com/29093946/81489360-56e20e00-926c-11ea-9086-0e953068c202.png">

iMac, Chrome

**Comment by harithzamri** [comment]
i will take a look at this

**Comment by manualzuru** [comment]
@harithzamri are you taking this one?

**Comment by harithzamri** [comment]
@manualzuru yes, i'm taking this one
