### ISSUE TITLE
fix icon layout on feed

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#279]
flow
- go to https://staging.fightpandemics.work/
- click on view community postings
- add a comment
- reply to that comment
- avatar is cut off

asset
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTGhWTUkY0xGbbdHyReD6227iz53ADtRmcn1PTN4GUS3clC6MCT&usqp=CAU

<img width="1012" alt="Screenshot 2020-05-10 at 22 01 52" src="https://user-images.githubusercontent.com/29093946/81510500-f99c9a00-9309-11ea-818d-2c5ebe7c3e1d.png">

iMac, Chrome

**Comment by jyclam** [comment]
Hi @anniegiang, I believe I have a fix for this, but don't have permission to submit a PR.

**Comment by anniegiang** [comment]
> Hi @anniegiang, I believe I have a fix for this, but don't have permission to submit a PR.

@jyclam I've invited you to join, please accept it.
