### ISSUE TITLE
arrow doesn't work on the first step on the flow

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#290]
flow
- go to https://staging.fightpandemics.work/
- click on need help
- click on the back arrow
- back arrow doesn't work on the first step on the flow

<img width="1380" alt="Screenshot 2020-05-11 at 03 33 19" src="https://user-images.githubusercontent.com/29093946/81519202-58790800-9338-11ea-827e-cdb01a8a96b2.png">

**Comment by TenNga** [comment]
Back button works while running on localhost, is https://staging.fightpandemics.work/ running latest code?

**Comment by stavares843** [comment]
> Staging
When a pull request is merged to master, it will automatically be deployed to the staging environment. You can view the build logs in GitHub Actions. After the build successfully completes, wait a few minutes for the changes to be reflected, and then access the staging app at http://staging.fightpandemics.work.



seems staging would always be automatically updated when merging a PR

**Comment by robinv85** [comment]
Seems to work now, this was recently fixed, maybe it wasn't deployed that at the time of creating this issue...
