### ISSUE TITLE
Create a reusable description card component

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#297]
- [ ]  Use the Card component provided by [antd](https://ant.design/components/card/) (not strict but ideal)
- [ ] Can accept and display data passed in as props
- [ ] Styles should be pixel perfect:
<img width="735" alt="Screen Shot 2020-05-10 at 10 06 38 PM" src="https://user-images.githubusercontent.com/42228386/81525848-db836980-930a-11ea-86ba-322e683f2fdb.png">

Reference:
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=3516%3A22832

**Comment by Chimaobi-Johnson** [comment]
@limaneto have you started on this? it is related to the issue im working on which is #313 and i have already created the component

**Comment by limaneto** [comment]
No, sorry!
