### ISSUE TITLE
Fixing the footer and adding the Desktop style

### ISSUE THREAD

**Issue by nadinejuraschek** [FightPandemics/FightPandemics#298]

**Comment by nadinejuraschek** [comment]
Please keep working on the Footnote branch to fix this issue! The Desktop styles for the footer are there already, but the positioning issue needs to be fixed. There is a PR for it as well, feel free to just take over! Or reach out on Slack!

**Comment by tiagocostasilva** [comment]
Hi, when this issue is corrected it means the footer will be visible both in Mobile and Web version?
