### ISSUE TITLE
Symptoms check - responses are incorrectly shown on Step 10 page

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#305]
env. https://staging.fightpandemics.work/symptoms-check#step10

Steps:
1. Open Symptoms check
2. Select several symptoms while answering to questions 2 and 3.
3. Go to step 10.
Responses section: Answers are shown in one line. No space between answers. Please see screen attached.
![Screen Shot 2020-05-11 at 14 26 03](https://user-images.githubusercontent.com/21987083/81561881-3319e780-9394-11ea-8f94-717bbc002c7c.png)

More info:
Browser: Chrom v. 81
mac os

Expected behaviour: Figma screen:
![Screen Shot 2020-05-11 at 19 07 06](https://user-images.githubusercontent.com/21987083/81590225-c82fd700-93ba-11ea-80e2-4700b5993dd3.png)

**Comment by omarzoghayyer** [comment]
Ill work on this issue

**Comment by vikjoshi** [comment]
@omarzoghayyer , I think I'm still seeing this issue- see screenshot below. 
![image](https://user-images.githubusercontent.com/41554004/82018046-4ac5ca00-9639-11ea-89c9-71358528a248.png)

This is on Chrome Desktop

**Comment by omarzoghayyer** [comment]
@vikjoshi  I think these weren't merged since the whole page need to be redesigned. Please reach out to @anniegiang  regarding that.

**Comment by anniegiang** [comment]
@omarzoghayyer @vikjoshi 

Good catch! Yes I opened issue #315, which is a major refactoring of all the mobile pages for Symptoms Check. Now that I think of it, that issue may be too large and smaller issues like this may be more reasonable.

**Comment by snowiesuet** [comment]
> @omarzoghayyer @vikjoshi
> 
> Good catch! Yes I opened issue #315, which is a major refactoring of all the mobile pages for Symptoms Check. Now that I think of it, that issue may be too large and smaller issues like this may be more reasonable.

Should we group up the smaller issues into #315 and just work on the smaller issues instead?

**Comment by snowiesuet** [comment]
Sorry, accidentally closed.

**Comment by omarzoghayyer** [comment]
This Issue has been resolved in a different PR. Im going to close it for now.
