### ISSUE TITLE
Symptom check - Button Done on Step 10 page doesn't work

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#306]
env. https://staging.fightpandemics.work/symptoms-check#step10

Steps:
1. Go to Symptom check
2. Answer questions and go to Step 10.
3. Scroll down to the button Done. 
Done looks like enabled button(css div class sc-fzpans cKJzHK) but it doesn't work. Should it redirect somewhere? Message sent on slack to  @Yu. 

![Screen Shot 2020-05-11 at 14 43 07](https://user-images.githubusercontent.com/21987083/81562828-c4d62480-9395-11ea-8395-0317b50f891d.png)

More info:
Browser: Chrom v. 81
mac os

Expected behaviour: Figma screen. This button should open Feed:

![Screen Shot 2020-05-11 at 19 09 27](https://user-images.githubusercontent.com/21987083/81590508-2f4d8b80-93bb-11ea-86be-c766e14e90e6.png)

**Comment by Fersubair40** [comment]
I'm working on it.

**Comment by anniegiang** [comment]
> I'm working on it.

Thanks! In the future please assign yourself on the right hand side.
