### ISSUE TITLE
Replace usage of Material UI and Grommet

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#307]
- [ ] Replace any usage of Material UI icons with the icons provided on Figma (instructions in README).
- [x] Replace any usage of Material UI fonts and with the current fonts used.
- [x] Replace any usage of Grommet components with styled-components or antd components.

**Comment by robinv85** [comment]
I think I've already removed Grommet in a previous issue, might have been reverted by some other merge, Quick search just shows entry in package.json https://github.com/FightPandemics/FightPandemics/search?q=grommet&unscoped_q=grommet

**Comment by anniegiang** [comment]
> I think I've already removed Grommet in a previous issue, might have been reverted by some other merge, Quick search just shows entry in package.json https://github.com/FightPandemics/FightPandemics/search?q=grommet&unscoped_q=grommet

Hmm interesting.. Looks there are some Grommet remains in the code base right now:

![Screen Shot 2020-05-11 at 9 05 01 AM](https://user-images.githubusercontent.com/42228386/81583655-8117f680-9366-11ea-9e30-b2cd8590550d.png)

**Comment by snowiesuet** [comment]
The Grommet icons in the current code base are being commented so they are not in use @anniegiang
