### ISSUE TITLE
Render CookieAlert only once 

### ISSUE THREAD

**Issue by anniegiang** [FightPandemics/FightPandemics#314]
Currently it appears on every page even after closing it the first time.

- [ ] Should show only once on very first visit to site
- [ ] Should not appear again on any pages after closing it

![Screen Shot 2020-05-11 at 6 32 44 PM](https://user-images.githubusercontent.com/42228386/81628551-d0d1de80-93b5-11ea-8e40-601b74e55c23.png)

**Comment by harithzamri** [comment]
i will work on this
