### ISSUE TITLE
clicking on done doesn't do anything

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#322]
flow
- go to https://staging.fightpandemics.work/
- click on need help
- symptoms checker flow
- on the end of the flow, clicking on done button doesn't do anything

<img width="1346" alt="Screenshot 2020-05-12 at 04 57 55" src="https://user-images.githubusercontent.com/29093946/81637012-29809600-940d-11ea-969a-daa60dc9c608.png">

**Comment by galeza** [comment]
Duplicate #306.
