### ISSUE TITLE
AirTableCOVID screen - buttons are not separated, not aligned correctly

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#323]
env: https://staging.fightpandemics.work/AirTableCOVID
1. From main screen select Give Help
2. Go to the Question 3
3. Select Skip link
4. AirTableCOVID screen is open.

Buttons are too big, overleaping. Not aligned correctly.
![Screen Shot 2020-05-12 at 13 46 46](https://user-images.githubusercontent.com/21987083/81684215-109cd280-9457-11ea-9972-5389501684eb.png)

Expected results:
Could we improve them? At least separate them?
More info:
Tested on Mac os. Chrom 81 browser.

**Comment by robinv85** [comment]
A while ago I updated that page bevcause it was using Bootstrap components and I replaced it with some other components without looking much at the styling, but I think that page will be removed eventually if I'm not mistaken, maybe @anniegiang knows?

**Comment by galeza** [comment]
Ok thank you! If it will be removed, please @anniegiang close this issue.

**Comment by anniegiang** [comment]
@galeza @robinv85 Yes I believe we will be removing this page. We will use the "posts" from this page to be in the Feed after mapping the data from Airtable to our database.
