### ISSUE TITLE
Need Help Other Onboarding -  Submit on question 3 page should open Feed page

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#324]
env: https://staging.fightpandemics.work/need-help#Step3

Steps: 
1. Select Need Help
2. Question 1 : Other Help
3. Go to Question 3 and click Submit button
4. https://staging.fightpandemics.work/medical is open

According to Figma user should be redirected to the Feed page
![Screen Shot 2020-05-12 at 14 06 06](https://user-images.githubusercontent.com/21987083/81688229-c2d59980-9459-11ea-97c1-e7f230a26ac6.png)

More info:
Mac os
Browser: Chrome 81

**Comment by galeza** [comment]
message sent to #design slack channel to confirm.

**Comment by galeza** [comment]
Should open Feed screen

**Comment by omarzoghayyer** [comment]
Ill work on this issue
