### ISSUE TITLE
Create post as an organization: layout is different than the mocks

### ISSUE THREAD

**Issue by Samdisha** [FightPandemics/FightPandemics#325]
Env: https://staging.fightpandemics.work/

Steps to recreate:
1. Land on https://staging.fightpandemics.work/
2. Offer help as an organization
3. Observe the next screen
<img width="1278" alt="Screen Shot 2020-05-12 at 09 32 45" src="https://user-images.githubusercontent.com/3345129/81698164-99097c00-9433-11ea-9f1d-785bef3e8587.png">

Current behaviour: 
1. Heading 'Question 1/3' is not centre aligned as in the mocks
2. The options are not presented in a box as designed in the mocks. 
3. The 'Back' and 'Next' verbiage is missing. Only the arrows are being displayed. 
4. The header options such as 'Feed', 'COVID-info', 'Login', and 'Register' are missing
5. The page background is not grey as seen in the mocks. 

Desired behaviour: 
<img width="859" alt="Screen Shot 2020-05-12 at 09 36 59" src="https://user-images.githubusercontent.com/3345129/81698633-441a3580-9434-11ea-8fce-1cb166375523.png">

**Comment by Oluwadamilareolusakin** [comment]
I will work on this!
