### ISSUE TITLE
Create a post as an organization: Question 2/3 layout

### ISSUE THREAD

**Issue by Samdisha** [FightPandemics/FightPandemics#328]
Env: https://staging.fightpandemics.work/

Steps to recreate:
1. Land on https://staging.fightpandemics.work/
2. Offer help as an organization
3. Select post as an organization
4. Observe the next screen

Current behaviour: 
<img width="1280" alt="Screen Shot 2020-05-12 at 09 42 21" src="https://user-images.githubusercontent.com/3345129/81723138-67eb7480-9450-11ea-90bb-8fe5fcaae016.png">

- [ ]  Heading 'Question 1/3' is not centre aligned as in the mocks
- [ ]  The location bar is not as per the design in the mocks
- [ ]  'Show me posting anywhere' is wrapped. Not as per the design in the mocks
- [x]  The header options such as 'Feed', 'COVID-info', 'Login', and 'Register' are missing
- [x]  The page background is not grey as seen in the mocks.

Desired behaviour:
<img width="549" alt="Screen Shot 2020-05-12 at 12 59 37" src="https://user-images.githubusercontent.com/3345129/81723176-76d22700-9450-11ea-830d-2950aa3c76ec.png">

**Comment by galeza** [comment]
The same screen is required for Need Help question 2/3 screen.

**Comment by nadinejuraschek** [comment]
related to these issues: 
#[471](https://github.com/FightPandemics/FightPandemics/issues/471), 
#[473](https://github.com/FightPandemics/FightPandemics/issues/473)

**Comment by ppagarawal** [comment]
@tiagocostasilva and me had worked to get this sorted. Different tickets were raised to have the desired UI and behaviour.
