### ISSUE TITLE
Fix HTML5 Geolocation call

### ISSUE THREAD

**Issue by mannykary** [FightPandemics/FightPandemics#336]
For some reason, the HTML5 geolocation call is failing, and returning an empty geolocation object. Consequently, the API call to our geoservice endpoint on the backend failed when the geolocation object was empty, since passing in the latitude and  longitude query parameters was required.

I have temporarily defaulted the geolocation latitude/longitude to San Francisco if the geolocation object is empty.

_Originally posted by @mannykary in https://github.com/FightPandemics/FightPandemics/pull/317_

**Comment by captchadex** [comment]
@mannykary hi there, I'm new to this project. Which page in the app triggers the geolocation call?

Thanks!

**Comment by mannykary** [comment]
@captchadex Thanks for picking up this ticket! The geolocation request is happening in `NeedHelp.js` (there's a call to `asyncGetGeoLocation`). I'm not actually sure if the call is failing, or if it's not saving to the browser local storage properly, which results in the `Medical.js` page not being able to get the `location` from the browser storage.

**Comment by joshmorel** [comment]
I'm going to resolve this with #649 or a 2nd PR related to geolocation front-end integration.

**Comment by idjevm** [comment]
This has been resolved by #649 so closing this up.
