### ISSUE TITLE
[Mobile] Landing/Home Screen - description disappears when screen is rotating 

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#343]
env. https://staging.fightpandemics.work/

Steps:
1. Open https://staging.fightpandemics.work/ on your mobile
2. Rotate screen
3. When screen is rotated description : Pandemics will continue to happen. We help communities prepare and respond - is not visible

![Screenshot_2020-05-14-15-12-19-657_com android chrome](https://user-images.githubusercontent.com/21987083/81938884-dae22000-95f5-11ea-884d-171ef203404e.jpg)
![Screenshot_2020-05-14-15-12-25-699_com android chrome](https://user-images.githubusercontent.com/21987083/81938892-df0e3d80-95f5-11ea-8a86-0095181eb686.jpg)
Expected results: description is visible

More info:
Android 9 , Chrome

**Comment by snowiesuet** [comment]
#345 related
