### ISSUE TITLE
[Mobile] design when screen rotates - it's not mobile but web desktop is shown

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#345]
env: https://staging.fightpandemics.work/
Steps: 
1. Open staging on your mobile phone
2. Rotate your phone
3. When phone is rotated app shows design for desktop. Please see screen attached:
![Screenshot_2020-05-14-19-40-36-407_com android chrome](https://user-images.githubusercontent.com/21987083/81967598-76d25280-961b-11ea-9e44-999a18905f7e.jpg)
![Screenshot_2020-05-14-19-40-23-314_com android chrome](https://user-images.githubusercontent.com/21987083/81967605-7934ac80-961b-11ea-92bb-d4db7837994d.jpg)
![Screenshot_2020-05-14-19-40-58-772_com android chrome](https://user-images.githubusercontent.com/21987083/81967609-79cd4300-961b-11ea-91db-e8e26990bfc9.jpg)
![Screenshot_2020-05-14-19-49-14-364_com android chrome](https://user-images.githubusercontent.com/21987083/81968047-23accf80-961c-11ea-98b1-2b679ed4d0a2.jpg)
![Screenshot_2020-05-14-19-49-09-853_com android chrome](https://user-images.githubusercontent.com/21987083/81968442-afbef700-961c-11ea-8a28-8b04c5676f38.jpg)

More info:
Android 9, chrome. Xiaomi Redmi note 8 6.3"
Tested also on Tablet Samsung Galaxy - app is open in a desktop design

**Comment by joshmorel** [comment]
@galeza Should tablet (portrait/landscape) be following the mobile design?

@TenNga / @anniegiang In such a case, similar issues may be encountered on many pages. Do you think it would be more efficient for one person to tackle this as a whole (instead of many separate PRs)?

**Comment by robinv85** [comment]
I guess currently there are just media queries based on the screen size, also known as "responsive web design". 
There are ways to add specific code for mobile like user agent detection and stuff like that but I would recommend against that, it's still possible to add some specific CSS rules for ios and android, but now that we have mobile apps in progress as well I would think that a responsive web app fulfills most of the requirements?

**Comment by galeza** [comment]
@joshmorel I'll ask designers to confirm to change it or not (if web app fulfils most of the requirements)

**Comment by joshmorel** [comment]
@robinv85 I do agree we should stick with media queries. Also with further thought and IMHO given the native app development and the drive to launch the MVP I don't think we should be concerned about testing the web app styling in tablets.

So maybe we just focus on getting the web app look to match the mobile design with a phone rotated to landscape for now? In such a case though is the max of 767px in `constant/theme.js` a little too small?

**Comment by anniegiang** [comment]
fixed by #349
