### ISSUE TITLE
Symptom Checker- Desktop and Mobile-Missing Landing Page and Disclaimer Page from Figma MVP

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#351]
![image](https://user-images.githubusercontent.com/41554004/82015358-6cbc4e00-9633-11ea-95d0-165fa89cdd66.png)

1. Landing page of Symptom checker needs to be updated to match Figma Design MVP (https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=4147%3A17391). 
2. Also missing the Disclaimer page from MVP

**Comment by nadinejuraschek** [comment]
Just to make sure: The page is supposed to match this now? 
<img width="776" alt="Screen Shot 2020-05-16 at 5 12 53 PM" src="https://user-images.githubusercontent.com/53962732/82132802-96db5080-9798-11ea-9a16-d3c4be35983b.png">

**Comment by vikjoshi** [comment]
Hey @nadinejuraschek , in Figma, there are two pages prior to this page that I think need to be implemented in staging. Currently, we are sent directly to this page.
 
![image](https://user-images.githubusercontent.com/41554004/82157696-fa688b00-9837-11ea-8a50-f6f37fa40f09.png)

**Comment by snowiesuet** [comment]
#400 will fix the mobile of this, need to add desktop after this is merged.

**Comment by dhruvdpatel** [comment]
Working as expected. Closing this.
