### ISSUE TITLE
Symptom Checker- Desktop and Mobile- Update SC Call Page to match Figma MVP

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#352]
Currently, SC Call page on staging looks like below- 
![image](https://user-images.githubusercontent.com/41554004/82015786-6d091900-9634-11ea-9f4e-417eb4567765.png)

Update staging to match MVP. Changes include: 
1. Match styling to MVP (fonts of 911 message
2. Update options to match MVP ("Yes, I am experiencing these symptoms", "No, I'm not experiencing these symptoms")
3. User should not be able to proceed to next page without selecting one of these options
4. If user selects "Yes, I am experiencing one of these symptoms"- modal should pop up like in Figma MVP (refer to SC-Call-Msg). Hitting close on that modal should take them back to SC-Call page

**Comment by dhruvdpatel** [comment]
This is not reproduced and fixed already so closing it. Thanks.
