### ISSUE TITLE
Symptom Checker- Desktop and Mobile- Question Numbering Incorrect

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#356]
The question numbering goes from 6/9 to 8/10 (see screenshot below). Let's fix for all questions after Question 6. 
![image](https://user-images.githubusercontent.com/41554004/82017695-90ce5e00-9638-11ea-8eb3-7788b7bffd5a.png)

**Comment by omarzoghayyer** [comment]
I'll have it done today.
