### ISSUE TITLE
Symptom Checker- Mobile- Preexisting Conditions Question Bug

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#358]
On page below (iOS Chrome v81), 
Expected Behavior: Selecting "None of these" should unselect all other selected options
Actual Behavior: Selecting "None of these" does not unselect all other options. 

![IMG_1341](https://user-images.githubusercontent.com/41554004/82020430-e78a6680-963d-11ea-95d5-55d61dba79fb.jpg)

**Comment by omarzoghayyer** [comment]
Ill work on this issue.

**Comment by omarzoghayyer** [comment]
@joshmorel @vikjoshi Just fixed this issue. I have a pull request under review for it.
