### ISSUE TITLE
Fix comments and reply being squeezed 

### ISSUE THREAD

**Issue by jyclam** [FightPandemics/FightPandemics#365]
**Steps to re-create:**
- go to https://staging.fightpandemics.work/
- click on view community postings
- add a comment
- reply to that comment
- reply to that comment 

After a few nested replies, open DevTools and view as a mobile device, ie. iPhone X

![Screen Shot 2020-05-15 at 8 13 32 PM](https://user-images.githubusercontent.com/26049767/82109750-69859880-96ed-11ea-82d0-f9eb92f40b96.png)

**Comment by snowiesuet** [comment]
We should have a limit of how many replies we can have nested and how the design should look like.

**Comment by robinv85** [comment]
@snowiesuet I think the limit is 1 reply level
does this mean this can be closed? @jyclam @indirabhowmick

**Comment by indirabhowmick** [comment]
@snowiesuet @robinv85 @jyclam - Yes, the issue can be closed. I just tested the functionality. Thanks!
