### ISSUE TITLE
Client Side Error Handling for Web in User Authentication Flow

### ISSUE THREAD

**Issue by sumerjoshi** [FightPandemics/FightPandemics#369]
This ticket is kind of a catch all - basically going through the code and updating every situation of which there is possibility for a client error.

Current Behavior: Right now, I don't believe there is a current Behavior for error handling client side errors.
Expected Behavior: Using inline error messages to handle client side errors

**Comment by robinv85** [comment]
Checking design inconsistencies, possibly mobile / desktop web variations are different, this design seems wrong with a red "placeholder text" or "input value" instead of a validation error under the input.

**Comment by robinv85** [comment]
Updated the issue description, removed the screenshot to avoid confusion, talked to designers and the conclusion is to stick to one consistent appraoch from the designs (red error text under the input and red underline)
