### ISSUE TITLE
[WEB] Handling errors from server for User Authentication Flow

### ISSUE THREAD

**Issue by sumerjoshi** [FightPandemics/FightPandemics#370]
Current Behavior: There is no uniform behavior in dealing with server side messages during the User Authentication Flow
Expected Behavior: In every case where there may be possibility for a server side error, there should should be a red box that appears with the appropriate server side error.
<img width="780" alt="Screen Shot 2020-05-16 at 12 50 07 PM" src="https://user-images.githubusercontent.com/593277/82129203-e5c3be80-9775-11ea-81cb-92a867505943.png">

**Comment by robinv85** [comment]
Updated title to match with #372
I'll work on these 2 tickets at the same time
