### ISSUE TITLE
[Mobile] Client side form validation for User Authentication Flow

### ISSUE THREAD

**Issue by sumerjoshi** [FightPandemics/FightPandemics#371]
Current Behavior: In the case of client side error handling the mobile design, there is no current or uniform way to handle how to display client side error messages to the user.
Expected Behavior: For every situation where there is a client side error, use this inline error message design in the picture below (as an example)
<img width="782" alt="Screen Shot 2020-05-16 at 12 49 47 PM" src="https://user-images.githubusercontent.com/593277/82129327-9e89fd80-9776-11ea-8c6c-cbe9a02d779e.png">

**Comment by robinv85** [comment]
Hi @sumerjoshi just FYI I've updated the ticket since I think it's more about "client-side validation:" on the forms, I will work on the #372 and this one is related but can be done mostly with the form components

**Comment by TenNga** [comment]
The only way I can do this is by DOM getElementById and changing the style color, if there is a better way please let me know. Meanwhile, I will continue doing my way.

**Comment by indirabhowmick** [comment]
@TenNga @robinv85 - Who is handling this ticket? @TenNga - Can you please assign the ticket to yourself?

**Comment by robinv85** [comment]
@indirabhowmick @TenNga yes well like I've already mentioned on the PR review I've completely refactored the login & signup flow with another library that we were also using on other pages so this handles most of the client-side validation by default and I've added the validation of server-side errors, it can probably be updated for some styling from the work on this other PR

**Comment by indirabhowmick** [comment]
@robinv85 Thanks for the explanation. I have assigned the ticket to myself. Once I am able to test the User Authentication, probable this ticket can be marked as closed.

**Comment by robinv85** [comment]
@indirabhowmick well actually my PR #415 contains the updates with the form library, which has error handling and validation, but it doesn't actually display the client-side validation under the inputs, which is what @TenNga was working on in another PR #409 so maybe we can merge those 2 PR's

**Comment by indirabhowmick** [comment]
@robinv85 @TenNga - should I close this ticket?

**Comment by robinv85** [comment]
@indirabhowmick actually i think this is still an open PR #409
but it should be refactored with the latest updates with react-hook-form 
unless you close it and we only #369 for web + mobile

**Comment by robinv85** [comment]
Closing it and handling it together with #369
