### ISSUE TITLE
[Mobile] Handling errors from server for User Authentication Flow

### ISSUE THREAD

**Issue by sumerjoshi** [FightPandemics/FightPandemics#372]
Current Behavior: In the case of server side error handling the mobile design, there is no current or uniform way to handle how to display client side error messages to the user.
Expected Behavior: For every situation where there is a server side error, use this error message design in the picture below.
<img width="883" alt="Screen Shot 2020-05-16 at 12 49 53 PM" src="https://user-images.githubusercontent.com/593277/82129354-dee97b80-9776-11ea-85f8-063f292d7ed6.png">

**Comment by joshmorel** [comment]
@sumerjoshi  If no one picks it up by 20/05/2020 I will work on it.

I would suggest the PR to resolve this issue also address these other issues - #371 #370 #369

**Comment by sumerjoshi** [comment]
@joshmorel I initially thought this would only be one PR, however, after talking to Robin, there might be multiple other places where this error design might need to be implemented. Just wanted to make sure each ticket was granular enough

**Comment by robinv85** [comment]
@sumerjoshi thanks for opening the tickets, good that there are multiple tickets for this, however it seems a bit confusing, this isn't really a backend ticket, it's rather how the frontend handles errors coming from the backend. 
The actual responses on the backend are separate tasks, and should be implemented already, unless some specific cases like here #225 which needs some more work, and can also be improved by additional frontend validation etc.

**Comment by sumerjoshi** [comment]
@robinv85 sounds good
