### ISSUE TITLE
Add geocoding (lat/lon from address)

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#393]
Current Behaviour:

The geo-service only does reverse geocoding (lat/lon to address).

Expected Behaviour:

Ability to send address and get back latitude/longitude coordinate pair. This is required for load of posts sourced by FightPandemics (to assign coordinates from City, State, Country entered by data team) but likely other purposes as well.

**Comment by PriyalPatney** [comment]
I am working on this.

**Comment by joshmorel** [comment]
@Naraujo13 Do you think we still need this on the backend (or the geo-service at all) since all geocoding will be done on the front-end with Google Maps api before sending to the backend?

We should decide before @PriyalPatney gets too far with this one way or the other.

I can come up with some other solution for the import from airtable.

**Comment by Naraujo13** [comment]
> @Naraujo13 Do you think we still need this on the backend (or the geo-service at all) since all geocoding will be done on the front-end with Google Maps api before sending to the backend?
> 
> We should decide before @PriyalPatney gets too far with this one way or the other.
> 
> I can come up with some other solution for the import from airtable. 
Isn't the frontend currently using the reverse geocode endpoint of the python service to do that?

**Comment by joshmorel** [comment]
I'm personally not sure the best choice. Current we are using https://github.com/thampiman/reverse-geocoder to get country from lat/lon for a V1.1 feature. It's for offline use but hasn't been updated in awhile so how accurate is it for finer details? We should bring this discussion to Slack engineering.

**Comment by joshmorel** [comment]
Closing as created new issue with better outlined requirements #469
