### ISSUE TITLE
Create Post desktop modals before Create Post

### ISSUE THREAD

**Issue by limaneto** [FightPandemics/FightPandemics#405]
Create steps before displaying the Create Post Form

Refer to Figma section Post Creation:

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

**Comment by snowiesuet** [comment]
Now that we have both mobile & desktop design, we should focus on the responsive implementation instead of just desktop. Just something to keep in mind during implementation 😃
