### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#41]

**Comment by indirabhowmick** [comment]
- Develop the Home Page UI

Refer to the Requirements Documentation in Notion:
https://www.notion.so/fightpandemics/Home-Page-a8730bc6d96d4d5bbdce9410fdb28f31

**Comment by luxumbra** [comment]
Hi @indirabhowmick I see that the mentioned Home Page UI (#41) ticket has been closed. Is there still a requirement for work on this? Also, I remember it being mentioned in one of the channels on Slack that there may be some more content added to the homepage. If that's the case, is there a document in Notion that covers this? Thanks :smile:

**Comment by nadinejuraschek** [comment]
see above :) Would love to know if this is completed or not as well

**Comment by indirabhowmick** [comment]
Here is the updated Requirement:
https://www.notion.so/fightpandemics/Home-Page-a8730bc6d96d4d5bbdce9410fdb28f31

I have created separate tickets in GitHub to create FootNote and add the contents on the Policy Pages which will be launched from Home Page.
https://github.com/FightPandemics/FightPandemics/issues/150
https://github.com/FightPandemics/FightPandemics/issues/149

**Comment by nadinejuraschek** [comment]
So should we close this issue?

**Comment by indirabhowmick** [comment]
@nadinejuraschek - Yes Please. Thanks
