### ISSUE TITLE
Hide the Twitter Login for desktop and mobile web UI's

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#412]
- [x] Enable feature flag to hide Twitter Login on the Login and Sign up Pages for both desktop and mobile web UI's - 
Designs have been updated in FIGMA

**Comment by robinv85** [comment]
Yea to keep it simple I've just added it in a comment, we don't have feature flags at the moment, we could add that later for 1.1 perhaps. MVP doesn't really need feature flags for now since we should all be working on the essential features.
