### ISSUE TITLE
Individual - Profile Completed Page - Frontend (Desktop and Mobile web UI)

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#423]
- [ ] Develop the front end for Complete Profile Page

- [ ] Designs should be pixel perfect, aligned with the design in FIGMA.
![image](https://user-images.githubusercontent.com/57240870/82575874-e2e21880-9b3d-11ea-9e6a-2894bd3c6db4.png)
![image](https://user-images.githubusercontent.com/57240870/82575981-0b6a1280-9b3e-11ea-9d6f-56b220d96ab2.png)

**Comment by Oluwadamilareolusakin** [comment]
Working on it!
