### ISSUE TITLE
[WEB] "Fight Pandemics" text and logo on the browser tab

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#428]
Hi Team,
the "Fight Pandemics" text on the browser tab should be corrected to "FightPandemics" in order to be consistent with the text within all pages,
Also the logo, should be set to the new one.
![image](https://user-images.githubusercontent.com/45389561/82606786-90414480-9baf-11ea-82ae-88a28a439df8.png)

Thanks,
Tiago

**Comment by stavares843** [comment]
title fixed here

https://github.com/FightPandemics/FightPandemics/pull/429

do you have the new logo?

**Comment by tiagocostasilva** [comment]
@stavares843  can you please check with @Yu Zhao where the logo is available please?

**Comment by stavares843** [comment]
reopen because still missing updating the logo

**Comment by tiagocostasilva** [comment]
@stavares843  it seems for me that this ok now, do you confirm?

**Comment by tiagocostasilva** [comment]
Issue is resolved.

**Comment by snowiesuet** [comment]
Updating the logo, it's not fixed yet

**Comment by tiagocostasilva** [comment]
@snowiesuet  is there something missing for the logo?

**Comment by robinv85** [comment]
@tiagocostasilva @snowiesuet this still has to be fixed?

**Comment by manualzuru** [comment]
@tiagocostasilva is in vacations for 1 more week. @ppagarawal can you help us here? We also need the meta tags! Andrea Ang and Sanchit Finished them.

**Comment by ppagarawal** [comment]
@robinv85 Please close this as the changes in this tickets have been made. I will raise another ticket for metatags
