### ISSUE TITLE
[WEB] Missing background color on Desktop

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#431]
Hi Team,
according to Figma there is missing a grey are surrounding the buttons on the main page as well as the text.

Current:
![image](https://user-images.githubusercontent.com/45389561/82608434-971d8680-9bb2-11ea-946a-0f1f833e4891.png)

Figma:
![image](https://user-images.githubusercontent.com/45389561/82608465-a56ba280-9bb2-11ea-9f5a-f9fe0a7ae3d6.png)

Can you please check and correct?

Thanks,
Tiago

**Comment by nadinejuraschek** [comment]
I've noticed this before, but I think the background color for all pages is meant to be grey for Desktop. And only the footer background color is white?

**Comment by tiagocostasilva** [comment]
Hi @nadinejuraschek , according to Figma yes, that´s it.

**Comment by nadinejuraschek** [comment]
@snowiesuet I fixed this issue with #473

**Comment by tiagocostasilva** [comment]
Hello Team, 
the grey are is completely de-aligned, can you please check?

I am testing this in Mozzilla.
![image](https://user-images.githubusercontent.com/45389561/83238115-df7a0d00-a18d-11ea-96be-6bd40861c006.png)

Also on the right side of the screen (not showing here) is not showing:
![image](https://user-images.githubusercontent.com/45389561/83238240-0c2e2480-a18e-11ea-9d99-54064108d68f.png)


Thanks,
Tiago

**Comment by tiagocostasilva** [comment]
@snowiesuet whats the status of the issue?
Now the design is different but not the correct one :S 
![image](https://user-images.githubusercontent.com/45389561/83571199-43e6f480-a51f-11ea-9a16-46db71a65a28.png)

**Comment by manualzuru** [comment]
Should we move this issue to Done? @tiagocostasilva @nadinejuraschek @snowiesuet

**Comment by nadinejuraschek** [comment]
I think so

**Comment by ppagarawal** [comment]
Hey @nadinejuraschek 
This is fixed and can be closed. Tiago/Snowie are not active at the moment. Please reach out to me for any clarifications.

**Comment by joshmorel** [comment]
Seems like it's done - closing
