### ISSUE TITLE
[WEB] Missing envelope icon on top right corner

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#432]
Hi Team,
envelope icon is missing on top right corner even logged out.

![image](https://user-images.githubusercontent.com/45389561/82609513-938aff00-9bb4-11ea-8f2e-d991b305972e.png)

The action of the envelope must be also implemented. Please contact @Yu Zhao.

Can you please correct?

Thanks,
Tiago

**Comment by omarzoghayyer** [comment]
@tiagocostasilva Im just waiting on the design team to finish the envelop icon.

**Comment by tiagocostasilva** [comment]
@omarzoghayyer do you have some news about the design ?

**Comment by omarzoghayyer** [comment]
@tiagocostasilva  I just finished it now. I still have one more question. Where is this envelop should link to?

**Comment by tiagocostasilva** [comment]
@omarzoghayyer we are checking that on https://fightpandemics.slack.com/archives/C01481306UA/p1590577875001000

**Comment by omarzoghayyer** [comment]
@tiagocostasilva I talked to @robin. These feed pages are still under progress.

**Comment by omarzoghayyer** [comment]
This issue has been addressed and fixed in this PR https://github.com/FightPandemics/FightPandemics/pull/489
