### ISSUE TITLE
Add missing fields to post endpoint.

### ISSUE THREAD

**Issue by silenceway** [FightPandemics/FightPandemics#437]
Please add to the GET /api/post these fields:
* liked (if logged in user liked the post).
* user avatar if the user has a photo and the full name to create a text avatar if the user doesn't have a picture.

**Comment by Naraujo13** [comment]
Hi @silenceway, 
Sure, I'll add the like and photo/avatar.

About the name, isn't that currently available through `post.author.name`, or did you mean something different?
