### ISSUE TITLE
[Mobile] Correct 2 scenarios when trying to save FP to home screen

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#442]
Hi Team,
i noticed that when i open FP (https://staging.fightpandemics.work/ ) on my mobile phone and i try i go to this menu and click on "Add to Home screen":
![image](https://user-images.githubusercontent.com/45389561/82709283-22148480-9c78-11ea-871c-7798a9eabc3f.png)

The following appears:
![image](https://user-images.githubusercontent.com/45389561/82709323-3eb0bc80-9c78-11ea-8358-305c1f9da493.png)

Can we change both the text and the icon to our favicon ?

Also, after adding to the home screen and trying to open the app from there, before our landing page i see a blank page with a text on the center saying "Create React App Sample". Difficult for me to capture this, but easily replicate following the steps here.
Can you also check it and correct it please ?

Thanks,
Tiago

**Comment by stavares843** [comment]
title fixed here

https://github.com/FightPandemics/FightPandemics/pull/443


> Also, after adding to the home screen and trying to open the app from there, before our landing page i see a blank page with a text on the center saying "Create React App Sample". Difficult for me to capture this, but easily replicate following the steps here.


instead of "Create React App Sample" what should it say?

**Comment by tiagocostasilva** [comment]
Waiting on some opinions from the community here: https://fightpandemics.slack.com/archives/C010QR5D4KY/p1590183606401800

**Comment by stavares843** [comment]
@TiagoaTavares any more suggestions there? should we just say ''Loading''?

**Comment by tiagocostasilva** [comment]
@tiagocostasilva  you mean? :D Just left a comment on the channel (same post) to get help from our rockstar designers

**Comment by tiagocostasilva** [comment]
Pending designer task to start : https://www.notion.so/fightpandemics/Loading-FP-logo-screen-before-the-app-1d444471f971472b9ca8a0ef41ef3c61

**Comment by stavares843** [comment]
edited

**Comment by tiagocostasilva** [comment]
@stavares843 the designs are on notion: https://www.notion.so/fightpandemics/Loading-FP-logo-screen-before-the-app-1d444471f971472b9ca8a0ef41ef3c61
Is there any use case where you can see this is useful ?

**Comment by stavares843** [comment]
still missing fixing the logo

**Comment by tiagocostasilva** [comment]
@stavares843 any update on this? :)

**Comment by stavares843** [comment]
still missing the logo

**Comment by tiagocostasilva** [comment]
You need the design of the logo?

**Comment by stavares843** [comment]
i mean, is still missing updating the logo but thats for someone to do, i don't have the ticket assigned

**Comment by robinv85** [comment]
Going to put this ticket back to "new" since it seems like it's not in progress

**Comment by kylejvh** [comment]
@tiagocostasilva This should be resolved by #974
