### ISSUE TITLE
[Desktop] Need Help Question 1 screen Back button design

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#456]
env: https://staging.fightpandemics.work/need-help

steps:
1. Select Need help 
2. Question 1 screen is open:
![Screen Shot 2020-05-24 at 18 00 12](https://user-images.githubusercontent.com/21987083/82758727-94a47200-9de8-11ea-89e6-f6b77a5c5fc6.png)

Back button according to Figma screen:
![Screen Shot 2020-05-24 at 18 00 26](https://user-images.githubusercontent.com/21987083/82758731-a259f780-9de8-11ea-9661-4c040f05883b.png)

**Comment by nadinejuraschek** [comment]
related to these issues: 
#[471](https://github.com/FightPandemics/FightPandemics/issues/471), 
#[473](https://github.com/FightPandemics/FightPandemics/issues/473)

**Comment by tiagocostasilva** [comment]
Just a doubt/correction, according to Figma the back button will stay down not on top left corner right? 
![image](https://user-images.githubusercontent.com/45389561/83333552-fce7cd80-a298-11ea-96cd-7ecd5b04feec.png)

**Comment by galeza** [comment]
Hi @tiagocostasilva @nadinejuraschek 

I think that this is a bug in the design figma/zeplin. All other screens have back button at the bottom.
Do we want to keep this issue open? Maybe it would be better to close it and add a comment/description in the Zeplin?

**Comment by ppagarawal** [comment]
@galeza @nadinejuraschek 
Tiago is unavailable. I think that this has been fixed to look much better. It will be good to close this ticket Galeza.

**Comment by galeza** [comment]
@ppagarawal 

Thank you! I'm closing this issue
