### ISSUE TITLE
[Desktop] Give Help Question 1 screen Back button design

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#457]
env: https://staging.fightpandemics.work/offer-help

Steps:
1. Selects Give Help
2. Question 1 screen is open
![Screen Shot 2020-05-24 at 18 05 02](https://user-images.githubusercontent.com/21987083/82758820-2d3af200-9de9-11ea-95f7-40f34b972ecf.png)

As per Figma design:
![Screen Shot 2020-05-24 at 18 05 17](https://user-images.githubusercontent.com/21987083/82758827-34620000-9de9-11ea-8890-ea9ff53ea93e.png)

**Comment by nadinejuraschek** [comment]
will be closed by this issue: 
#[473](https://github.com/FightPandemics/FightPandemics/issues/473)
