### ISSUE TITLE
[Desktop] Give Help - Question 3 screen

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#467]
env: https://staging.fightpandemics.work/offer-help#Step3

Steps:
1. Select Give Help
2. Go to the Question 3 screen
![Screen Shot 2020-05-25 at 14 51 29](https://user-images.githubusercontent.com/21987083/82814364-4b5f2b80-9e97-11ea-8dbd-b0ac7a8d8a7e.png)
 As per Figma design:
![Screen Shot 2020-05-25 at 14 51 40](https://user-images.githubusercontent.com/21987083/82814372-531ed000-9e97-11ea-9687-3f56a4f2e732.png)

**Comment by nadinejuraschek** [comment]
related to these issues: 
#[471](https://github.com/FightPandemics/FightPandemics/issues/471), 
#[473](https://github.com/FightPandemics/FightPandemics/issues/473)

**Comment by nadinejuraschek** [comment]
see slack: https://fightpandemics.slack.com/archives/C010P7A17V3/p1590605869106400

**Comment by nadinejuraschek** [comment]
@manualzuru @robinv85 Can this issue be closed? We decided on keeping the Submit button instead of changing it to a Next button right? Or did that change in the past two weeks (sorry I haven't been able to find a clear update on this on Slack)?

**Comment by galeza** [comment]
@nadinejuraschek 

We decide to have Submit button :)
I'm closing this issue.
