### ISSUE TITLE
[Web] Onboarding |Need Help| Design inconsistency with figma

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#471]
Hey Team,
We have some design inconsistencies with Figma. Can you please correct?

**Note:** This screens must be consistent with the screens from "Give help". Please pick both issues or align with whom is taking care of: https://github.com/FightPandemics/FightPandemics/issues/473

For "Medical" and "Other help" the designs are not consistent.

**Scenario 1**
1 . You go to https://staging.fightpandemics.work/ on desktop
2. Click on "Need Help"
3. you find this:
![image](https://user-images.githubusercontent.com/45389561/82844936-525b5d80-9eda-11ea-95d3-05dcfa3bb36c.png)

It is inconsistency with Figma
![image](https://user-images.githubusercontent.com/45389561/82844947-5e471f80-9eda-11ea-8dc4-6084ef920a31.png)
 
**Scenario 2**
4. If you click on "Medical" then you see also this screen:
![image](https://user-images.githubusercontent.com/45389561/82845418-63a56980-9edc-11ea-8897-716a3777fdb9.png)

This is different also from figma:
![image](https://user-images.githubusercontent.com/45389561/82845430-6f912b80-9edc-11ea-89cd-c44af9963944.png)

**Scenario 3**
"Other help menu sends to the wrong localization screen also"

**Scenario 4**
For the complete workflow, please check the 2 next screens on figma.

Thanks,
Tiago

**Comment by nadinejuraschek** [comment]
I'm working on #473. I fixed the buttons and footer positioning, but am having trouble overwriting ant-design for the inputs. Would love to collaborate with someone on this!

**Comment by nadinejuraschek** [comment]
I think some of these issues have been fixed already due to #473 being merged.

**Comment by tiagocostasilva** [comment]
Scenario 1 is **OK** and corrected in https://github.com/FightPandemics/FightPandemics/issues/456

Scenario 2 is still **NOK**
The buttons size/design in question 1 and 2 are not according to figma. 
The location screen seems the right one for giving help, but it is not the same menu here yet.

Scenario 3
Same as scenario 2
 
I would keep this open since i still see different scenarios on give and need help and this must be aligned.

**Comment by joshmorel** [comment]
We updated the location input so it's consistent across the app. The medical step 2 input is similar but not the same as the design screenshot above. We can iterate based on feedback later or update the design to match. I will close this one.
