### ISSUE TITLE
[Web] Onboarding |Give Help| Design inconsistency with figma

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#473]
Hello Team,
so we need your help to fix some screen inconsistencies with Figma.

**Note:** This screens must be consistent with the screens from "Need help". Please pick both issues or align with whom is taking care of: https://github.com/FightPandemics/FightPandemics/issues/471

**Scenario 1**
1 . You go to https://staging.fightpandemics.work/ on desktop
2. Click on "Give Help"

> The size of the buttons are not ok. 
> The back button is not ok also.
Please check Figma.

![image](https://user-images.githubusercontent.com/45389561/82845959-90f31700-9ede-11ea-91b9-350a16e02053.png)

**Scenario 2**
> The text should be darker
> The location box is not the same
> the "share my location" do not have the same colors or positioning
> The "Show me postings from anywhere" should be bellow the buttons
Please check the screen in figma.
![image](https://user-images.githubusercontent.com/45389561/82846396-95203400-9ee0-11ea-9357-c90f57a40523.png)

**Scenario 3**
The question 3 is screen do not match figma. 
>The box where you put the email
>The buttons
![image](https://user-images.githubusercontent.com/45389561/82846519-1e376b00-9ee1-11ea-9388-ef72b43ece73.png)

Can you please check?

Thanks,
Tiago

**Comment by nadinejuraschek** [comment]
@anniegiang I finally found the footnote positioning error! It was the wizard-container that had a huge margin

**Comment by galeza** [comment]
Hi,
There are several bugs related to this issue: #456 , #457 , #467 , #328

**Comment by anniegiang** [comment]
@nadinejuraschek  Wow nice catch!!! 💯
