### ISSUE TITLE
[WEB] Multiple Scroll bar issue

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#476]
Hey Team,

While performing few checks I came across a scrolling issue on the Homepage and onboarding pages
The screen shows up 2 scroll bars under a specific condition.

Steps to replicate:
1. Download a file on web and let the downloaded file be shown on the footer.
2. You will find multiple scroll bars on the homepage and onboarding pages. Please refer to the image attached.

![2 scroll bar issue](https://user-images.githubusercontent.com/6276256/82867300-38586400-9f48-11ea-8ce6-923ab74351ac.png)

The goal of the task is to go trough all the the screens in FP and identify:
Which screen need scrolling or not (create a sort of table with for other to consult also)
On the one screens that dont need and have scroll, correct them to be consistent all over the FP app.

Please note that this issue is related to but different from https://github.com/FightPandemics/FightPandemics/issues/474

**Comment by snowiesuet** [comment]
#304 related

**Comment by Joeu** [comment]
Based on the screenshot, seems like an overflow in the body when the visible space decreases. Maybe setting the overflow-y to hidden can solve this.
Assigning it to me.

**Comment by Joeu** [comment]
Not reproducible anymore. Closing this issue.

![Screenshot from 2020-06-30 11-14-09](https://user-images.githubusercontent.com/1004896/86136830-e82e6d80-bac2-11ea-9f38-3337d3da1c77.png)
