### ISSUE TITLE
[Desktop][Mobile]- Sign In/Up sign with section missing icon

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#482]
env: https://staging.fightpandemics.work/

Steps:
1. Open Sign In or Sign Up
2. Go to the Sign up with section/ Sign in with section
On Figma design there is one additional icon: Twitter. Do designers decided to remove Twitter icon?
Application:
![Screen Shot 2020-05-26 at 18 48 09](https://user-images.githubusercontent.com/21987083/82928152-1f6ca480-9f82-11ea-98eb-99dcc2517bcc.png)
Figma:
![Screen Shot 2020-05-26 at 18 52 20](https://user-images.githubusercontent.com/21987083/82928164-2398c200-9f82-11ea-8ccb-7b0eac066088.png)

**Comment by robinv85** [comment]
Just fixed #412 recently to hide it for MVP since it doesn't have email and it will require an extra step for users to provide their email but that will be for a later version.

**Comment by manualzuru** [comment]
@galeza for MVP we decided to remove the twitter Icon as we don't have a clear way of getting their email.

**Comment by galeza** [comment]
Thank you for your comments!
