### ISSUE TITLE
[Desktop] [Mobile] Feed screen | Filter section Location not as in Figma design

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#483]
env: https://staging.fightpandemics.work/feed
Steps:
1. Open Feed screen
2. Go to Filters -> Location
3. In the search box we have a wrong tooltip, wrong search icon
4. Arrow is different then the design
5. Share My Location text has a different size/font
Application:
![Screen Shot 2020-05-26 at 21 13 55](https://user-images.githubusercontent.com/21987083/82941047-00780d80-9f96-11ea-9821-c3b2fd8fc1d4.png)
Figma:
![Screen Shot 2020-05-26 at 21 14 05](https://user-images.githubusercontent.com/21987083/82941060-04a42b00-9f96-11ea-8a23-b05cf7874a71.png)

**Comment by omarzoghayyer** [comment]
Im waiting on the design team to for the new share my location logo.
<img width="325" alt="Screen Shot 2020-05-27 at 4 38 47 PM" src="https://user-images.githubusercontent.com/49251966/83082521-8b114900-a038-11ea-8121-462e5911dcfd.png">
