### ISSUE TITLE
[MOBILE] Delete a comment in a post

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#485]
Goal: To be able to delete a comment by a logged in User.

Delete a comment:
As a logged in user, I want to delete a comment so that I can remove it permanently

![image](https://user-images.githubusercontent.com/6276256/82940173-10054f80-9fb2-11ea-87ec-0b33faa92b82.png)

![image](https://user-images.githubusercontent.com/6276256/82941464-0381f680-9fb4-11ea-8711-0bd5b920b269.png)

Acceptance criteria:
Only the original poster should be able to delete the comment in a post
The poster should be logged it to delete the comment
When the user clicks on delete, he is asked to confirm his action
The dialog box must appear on top of the existing screen 
If sub-comment exists then show the message [Deleted]

Please feel free to reach out to me in case you need any clarifications.

**Comment by indirabhowmick** [comment]
@ppagarawal - can you please include the mobile web requirements in the web ticket that you have created, since its just CSS styling change. We do not need separate tickets as discussed. This can then be closed

**Comment by ppagarawal** [comment]
Closing this issue as this has been merged with the web ticket #488
