### ISSUE TITLE
[WEB] [MOBILE] Edit a comment in a post

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#486]
**Goal**: To be able to edit a comment by a logged in User.

**Edit a comment**:
As a logged in user, I want to edit a comment so that I can rectify my spellings/errors/thoughts

Web:
![image](https://user-images.githubusercontent.com/6276256/82942190-38427d80-9fb5-11ea-8243-495c08ea00d1.png)

![image](https://user-images.githubusercontent.com/6276256/82942241-4bede400-9fb5-11ea-8059-c77acd32a5cd.png)

![image](https://user-images.githubusercontent.com/6276256/82942283-58723c80-9fb5-11ea-80ff-4d9d524c874c.png)

Mobile:
![image](https://user-images.githubusercontent.com/6276256/82940173-10054f80-9fb2-11ea-87ec-0b33faa92b82.png)

![image](https://user-images.githubusercontent.com/6276256/82940864-0af4d000-9fb3-11ea-9b54-89e10fb8eaa3.png)

**Acceptance Criteria:**
Only the original poster should be able to edit the comment in a post
The poster should be logged it to edit the comment
The time of update should be stored
When the user clicks on edit, he should be able to see the existing comment and modify it
The comment must accept the max number of characters.
Save button must update the comment
The user should be able to edit the comment any number of times
If a user has logged from multiple devices and editing the same comment, only the latest comment must be visible
Mobile specific: The keypad must appear and accept the max number of characters.
Send button from the keyboard must update the comment

Please feel free to reach out to me in case you need any clarifications.

**Comment by BMariscal** [comment]
depends on https://github.com/FightPandemics/FightPandemics/pull/378

**Comment by vikjoshi** [comment]
@BMariscal - #378 has been merged. Any other blockers for this issue?

**Comment by BMariscal** [comment]
No other blockers from what I can tell @vikjoshi I recently picked up this issue: https://github.com/FightPandemics/FightPandemics/issues/606 and will be spending time on it for the next few days. I'm going to remove myself as the assignee here but will pick it back up if it hasn't been picked up by someone else by Monday.

**Comment by vikjoshi** [comment]
Makes sense- thanks! 
CC: @ppagarawal
