### ISSUE TITLE
[WEB] [MOBILE] Delete a comment

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#488]
**Goal**: To be able to edit/delete a comment by a logged in User.

**Delete a comment**:
As a logged in user, I want to delete a comment so that I can remove it permanently
Web:

![image](https://user-images.githubusercontent.com/6276256/82942839-3dec9300-9fb6-11ea-8d53-1b8ca1340a6e.png)

![image](https://user-images.githubusercontent.com/6276256/82942878-4f359f80-9fb6-11ea-87ba-1b6621f17463.png)

Mobile:

![image](https://user-images.githubusercontent.com/6276256/82940173-10054f80-9fb2-11ea-87ec-0b33faa92b82.png)

![image](https://user-images.githubusercontent.com/6276256/82941464-0381f680-9fb4-11ea-8711-0bd5b920b269.png)

**Acceptance Criteria:**
Only the original poster should be able to delete the comment in a post
The poster should be logged it to delete the comment
When the user clicks on delete, he is asked to confirm his action
The dialog box must appear on top of the existing screen
If sub-comment exists then show the message [Deleted]
Keep button will not affect the comment and navigate the user back to the feed

Please feel free to reach out to me in case you need any clarifications.

**Comment by indirabhowmick** [comment]
@ppagarawal - can you please include the mobile web requirements in the same ticket, since its just CSS styling change. We do not need separate tickets as discussed.

**Comment by BMariscal** [comment]
depends on #378

**Comment by pthoma14** [comment]
@BMariscal - hey is this issue still open or can we close it?

**Comment by joshmorel** [comment]
Resolved by #859
