### ISSUE TITLE
[Mobile] Feed Page | Create new post as ind/organisation is half visible

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#495]
env: staging
MOBILE phone
Steps:
1. Open application and go to Feed page
2. Click + sign to add a new post
New window is open, half visible:
![Screenshot_2020-05-27-15-51-36-492_com android chrome](https://user-images.githubusercontent.com/21987083/83029900-7f6f5380-a033-11ea-999b-313945aa0d8a.jpg)

**Comment by gullwings13** [comment]
This seems to be fixed* in staging and the version I just pulled from github. Though now the desktop version of the buttons are gone. Trying to figure out what code was used for the buttons shown above.

**Comment by galeza** [comment]
@gullwings13 
I confirm it was solved:
![Screenshot_2020-05-29-20-28-45-488_com android chrome](https://user-images.githubusercontent.com/21987083/83293002-5e516300-a1eb-11ea-88ee-e3350ee31577.jpg)
I'm closing this issue.
