### ISSUE TITLE
User Profile - Front End

### ISSUE THREAD

**Issue by MohamedEl1** [FightPandemics/FightPandemics#50]
- [x] frontend user profile

**Comment by indirabhowmick** [comment]
Here is the Requirements for Create Individual Profile UI
https://www.notion.so/fightpandemics/Create-Individual-Profile-UI-cf719e2292874303a2ce943c912bdbf3

**Comment by CeesWang** [comment]
- Finished styling the user profile,
- created edit-profile / edit-account routes and components

wip
-   styling on edit-profile and edit-account components
-  handle data flow for my activity in user profile

**Comment by indirabhowmick** [comment]
@CeesWang - any updates on this issue?

**Comment by CeesWang** [comment]
@indirabhowmick talking to T-Allen regarding further progress.

**Comment by indirabhowmick** [comment]
@CeesWang Thanks for the update. Please keep us posted on the progress of the issue

**Comment by manualzuru** [comment]
@CeesWang @T-Allen is this solved?

**Comment by T-Allen** [comment]
@manualzuru is this the same as issue #176 ?

**Comment by manualzuru** [comment]
It is the same mobile and desktop only styling changes depending on the device @T-Allen

**Comment by T-Allen** [comment]
I'm still confused, because going by what's on Zeplin, the pages seem quite different:

[create-profile (desktop)](https://zpl.io/2EJWx6v)
[create-profile (mobile)](https://zpl.io/ang47mv)
[edit-profile (desktop)](https://zpl.io/bJJ4g99)
[edit-account-info (desktop)](https://zpl.io/VDJ91X3)

**Comment by indirabhowmick** [comment]
@T-Allen by Mobile we meant mobile web not the native mobile app. Please reach out if there are any questions.

**Comment by T-Allen** [comment]
@indirabhowmick Right, I am working on the web app.

**Comment by manualzuru** [comment]
@T-Allen you are right. Those are 2 different screens, you are right. We need both for having profile.

**Comment by robinv85** [comment]
Can we update this ticket or add another ticket and maybe tags to have a better view on the user profile status?
The user v2 data model is not implemented yet and I'm working on "create user" so I think both of these edit / view user aren't implemented with API yet?

**Comment by CeesWang** [comment]
No they are not implemented with API yet

**Comment by robinv85** [comment]
@CeesWang i'm working on this to finish some details and integrate with API

**Comment by CeesWang** [comment]
@robinv85 awesome let me know if theres anything I can do regarding this issue
