### ISSUE TITLE
[WEBAPP] Shadow with buttons

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#507]
Hello ,

The buttons in the webapp under question 1/3 shows up for 2 of the 3 buttons. The shadow must not be present as per the design

Figma design:
![image](https://user-images.githubusercontent.com/6276256/83174757-774d0c00-a138-11ea-8d5c-73a3f653c8fa.png)

Actual Image:
![image](https://user-images.githubusercontent.com/6276256/83174708-643a3c00-a138-11ea-839e-1358750d5b1f.png)

Steps to replicate:
1. Go to https://staging.fightpandemics.work/ on desktop
2. Click on "Give Help"
3. You will land on the page with the design isssue.

Please let me know if you need any clarifications

**Comment by omarzoghayyer** [comment]
@ppagarawal the issue doesn't seem to be there anymore. Take a look at my screenshot below.

<img width="829" alt="Screen Shot 2020-05-28 at 4 03 58 PM" src="https://user-images.githubusercontent.com/49251966/83202634-d8ef8500-a0fc-11ea-9205-938cd70a7796.png">

**Comment by ppagarawal** [comment]
Apparently, I still find it. Please find the screenshot below. Let me know if you need any system information to resolve this.

![image](https://user-images.githubusercontent.com/6276256/83228356-d1cf8200-a1a3-11ea-9ca6-9938b94acaa0.png)

**Comment by omarzoghayyer** [comment]
@ppagarawal  What browser do you use?

**Comment by ppagarawal** [comment]
@omarzoghayyer I am using Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nadinejuraschek** [comment]
@omarzoghayyer and @ppagarawal I'm using Google Chrome too but I don't see a shadow... There is also no box-shadow in the code for the buttons

**Comment by omarzoghayyer** [comment]
@ppagarawal perhaps you can use a different browser and see if the issue is still there?

**Comment by ppagarawal** [comment]
@omarzoghayyer I tried with internet explorer, however, the page did not load on it (may be due to outdated version). However, I found the same piece of shadow on the mobile web. Please see below

![image](https://user-images.githubusercontent.com/6276256/83292415-ac745f80-a207-11ea-8535-7cb4f0a35d1d.png)

Is that relatable?

**Comment by omarzoghayyer** [comment]
@ppagarawal thats odd. Thank you for trying.

**Comment by omarzoghayyer** [comment]
@nadinejuraschek Any idea why this might happen?

**Comment by nadinejuraschek** [comment]
@omarzoghayyer No, I tried it on multiple devices and in various browsers and never had the issue... I also don't see a box-shadow anywhere

**Comment by snowiesuet** [comment]
I'll look into this. I can see this on Windows Chrome.

**Comment by joshmorel** [comment]
I can't recreate on Firefox, Edge or Chrome. I'm going to close because there hasn't been an update for awhile and we should focus our efforts on other things.
