### ISSUE TITLE
[WEB] Text colour in a Post

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#519]
The text colour in an input text needs to be in sync with the design.
![image](https://user-images.githubusercontent.com/6276256/83230109-d2b5e300-a1a6-11ea-9afc-ea8f796275a0.png)

However, the current implementation uses some other colour. Please see the screenshot below
Sample text: Lorem Ipsum.
![image](https://user-images.githubusercontent.com/6276256/83229993-9d10fa00-a1a6-11ea-91c5-5663fd7a37dd.png)

This change needs to be for both the tabs, "Offering Help" and "Requesting Help"

Please reach out to me in case of questions.

**Comment by nadinejuraschek** [comment]
@snowiesuet @anniegiang I think the design we have here is outdated right? If it is, there would be no point in me changing the text color for an old design, we should just fix that when we redesign it
Just want to make sure, I'm not certain I found the right design for this

<img width="223" alt="Screen Shot 2020-05-29 at 10 05 22 AM" src="https://user-images.githubusercontent.com/53962732/83285896-ea37a080-a193-11ea-833f-2213c6da5747.png">

**Comment by snowiesuet** [comment]
@Yu-Alexa-Zhao can you confirm this please?

**Comment by Yu-Alexa-Zhao** [comment]
I just corrected the design bugs in the above mobile design. The text color for input text should be #282828, when there's no input text, the color is #939393.

![image](https://user-images.githubusercontent.com/44085699/83290177-3e527d00-a1b4-11ea-84e8-742223b583a3.png)

**Comment by anniegiang** [comment]
Yea I actually noticed the text color differences from the PR related this but it was taking a while fix revisions so I decided to merge it anyways to speed up progress
