### ISSUE TITLE
[WEB][MOBILE] Selecting the checkboxes

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#529]
Scenario:
Selecting the checkboxes leads to checking/unchecking of the option in Question 1/3 of "Give Help" page. However, selecting the button does not lead to checking/unchecking of the option.
It is required that the checks toggle when the user clicks on the buttons.

![image](https://user-images.githubusercontent.com/6276256/83322829-61defb80-a278-11ea-9ed7-361863570160.png)

![image](https://user-images.githubusercontent.com/6276256/83322842-7622f880-a278-11ea-8490-d0e18d352112.png)

Please reach out in case of questions

**Comment by BMariscal** [comment]
hello @ppagarawal. I'm working on this ticket and this gif shows my fix. I'd like to verify if this is the expected behavior: 

![gif](https://i.imgur.com/dAFdJVe.gif)  

Thanks!

**Comment by ppagarawal** [comment]
@BMariscal The ticket was to fix the area of the button that would 'check' the box. Instead of clicking on the tick box making a check on the option, if we can use the whole button to check the box, that'll be great. Please refer to the diagram to understand this
Current screen that enables a 'check; mark:
![image](https://user-images.githubusercontent.com/6276256/83406622-ae6b3800-a42c-11ea-9a7c-8a9e9f18ffb9.png)

Required state that enables a check mark:
![image](https://user-images.githubusercontent.com/6276256/83406700-d2c71480-a42c-11ea-9e9a-18d01d76dd0c.png)


The idea to have multiple select options is correct and should not be changed. 
Please refer to the gif to understand the issue.

![select](https://user-images.githubusercontent.com/6276256/83405412-0e141400-a42a-11ea-9c8b-f26324ca6635.gif)

**Comment by BMariscal** [comment]
Thanks @ppagarawal

**Comment by BMariscal** [comment]
PR here: https://github.com/FightPandemics/FightPandemics/pull/549
