### ISSUE TITLE
Envelope Icon not sending to Feeback Page

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#540]
Hi Team,
on the Home Page the envelope icon when clicked is sending to FEED instead of Feedback page, can you check it ?

![image](https://user-images.githubusercontent.com/45389561/83359146-3d664a80-a370-11ea-8d4a-98ae40dcce61.png)

Thanks,
Tiago

**Comment by omarzoghayyer** [comment]
@TiagoaTavares I think the feedpages aren't ready yet. It should eventually go to the pages below. Ill change it once they are done.
<img width="755" alt="Screen Shot 2020-05-31 at 3 34 49 PM" src="https://user-images.githubusercontent.com/49251966/83364185-4517f600-a354-11ea-8301-c8d81b818d5a.png">

**Comment by robinv85** [comment]
this is WIP on another branch

**Comment by tiagocostasilva** [comment]
Hello guys, just to follow-up on this. Which ID it is ?
