### ISSUE TITLE
Improve verify-email page content/layout

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#545]
I don't see any design for this but we need to improve both the layout and content

Currently it is:
 
![image](https://user-images.githubusercontent.com/10546720/83362728-84007880-a361-11ea-9b0f-27ba1a01f43a.png)

**Content:** Change `<h1>Please verify your email</h1>` to:

```html
<h1>Check your inbox</h1>
<p>We just emailed a link to {{ THE@EMAIL }}. Click the link to confirm your account and complete your profile. If you don't see a message within a few minutes please check your spam folder. </p>
```

**Layout:** Center the content horizontally and move the content down on the page so it starts ~25-30% from the top of the page.

**Comment by Yu-Alexa-Zhao** [comment]
Designer here! Few questions: (1) Is this issue for both mobile and desktop? , (2) we have a pop-up design for the mobile version but the content is different, should we change the content to what you have rn?
![Sign up-modal](https://user-images.githubusercontent.com/44085699/83434617-d0eb5a00-a408-11ea-9ecf-36ebb1e9c511.png)

**Comment by Yu-Alexa-Zhao** [comment]
This is a design for email-sign-up design (if it works I can export this to Zeplin). Do you have the "resend email" feature? If we do, I can add a button below and main paragraph
![sign-up-email-verify](https://user-images.githubusercontent.com/44085699/83435917-fc6f4400-a40a-11ea-84e8-49e42528f78e.png)

**Comment by manualzuru** [comment]
@Yu-Alexa-Zhao was this added to Zeplin?

**Comment by joshmorel** [comment]
@manualzuru  I'm pretty sure this can be worked on. We have the design except maybe for resend component - but someone can certainly start working on this.

**Comment by Yu-Alexa-Zhao** [comment]
Yes it was exported to zeplin:https://zpl.io/bJJMeDK

**Comment by rabbi08** [comment]
> I don't see any design for this but we need to improve both the layout and content
> 
> Currently it is:
> 
> ![image](https://user-images.githubusercontent.com/10546720/83362728-84007880-a361-11ea-9b0f-27ba1a01f43a.png)
> 
> **Content:** Change `<h1>Please verify your email</h1>` to:
> 
> ```
> <h1>Check your inbox</h1>
> <p>We just emailed a link to {{ THE@EMAIL }}. Click the link to confirm your account and complete your profile. If you don't see a message within a few minutes please check your spam folder. </p>
> ```
> 
> **Layout:** Center the content horizontally and move the content down on the page so it starts ~25-30% from the top of the page.

Also, Kindly make the FP logo clickable in this page, so that user can directly navigate to home page to login after the sign up.
