### ISSUE TITLE
Update comments API to allow replies.

### ISSUE THREAD

**Issue by silenceway** [FightPandemics/FightPandemics#551]
It depends on https://github.com/FightPandemics/FightPandemics/pull/378

**Comment by vikjoshi** [comment]
@silenceway , #378 has been merged. Are there any other blockers to being working on this?

**Comment by adisen** [comment]
This is like replying to comments right?

**Comment by vikjoshi** [comment]
@adisen , yes that's right

**Comment by adisen** [comment]
Okay.

**Comment by Naraujo13** [comment]
This was already implement in # as discussed in #672.

**Comment by robinv85** [comment]
Ok I think @silenceway wass working on this in the frontend, might have been a misunderstanding that this wasn't implemented yet...
