### ISSUE TITLE
Page transition scroll issue in onboarding

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#557]
When the user clicks on the next button on onboarding pages, he must be able to transition to the next page seamlessly. However, on clicking the next button, the user sees a scroll bar during transitioning. 

![scrollissue](https://user-images.githubusercontent.com/6276256/83564653-ac8f9a80-a53a-11ea-86d1-20bdee1b59f7.gif)

For a better experience, the scroll bar should not appear and the screen should remain static.

**Comment by CeesWang** [comment]
https://github.com/FightPandemics/FightPandemics/pull/558

**Comment by galeza** [comment]
Hi @CeesWang 
If this issue was fixed in this PR: fixed bug by adding overflow-x and y to hidden #558, could we close this issue?
