### ISSUE TITLE
Fix home navbar signed in view 

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#561]
@robinv85 mentioned this was working awhile ago but not anymore. Can someone get this fixed for both mobile and desktop?

**Mobile**
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed56445c6ac97228f5752dd
![image](https://user-images.githubusercontent.com/10546720/83635882-f98f6300-a572-11ea-81c4-1c3c9e7778e3.png)

**Important:** Exclude "Health Facilities" and "Symptom Check" links for now MVP (will add later post-MVP)

**Desktop**:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed034aa6f722bba0e0e6db2
![image](https://user-images.githubusercontent.com/10546720/83636579-3019ad80-a574-11ea-9d3d-2585952b25de.png)

~~Note: There is some inconsistencies with design for Desktop I will follow up with designers in Slack.~~ (addressed use one above)

**Comment by agmaal1** [comment]
Some doubts:
What is the "+add new one button" expected to do? 
What route "feedback" points to?
