### ISSUE TITLE
Fixing the position on buttons on landing pages

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#562]
The position of the "Next" and "Back" buttons on onboarding pages seem to change with the change when transitioning from step to another. This position needs to be the same throughout. Please refer to the GIF below.

![nextandbackbutton](https://user-images.githubusercontent.com/6276256/83643796-1ad16d00-a5ce-11ea-838b-7bcb63a18390.gif)

Let me know of questions.

**Comment by Joeu** [comment]
> @Joeu Please make sure that the button colours are consistent and blue as in the design

They are, @ppagarawal . Probably the extension that I used to capture the gif tweaked the colors.
