### ISSUE TITLE
[Mobile] Home Page | incorrect Need Help, Give Help | no corners

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#564]
env: staging

Steps:
1. Open app on mobile phone
2. There are no corners for Need Help, Give Help - please see screenshot

![Screenshot_2020-06-03-19-00-31-592_com android chrome](https://user-images.githubusercontent.com/21987083/83666466-4738b980-a5cd-11ea-84f8-33fc22e9c6b0.jpg)

**Comment by Joeu** [comment]
Fixed with this [PR](https://github.com/FightPandemics/FightPandemics/pull/650)
