### ISSUE TITLE
Make log level configurable/Set up Papertrail

### ISSUE THREAD

**Issue by robinv85** [FightPandemics/FightPandemics#571]
The backend uses the built-in logger from Fastify which is Pino and by default uses "info" level.
It should be possible to change this configuration, so you can change, for example for debugging the application locally. 
It could also be nice to use a logfile locally for better debugging, both are configurable in fastify which is documented [here](https://github.com/fastify/fastify/blob/master/docs/Logging.md).
On deployed environments we also don't want to log everything so it's best to only log WARN and ERROR messages so they can be monitored and if needed handled appropriately.

**Comment by mannykary** [comment]
@robinv85 I'm working on adding Papertrail, so I can take care of this.
