### ISSUE TITLE
Add route to update IndividualUser

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#575]
We are missing update on `backend/endpoints/posts.js`.

Once this is implemented we can start troubleshoot this issue #574

**Comment by adisen** [comment]
Quick question: Is the update individual route supposed to be in the backend/endpoints/posts.js file?

**Comment by BMariscal** [comment]
I don't remember unassigning you @robinv85  or even seeing this ticket D: Sorry!!!
