### ISSUE TITLE
Hide "Covid-info for MVP

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#576]
Hello Team,
"Covid-info" must be hidded since it wont be used for MVP. Can you do it please ?

![image](https://user-images.githubusercontent.com/45389561/83694934-05216f00-a5f1-11ea-955f-b412ea059cc1.png)

Thanks,
Tiago

**Comment by galeza** [comment]
Hi @stavares843 Need one more review to merge PR #578
