### ISSUE TITLE
Remove "Data Privacy" from mobile

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#577]
Hello Team,
can you remove "Data Privacy" from mobile because we already have it on the footer?

![image](https://user-images.githubusercontent.com/45389561/83695321-b6c0a000-a5f1-11ea-844b-e1beed2990a0.png)

Thanks,
Tiago

**Comment by galeza** [comment]
Hi @stavares843 need one more review to merge PR #579
