### ISSUE TITLE
fix border on create a post flow

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics#581]
flow
- go to https://staging.fightpandemics.work/
- do all the flow on need help section
- create a post
- appears like that

<img width="673" alt="Screenshot 2020-06-03 at 23 48 07" src="https://user-images.githubusercontent.com/29093946/83696532-980fd880-a5f4-11ea-946e-ec5878eae575.png">

Chrome

**Comment by idjevm** [comment]
This issue was solved with PR #608
