### ISSUE TITLE
Relink a dead link

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#594]
As a user when I click on "Show me postings" on the onboarding page, I should be redirected to the feed page. 

![showmelink](https://user-images.githubusercontent.com/6276256/83795640-5f880180-a6bd-11ea-956a-a8d1cdedd75f.gif)

Feed page link: https://staging.fightpandemics.work/feed

Please reach out in case of questions.

**Comment by galeza** [comment]
Merged
