### ISSUE TITLE
Back button flow from feed to onboarding 

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#599]
When a user clicks on back button after onboarding and landing on feed, he is redirected to a webpage with nearest hospitals, symptoms checker. need help page. 

Expected functionality:
Since, the user flow has to be bidirectional, he must land back on the onboarding pages and not land on the medicals page(nearest hospitals, symptoms checker. need help tabs) when the user clicks on back button of the browser.

![backbug](https://user-images.githubusercontent.com/6276256/83802775-00c88500-a6c9-11ea-908f-84736b1ff7b4.gif)

**Comment by pthoma14** [comment]
@ppagarawal we believe this is fixed now
