### ISSUE TITLE
[Desktop][Mobile] Create post dropdown options

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#605]
env: https://staging.fightpandemics.work/feed

Steps:
1. Go to Feed
2. Create new post
3. Section visibility. Currently we have:
![Screen Shot 2020-06-05 at 14 18 56](https://user-images.githubusercontent.com/21987083/83875565-9d297080-a737-11ea-8e68-8a453d6a4db8.png)

In figma design we have a different options dropdown:
![Screen Shot 2020-06-05 at 13 52 38](https://user-images.githubusercontent.com/21987083/83875602-ae727d00-a737-11ea-83e6-768a09b57bab.png)

@Yu-Alexa-Zhao In fact we have a text: **The post will be visible to** ... and then dropdown menu with the Figma design: **in my state**/country/zip code. (sounds incorrect) 
1. Should we change text or dropdown? 
2. Should we remove city option?
Zeplin: here we have city in the drop down:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed034d5050623b5f5fe5555

**Comment by Yu-Alexa-Zhao** [comment]
You are right about the data model being incorrect - I checked the data model again and thinks that the correct options should be "**in my neighborhood, in my city, in my country and worldwide**". 

I think we can **keep the dropdown design** for now maybe at the next iteration we can think of something more intuitive lol

**Comment by galeza** [comment]
Hi @Yu-Alexa-Zhao 

So we will have:
The post is visible  in my neighborhood (or **neighbourhood???**) | in my city | in my country | worldwide"

**Comment by joshmorel** [comment]
Hey there was executive decision to remove zip code but the designs weren't updated. We can add in my neighborhood much later (once we get user feedback post MVP) if it makes sense - but it might be too granular.

**Comment by galeza** [comment]
Hi @joshmorel,

For now I'm closing #523 and #605
