### ISSUE TITLE
[Desktop][Mobile] Need help | Question 3 screen | submit button is disabled

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#615]
env: https://staging.fightpandemics.work/need-help#Step3

1. Go to Need Help Question 3 screen
2. Press Submit button
3. Button is disabled. Feed screen is not open

![Screen Shot 2020-06-06 at 18 13 59](https://user-images.githubusercontent.com/21987083/83949075-18ffe780-a822-11ea-8a6c-f87e0d149501.png)
 
and with my email:
![Screen Shot 2020-06-06 at 18 35 21](https://user-images.githubusercontent.com/21987083/83949569-e0add880-a824-11ea-9c67-9e1fc23356de.jpg)

**Comment by joshmorel** [comment]
@robinv85 though you were working on getting this step wizard refactored/working (offer-help/need-help)?  Is this work in progress?

**Comment by robinv85** [comment]
@joshmorel I wasn't working on this, I did this couple of weeks ago, not sure if anyone is currently working on it. I recently just added email validation and realised that the requirements weren't clear regarding 
- is email required to submit?
- what do we do with the data?

**Comment by galeza** [comment]
Hi @robinv85 I'm reassigning this issue to PMs to get answers to your questions.

**Comment by galeza** [comment]
Hi @ppagarawal @tiagocostasilva 

We have questions about submit button on Need Help (on question 3 screen) and also Give Help  (on question 3 screen):

- is email required to submit?
- what do we do with the data?

**Comment by ppagarawal** [comment]
@manualzuru @Yu-Alexa-Zhao Can you please help answer these questions?

**Comment by galeza** [comment]
Button submit is also disabled on Give Help Question 3 screen

**Comment by Yu-Alexa-Zhao** [comment]
I think users are able to skip the third step in the process. The button is disabled until the user enters a valid email address to continue. 
![image](https://user-images.githubusercontent.com/44085699/84185677-5dc39280-aa5d-11ea-9f9c-2617a61a239f.png)

**Comment by ppagarawal** [comment]
@Yu-Alexa-Zhao Do we need to store this data?

**Comment by Yu-Alexa-Zhao** [comment]
I think @manualzuru can better answer this question. The back story for this feature is for markets to gather users' email to send them promotions even if they are not registered with us. 
So I gather it depends on the marketing team if they are planning to utilize user email. 
1) If marketers have a plan to use user emails, then there is a need to store this data
2) If they don't for have a plan in terms of how to use the email address, then I would say there is no need in having this feature in the soft launch?

**Comment by ppagarawal** [comment]
@manualzuru In that case, I believe that it will be good to inform the users that their email is being captured for marketing mails. The current screen does not convey that. Please let me know the purpose so that we can proceed accordingly.

**Comment by idjevm** [comment]
Ohh, I understand now, so as of now there is no really any usage of the submit button. 🤔 commenting here to follow what we would decide to do with the user data.

**Comment by ppagarawal** [comment]
@idjevm Can we close this as this has been merged?

**Comment by idjevm** [comment]
Yeah I will close this one up as it will get resolved once we merge #731 as we have decided what to do with the data atm.
