### ISSUE TITLE
Create FAQ page to be accessed from the footer

### ISSUE THREAD

**Issue by tiagocostasilva** [FightPandemics/FightPandemics#616]
Hello Team,
We need to create a page for FAQ do add on the footer. 
Can you please align with Andrea Steves to get which info will exist there ?

This issue is related with https://github.com/FightPandemics/FightPandemics/issues/541.
 
Thanks,
Tiago

**Comment by idjevm** [comment]
Is there a specific design for the FAQ page?

**Comment by tiagocostasilva** [comment]
I would risk to say that for MVP we could do something simple like the other privacy pages that are on the footer: https://staging.fightpandemics.work/terms-conditions . Only if Andrea has some specific need.

**Comment by idjevm** [comment]
Sweet, I will get a PR right now for this one, I guess I will add a few FAQs there so we can at least have something and worry about the design later.

**Comment by nadinejuraschek** [comment]
This issue can be closed right? @idjevm @tiagocostasilva

**Comment by idjevm** [comment]
Hey @nadinejuraschek, let's leave it open for now. As we still need to make more updates to the FAQ page.

**Comment by idjevm** [comment]
@tiagocostasilva I have pushed a new version of the FAQ page, and have some thoughts of what else I can do to make it more user friendly. Please pass along the designers the word to review -> https://staging.fightpandemics.work/faq

I have to deploy the changes to staging though, looks like the latest changes are not in staging yet.

**Comment by tiagocostasilva** [comment]
@ppagarawal can you please follow-up here? @idjevm are the all the changes done already? I saw the faq page still has some missing questions:
![imagem](https://user-images.githubusercontent.com/45389561/84078133-4a1e1a80-a9d0-11ea-8c57-5485cbc8d362.png)

But regarding the design, i think you did a great job on it ;)

**Comment by idjevm** [comment]
Marking this issue as done as it has been already merged and resolved.
