### ISSUE TITLE
Geolocation page is different for giving and offering help

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#619]
The geolocation page (onboarding step 2/3) for giving and offering help is different.
It is recommended to streamline the two pages and have the Give help standard (with location dropdown) for both the onboarding flow 

Need help:
![image](https://user-images.githubusercontent.com/6276256/83954571-fc869e00-a867-11ea-9cab-761725ccc4da.png)

Give Help:
![image](https://user-images.githubusercontent.com/6276256/83954588-2770f200-a868-11ea-9bcf-1a6d3dd15967.png)

**Comment by omarzoghayyer** [comment]
@ppagarawal Are you asking that you need to have `Needs help page Step 2/3 ` to be same as Give Help Page?

**Comment by ppagarawal** [comment]
That's right @omarzoghayyer . @joshmorel please take a note here.

**Comment by joshmorel** [comment]
I'll fix this with other geolocation integrations. FYI we discussed in #mvp_posts and for now the search input & dropdown will be the same as for create/update profile address. So it will look a little different. This is to reduce effort given timelines. After soft launch or MVP we can correct or more ideally come up with a consistent design for a single location/address search component.

**Comment by pthoma14** [comment]
@joshmorel if this UI fix can be fixed up for the MVP launch. Can we remove the soft launch tag "MVP-Critical" from this issue and keep the "MVP - Release 1" tag?
