### ISSUE TITLE
[Desktop][Mobile] Create Profile | select address from drop down

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#629]
env: https://staging.fightpandemics.work/create-profile

Steps:
As PR with dummy location was merged (#617 ) I wanted to create profile for a new user 
1. Go to Sign Up screen - then confirm email
2. Go to the Login screen, enter email, password. You are redirected to the Create User profile screen
3. In the address field we see dummy location: New York
4. I wanted to select this loc from dropdown menu and click Create Profile button -> location is not shown in the address field and button is disabled. 
I ha to write address manually. Should it work like this currently?
![Screen Shot 2020-06-07 at 13 44 46](https://user-images.githubusercontent.com/21987083/83968186-a1849380-a8c7-11ea-9e2d-91175ad3c513.png)

**Comment by robinv85** [comment]
@galeza this shouldn't be reported as a bug yet since the location hasn't been implemented yet

**Comment by galeza** [comment]
Ok, so I'm closing this issue.
