### ISSUE TITLE
Recover Password UI

### ISSUE THREAD

**Issue by indirabhowmick** [FightPandemics/FightPandemics#63]
- [ ] Develop the UI

Detailed Requirements in Notion
https://www.notion.so/fightpandemics/Recover-Password-UI-87b6fce7cffb4f5c823d5b81234cb3c3

**Comment by markthien** [comment]
created pull request for this

**Comment by indirabhowmick** [comment]
Thanks so much!

**Comment by indirabhowmick** [comment]
@markthien Please refer to the latest UI design in FIGMA:
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=11%3A2.

I have moved the ticket to In Progress Column

**Comment by indirabhowmick** [comment]
@markthien 

- [ ] Can you please include the styling updates for Desktop also in the same PR? 

Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ] Designs need to be pixel perfect

**Comment by indirabhowmick** [comment]
@markthien any updates on this issue?

**Comment by joshmorel** [comment]
@indirabhowmick I'm going to take over this work. @robinv85 I'm referencing the work done so far as a starting point but it's only front-end. This PR should include back-end and should be [this Auth0 endpoint](https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change), correct? (there is [another change password endpoint](https://auth0.com/docs/api/authentication#change-password) but it's for a different setup than ours I'm pretty sure).

**Comment by indirabhowmick** [comment]
@joshmorel - Thanks so much.

**Comment by indirabhowmick** [comment]
@joshmorel - Please confirm if both the mobile web and desktop web UI's will be covered under the same ticket.

**Comment by joshmorel** [comment]
@indirabhowmick Yes I would complete both mobile web and desktop web in same ticket. I'm going to look into dependencies (mostly around Auth0 tenancy stuff) and then make an effort estimate for our MVP launch check list.

**Comment by robinv85** [comment]
Hey @joshmorel sorry for the late reply, seems like I've missed this mention among lots of updates, I think this ticket was actually mostly about the frontend, which has an open PR with changes requested... for the backend we should probably add that in our `/auth` endpoints similar to the login and signup routes, and indeed using one of those endpionts that you've mentioned... at first sight I'd say the first one, not sure if we currently store the Auth0 user_id in our database by the way, just in case we need that, might need to update this when creating users in our database as well.

**Comment by joshmorel** [comment]
Closing in favor of #649. We do need to start from scratch and it is good to have visibility at the top
