### ISSUE TITLE
Login via FB App Bug

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#632]
When testing E2E user login flow, if I use FB to sign up, it throws back the following error:
![image](https://user-images.githubusercontent.com/41554004/83976253-bfdd9580-a8ad-11ea-9ae3-765a9efcdff8.png)

**Comment by stavares843** [comment]
if on staging environment is using the facebook on development mode, your email needs to be added on facebook developer console to be able to work
