### ISSUE TITLE
Skip button in a post enable the control flow to originating page

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#636]
Current functionality:
On clicking the skip button the user is redirected to login page. 
Actual functionality:
It must redirect to the originating page ie the feed.

![image](https://user-images.githubusercontent.com/6276256/83977513-9a3ca480-a91e-11ea-8501-cd30858533ab.png)

**Comment by indirabhowmick** [comment]
@ppagarawal - Once the user has submitted the post, this is the modal window that should pop up.
![image](https://user-images.githubusercontent.com/57240870/84225904-34bef400-aa95-11ea-864d-df8799a664df.png)

On clicking on the skip button, success modal should disappear and the user should be able to see the Feed UI.

**Comment by idjevm** [comment]
@indirabhowmick @ppagarawal Hey guys, so I am thinking about this modal and was wondering if as for now we should have it just show a success message. Implementing the `complete profile` would require actually checking in the backend for this user profile and notifying the frontend that the user has not yet completed the profile, perhaps we could add a flag or something when the user doesn't finish completing their profile so we can identify incompleted profiles? @robinv85 what are your thoughts on this? I mean I think for the purpose of simplicity and for the MVP we should have this modal just show a success message. I am not sure though, but that's just a thought. 

I am not sure also what would be the definition of an uncompleted profile? does that mean that they are missing some info? social info? personal info?

**Comment by robinv85** [comment]
@idjevm @ppagarawal well this seems confusing to me, I see 2 different messages on the popup here:
- create profile
- complete profile

The first one is "creating a user" in mongodb, currently you get it back at `/login` but we could also make the extra request explicit to `/users/current` after login.

If "complete profile"  has another meaning and a separate screen (I just implemented the "edit profile" page) then we could set a flag on the user object but not sure if that makes sense? I think it's too much complexity.

**Comment by indirabhowmick** [comment]
@idjevm @ppagarawal @robinv85 - Usecase - Let's say a user is checking out the platform without Signing up or Logging in. On the Home Page, clicks on "View Community Postings", lands on the Feed Page. Then decides to create a post, the user will be redirected to the signup screen, after signing up, creating a profile, will be back on creating the post. Once the post has been created, the system will display a successful modal window.
![image](https://user-images.githubusercontent.com/57240870/84580996-6aaff100-ad91-11ea-96c5-72d9e2061d69.png)
When the user clicks on the Complete Profile, it will be redirected to the following page which @robinv85 has already created.
![image](https://user-images.githubusercontent.com/57240870/84581025-b2cf1380-ad91-11ea-8845-9c42760609a8.png)
When the user clicks on the skip button, the modal window will close and the user will be on the Feed Page. I hope was able to explain the functionality and help answer the questions. Thanks!

**Comment by ppagarawal** [comment]
@Gtstride Please let me know if you have all the information to proceed or need any clarification.

**Comment by jyclam** [comment]
@ppagarawal @idjevm 
Confirming what we discussed. The final requirements for this ticket with consideration for mvp delivery is to:
* remove create profile button
* re-route skip button to link to newly created post

**Comment by ppagarawal** [comment]
> @ppagarawal @idjevm
> Confirming what we discussed. The final requirements for this ticket with consideration for mvp delivery is to:
> 
> * remove create profile button
> * re-route skip button to link to newly created post

The first bullet is for a logged in user only

**Comment by jyclam** [comment]
@ppagarawal @idjevm 
Discussed off thread, non logged in user is redirected to main login / sign up page. Can revisit ux flow after mvp
