### ISSUE TITLE
Set-up Amazon SES for transactional emails

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#638]
Without a SendGrid pro account we need to switch to Amazon SES.

Emails will be from X@fightpandemics.com

**Comment by mannykary** [comment]
Followed instructions here, up until step 7: https://auth0.com/docs/email/providers#configure-amazon-ses

I set up Amazon SES, and submitted a support case to AWS to request our account be brought out of sandbox mode.

Once we have our production setup, we can add the AWS credentials in Auth0.

**Comment by mannykary** [comment]
We have been approved for production access for SES. I set up the AWS credentials in each of our Auth0 tenants, and sent test emails, which worked.

I have submitted another request to lease two dedicated IP addresses. This will boost our sender reputation, making it less likely for us to be blacklisted from email providers. The IP addresses will also be automatically warmed. But as far as this ticket goes, we can close this.
