### ISSUE TITLE
On the website, the location filter is not working. 

### ISSUE THREAD

**Issue by umerhassan** [FightPandemics/FightPandemics#641]
![image](https://user-images.githubusercontent.com/33638819/83990244-31493280-a906-11ea-8ca2-ab00c91d17da.png)

https://fightpandemics.com/feed

When clicking on the location: I am getting: [object Object] as seen in the screenshot attached.

**Comment by joshmorel** [comment]
Hi @umerhassan This I'll resolve with further work related to #649 .

**Comment by pthoma14** [comment]
Hi @joshmorel since #649 has been merged. Do you still want this issue open or would you like me to close it?

**Comment by joshmorel** [comment]
This one will be addressed with #679 which is more broadly addresses integration of all the feed filters (incl location) with the now ready backend. I'll close this one.
