### ISSUE TITLE
[Desktop][Mobile] Add post when user is sign in - pop up

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#646]
env: https://staging.fightpandemics.work/profile

**It's a question about flow when user is sign in and profile was created.**

Steps:
1. Go to Sign In page - log in. Your profile is already created.
2. Click Profile from navbar. You can see Profile page with all your information.
3. Click plus sign and add a post
4. Save post
5. You will see confirmation: Success and button "Create profile"

When my profile is created and I'm sign in why I'm redirected to Create profile?
I understand that it's useful when user is not sign in but what when profile was created?

![Screen Shot 2020-06-08 at 13 54 27](https://user-images.githubusercontent.com/21987083/84028443-022bd300-a991-11ea-9f5d-02b580ae00d7.png)

**Comment by galeza** [comment]
We need a confirmation popup for a logged in user

**Comment by MohamedEl1** [comment]
will it be better to change it to 'view profile' instead?

**Comment by ppagarawal** [comment]
This is being handled here:
https://github.com/FightPandemics/FightPandemics/issues/687

**Comment by galeza** [comment]
@ppagarawal @MohamedEl1 

I'm closing this issue
