### ISSUE TITLE
[Desktop][Mobile] persist login session after refresh

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#656]
env: https://staging.fightpandemics.work/

Steps:
1. Log in to app
2. Go to Profile page (See you email, account data)
3. Refresh page
4. Login screen is shown. User is logged off. 

Should add "keep me logged in" feature.

**Comment by robinv85** [comment]
@galeza following your description of the issue
is it ok if I rename the title to "persist login session after refresh" or something like that?
then we can look at a more advanced "keep me logged in" feature  later which is not only session after refresh, but can keep a logged in user later, also depending on token expiration time etc.

**Comment by galeza** [comment]
Hi @robinv85 

I'm changing the title of this issue to "[Desktop][Mobile] persist login session after refresh"
Should I add a new issue "[Desktop][Mobile] Add advanced "keep me logged in" feature" or sth like that? Just I want to keep track of this problem?

**Comment by robinv85** [comment]
@galeza maybe we should ask to product / designers if it should be added on the login page

**Comment by galeza** [comment]
@robinv85 
I'll ask product/designers.

**Comment by galeza** [comment]
@indirabhowmick @ppagarawal 

Are we going to implement an advanced "keep me logged in" feature. Some application have checkbox:  keep me logged in?
If yes, I'll create a separate issue for that.

**Comment by pthoma14** [comment]
Hi @galeza I think an advanced "keep me logged in" feature is a great idea!  I personally think for now though we should add it to our Product backlog on Notion to be discussed further. I'm not sure adding it as an issue right now is the best strategy as we're all laser-focused on launching our MVP-Critical features.

**Comment by indirabhowmick** [comment]
@galeza @robinv85 @ppagarawal - I like the idea of having a persist login session after a refresh. Like @ppagarawal mentioned - we can add to the product backlog and prioritize for later release. Thanks so much!

**Comment by manualzuru** [comment]
But let's eitherway keep them logged for softlaunch. For a later release we give them the option.

**Comment by joshmorel** [comment]
@galeza @manualzuru @indirabhowmick @pthoma14 This will be resolved with #732.

With regards to keeping them logged in - I set it for a week expiry for now. We can either ask them to keep them logged in (after browser close) or just do it for them. Because this isn't an app where, for example, you aren't moving funds around like a banking app, the later may be better. GitHub, as one example, does this but but if you want to do something destructive (like deleting a repo) requests your password.

**Comment by robinv85** [comment]
@joshmorel i think this should probably be aligned with token expiration time? 
And we don’t have refresh tokens configured yet either.
