### ISSUE TITLE
Dont show emergency num for mvp

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#667]
This seems to be only mobile related. We're not providing emergency numbers as part of MVP s let's not show this for now. 

![Screenshot_20200609-224311_Samsung Internet](https://user-images.githubusercontent.com/10546720/84221407-27106b00-aaa3-11ea-9bc5-c8dbfe70b7d3.jpg)

**Comment by omarzoghayyer** [comment]
@joshmorel I just uncommented it, so that its easier to get it back to normal once we decided to show it.
