### ISSUE TITLE
Navigation buttons overlay adjustments on mobile UI

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#671]
Issue:
The user faces trouble during navigation in onboarding due to partial visibility/non-visibility of the buttons.

Current visual:
The mobile UI of the onboarding pages has next and back buttons which gets behind the visuals.

Expected visual
The next and back buttons in the UI must go in front of the visuals.

![image](https://user-images.githubusercontent.com/6276256/84241256-e0f7ed80-ab1c-11ea-9219-bb880c8a0667.png)

**Comment by Joeu** [comment]
The PR was merged, @ppagarawal , therefore I'm closing this issue.
