### ISSUE TITLE
[Web] Problems with editing account information/profile

### ISSUE THREAD

**Issue by LastedGuide** [FightPandemics/FightPandemics#673]
**Steps to recreate:** 

1. Create a new account
2. Go to you profile
3. Press the edit button (the pen icon)
4. Select _edit profile_ or _edit account information_
5. The page is blank and there is an error in the console
6. You may also notice that you were logged out of your account if you go back in your browser. 

![image](https://user-images.githubusercontent.com/20052500/84269637-78e2e080-aaf7-11ea-9f6f-15ac4d2e9d6c.png)

**What should happen:**

You should have the option to edit account or profile information.

Also, Instead of displaying a completely blank page, it may be a good idea to make a error page, and maybe even let the user submit the error.

**Comment by Gtstride** [comment]
I think, since we are sure, that since Robin is working on this, it can be assigned to him, so persons, would be well informed.

**Comment by robinv85** [comment]
@LastedGuide the feature is not implemented yet so I will close this ticket, I've been working on it and my PR is in draft at the moment if you want to check it and test it: #654
Please first check if there is already a ticket or work in progress before opening new issues
