### ISSUE TITLE
[Desktop][Mobile] Light blue border Need Help | Give Help buttons (LOW PRIORITY)

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#677]
env: https://staging.fightpandemics.work/

**THIS IS LOW PRIORITY**

Open home screen: Need Help, Give Help have light, blue borders:
![Screen Shot 2020-06-09 at 18 31 30](https://user-images.githubusercontent.com/21987083/84297082-45cb3c00-ab4d-11ea-96d1-c930204bc2e4.png)

**Comment by galeza** [comment]
Please refer also to the PR #289 

Tested 11 June:
![Screen Shot 2020-06-11 at 10 48 14](https://user-images.githubusercontent.com/21987083/84365329-95ebe200-abd1-11ea-9cfe-21c1eeaeb704.png)

**Comment by phuclb** [comment]
This is because of wrong color for border:
<a.am-button> uses rgb(66, 90, 242) while its pseudo (:before) uses #108ee9

Replace one by the other will fix the issue.
