### ISSUE TITLE
Post only the success message after posting

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#687]
As a logged in user, I would like to get a clear confirmation message that my post was successful

Current scenario:
I get a message to create my profile after my post is successful. Even when my profile is created and I am logged in. 

Expected behaviour:
Display only post successful message. Please ensure that this works for both organization and individual profiles.

![image](https://user-images.githubusercontent.com/6276256/84416060-50f79800-ac31-11ea-9bc6-0ee323cd6a0b.png)

**Comment by idjevm** [comment]
@Gtstride I think @Joeu  is working on this based on a few conversations that we had yesterday. 

Have you started on this one yet? or @Joeu did you not start this one yet? If not, then I guess it would be fine that Godstime has taken the issue.

**Comment by Gtstride** [comment]
Yes, i have, once i make a PR, this should be fixed.

**Comment by jyclam** [comment]
@ppagarawal @idjevm 

See #636 for updated requirements.

**Comment by ppagarawal** [comment]
@jyclam please make the size of view post a little smaller or enlarge the size of success by 3-4 pt. You should be good to go then.

**Comment by jyclam** [comment]
@ppagarawal done!
