### ISSUE TITLE
Transition from home page to onboarding pages (Nice to have)

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#689]
The flow of screen from the home page to onboarding is instant. The user needs to have a smooth experience while navigating.

Current behaviour:
![current](https://user-images.githubusercontent.com/6276256/84430676-adfe4880-ac47-11ea-96c2-156188ef99cd.gif)

Expected behaviour, transition has to be similar to below:
![expected](https://user-images.githubusercontent.com/6276256/84430832-e9991280-ac47-11ea-92d0-fee8b27efd99.gif)

**Comment by Joeu** [comment]
@ppagarawal , the animation should be applied for other pages transitions too?
