### ISSUE TITLE
Mobile Organization profile - Front end

### ISSUE THREAD

**Issue by MohamedEl1** [FightPandemics/FightPandemics#69]
- [ ] frontend organisation profile

**Comment by indirabhowmick** [comment]
Here is the Requirement for Create Org Profile UI
https://www.notion.so/fightpandemics/Create-Org-Profile-UI-d1438cad0cdb4ca09a9684366009fc8f

**Comment by manualzuru** [comment]
@indirabhowmick I believe this isn't the latest. We have changed some of the things, didn't we?

**Comment by indirabhowmick** [comment]
Please refer to the updated UI design from FIGMA:
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=775%3A538

**Comment by manualzuru** [comment]
@YehualashetGit isn't responsive so I'm putting this back to New.

**Comment by manualzuru** [comment]
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1806%3A13250

**Comment by manualzuru** [comment]
@alexjmcm do you have any update?

**Comment by indirabhowmick** [comment]
@MohamedEl1 - Can you please look into this? This is part of MVP. Back end has already been completed by @mannykary

**Comment by vikjoshi** [comment]
@MohamedEl1 @alexjmcm @indirabhowmick - can you confirm the pages on the front-end that would be created via this issue? I'm trying to figure out what this encompasses so I can determine if/what new issues need to be created. Thanks!

Pages to "Create Profile:
![image](https://user-images.githubusercontent.com/41554004/82165447-ef2e5300-9869-11ea-9108-a81fef7d0a7f.png)

Pages to Edit/Complete Profile
![image](https://user-images.githubusercontent.com/41554004/82165471-08cf9a80-986a-11ea-8d23-c54d4a2dd169.png)

There's also requirements around interactivity- e.g., clicking the pencil icon from the profile should open up a modal to either "Edit Account Information" or "Edit Profile".

**Comment by vikjoshi** [comment]
@alexjmcm or @anniegiang , could you tell me which screens we are enabling with the PR #399? I'm happy to test as well once the PR has been merged. I'm trying to figure out which other tickets I need to create for mobile based on what's in the Figma

**Comment by alexjmcm** [comment]
@vikjoshi With the PR #399  we are working on the create-profile screen similar to this:
![Capture 2](https://user-images.githubusercontent.com/23041987/82397220-eda58c00-9a1d-11ea-8bf9-92983265b19e.PNG)

**Comment by vikjoshi** [comment]
Thanks @alexjmcm . I also want to call out how an organizational user would access this page so we have the right paths built in. Organizational user would access this page: 

1. By clicking on "Edit Account Information" from the View Profile page- 
![image](https://user-images.githubusercontent.com/41554004/82503871-eed2c980-9aae-11ea-89f8-ff60eff18a5b.png)

2. When submitting a post as an organization- 
![image](https://user-images.githubusercontent.com/41554004/82505459-a5847900-9ab2-11ea-8972-d699c78744aa.png)
