### ISSUE TITLE
[Desktop] Need Help| Give Help | Question 1 screen | back button

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#695]
env: https://staging.fightpandemics.work/

1. Open Need Help|Give Help Question 1 screen 
2. Could we correct back button: have the same space between arrow and text like on the Question 2 screen:

Question 1 screen back button:
![Screen Shot 2020-06-12 at 13 29 21](https://user-images.githubusercontent.com/21987083/84498419-edad4a80-acb0-11ea-81f2-51d3c5f846b6.png)

Question 2 screen back button:
![Screen Shot 2020-06-12 at 13 29 27](https://user-images.githubusercontent.com/21987083/84498407-e9812d00-acb0-11ea-8b9e-3d11bc24b042.png)

**Comment by idjevm** [comment]
Hey @Joeu remember about this bug that I mentioned you? Now we have an issue for :)))

**Comment by Joeu** [comment]
A gif showing the result of my change:

![backButtonIssue](https://user-images.githubusercontent.com/1004896/84509295-df9fff80-ac99-11ea-8d6e-4058640ba478.gif)

**Comment by galeza** [comment]
@Joeu 

it looks good!
