### ISSUE TITLE
[Desktop] Feed | feed page after scrolling is emty

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#696]
env: https://staging.fightpandemics.work/feed

Steps: 
1. Open Feed
2. Scroll down to the bottom of the page (no more feeds to display)
3. Click Request help, then Offer Help , and All posts. Screen is empty.
Gif below: 

![Jun-12-2020 14-01-21](https://user-images.githubusercontent.com/21987083/84500704-5dbdcf80-acb5-11ea-85a7-0a3f4e475389.gif)

**Comment by idjevm** [comment]
So I took a look at this issue, and it looks that what happens that there are not more requests made to the server for posts once `skip` reaches 100; @robinv85 @joshmorel Should we reset the skip value to 0 or  what do you guys think a solution would be for this?

**Comment by doheekim93** [comment]
Hey @idjevm, do you know why the page bounces when the posts are loading? You can see it in the Gif above. It happens both on Desktop and Mobile.

**Comment by idjevm** [comment]
So based on what I understood by looking at the codebase, every time that you reach the end, this page makes an API call to get the next 5 posts, and it does so until the skip is 100; What do you think @robinv85 ? I am not sure if we could change this or perhaps use a debounce function or set timeout to allow the API to get those next 5 posts.

**Comment by silenceway** [comment]
This issue was reviewed and fixed in https://github.com/FightPandemics/FightPandemics/pull/720. Filters weren't implemented when this issue was created.
FYI @CeesWang and @robinv85

**Comment by idjevm** [comment]
True, we should close this issue for now. I checked and it is already resolved as mentioned by @silenceway. I do think that we should address what @doheekim93 mentioned though. Closing this for now and will open a new one to address the bouncing when the end is reached.
