### ISSUE TITLE
Share button (on posts) functionality not working - does not copy link

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#698]
env: [https://staging.fightpandemics.work/feed](url)

Expected: User clicks share button --> Link is copied to user's clipboard --> "Link copied!" dialog pops up

Current (Desktop): User clicks share button --> "Link copied!" dialog pops up
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66695502/84527787-2a267980-aca4-11ea-8526-a4b41c16763e.gif)

Current (Mobile): User clicks share button --> 
![Animated GIF-downsized](https://user-images.githubusercontent.com/66695502/84526373-cd768f00-aca2-11ea-883c-35a5d4b847b7.gif)

**Comment by kaydeejay** [comment]
I'm happy to try to fix this. I've recreated a simple implementation of react-copy-to-clipboard and done a little bit of debugging on the application. I estimate I could have it working by Monday 2020-06-22.

**Comment by joshmorel** [comment]
Hi @kaydeejay before you go to far I think this will also be resolved with pr @BMariscal is merging for related stuff #661
