### ISSUE TITLE
Sorting posts on feed based on location 

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#704]
Please follow the requirement for feed for posts sorting.
Business Rule: Land on the Feed without filter, and sorting by the location with the IP (nearest posts first)
This is applicable for landing from any page to the feed for all the users.

Acceptance criteria:
- [ ] The sorted feeds remain the same unless there are new posts from areas close by. 
- [ ] The order should not change while navigating from different pages to the feed or refreshing it.
- [ ] Any new post posted must show up on the feed

**Comment by joshmorel** [comment]
Hey @ppagarawal . Right now it should be sorting correctly if the user is authenticated and has a location. We are working on the feed filters (specify a location) but IP - there is another issue flagged as post MVP - #376 that's about this. So is this the same as 376 or something else and if the same as 376 is it v1.1 or MVP?

**Comment by ppagarawal** [comment]
Good catch @joshmorel . It is the same as 376.

**Comment by ppagarawal** [comment]
Closing as this is a duplicate issue
