### ISSUE TITLE
[Desktop][Mobile] Create post reset values

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#711]
env: https://staging.fightpandemics.work/feed

Steps:
1. Go to Feed
2. Add new post
3. Add post Title, text, tags and the visibility of the post
4. Click Request Help and then come back to Offering Help
5. All values were reset except post visibility. **Why we reset all values except visibility?**
![Screen Shot 2020-06-13 at 18 27 45](https://user-images.githubusercontent.com/21987083/84573911-a489f300-ada3-11ea-9c9f-3fdf6fae4840.png)
Second question: **Do we have a max size for text? Should we have it?**
User can drag and expand text area, no max set.

**Comment by Joeu** [comment]
Regarding the text area, what do you think about this approach below, @galeza ?

![createPostTextArea](https://user-images.githubusercontent.com/1004896/84897532-1bf9a400-b07c-11ea-8a4e-949cf1b32775.gif)

**Comment by galeza** [comment]
Hi @Joeu 
I like this approach. I would ask @manualzuru and @Yu-Alexa-Zhao about it.

**Comment by Yu-Alexa-Zhao** [comment]
I agree with you @Joeu here! Cleaning the tab value can be frustrating to users indeed

**Comment by Joeu** [comment]
So is it okay for me to proceed with the suggestion? @Yu-Alexa-Zhao , @galeza

**Comment by Joeu** [comment]
![formOfferRequestHelp](https://user-images.githubusercontent.com/1004896/84973195-e3e37700-b0f6-11ea-966c-c995b0694bd7.gif)
