### ISSUE TITLE
Images not showing up on Feed page

### ISSUE THREAD

**Issue by umerhassan** [FightPandemics/FightPandemics#712]
![image](https://user-images.githubusercontent.com/33638819/84575010-7be40800-ad67-11ea-834e-9ae4ed9bed3e.png)

Maybe add a default image if the image is not found.

**Comment by idjevm** [comment]
I think this is not an issue. As I mentioned on Zoom. You should be looking at https://staging.fightpandemics.com

Closing this issue as it is not an issue in staging.

**Comment by joshmorel** [comment]
For sourced by fightpandemics stuff, I got it fixed review/prod/staging (staging: https://staging.fightpandemics.work/feed not .com)

We should be storing this images in S3 so we have control and not rely on external urls but that is post launch issue (we should create an issue at least).

If they truly do not provide a photo we do have an alternate avatar based on initials:

![image](https://user-images.githubusercontent.com/10546720/84579642-64c00d00-ad9d-11ea-8c46-6b0fcc90eb1e.png)

**Comment by joshmorel** [comment]
I added an issue for v1.1 #715
