### ISSUE TITLE
Post text limit and "View More" functionality

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#713]
env: [https://staging.fightpandemics.work/feed](url)

**For signed in users**
Expected: The posts are limited to 25 words --> User clicks "View More" --> Post shows all text

Fix: 
- Limit posts to 25 words
- When "View More" is clicked --> expand post to show rest of text

**For users unregistered or not logged in**
Expected: The posts are limited to 25 words --> User clicks "View More" --> User is directed to sign up page

Fix: 
- When "View More" is clicked --> user is directed to sign up page

Issue seen in: Desktop and Mobile

**Comment by manualzuru** [comment]
@doheekim93 Actually we do need this. We just need to be consistent and only show 25 words right @Naraujo13?

**Comment by manualzuru** [comment]
The idea is to have consistency in how long the posts are.

**Comment by Naraujo13** [comment]
Not sure how it is done in the frontend but the `/posts` endpoint is limiting already based on wether the user is logged in or not.

If the user is logged the backend returns full content, otherwise it limits to 120 char (Twitter limit I think, we talked about this being easier to do a while agora @manualzuru).

**Comment by doheekim93** [comment]
From Figma:
<img width="334" alt="Screen Shot 2020-06-13 at 1 20 11 PM" src="https://user-images.githubusercontent.com/66695502/84576228-b013f480-ad78-11ea-81e0-e36343143e49.png">
I think this is why the text is not limited to 25 words for logged in users? Like @Naraujo13 said, the text IS limited for unregistered/not logged in users though, so we can make it consistent between all users if we want to.

**Comment by Naraujo13** [comment]
Not sure ai got that. You mean limiting for logged users also?

**Comment by doheekim93** [comment]
@manualzuru Do you want to limit text for logged in users as well?

**Comment by doheekim93** [comment]
@Naraujo13 Let's streamline it, so posts are always defaulted to 25 words regardless of whether the user is logged in or not. I will update the ticket!

**Comment by Naraujo13** [comment]
But defaulting to 25 words is against the requirements...

I'm not seeing the problem here.

Wouldn't it be:

If the user is not logged, he sees only 25 words, with no view more. This was what is said at the requirements, to direct them to signing up.

If he is logged he sees 25 words with the view more, being able to see the whole post.

Is that it @manualzuru ?

**Comment by Naraujo13** [comment]
Oh I see now the description @doheekim93, that is exactly what I thought. The backend already does that, we should add to the frontend to always show 25 words and the view more and then, based on wether the user is logged or not, we redirect him to sign-in/sign-up or expand the post

**Comment by manualzuru** [comment]
On the frontend we should have consistency that's for sure. So I'd say that yes we need to show X amount of characters always (they can click on view more).

**Comment by Naraujo13** [comment]
At the backend it is currently done by char

**Comment by idjevm** [comment]
@BMariscal isn't this also being taken care of by the big CRUD PR that is pending? Thought I saw this functionality on the demo video, we should assign it to you and link this issue on that PR

**Comment by doheekim93** [comment]
@idjevm Yes, I think that was taken care by the big CRUD PR. However, there are posts that are less than the char limit that shows "View More", like this post here:
<img width="980" alt="Screen Shot 2020-06-20 at 4 35 22 PM" src="https://user-images.githubusercontent.com/66695502/85212012-28982980-b314-11ea-8318-6122617c4991.png">

**Comment by BMariscal** [comment]
@doheekim93  Please take a look at these changes: https://streamable.com/pajksg 

Now the user can click on the div itself (the title and description section) to access the post's page and can share the post's link from the feed.

**Comment by doheekim93** [comment]
That looks so good!!! Definitely better UX this way. Thanks, @BMariscal!

**Comment by idjevm** [comment]
Since this functionality has already been implemented by @BMariscal, let's close this issue, and open any new issue to iterate and update if needed.
