### ISSUE TITLE
The View More in the Feed page is not clickable 

### ISSUE THREAD

**Issue by pokiza** [FightPandemics/FightPandemics#717]
Staging: 
https://staging.fightpandemics.work/feed

1.Go to Feed Page 
2.Try to click **View More** after any post..
3.Observe

**View More** hyperlink on the Feed page isn't enabled.

![FightPandemics](https://user-images.githubusercontent.com/55517631/84585075-cdc57600-add9-11ea-9fbc-3ba49cb654c7.png)

**Comment by idjevm** [comment]
This is a duplicate issue #713
