### ISSUE TITLE
Home Page Layout Cutoff 

### ISSUE THREAD

**Issue by pokiza** [FightPandemics/FightPandemics#722]
1)Go FightPandemic staging homepage
2)Minimize the screen to mobile layout
3)On the mobile layout click nav bar --> exit nav bar
4)Expand the layout to desktop layout 
5)Observe...

![FightPandemics_and_Slack_____testing___FightPandemics⚛️___1_new_item](https://user-images.githubusercontent.com/55517631/84705306-2eaf9400-af29-11ea-8021-8be3d630e6cc.png)

**Comment by joshmorel** [comment]
I've noticed the same thing @pokiza on Chrome (albeit not consistently), however not Firefox. Certainly I don't expect our users for the most part to open dev tools so low priority and also might be a browser bug (not ours) but might be a good issue for a new front end engineer to look into.

**Comment by kterry1** [comment]
@pokiza I tried to replicate this on Chrome and was unable to. Are you still seeing this? I'm curious it if it was fixed in a different PR.

**Comment by kterry1** [comment]
@joshmorel I'm unable to replicate this but I'm also on Chrome. Are you seeing this on Firefox? If not, I think we are alright to close this out.

**Comment by joshmorel** [comment]
@kterry1 same. I think there was some change to Chrome since June 15 that fixed this for us.  

Closing
