### ISSUE TITLE
Feed page bouncing every when loading more comments

### ISSUE THREAD

**Issue by idjevm** [FightPandemics/FightPandemics#726]
Sometimes when the user is scrolling the feeds page, you will notice that as it is loading more posts, there is some bouncing.

Ideally, we would want the feed page to stay stable and only show or not show that more posts are being loaded. 

I have attached the gif below, displaying the issue. Just part of the gif shows the problem. 

Tagging @doheekim93 as she pointed out this issue, feel free to edit this and add any comments or thoughts about this

![Screen Recording 2020-06-15 at 11 07 PM](https://user-images.githubusercontent.com/25408660/84727819-e78fc600-af5d-11ea-9d5f-24b053100daa.gif)

**Comment by BMariscal** [comment]
The infinite scroller is still jumping. This could be an option: https://github.com/danbovey/react-infinite-scroller

**Comment by joshmorel** [comment]
This seems like it was fixed when we merged this massive PR including the new Loader graphic - #661
