### ISSUE TITLE
Send onboarding email to marketing list

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#731]
If a non-logged in user provides their email during onboarding add them to the appropriate SendGrid list: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/index.html

**Comment by joshmorel** [comment]
We also need to send ancillary data - location, give-help vs need-help as well as question 1 answers:
![image](https://user-images.githubusercontent.com/10546720/84954777-0c9e4900-b0c4-11ea-98ef-208a31f5a0b2.png)

**Comment by silenceway** [comment]
@joshmorel Maybe we need to add a boolean to the SendGrid options, If somebody clones repository and SendGrid is not required, it will create errors or unnecessary flows.

**Comment by idjevm** [comment]
Reopening this since the only thing that has ben merged was the backend part.
