### ISSUE TITLE
Fix Filter Feed for Mobile

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#737]
@CeesWang because you worked on this and we got it working for desktop can you look into this issue for mobile.

* It seems like it's sending the API request to the backend with the right filter for location/provider/type but it's not updating the actual list.
* For need help/give help, it's not adding that to `objective` parameter correctly.  

![image](https://user-images.githubusercontent.com/10546720/84906487-ff5f6b00-b07f-11ea-914e-83e964fd1274.png)

**Comment by CeesWang** [comment]
https://github.com/FightPandemics/FightPandemics/pull/720
