### ISSUE TITLE
Integrating posts and Org profile

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#738]
The modal window displays 2 notion organization pages by default. These modal windows should 
- [x] check for existing organization
- [x] display all the existing organizations which user is a part of, if any
- [x] display the create an organization button (this is existing, do not change it)
- [x] changes need to be done for desktop and mobile
- [x] there should be no organization displayed by default (ex - the one displayed below in the gif should not be displayed)

![org](https://user-images.githubusercontent.com/6276256/84918084-cd7cf180-b0dd-11ea-955d-622a5a5bb873.gif)

**Comment by ppagarawal** [comment]
@MohamedEl1 Mohamed, are there any updates on this ticket?

**Comment by MohamedEl1** [comment]
> @MohamedEl1 Mohamed, are there any updates on this ticket?

Hi @ppagarawal i have been working on #752 lately so as soon as iam done i can start this unless there is an available engineer ready

**Comment by nr431207** [comment]
@ppagarawal just to clarify, we do NOT want the default notion organizations to show in the modal, and instead we want to see the existing organizations. If there is no organizations created, what do we want to see instead of the two default notions?

**Comment by ppagarawal** [comment]
@nr431207 We do not want the default notion organizations to show in the modal. The user wants to see the existing organizations. If he is not associated with any organization we give him an option to create one. If there are organizations created, we still provide him an option to create an org.

**Comment by nr431207** [comment]
@ppagarawal in the list of orgs that are going to show in the modal, are users supposed to see all the organizations that were created by others as well as the ones they create themselves or just the ones they own/create?

**Comment by ppagarawal** [comment]
> @ppagarawal in the list of orgs that are going to show in the modal, are users supposed to see all the organizations that were created by others as well as the ones they create themselves or just the ones they own/create? 

@nr431207 the user should see only the organizations he/she created. No other organization should be visible

**Comment by idjevm** [comment]
Resolved with #849! :) @nr431207 Thank youu!
