### ISSUE TITLE
Integrate onboarding answers w feed filter including geolocation

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#742]
Requirement:
- [ ] The posts in the feed should be sorted from near to far based on geolocation input from the left pane. 
- [ ] The resultant sorted order has to be consistent in the session unless the location has been changed by the user. 
- [ ] The results must also be consistent across devices
- [ ] Absence of geolocation data must result in all the posts in the feed
- [ ] The input values have to be persistent for a session

Please refer to the below mapping for filters and onboarding questions:
Offer help - Offering Help

As a Volunteer - Individual
As a Donor/Investor - Individual
As an Organisation - Startup, company, community, government, R&D, Non-profit, University, Health care provider, Other

Request help - Requesting Help

Medical - Medical Supplies
Other Help - All other options

Assumption:
The posts without the location data are considered to be worldwide and hence must come up on feed for all the location

**Comment by Naraujo13** [comment]
Isn't this already working?

When I implemented #204, the geo sorting was one of the implemented features. Later on @joshmorel implemented the location filter.

If I'm not mistaken, the implemented behavior is the following:
 
The posts are sorted by distance to the user, using the location at his profile. If the user uses the location filter, it overrides the location, sorting by distance to that point instead. As a last case, if the user is not logged, it defaults to sorting all posts by creation date.

About the assumption, I'm not sure I follow.
Is it possible to have a post without a location? 
Also, if there is no location, we can't calculate how far away the post is from the user to define its position on the feed, therefore it will probably be left at the end of the feed. 
The visibility worldwide means that it is shown to everyone, but doesn't account for the ranking/sorting.

**Comment by joshmorel** [comment]
By sending location captured at question 2 we should achieve the above through the onboarding flow.

By going through need-help flow we set objective=request

By going through offer-help flow we set objective=offer

The 1st question - this I think is just for our contact list. So can be added w email to send to SendGrid w issue #731
