### ISSUE TITLE
The GTM ID is the same on staging and production, needs to be changed

### ISSUE THREAD

**Issue by lelecanfora** [FightPandemics/FightPandemics#747]
Staging and production should have 2 separate Google Tag Manager IDs, the staging environment is for testing. Currently they both use the staging one.

Staging gtmId: GTM-TT348T3
Production gtmId: GTM-5N4PCVS

**Comment by lelecanfora** [comment]
@MohamedEl1 I saw you requested the initial pull, I could not find the latest change but it's fixed on the production website

**Comment by joshmorel** [comment]
This is resolved - closing
