### ISSUE TITLE
Profile Dropdown on Desktop 

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#752]
As a logged in user, I have no way to add an organization or view my org. profiles on Desktop. 

Current: 
As a user, if I am logged in on Desktop and click on Profile at the top right, I am taken to my User (Individual) Profile

Expected: 
As a user, if I am logged in on Desktop and click on Profile on the top right: 

1. Dropdown should pop up with the following options: 

- [x] a. My Profile--> Redirects you to the User (Individual) Profile
- [x] b. "Org" Profile--> Redirects you to the "View Org. Profile" page for any organizations you've associated with that user. They could have many orgs associated with them so each one needs to be listed out in the dropdown and should redirect you to that org's profile page
- [x] c. "Add Organization"- Redirects you to the "Create Org. Profile" page and lets you create a new organization profile. Once that organization has been created, it should then show up in the dropdown
- [x] d. Nice to Have: Logout button (currently in Desktop) it is in the top right menu but it would be nice to have it in this dropdown instead
![image](https://user-images.githubusercontent.com/41554004/85079350-79284f00-b17b-11ea-9ba9-dd9c1e11fa4b.png)

**Comment by vikjoshi** [comment]
@joshmorel and @robinv85 , created this ticket to address the profile nav button issue for org. profiles on desktop. 

Would it make sense to have @MohamedEl1 take this on?

**Comment by manualzuru** [comment]
@MohamedEl1 @vikjoshi should we put this in progress?

**Comment by vikjoshi** [comment]
@manualzuru , yes it should be. Just moved it
