### ISSUE TITLE
Liking/unliking posts API integration

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#761]
Will add details later...

**Comment by joshmorel** [comment]
Might be some backend changes required especially w GET posts/:id

**Comment by joshmorel** [comment]
K @silenceway @vikjoshi I think this is mostly done f/e wise but there are some changes needed on the b/e for GET posts/:id. Let me know if you need help with that

**Comment by manualzuru** [comment]
@silenceway @joshmorel should we put this on in progress?

**Comment by silenceway** [comment]
PR with frontend changes created.
@joshmorel In backend we need to receive liked and likesCount in /post/:postId as we receive it in /posts.
