### ISSUE TITLE
Email received during Sign Up (email valid...) is having 'Password change' instructions

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#771]
Currently the email validation send while new user sign up, is having the content related to password change request. 
<img width="836" alt="Screen Shot 2020-06-21 at 6 35 26 PM" src="https://user-images.githubusercontent.com/67168400/85236814-34a4e980-b3ef-11ea-9712-922617cbdd69.png">

The expected content for email validation should be like:

Please click the button to validate your account.
                 <Confirm my email> button.

**Comment by joshmorel** [comment]
I think this is fixed by changing Auth0 template but there is some other unexpected staging issue I need to look into.

**Comment by idjevm** [comment]
@joshmorel seems to be working fine on my end, are able to reproduce the issue @rabbi08  or it only happened once? 
![image](https://user-images.githubusercontent.com/25408660/85266517-f258c800-b441-11ea-8a93-eecea50c8e94.png)

**Comment by joshmorel** [comment]
@rabbi08 - Should be fixed please confirm and then close this issue.

**Comment by rabbi08** [comment]
Validate with new user account, It is working fine as shown in below screenshot.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/67168400/85325669-ff090a80-b499-11ea-8d43-679bb9fc5e75.png">
