### ISSUE TITLE
getServerToken error - Expired token received for JSON Web Token validation

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#773]
**Update from @joshmorel**:

Adding to this with technical details. It seems resolved now in staging (rebuild after merge?) but I saw this in papertrail relating to  https://github.com/FightPandemics/FightPandemics/blob/d66f9e6a3d402578711808a8b34a4cb605628ea2/backend/lib/plugins/auth.js#L97 used by email/password sign-up. I guess it still used the token in the cache which had expired - but the fp-staging tenant access token expiry  & cache TTL are both 24hours. Any ideas @mannykary @robinv85 why this might have occurred?

```
Jun 21 21:47:57 49635c5f4095 fp-backend-staging {"level":50,"time":1592801277545,"pid":18,"hostname":"49635c5f4095","reqId":1125,"message":"Expired token received for JSON Web Token validation","msg":"Error creating user","stack":"UnauthorizedError: Expired token received for JSON Web Token validation\n    at wrapError (/app/lib/components/Auth0.js:31:9)\n    at Object.createUser (/app/lib/components/Auth0.js:72:12)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","v":1}
```

---

**Original** :
---

My userid 'rabbi08@gmail.com' is not woking, following error is displayed:

Login failed, reason: Internal Server Error
<img width="815" alt="image" src="https://user-images.githubusercontent.com/67168400/85238136-d9c4bf80-b3f9-11ea-891b-53d40dd7ccc5.png">

I created this account directly at FP, yesterday and was working fine.
But today, I am able to login through google with same email but can't login directly in FP.

**Comment by idjevm** [comment]
@rabbi08 I tested this issues on staging and it seems to be working fine. @joshmorel I am able to sign up with new email and sign in fine, as well as signing in with a previously created account.
