### ISSUE TITLE
Back button from posts

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#775]
When a user clicks on the back button in a post detailed view, then he should be able to go back to the location in the feed where he came from so that the to and back navigation is complete.

Existing case:
There is no back button in the detailed post view

Expected scenario:
- [ ] A back button has to be visible to redirect the user to the exact location on the feed where he came from
- [ ] This button can be placed on bottom left of the post
- [ ] Should work both for mobile and desktop

![backbutton](https://user-images.githubusercontent.com/6276256/85268738-86ec1600-b494-11ea-81d7-f0b7b75227a0.gif)

**Comment by idjevm** [comment]
@ppagarawal is there any design? if not what would be the preference?

**Comment by idjevm** [comment]
@nr431207 perhaps you can work on this on next 😄 ?

**Comment by ppagarawal** [comment]
> @ppagarawal is there any design? if not what would be the preference?

There is no design for this yet. I recommend you to reuse the back button from the elements in onboarding pages. The back button from mobile can be used in mobile UI and the one in desktop be used on desktop UI.

**Comment by nr431207** [comment]
@ppagarawal does this look good for the desktop UI? 
<img width="653" alt="Screen Shot 2020-06-22 at 5 08 13 PM" src="https://user-images.githubusercontent.com/37174253/85346759-4fd52f00-b4ab-11ea-8a50-5d0f571e85d9.png">

**Comment by ppagarawal** [comment]
> @ppagarawal does this look good for the desktop UI? 
> <img width="653" alt="Screen Shot 2020-06-22 at 5 08 13 PM" src="https://user-images.githubusercontent.com/37174253/85346759-4fd52f00-b4ab-11ea-8a50-5d0f571e85d9.png">
> 

@nr431207 it'll be great if you can share a gif. That'll help me visualise the interaction

**Comment by nr431207** [comment]
@ppagarawal 
![FightPandemics](https://user-images.githubusercontent.com/37174253/85360978-7d33d400-b4cf-11ea-896d-49bb40a54db4.gif)

**Comment by ppagarawal** [comment]
Lgtm @nr431207

**Comment by idjevm** [comment]
@nr431207 It's better if you open a Draft PR, so that way we can see your changes and also there will be a BUILD URL that we can review the changes and ask you if there needs to be changes...

**Comment by idjevm** [comment]
Closing this as it was resolved with #788
