### ISSUE TITLE
[Mobile] Navbar on Feed screen not visible when screen opens

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#776]
env: staging

This is a question about Mobile Navigation bar on Feed screen.
Did we decided to make NavBar for feed screen invisible? 
When you open Feed screen Navigation bar is not visible. You have to scroll down to see.
Zeplin shows logo - navBar:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed565218587a93f917fdb89
Steps:
1. Open Feed screen
2. NavBar (with logo) is not visible
3. Scroll down to see logo
When you scroll up it's not visible

![Screenshot_2020-06-22-10-56-30-990_com android chrome](https://user-images.githubusercontent.com/21987083/85269900-d6bce400-b478-11ea-97bc-e73e22c9b37f.jpg)

**Comment by ppagarawal** [comment]
@galeza This has been closed via https://github.com/FightPandemics/FightPandemics/issues/764

**Comment by idjevm** [comment]
Closing this as it was resolved by @jyclam with #764

**Comment by idjevm** [comment]
Yes, now we just need to update if needed!
