### ISSUE TITLE
[Mobile] NeedHelp|GiveHelp Question3 screen

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#777]
env: staging

This is a question.

Steps:
1. Go to NeedHelp or GiveHelp Question3 screen.
Could we improve this screen for Mobile by adding eg. more space between a href Terms & Conditions and div Enter your email address?
For desktop it looks better, more separated. For mobile it's little clustered.

Mobile:
![Screenshot_2020-06-22-10-58-45-371_com android chrome](https://user-images.githubusercontent.com/21987083/85272437-75970f80-b47c-11ea-8338-63e91d1d3991.jpg)

Desktop:
![Screen Shot 2020-06-22 at 11 38 05](https://user-images.githubusercontent.com/21987083/85272763-e50cff00-b47c-11ea-891b-9376abb51092.png)

**Comment by ppagarawal** [comment]
@galeza Thanks for pointing this out. We can rectify this in future releases. Our main focus for the soft launch is to get the core functionalities working. Moreover, I think that it will be good to have the whole onboarding steps vertically centre aligned with proper spacing.

**Comment by ppagarawal** [comment]
@idjevm @rixiobarrios we can add more more spacing between elements for web as well
