### ISSUE TITLE
[Desktop][Mobile] NeedHelp|GiveHelp Question1 screen load time

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#779]
env: staging

Related to the #770 

Could we improve load time when opening Question 1 screen. 
Steps: Home screen -> NeedHelp|GiveHelp -> Question1 screen

Transitions from Question 1 ->2->3 screens are faster then transition Home -> Question 1

**Comment by idjevm** [comment]
This isssue has been resolved.
