### ISSUE TITLE
Auth0 user account linking (v1.1+)

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#781]
We don't allow duplicate emails so if someone tries to signup with a social account and the same email already registered under they get an error (see #772). 

Eventually we want to enable user account linking in such a case. Not critical - release v1.1 (or later). 

https://auth0.com/docs/users/concepts/overview-user-account-linking

**Comment by adisen** [comment]
Will I need access to auth0 to work on this?

**Comment by robvenn** [comment]
@adisen yes there is a setting for this on Auth0, so first need to enable on the dev environment and later also on the other environments, there is also a lot of documentation on Auth0 how that works, I looked at it before but then we didn't have the premium features yet so it was not supported in the free version. I think it should be possible to use their API for this, and we can show a custom page on our frontend and to go through our back-end to let the user confirm if they want to merge the login methods.

**Comment by adisen** [comment]
Yes Robin, similar to what is on eBay. A user get prompted, if when they want to signup with a social media account with the same email, to link the 2 accounts.

**Comment by tejasm2** [comment]
Hey @adisen @joshmorel @robinv85 , do we have an update on this issue?

**Comment by adisen** [comment]
Sorry I've been unable to implement this. Someone can pick it up

**Comment by joshmorel** [comment]
No problem @adisen. Thanks for giving us an update.

@tejasm2 : 

* we are going to just return an error for now when addressing issue #1437 if a user tries to sign up with same email
* I think we still want this - but likely put it on the back burner (i.e. low priority)

**Comment by manualzuru** [comment]
We should definitely be able to link the accounts Auth0 enables this quite easily. But let's put P3 maybe.

**Comment by ddveloper** [comment]
progress update: 
1. able to replicate Auth0's demo of accounts linking locally
2. able to reproduce #1226 phenomenon
3. applied user accounts detection code, got 403 error from Auth0  

Todo next:
* need access to Auth0 account, to update API rules

**Comment by ddveloper** [comment]
progress update:
1. 403 error was due to using a wrong token
2. Auth0 new function `getUsersWithSameEmail()` is completed and tested  

Todo next:
* finish integration of functions `linkAccount()` and `unlinkAccount()` + `mergeMetaData()`  

Questions:
> are we creating new endpoints for querying / linking / (unlinking)?
> if that's true, new endpoints purposal: `get /same-email-accounts`, `post /link-accounts`, (`post /unlink-accounts`)

Discussion:
* what if the user chooses not to link? how to differentiate those accounts then (email cannot be a single key)

**Comment by ddveloper** [comment]
just want to give an update:
slowing down due to another higher priority issue, and I am still working on this : )

**Comment by ddveloper** [comment]
draft PR #1727 has the code, it's doing an automatically linking right now, depends on the project design, we can fine-tune it.

**Comment by ddveloper** [comment]
the basic version is done, ready for review.
one note: not sure how we're going to QA this feature, will need Auth0 account delete to repeat tests.

**Comment by ddveloper** [comment]
the latest update, add dialog (learned from @Zaydme code : ) to remind the user 

![image](https://user-images.githubusercontent.com/44758313/99587761-691cd180-299e-11eb-9c33-5ebb493d443d.png)

**Comment by rabbi08** [comment]
@ddveloper @joshmorel 
Customers are observing this issue and reporting, can we prioritize this issue for this upcoming release on Dec 15?
Thanks

**Comment by joshmorel** [comment]
@rabbi08 see JV's comment here - https://github.com/FightPandemics/FightPandemics/pull/1727#issuecomment-736267702 . They want QA to test before merging to staging.

**Comment by rabbi08** [comment]
> @rabbi08 see JV's comment here - [#1727 (comment)](https://github.com/FightPandemics/FightPandemics/pull/1727#issuecomment-736267702) . They want QA to test before merging to staging.

great thanx @joshmorel for highlighting, this was missed from my side. will test.
