### ISSUE TITLE
Auth0 user should be logged off from all tabs

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#782]
env: staging

Steps:
1. Open staging in the first tab and log in. Go to profile screen
2. Open staging in the second tab. You are already logged in and you can open your Profile page. 
3. In the second tab click Logout
4. Go to the first tab
In the first tab Navigation bar shows Profile (it's for a logged in user). When you click Profile you'll see error: Failed loading profile, reason: No Authorization was found in request.cookies

I would expect that my user will be logged of in both tabs. And in the first tab I'll see Login, Register buttons.

Desktop:
![Screen Shot 2020-06-22 at 20 01 13](https://user-images.githubusercontent.com/21987083/85320795-f299a780-b4c3-11ea-8757-518817aac6dd.png)

**Comment by joshmorel** [comment]
Thanks @galeza. I guess we could run setInterval on `App.js` that checks the remember cookie every second or few seconds and if it's not there dispatches `AUTH_LOGOUT`. @robinv85 if you have another suggestion let me know. I'll start work on this later today.

**Comment by joshmorel** [comment]
I checked Facebook, LinkedIn & Amazon and none will log you out of the other tab with something like `setInterval` doesn't mean it's not a bad idea but dunno what the best practice is. Facebook does log you out after OG graph API call returns error (not sure if they are timed or random).

No matter, clicking a LoggedIn only page (like Profile in example) when the `remember` cookie is not present should redirect to home. I can at least add that and we can consider `setInterval` later.

**Comment by galeza** [comment]
Hi @joshmorel 

Ok, agree. So we can redirect user to Home screen or maybe Login screen?

**Comment by joshmorel** [comment]
@galeza That's okay I think the title is fine.

**Comment by tejasm2** [comment]
Hey @joshmorel should I add this to "done"?
