### ISSUE TITLE
user should be able to logged in using <enter> key also.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#787]
Steps to reproduce:

1. Open "https://staging.fightpandemics.work"
2. Click on 'Login'
3. Enter valid email/password used during SignUp
Press <enter>
You will observe nothing happen

So then. 4. Click on 'Sign In' button

User is successfully logged in.

Issue: User should be able to SIGN IN using <enter> key along with clicking on 'Sign In' key.
Please note that <enter> key does not work during sign ups too.

**Comment by idjevm** [comment]
Reopening this one @adisen since we would like maybe to find a way to do this without messing up the styled, let's continue the work on #937

**Comment by tejasm2** [comment]
Hey @rabbi08 , is this issue implemented already or still needs to be worked on?

**Comment by rabbi08** [comment]
> Hey @rabbi08 , is this issue implemented already or still needs to be worked on?

Yes this issue still exist and it should be fixed.

**Comment by adisen** [comment]
Yes. The PR has been since. No movement 
https://github.com/FightPandemics/FightPandemics/pull/937

**Comment by guvarallo** [comment]
Hey @adisen is there anyone working on this? If not I can do it.

**Comment by adisen** [comment]
@guvarallo No. I was supposed to work on it. But couldn't. So you can sure pick it up. 
Tag me in the PR when you have something

**Comment by rabbi08** [comment]
Verified in STG, working fine:
User is able to login using <enter> key, Refer below GIF
https://share.getcloudapp.com/2Nuj5K7E

User is able to 'Join Now' using <enter> key, Refer below GIF:
https://share.getcloudapp.com/2Nuj5KWg
