### ISSUE TITLE
Change the text in the buttons

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#792]
Please change the text on the buttons 
- [x] from 'give help' to 'offer help'
- [x] from ' need help' to 'request help'

![image](https://user-images.githubusercontent.com/6276256/85427291-30b4cb00-b599-11ea-81da-024b5e73781e.png)

**Comment by stavares843** [comment]
https://github.com/FightPandemics/FightPandemics/pull/793

**Comment by tejasm2** [comment]
I think this is implemented and should be closed? @ppagarawal @stavares843 @joshmorel ?
