### ISSUE TITLE
Unable to ADD social media links in my profile.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#795]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/password 
3. Click on 'Profile' -> 'EDIT Profile icon'
4. Click 'EDIT Profile'
5. Try to add your either Facebook/github/Linkedin/twitter link

Issue: You will observe that:
1. You will not be able to DELETE or EDIT the URL address already written in these social media URL test box.
2. Below error is displayed when user enter anything in text box
  "Invalid entry: only alphanumeric characters are allowed"

Please refer attached screenshot:
<img width="1105" alt="Screen Shot 2020-06-23 at 1 55 33 PM" src="https://user-images.githubusercontent.com/67168400/85440590-38a24a00-b55c-11ea-8466-27ef661b32c1.png">

**Comment by rabbi08** [comment]
<img width="920" alt="Screen Shot 2020-06-23 at 4 13 22 PM" src="https://user-images.githubusercontent.com/67168400/85457337-ecf89c00-b56d-11ea-8ffc-796f446a2f83.png">

**Comment by robinv85** [comment]
Hi @rabbi08 thanks for reporting, yeah for LinkedIn I couldn't find the exact validation rules, I thought it was alphanumeric based on my own profile and their description in the documentation for custom profile URL's states this:

> Your custom URL can have 5-30 letters or numbers. Don't use spaces, symbols, or special characters. 

But this is for custom URL's. so I suppose your example might be automatically generated, and also contains dashes.
So I will just adjust it to allow 5-30 alphanumeric characters and dashes.

**Comment by rabbi08** [comment]
Fix validated, I am able to append the social media links.
But if user by mistake enters <space> error is displayed, but that is low priority issue which can be addressed in next upcoming releases.
