### ISSUE TITLE
Cannot CHANGE profile logo 

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#797]
1. Open "https://staging.fightpandemics.work/"
2. Login using valid email/password
3. Click on 'Profile' -> edit profile icon
4. Click on 'EDIT PROFILE'
5. Click on 'Change' present in blue under profile logo present in the top right corner of the FP page.

Issue: You will observe that 'Change' is NOT clickable, hence user is not able to change their logo image which is AGAINST the option we are displaying. 

Please see the screenshot below.
<img width="792" alt="Screen Shot 2020-06-23 at 2 23 20 PM" src="https://user-images.githubusercontent.com/67168400/85443813-b0be3f00-b55f-11ea-8fc7-77ba65249e6c.png">

**Comment by joshmorel** [comment]
This will be added post soft launch. But I think we should hide "Change" text for now so initial users aren't confused.

**Comment by rabbi08** [comment]
Yeah that will quick solution to avoid confusion.

**Comment by joshmorel** [comment]
@rabbi08 I merged PR to hide "Change" text for now. Issue #715 is to implement to functionality.
