### ISSUE TITLE
[Desktop] User cannot post comments on the posts in the Feed Section as there is no post button available. Also user cannot access comment button directly from the post list.

### ISSUE THREAD

**Issue by gkjain82** [FightPandemics/FightPandemics#800]
Steps to Reproduce:
Open "https://staging.fightpandemics.work/"
Login using valid email/password
Click on 'Feed' -> Comment on any Post
The comment would not get posted as there is no post button available.

Expected Result:
Users should be able to post comments on any post.

Actual Result:
The user is not able to post comments on any post.

![Comment Bug](https://user-images.githubusercontent.com/62069057/85465175-790ec180-b576-11ea-9302-b9451fb84355.jpg)

**Comment by joshmorel** [comment]
Hi @gkjain82 this should be resolved with #769
