### ISSUE TITLE
Posts back button should be displayed regardless of View More being extended

### ISSUE THREAD

**Issue by idjevm** [FightPandemics/FightPandemics#804]
I believe the button should be always displayed. 

To reproduce, go to feed, click on view more, you will be redirected to the post's page, then click on view less, and the back button will disappear. 
Changes that need to be applied : 

- Center the back button
- Make sure the back button is visible at all times

Refer to the image below. 
![Screen Recording 2020-06-24 at 02 09 AM](https://user-images.githubusercontent.com/25408660/85507273-20fcad00-b5c0-11ea-9f73-cbc333401b7b.gif)

![image (2)](https://user-images.githubusercontent.com/37174253/85789207-02db9d80-b6e3-11ea-8e4c-f489b4e48d49.png)

**Comment by kylejvh** [comment]
I can start working on this.

**Comment by ppagarawal** [comment]
@idjevm @kylejvh I believe that this has been fixed via another ticket.

**Comment by ppagarawal** [comment]
> @idjevm @kylejvh I believe that this has been fixed via another ticket.

Closed via https://github.com/FightPandemics/FightPandemics/issues/775

**Comment by idjevm** [comment]
The issue still exists. Please test it out on the comment page. 

@ppagarawal the issue you mentioned just adds the button to the feed. This issue happens with that button on the feeed that makes the the button disappear if you click view less. Feel free to take it over Kyle and reach out for any clarification.

**Comment by nr431207** [comment]
@idjevm this is a duplicate of the ticket I created earlier and self assigned (#812), if @kylejvh wants to work on it instead no worries I can delete the one I created

**Comment by idjevm** [comment]
Let's address those issues here. @nr431207 since you worked on that button could you take this one then? And also center the button as mentioned on the duplicate issue #812 ?

**Comment by nr431207** [comment]
Just edited this ticket, thanks for closing #812

**Comment by nr431207** [comment]
@idjevm Ive checked and this issue doesnt exist any more, can you also double check and close this ?

**Comment by idjevm** [comment]
Yup that's right. I think it was not closed cuz it was not linked to the PR. Thanks for checking!!
