### ISSUE TITLE
Symptom Check UI

### ISSUE THREAD

**Issue by Valrud** [FightPandemics/FightPandemics#81]
Requirements:
https://www.notion.so/fightpandemics/Symptoms-Checker-UI-ece79c396f0643f1adbb7bb48da36078

**Comment by luxumbra** [comment]
@mutebironald are you working on this? I have been working on the Onboarding wizard, which I am assuming shares code. Just wondering if you've done any work on this yet.

**Comment by mutebironald** [comment]
@luxumbra , I am working on this though I don't think it shares functionality with the onboarding wizard. I just display relevant messages on the result dashboard depending on the answers given.

**Comment by luxumbra** [comment]
:+1: OK thanks mate.
