### ISSUE TITLE
Post back button position

### ISSUE THREAD

**Issue by nr431207** [FightPandemics/FightPandemics#812]
#### Post back button position needs to be centered and positioned outside of the post border  so that when the post is collapsed, the back button should be still visible (currently the back button disappears when post is collapsed): 
![image](https://user-images.githubusercontent.com/37174253/85624271-7ebfe200-b61e-11ea-8d44-099d384fb1fe.png)

**Comment by idjevm** [comment]
This is a duplicate issue. See #804 I created yesterday.

**Comment by idjevm** [comment]
Let's edit the other one and close this duplicate for now.
