### ISSUE TITLE
[Desktop][Mobile] Create Post - cannot set visibility to DAY

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#818]
env: staging

Steps:
1. Login
2. Go to Feed and add a new post
3. Select visibility DAY:
![Screen Shot 2020-06-25 at 13 50 36](https://user-images.githubusercontent.com/21987083/85714951-3c180b80-b6eb-11ea-99b7-c264861bd8a9.png)
4. Save your post
5. Open Feed screen and scroll down to your post
6. Click View more and then edit 
7. Visibility is displayed as Month:
![Screen Shot 2020-06-25 at 13 51 08](https://user-images.githubusercontent.com/21987083/85715178-741f4e80-b6eb-11ea-8b1b-c3c08ac84df9.png)

**Comment by joshmorel** [comment]
Definitely a frontend issue during post creation (not edit) only:

**Comment by kylejvh** [comment]
I'll give this one a shot.

**Comment by kylejvh** [comment]
There's a lot of prop drilling going on here. Some of the passed props going into the onChange handlers are undefined. Have we committed to using useReducer or Context? The state handling could use a refactor here.

**Comment by joshmorel** [comment]
Hi @kylejvh haha no. State handling is an open discussion - I'll send some links in Slack if you'd like to contribute to discussion. For this issue, now, I guess get it working in line with mostly with the current approach around creating a post. Refactoring state handling plus general guidelines in approach is something we definitely need however.
