### ISSUE TITLE
[Desktop] [Mobile] Recovery password screens are incorrect when email with a recovery link was sent

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#821]
env: staging

Steps:
1. Go to the login screen and press Forgot password? hyperlink
2. Enter email and click: Email me a recovery link
3. For a desktop you'll see:
![Screen Shot 2020-06-25 at 19 55 25](https://user-images.githubusercontent.com/21987083/85773200-e27d0480-b71d-11ea-83d6-590306b3fe4c.png)

For a mobile you'll see:
![Screenshot_2020-06-25-19-57-24-003_com android chrome](https://user-images.githubusercontent.com/21987083/85774228-ebbaa100-b71e-11ea-8a33-041b36518536.jpg)

In zeplin there is a screen for a MOBILE:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed562d60bba151f41673497

**We need the same screen for desktop.**
We have only this screen for sign-up confirmation:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed55f6ecb9fd341cc291344

**Comment by galeza** [comment]
Screen design:
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=12174%3A45410

**Comment by galeza** [comment]
hi @pthoma14 

We have both screens design. Please prioritize this issue.
Thank you,
Agnieszka

**Comment by galeza** [comment]
Hi @pthoma14 

Please prioritize. It's just a text to change for desktop. Currently we have a text: We just emailed a link to galeza_agnieszka@gmail.com. Click the link to confirm your account and complete your profile. If you don't see a message within a few minutes please check your spam folder.
We should have: 
![Screen Shot 2020-07-13 at 18 56 50](https://user-images.githubusercontent.com/21987083/87331667-a24dbc80-c53a-11ea-9407-83c67dcd1826.png)

**Comment by galeza** [comment]
The same for mobile: Text should be changed.
Text is here:https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed562d60bba151f41673497

**Comment by pthoma14** [comment]
> Hi @pthoma14 
> 
> 
> 
> Please prioritize. It's just a text to change for desktop. Currently we have a text: We just emailed a link to galeza_agnieszka@gmail.com. Click the link to confirm your account and complete your profile. If you don't see a message within a few minutes please check your spam folder.
> 
> We should have: 
> 
> ![Screen Shot 2020-07-13 at 18 56 50](https://user-images.githubusercontent.com/21987083/87331667-a24dbc80-c53a-11ea-9407-83c67dcd1826.png)
> 
> 

Hi @galeza thanks for the tagging me. I'll discuss with the product team on the best way to prioritize this issue.

**Comment by vikjoshi** [comment]
Hi @galeza , I tried to test this and it is working as expected for me. 

See below for screen I am seeing: 
![image](https://user-images.githubusercontent.com/41554004/87367180-24d07f00-c52f-11ea-94fa-3fd7a86b66e3.png)

**Comment by galeza** [comment]
Hi @vikjoshi 

No it's not correct. Please look carefully at the text message: Click the link to confirm your account and complete your profile. If you don't see a message within a few minutes please check your spam folder.
This is a text and screen for Sign-up! : https://staging.fightpandemics.work/auth/verify-email

Here user doesn't have to complete Profile, confirm account. He/She should see: Recover password, An e-mail has been sent with further instructions. Please check your inbox.
URL should be the same as for sign up?

https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5f0cafbd6ec5349ea00dce86

For mobile:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed562d60bba151f41673497

For mobile we have a link back to the Sign In screen. We don't have it for a desktop version? What should be the behaviour of FP logo?

**Comment by vikjoshi** [comment]
Ahh yes thank you @galeza , I was looking at your first post and thought the issue was you were not seeing any text. Got it!

@idjevm or @joshmorel- quick update to the text on Recover Password Screen once the email is sent. Currently, it shows what we show for create profile

Current State: 
![image](https://user-images.githubusercontent.com/41554004/87448347-90a6fc00-c5b0-11ea-9e5a-a1b9c00f35e3.png)

Expected State: 
https://user-images.githubusercontent.com/21987083/87331667-a24dbc80-c53a-11ea-9407-83c67dcd1826.png
![image](https://user-images.githubusercontent.com/41554004/87448365-97ce0a00-c5b0-11ea-95ba-386c44ba64cd.png)

Could we have someone make some quick changes?

**Comment by joshmorel** [comment]
@vikjoshi @galeza - this is fixed you can check it out here 
https://featurecorrect-password-change-content.fightpandemics.xyz/auth/check-email

I needed to re-use the verify-email page for this so I renamed the path to `check-email` as it works for both. All our auth pages for login etc need to be refactored. It's become a bit of a mess. We really should have one page per path with common components that address layout etc. I will create a new issue and work on it at a lower priority and the change password instructions can be on the same `auth/forgot-password` path as the form.

**Comment by vikjoshi** [comment]
@joshmorel thank you! This looks good to me via the url. I will test on staging once deployed.

**Comment by rabbi08** [comment]
Tested on Desktop and iPhone:

Recovery Password feature and screens working as expected. I receive the email in my hotmail INBOX as shown below:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/67168400/87614270-8c2c3180-c6dd-11ea-8386-051e60822d41.png">

GIF Showing change password process:

https://share.getcloudapp.com/6qu249Ag

I am able to login with new updated password:

Below are screens captured from desktop and iPhone.
DESKTOP:

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/67168400/87614010-e4166880-c6dc-11ea-80a1-3e2236d965fa.png">

IPHONE:

![image](https://user-images.githubusercontent.com/67168400/87614037-f8f2fc00-c6dc-11ea-884f-b249e511e97a.png)

**Comment by joshmorel** [comment]
Thanks @rabbi08 . I'm curious we're you redirected to /auth/login after changing the password in Auth0? We've had some inconsistent results on that recently so I plan to look into Auth0 settings tomorrow.

**Comment by rabbi08** [comment]
> Thanks @rabbi08 . I'm curious we're you redirected to /auth/login after changing the password in Auth0? We've had some inconsistent results on that recently so I plan to look into Auth0 settings tomorrow.

I click -> Forgot pwd -> Enter Email -> Send recovery link -> On the notification page -> Reload the FP home page by appending the URL as shown in below GIF:

https://share.getcloudapp.com/9ZujnGrY

**Comment by joshmorel** [comment]
Ah okay @rabbi08 - I was thinking of clicking from the email sent by Auth0.

![image](https://user-images.githubusercontent.com/10546720/87595889-42cbea00-c6bd-11ea-83b1-d66b27e32a47.png)

After changing the password it should redirect you back to /auth/login.

Anyways don't worry I'm pretty sure this isn't working at least consistently. I will look into fixing tomorrow.

**Comment by vikjoshi** [comment]
@joshmorel , it does not redirect me back to FP. Works as expected E2E though!

![image](https://user-images.githubusercontent.com/41554004/87616430-ddcac100-c6c9-11ea-9fe8-d0f254c959af.png)

**Comment by joshmorel** [comment]
Thanks @vikjoshi . I'll look into the Auth0 settings tomorrow. Hopefully it's that and not an Auth0 bug but in that case I'll contact them.

**Comment by rabbi08** [comment]
> Ah okay @rabbi08 - I was thinking of clicking from the email sent by Auth0.
> 
> ![image](https://user-images.githubusercontent.com/10546720/87595889-42cbea00-c6bd-11ea-83b1-d66b27e32a47.png)
> 
> After changing the password it should redirect you back to /auth/login.
> 
> Anyways don't worry I'm pretty sure this isn't working at least consistently. I will look into fixing tomorrow.

Yes you are right, and actually I didn't expect that to work from there as there is no link to FP or so available after password resets. Though you are full aware of the issue, just sharing the above thoughts as QA/End-user. Thanks
