### ISSUE TITLE
Have posts from organization show up under organization profile

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics#825]
MVP-Critical: As a user associated with an organization, if I go to my organization page, under "My Activity" I should see the posts that anyone in my organization has created. As part of the logic, you should use the Author ID to filter posts for the specific organization

![image](https://user-images.githubusercontent.com/41554004/85789546-a88f0c80-b6e3-11ea-9a6b-62aa2abf1d95.png)

Post-MVP Launch: Activity should also show any posts that the user has liked or commented on

B/E Ticket that is complete: #811 

From @joshmorel :For Activity, use posts created by organization (authorId={orgId})

**Comment by kylejvh** [comment]
@cvaldez98 @vikjoshi Will the fixes here carry over to #824 ? 
I assume they will for the most part. Wanted to make sure before I started work on it.

**Comment by idjevm** [comment]
@kylejvh Great question. I don't think they will be carried over so you can start working on the user profile one. But also we can ask @joshmorel,  @robinv85, and @Naraujo13 who have been working on the data model as well as some of these features. 

Guys, what are your thoughts?

**Comment by cvaldez98** [comment]
Hey all, I'm starting this ticket and will ask if I run into any issues. Thanks!

**Comment by Naraujo13** [comment]
> @kylejvh Great question. I don't think they will be carried over so you can start working on the user profile one. But also we can ask @joshmorel, @robinv85, and @Naraujo13 who have been working on the data model as well as some of these features.
> 
> Guys, what are your thoughts?

Not sure I got that. 
Do you guys mean if changes to #824 will be carried over to this one (#825)?

**Comment by kylejvh** [comment]
> > @kylejvh Great question. I don't think they will be carried over so you can start working on the user profile one. But also we can ask @joshmorel, @robinv85, and @Naraujo13 who have been working on the data model as well as some of these features.
> > Guys, what are your thoughts?
> 
> Not sure I got that.
> Do you guys mean if changes to #824 will be carried over to this one (#825)?

Yeah, that was what I wanted to know. User post activity just needed a quick fix so you can disregard.

**Comment by pthoma14** [comment]
@vikjoshi is this issue still open?

**Comment by idjevm** [comment]
@pthoma14 Yes it is still open but almost to be closed. As you can see, there is a pending PR for this issue.

**Comment by pthoma14** [comment]
@idjevm - Thank you JV! Sorry I didn't see the PR for this issue.
