### ISSUE TITLE
After adding a POST user should land on FP Feed page.

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#827]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/password
3. Create a POST and if you have multiple POST existing, then the POST will be added randomly but not as new/recent POST on the top.

Issue#1: User should land on FEED page rather than FP home page.
Issue#2: While adding multiple POST, the recent POST should be added on the top, currently it is added at the last of the users POSTs.

P.S. the video zip file for the functionality.
[Screen Recording 2020-06-25 at 4.54.03 PM.zip](https://github.com/FightPandemics/FightPandemics/files/4833768/Screen.Recording.2020-06-25.at.4.54.03.PM.zip)

**Comment by idjevm** [comment]
I will be closing this issue since we have already something on going for this. @ppagarawal and @jyclam have decided that we will give the option to the user to navigate to the newly created post (view post) or close the modal of success on post creation. Please refer to #636 & #687.

**Comment by idjevm** [comment]
Also, I would highly encourage you to use a tool such as this one -> https://www.getcloudapp.com

This app will allow you to record short gifs for about 15secons and short videos if you need to and give you a URL that you can post here, and Engineers will be able to see it on the cloud without having to download a file, and then unzip and then play...

**Comment by rabbi08** [comment]
> Also, I would highly encourage you to use a tool such as this one -> https://www.getcloudapp.com
> 
> This app will allow you to record short gifs for about 15secons and short videos if you need to and give you a URL that you can post here, and Engineers will be able to see it on the cloud without having to download a file, and then unzip and then play...

Sure, thnx for sharing.
