### ISSUE TITLE
Visibility filter doesn't seem to be working correctly with non-ASCII 

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#828]
E.g. visibility: state where state = Aragón.

This requires more investigation & may have to do with inconsistency with how "state" is returned by geolocation for different addresses - "Aragon" sometimes, "Aragón" other times.

Or something maybe something else?

NOT a good first issue :slightly_smiling_face:

**Comment by tejasm2** [comment]
Hey @joshmorel , do we need  to work on this?

**Comment by joshmorel** [comment]
I couldn't recreate my own issue :laughing: . Maybe they were two different cities differentiated by accent.

I will close
