### ISSUE TITLE
Integrating GTM

### ISSUE THREAD

**Issue by Jose-Tejera** [FightPandemics/FightPandemics#83]
We would like to include Google Tag Manager to the WebApp and main website/landing page so we are able to add tracking and add tags on the fly without the need of deploying new code. 

To add GTM to the website, we need to add the following as high as possible after <head>

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({‘gtm.start’:
new Date().getTime(),event:‘gtm.js’});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=‘dataLayer’?‘&l=‘+l:‘’;j.async=true;j.src=
’https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,‘script’,‘dataLayer’,‘GTM-K32K347’);</script>

And the following piece of code immediately after the <body> tag

<noscript><iframe src=“https://www.googletagmanager.com/ns.html?id=GTM-K32K347”
height=“0" width=“0” style=“display:none;visibility:hidden”></iframe></noscript>

Thank you!

**Comment by manualzuru** [comment]
@MohamedEl1 I think this is the wrong GTM. Please get in touch with Federica!

**Comment by robinv85** [comment]
@MohamedEl1 this is done?

**Comment by galeza** [comment]
@robinv85 
Will ask Federica Zanini. I think it was done.
