### ISSUE TITLE
Unable to SUBMIT -> "Offer/Request HELP" without Signing In

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#833]
1. Open "https://staging.fightpandemics.work"
2. Click on 'Request Help -> Medical -> Share My location -> Enter valid email address
3. Click on 'Submit' button

Issue# You will observe that nothing happens.
'SKIP' button works.

**Comment by idjevm** [comment]
Duplicate with #731 and it will be resolved with #731 and  #742. Please refer to those issues. Closing this for now
