### ISSUE TITLE
[Mobile] Recover password - Back button overshadows Email me a recovery link button 

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#839]
env: staging

Steps.
1. Open staging on your mobile phone
2. Go to Login screen and click hyperlink Forgot password
3. On the Recover Password screen - start typing your email.
4. When soft keyboard on your phone is launching Back to the Login screen hyperlink moves and overshadows Email me a recovery link button. 
5. When I wanter to click Email me a recovery link button I ended up on the SignIn screen.
Please see screenshot:
![Screenshot_2020-06-26-13-56-07-353_com android chrome](https://user-images.githubusercontent.com/21987083/85855180-215e9900-b7b6-11ea-93d8-f44c29b0bd81.jpg)
![Screenshot_2020-06-26-13-55-24-898_com android chrome](https://user-images.githubusercontent.com/21987083/85855188-23c0f300-b7b6-11ea-9915-13193ff4ad95.jpg)
![Screenshot_2020-06-25-19-56-34-423_com android chrome (1) 2](https://user-images.githubusercontent.com/21987083/85855193-26bbe380-b7b6-11ea-9faf-808fdbd94f67.jpg)

**Comment by tejasm2** [comment]
Do we have an update on this @mel-chiu ?

**Comment by mel-chiu** [comment]
yes. But I found the problem right now is that the button doesn't show at all or everything moves to the same place. 
![1](https://user-images.githubusercontent.com/56417930/91640034-078e3c00-ea1b-11ea-9c1c-507d5e10a976.jpg)
![2](https://user-images.githubusercontent.com/56417930/91640037-12e16780-ea1b-11ea-900d-ce379e09db22.jpg)
