### ISSUE TITLE
/profile error due to null post & not rendering posts

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#845]
Merging #769  broke #831 . /profile 

@BMariscal I think we didn't take into account that are now using Posts component for profile activity (recent PR by @kylejvh )

Only occurs if user created posts.

In staging I see this:

```
TypeError: "T is undefined"
    Au Post.js:67
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    e Profile.js:120
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 2
react-dom.production.min.js:209:194
```

In local dev we have error about undefined `post`.
![image](https://user-images.githubusercontent.com/10546720/85891757-b2853e00-b7bd-11ea-9afe-6e40c103525c.png)

Fixing this - the posts aren't rendered. Not sure who it makes sense to work on it... We can discuss in Slack.

**Comment by joshmorel** [comment]
@BMariscal - Kyle says he has time now so he'll look into fixing this

**Comment by BMariscal** [comment]
oh oh. Thanks @joshmorel

**Comment by BMariscal** [comment]
Yeah I didn't test the profile page. Oops.
