### ISSUE TITLE
'Feed' share link not working as expected (only copy, no links to social media)

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#853]
1. Open "" 
2. Login using valid email/password
3. Click 'FEED' and click on 'Share' icon to share the FEED

Issue: Mismatch with the FP design, because as per Zeppelin design, the user should be directly be able to share the link on email/whatsapp/msg, etc. But currently it say that the link is copied.

Note: Though user is able to explicitly copy/paste the Link.

Please refer attached screenshots.

![image](https://user-images.githubusercontent.com/67168400/85909241-ce510a00-b7e6-11ea-8b94-6613faadeec6.png)

<img width="554" alt="Screen Shot 2020-06-26 at 7 43 06 PM" src="https://user-images.githubusercontent.com/67168400/85909110-381ce400-b7e6-11ea-8e38-29f56c773b98.png">

**Comment by joshmorel** [comment]
Thanks @rabbi08 I think we should aim to do this post mvp or at least post soft launch.
