### ISSUE TITLE
Create a send button for posting comments

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#857]
Please create a send button for posting comments

![image](https://user-images.githubusercontent.com/6276256/85916153-81fbdd80-b86b-11ea-9069-bd0f5a03eeb8.png)

- [ ] The user is able to create a comment via keyboard and button, both
- [ ] The send button is placed on right end of the text box

**Comment by idjevm** [comment]
@BMariscal Are you covering this on your PRs too? I could put my hands on this one but I know a lot of things are going on your end on the posts so probably leave this to you?
