### ISSUE TITLE
[Desktop][Mobile] Add Checkboxes to accept Terms & Conditions and Privacy Policy on Create Individual Profile Page.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#858]
As a user,
Given that I am on the Create your Profile page,
Then I should have an option (checkboxes) to accept Terms & Conditions and Privacy Policy.

Desktop:
![Create Profile- Terms n Condi 0](https://user-images.githubusercontent.com/66698276/85917165-7dd4bd80-b875-11ea-9656-4b843cf47553.png)

Mobile:
![Create Profile- Terms n Condi Mobile 0](https://user-images.githubusercontent.com/66698276/85917458-d1e0a180-b877-11ea-9864-7e7485f6f1ec.png)

**Comment by idjevm** [comment]
Isn't this issue already resolved?? @tejasm2 where did you get this from?

 Where are you checking??

**Comment by idjevm** [comment]
Closing this as this already exists.

**Comment by idjevm** [comment]
Seems like it is still an issue for the user profile! We have this already for ORG profile!

**Comment by pthoma14** [comment]
@idjevm thank you for clarifying this issue will be resolved with the #860 PR. I'm going to remove the "MVP-Critical"  tag
