### ISSUE TITLE
Redirect to Main Profile page after the editing is complete and saved.

### ISSUE THREAD

**Issue by tejasm2** [FightPandemics/FightPandemics#861]
**Currently:**
When we click on “Save Changes” button on the Edit Profile/Edit Account Information page, it redirects to that same page. (Check the gif below).

**Expected:**
As a user, 
Given that I am on the Edit Profile page (same for Edit Account Information/ Profile Information),
When I fill up/edit  the required information and click on “Save Changes” button,
Then I should be redirected to the main profile page.

![Edit profile redirection buggg](https://user-images.githubusercontent.com/66698276/85922201-13387780-b89f-11ea-9bd0-9f7f8eab2960.gif)

Main Profile Page:

![Main Profile Page 0](https://user-images.githubusercontent.com/66698276/85922373-50513980-b8a0-11ea-830c-225590a0283d.png)

**Comment by robinv85** [comment]
@tejasm2 @idjevm 
Was this approved by PM's? I think it's not a good idea, what if you want to edit both profile & account? Or you made a mistake?
I mentioned this before and in my opinion a good UX would indicate the update was successful but stay on the same page.

**Comment by idjevm** [comment]
I believe it was @indirabhowmick who wanted this change originally. I do agree with you about showing a message that the changes were saved correctly. And yeah dirty checking is already enabled when you created it I believe.

**Comment by indirabhowmick** [comment]
@idjevm @robinv85 - I am going to test to see if the dirty checking is enabled

**Comment by indirabhowmick** [comment]
@robinv85 @idjevm - Dirty checking is not enabled. Save button should be enabled only when the user makes some changes on the UI

**Comment by joshmorel** [comment]
I would say we should be consistent with typical UX. What does facebook/linkedin/etc do?

**Comment by idjevm** [comment]
@joshmorel I agree with you actually. But yeah, all of them have a modal nowadays, so basically on save, the modal sometimes closes, or on x button. sometimes it will ask you if you had made any changes if you want to discard them.

**Comment by robinv85** [comment]
hmm I think it currently only has "valid" check but not "dirty" for all the forms with react-hook-form that I worked on

**Comment by joshmorel** [comment]
@idjevm yeah was looking at some examples and it kind of depends - some use modals so it closes and you see the updated profile, also on mobile both LinkedIn/Facebook redirect back. Some things on Facebook keep you there after save on desktop.
