### ISSUE TITLE
Add organization list in mobile navbar + fix desktop key prop

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#865]
Similar to work on desktop but we also need to add here:

https://github.com/FightPandemics/FightPandemics/blob/f2cd1e9b875cb516776005650e1813d01e9777e0/client/src/templates/layouts/NavigationLayout.js#L210

Also let's just fix this other issue here:

React expects a key for list of items. So we need a key={organization._id} on `<Menu.Item>` for desktop as well.

Warning: Each child in a list should have a unique "key" prop.

```
Check the top-level render call using <Menu>. See https://fb.me/react-warning-keys for more information.
    in MenuItem (at Header.js:113)
    in Unknown (at NavigationLayout.js:268)
    in div (created by Drawer)
    in div (created by Drawer)
    in Drawer (created by Drawer)
    in Drawer (at NavigationLayout.js:255)
    in div (at NavigationLayout.js:254)
    in NavigationLayout (at RouteWithSubRoutes.js:80)
    in Route (at RouteWithSubRoutes.js:43)
    in RouteWithSubRoutes (created by ConnectFunction)
    in ConnectFunction (at App.js:21)
    in Switch (at App.js:19)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:18)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:21)
    in Provider (at src/index.js:19)
```

**Comment by kylejvh** [comment]
The key warnings should be addressed with PR #885.

**Comment by kylejvh** [comment]
I just finished up the rest of the issue with PR #886 . Sorry @MohamedEl1 if you were working on this one.

**Comment by pthoma14** [comment]
@kylejvh should this issue be closed?

**Comment by vikjoshi** [comment]
@MohamedEl1 @pthoma14 @kylejvh - I'm going to go ahead and close this issue because it has been resolved
