### ISSUE TITLE
By default Org is created as 'I Need Help' 

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#869]
1. Open "https://staging.fightpandemics.work"
2. Navigate Profile -> Already Created Organizations 

Issue# You will observe that it display 'I need HELP' for the Organizations I have created by DEFAULT
Even can't edit the status for the org.

P.S refer GIF.
https://share.getcloudapp.com/X6uo8eZ5

**Comment by vikjoshi** [comment]
@rabbi08 - my thinking for this is that Org should not show "I need help/want help" at all because it's not part of the Org. Profile sign up. Let's go ahead and remove it for now- what do you think?

**Comment by rabbi08** [comment]
> @rabbi08 - my thinking for this is that Org should not show "I need help/want help" at all because it's not part of the Org. Profile sign up. Let's go ahead and remove it for now- what do you think?

Agree, we should remove 'I need Help' from Org profile.
