### ISSUE TITLE
City Name is not displayed , only country name is displayed for a Post( Feed->Post)

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#877]
Summary : City Name is not displayed , only country name is displayed for a Post( Feed->Post)

Steps:
Go to Url,  https://staging.fightpandemics.work/feed

Actual Result: Only country name is displayed for a Post
![post](https://user-images.githubusercontent.com/65972693/85930343-62b37f00-b870-11ea-8558-82f61d055602.png)

Expected Result:
As per zeplin,City name is displayed along with country name
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed034ab3d8c25b62217f26f

**Comment by joshmorel** [comment]
Good first issue if someone wants to take it on. Note that currently for location we can have just "California, US" or even just "US" so city is optional (plus some of sourced by FP posts - have no country at all).

**Comment by ac5144** [comment]
I would like to solve this issue

**Comment by vikjoshi** [comment]
@ac5144 assigning this to you
