### ISSUE TITLE
Add correct fonts and homepage tweaks

### ISSUE THREAD

**Issue by luxumbra** [FightPandemics/FightPandemics#88]
1. The correct fonts for the App are Poppins and Work Sans, neither are being used at present.
2. The Menu icon is an ellipsis but in the designs it's showing a hamburger. It's also not vertically aligned with the logo. 
3. Vertical white space on the homepage needs tweaking

**Comment by luxumbra** [comment]
1. I've added in imports the same way we were importing Roboto (`typeface-roboto`) with `typeface-poppins` and `typeface-work-sans`. Poppins is working a treat but despite `typeface-work-sans` being installed in `node_modules`, I am getting the following error:
`./src/index.js
Module not found: Can't resolve 'typeface-work-sans' in '/app/src'`
2. I've changed the icon for the menu and is now the correct color and aligned with the logo.
3. I've tweaked the spacing on the homepage to match the designs.

**Comment by robinv85** [comment]
@luxumbra seems like this was also updated in #89 see https://github.com/manualzuru/FightPandemics.com/pull/89/files#r406724649

Any idea about current status? Seems to me that Roboto can be removed, and that "Poppins" is now added as a Google font, so maybe can be removed from npm depencencies?

**Comment by luxumbra** [comment]
I have some tweaking to do after feedback from design, then the other wizards will need to have the new styled components that I've created added to them, which should bring them all into line with designs. I'll remove roboto and the poppins dependency. Thanks

**Comment by luxumbra** [comment]
The work this issue was created for has been completed and merged, so I am closing this. I'll open a new issue for the work required for integrating the styled components I created for the wizards. Any additional font / theme oriented work can be done under issue #74. @robinv85 @anniegiang does this seem reasonable?
