### ISSUE TITLE
Fix footer position -> needs to be at the bottom of the page

### ISSUE THREAD

**Issue by idjevm** [FightPandemics/FightPandemics#893]
![image](https://user-images.githubusercontent.com/25408660/85956722-b77cf580-b955-11ea-9c5b-cd48b8b081ba.png)
Remove extra white space after the footer and have only the footer as the last thing on the page.

**Comment by pthoma14** [comment]
Hi @idjevm thank you for logging this issue! 

Just letting you know that as the product team starts to prioritize issues for the soft launch we want to make sure UI issues don't have the "MVP-Critical" tag if they don't seriously interfere with the functionality of the product. 

This is an issue that does need to be addressed. We just want to be cautious when it comes to using this tag. 

Does that make sense?

**Comment by ppagarawal** [comment]
Please note that this needs to be fixed for mobile as well

![image](https://user-images.githubusercontent.com/6276256/86148314-168a6800-bb18-11ea-8494-136db4ae6250.png)
