### ISSUE TITLE
Profile -> My profile -> My activity -> All user's own POSTs are not visible

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#897]
1. Open "https://staging.fightpandemics.work"
2. Navigate 'Profile -> My Profile "
3. Under 'My Activity' 

as logged in user, user is supposed to their own generated POSTs.

Issue: You will observe that only few POSTs are displayed, For. eg for my user NS, only 5 POSTs are displayed under 'My Activity' But under FEEDs, all of my POSTs are displayed.

P.S below GIF

https://share.getcloudapp.com/qGuKr48z

**Comment by idjevm** [comment]
@rabbi08 Yeah I think this was something discussed with @kylejvh & @Naraujo13, I think that we are only showing the latest 5 posts. Kyle / Nicolas, wasn't this something that was at least mentioned on the PR that was merged to display posts on user profile?

**Comment by indirabhowmick** [comment]
There might be a limit on the number of posts that are being fetched from the backend. Tagging @joshmorel @robinv85 @vikjoshi

**Comment by idjevm** [comment]
That's correct @indirabhowmick, I believe when @kylejvh implemented the feature to display the posts on the profile, it was limited / or it is limited by default to 5.

**Comment by Naraujo13** [comment]
I remember talking about this, but I thought we settled with an unlimited number for the profile.
Anyway, it is probably just changing the `limit` parameter to -1.

**Comment by idjevm** [comment]
Alrighty, let's do that, for now, @Naraujo13, and revisit later for pagination.
