### ISSUE TITLE
Sort posts by most recent in profile activity

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#904]
Mentioned here #875 we should sort posts by most recent in profile activity pages.

@Naraujo13 we need to ignore location in this case. We talked about another parameter but I also wonder, at least for now if authorId is set then they are viewing the profile activity so in such a case ignore location. Or is this not explicit enough?

**Comment by Naraujo13** [comment]
> Mentioned here #875 we should sort posts by most recent in profile activity pages.
> 
> @Naraujo13 we need to ignore location in this case. We talked about another parameter but I also wonder, at least for now if authorId is set then they are viewing the profile activity so in such a case ignore location. Or is this not explicit enough? 

I would prefer having a sort parameter where we can choose the location criteria so it is more explicit. 

It won't require much change in the frontend, just adding this param to the r request.

**Comment by joshmorel** [comment]
Feel free to take this on and do b/e only. I can add f/e in separate issue or with PR review.

**Comment by Naraujo13** [comment]
Ok!

**Comment by joshmorel** [comment]
@Naraujo13  hey I asked PMs in Slack and for activity we should exclude all visibility filters.

So for activity we should have some query param flag that totally ignores user location stuff (both geo sorting & visibility filters) - so a similar result to non-logged in user with no location filter. 

I say we address both here 

Not sure what we want to call it maybe `ignoreLocation=true`

**Comment by Naraujo13** [comment]
So we would ignore location, expiration and visibility filters, right?

**Comment by vikjoshi** [comment]
@indirabhowmick @joshmorel @Naraujo13 , since we're adressing the visibility filters for posts under profile, I moved this into MVP-Critical

**Comment by joshmorel** [comment]
Location & visibility definitely. I think expiration might be tricky unless, if we include these on activity we need some kind of display to clarify that the post is no longer valid. 

My inclination would be for still filter out expired posts out until we decide how that information should be conveyed.

Thoughts @vikjoshi ?

**Comment by vikjoshi** [comment]
Based on Slack convo, we will just remove the filter for soft launch for expiration. I will create a new ticket to address a tag or something like that to differentiate between expired and unexpired posts- to be tackled post soft launch. 

CC: @Naraujo13 @joshmorel @indirabhowmick

**Comment by Naraujo13** [comment]
Okay, but that is just for the profiles right?

At the feed we maintain the filter?

**Comment by vikjoshi** [comment]
@Naraujo13 yup exactly! This is just for what shows up on the View Profile page for Individual and Org profiles

**Comment by vikjoshi** [comment]
@joshmorel @Naraujo13 , just tested on staging and it looks like we are still seeing the issue where if the org. address is in a different city/state/country than the individual profile address, then the post does not show up under the org. profile page. Are one of you or someone else working on that?

**Comment by vikjoshi** [comment]
@Naraujo13 let @joshmorel and I know whether you are able to address my comment above- if not Josh will take this on so we can get it in prior to code freeze this week

**Comment by joshmorel** [comment]
I'll take this one on as I have bandwidth. Hope to have PR this morning.
