### ISSUE TITLE
Update/delete posts made as organization

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#906]
#891 enabled posting as organization but a user still needs to update & delete posts of organizations that they own (similar to their own posts).

From Sheeba Jose:
I am adding more info copied from #971  as suggested by JV.

Issue: Unable to edit/delete Organization posts created(from feed Or profile) by loggedin user, as Ellipsis is missing
Expected Results: Organization posts created via Feed OR My profile should have edit/delete functionality by providing the ellipsis

Steps:
1. Log into https://staging.fightpandemics.work/
2. Go to feed->Create Post
3. Choose Organization and create a post and select 'view  your post'
4. Notice that Ellipsis is missing as shown below in picture 1.
5.Go back to feed->posts by clicking 'back'. Notice that Ellipsis is missing as shown below in picture 2.
6.Repeat the creation of organization posts from 'MyProfile' and notice that ellipsis is missing and so unable to edit/delete posts .

picture 1

![image](https://user-images.githubusercontent.com/65972693/86404426-742bcb00-bc64-11ea-9797-68b48ee572d5.png)

picture 2 from feed
![image](https://user-images.githubusercontent.com/65972693/86404374-5b231a00-bc64-11ea-98a3-ab94f6942eb5.png)

**Comment by sheeba1** [comment]
@idjevm  added more info from #971. thanks!
