### ISSUE TITLE
Fix home page sizing to fit different screen

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#908]
As a User, I want to have consistent UI experience across devices.

Currently, the components of the homepage are not proportionate to the different screen sizes. The frontend needs to be proportionate across screens. This change has to be implemented across all the different features.

Eg: 
![image (4)](https://user-images.githubusercontent.com/6276256/86091054-db147d00-bac8-11ea-8ae3-c3ace1cda991.png)

@Yu-Alexa-Zhao Can you please share the proportion of the component in the screen.

**Comment by pthoma14** [comment]
@ppagarawal this is a great issue! Thanks for logging this. 

Maybe for these UI type issues we don't use the "MVP-Critical" tag but rather "MVP-Release 1" and "Good First Issue" tags

Thoughts?

**Comment by Yu-Alexa-Zhao** [comment]
Is it possible to - 
1) For both the left and right sections to take up the entire height? 
2) Ideally the two boxes would take up to 75% of the height of the div ...

Not sure if I am being descriptive here...
![image](https://user-images.githubusercontent.com/44085699/86192057-a29b9000-bb16-11ea-8b90-f8cb6c038a56.png)

**Comment by Joeu** [comment]
@Yu-Alexa-Zhao , can you check how it is now in https://staging.fightpandemics.work/ and give you thoughts about it? I just pushed a fix for other issue that deals with this blue part on the home page.
I'd also like to know which screen sizes we are going to support, so we can change the proportions using the font-size approach.

**Comment by Yu-Alexa-Zhao** [comment]
Yes I think the design now makes perfect sense to me

**Comment by idjevm** [comment]
I am not sure about supporting 4k resolutions, I mean I guess we should consider having a bit screen resolution but most probably will ok without 4k res.

**Comment by Joeu** [comment]
I made a lot of changes to deal with sizing and proportion. Now we are able to set the proportion by adjusting the font-size in the GlobalStyles.js file.

@idjevm , @jyclam , @manualzuru , @Yu-Alexa-Zhao , @ppagarawal , please check and make comments regarding the screenshots below (representing 4k screens):

![4kScreenProportions1](https://user-images.githubusercontent.com/1004896/86392135-57e25b00-bc71-11ea-8ee8-0dc49151a703.png)
![4kScreenProportions2](https://user-images.githubusercontent.com/1004896/86392149-5ca70f00-bc71-11ea-9517-40b00fa97a03.png)
![4kScreenProportions3](https://user-images.githubusercontent.com/1004896/86392180-67fa3a80-bc71-11ea-9c59-f4dc8e354fac.png)
![4kScreenProportions4](https://user-images.githubusercontent.com/1004896/86392193-6cbeee80-bc71-11ea-9c83-310976064dbd.png)
![4kScreenProportions5](https://user-images.githubusercontent.com/1004896/86392201-6e88b200-bc71-11ea-8fa3-5c21568f1953.png)

**Comment by ppagarawal** [comment]
This looks good @Joeu
How will the other pages like feed, post, profile look like? Will the changes be applied there as well?

**Comment by ppagarawal** [comment]
Also we may need to change the 'view more' button depending on screen size apparently, in the future releases

**Comment by Joeu** [comment]
> Also we may need to change the 'view more' button depending on screen size apparently, in the future releases

I put screenshots for those pages also, @ppagarawal

**Comment by Joeu** [comment]
> This looks good @Joeu
> How will the other pages like feed, post, profile look like? Will the changes be applied there as well?

I uploaded prints for those pages too, @ppagarawal .

**Comment by ppagarawal** [comment]
We should be good. I assume that these changes are being applied globally.

**Comment by Joeu** [comment]
Yes. Since the elements are using rem units.
