### ISSUE TITLE
Fix styles in the onboarding flow <> other places in the platform. 

### ISSUE THREAD

**Issue by idjevm** [FightPandemics/FightPandemics#910]
I believe that PR #813 messed up some stuff in the frontend. 

Please refer to this slack post -> https://fightpandemics.slack.com/archives/C010J3BMS9H/p1593525056033700

**Comment by idjevm** [comment]
also #912 @adisen let's just address them here.

**Comment by omarzoghayyer** [comment]
Also the submit button on >>Needs help page >> Step 3

**Comment by idjevm** [comment]
Yeah the onboarding is the Needs help/ Offer Help pages, but this ticket addresses all the buttons across the platform. Most of them got messed up, so working with @adisen to find a solution. @adisen make sure you check all buttons, filters, creating a post, mobile/desktop, onboarding page, creating profile/organization. I noticed that a lot of them got messed up.

**Comment by adisen** [comment]
Working on it. Gonna push the code today.

**Comment by idjevm** [comment]
So we will close this one since I have reverted #813.
