### ISSUE TITLE
Feed filter button styling broken

### ISSUE THREAD

**Issue by joshmorel** [FightPandemics/FightPandemics#912]
@adisen  I think this might have broken these ones https://github.com/FightPandemics/FightPandemics/pull/813

If you're able take it on and fix within 1-2 days please assign yourself, otherwise let me know and we can ask someone to volunteer.

I guess just update `FiltersSidebar.js` to use `SubmitButton` based on recent commit but we should check anywhere else the it is used.

![feed-buttons-broken](https://user-images.githubusercontent.com/10546720/86142957-d26c7880-bac1-11ea-898a-2978c5cd5b55.gif)

**Comment by idjevm** [comment]
Yeah, I think this is a duplicate, I will update the other issue, since the changes on 813 probably affected all buttons. 
https://github.com/FightPandemics/FightPandemics/issues/910
