### ISSUE TITLE
Like should be clickable on Post details page

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#914]
On Feed, user can click 'Like' for his  Post, but cannot click 'Like' (Like is disabled) when he clicks and selects his post as shown below:

![image](https://user-images.githubusercontent.com/65972693/86152266-ca5a0c00-bab4-11ea-830c-efdbf0ebf084.png)

steps:
Login and Go to feed and Create a Post. On feed page you can click on 'Like', But if you go to Post page by clicking the post, you cannot click 'Like' element.

- [ ] Expected: Like should be clickable, 

- [x] Also, the number of 'Likes' for a post should be displayed on feed page correctly. ex: 1 Like, 2 Likes etc.

**Comment by BMariscal** [comment]
This functionality is being addressed here: https://github.com/FightPandemics/FightPandemics/pull/834

**Comment by pthoma14** [comment]
@BMariscal Is it possible to link this issue with #834 or should we just close this issue?

**Comment by BMariscal** [comment]
@silenceway @cvaldez98  fyi ^

**Comment by sheeba1** [comment]
@cvaldez98 , we need this fix for mobile too. Thanks!
