### ISSUE TITLE
User need to enter 'Add Org' data again if they navigate to privacy or terms& condition links

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#917]
1. Open "https://staging.fightpandemics.work"
2. Navigate Profile -> Add Organization
3. Enter the details to create new Organization.
4. Click on 'Privacy Policy' or ' Terms and Conditions' link
5. Click on 'BACK' button of the browser to come back to finish adding new Organization

Issue: You will observe that user's entered data to create Organization profile is deleted and user need to re-enter all the details.

Refer attached GIF.

https://share.getcloudapp.com/YEupky7y

**Comment by rabbi08** [comment]
@vikjoshi FYI

**Comment by idjevm** [comment]
Easy solution for this will be to have those links open up on a new tab. What do you think @rabbi08 ?

**Comment by rabbi08** [comment]
> Easy solution for this will be to have those links open up on a new tab. What do you think @rabbi08 ?

Yeah that's will be quick and easy fix. Thnx

**Comment by vikjoshi** [comment]
@rabbi08 @idjevm, given that this is not urgent, i will prioritize this for MVP release, not soft launch
