### ISSUE TITLE
Profile "Logo" is different than which is displayed on the POSTs added by the respective Organizations

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#918]
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/Password
3. Navigate to Profile -> [Org_name_added before]
4. Create a POST

Issue# You wil observe that the profile logo displayed on Company profile is different than its display on the POST added by them.

Refer below GIF. 

https://share.getcloudapp.com/NQuglJ90

**Comment by rabbi08** [comment]
@vikjoshi FYI

**Comment by vikjoshi** [comment]
@rabbi08 given we are only showing initials on the avatar, Im going to prioritize this for MVP-Launch, not soft launch

**Comment by omarzoghayyer** [comment]
Ill look into this issue and try to get it done soon.
