### ISSUE TITLE
Error is displayed while user click on 'Comment' icon for Post of Organization-> My Activity

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#925]
1. Open "https://staging.fightpandemics.work/"
2. Navigate to Profile -> [Org_name(prev added)] -> My activity
3. click on 'Comment' icon on any post existing.

Issue# You will observe that following error is displayed:
"Failed loading profile, reason: Cast to ObjectId failed for value "post" at path "_id" for model "OrganizationUser"

Please note this feature is working fine for Individual post as of now.

Refer attached GIF

https://share.getcloudapp.com/OAuB88O2

**Comment by rabbi08** [comment]
@vikjoshi FYI

**Comment by vikjoshi** [comment]
Hmm @rabbi08 I just tried to replicate and I am seeing this work as expected. Could you try one more time? 

![image](https://user-images.githubusercontent.com/41554004/86191572-3f046900-bafc-11ea-8297-27e2a7735558.png)

**Comment by rabbi08** [comment]
> Hmm @rabbi08 I just tried to replicate and I am seeing this work as expected. Could you try one more time?
> 
> ![image](https://user-images.githubusercontent.com/41554004/86191572-3f046900-bafc-11ea-8297-27e2a7735558.png)

Unable to replicate, will keep this scenario for further testing.
Currently closing as no longer replicate.
