### ISSUE TITLE
Post description goes  beyond the Post detail page

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#928]
Post description goes beyond the Post detail page as shown in picture 2. 
Steps: login staging FP and go  to feed,create Post as Individual/Organization. Enter the description until the entire row is filled.Create Post and view post.

![image](https://user-images.githubusercontent.com/65972693/86181896-b37ede00-bae3-11ea-9283-cacf53fee872.png)

Picture 2
![image](https://user-images.githubusercontent.com/65972693/86181971-d90be780-bae3-11ea-977e-5a583772c4f4.png)

**Comment by idjevm** [comment]
Can you guys try again in incognito mode in staging?? I am not seeing this issue on my end 
![image](https://user-images.githubusercontent.com/25408660/86254549-f6908e00-bb83-11ea-9e78-2459de0ae793.png)

**Comment by doheekim93** [comment]
@idjevm I think the error happens when it's one long string with no spaces!

**Comment by idjevm** [comment]
Yup that's correct @doheekim93 I don't think this is a critical issue. This was probably there since the very beginning and briceida didn't think of the posibility of someone creating a one line long without spaces post.

**Comment by idjevm** [comment]
We should change the tags of this as this is not critical, and probably not happen unless the user makes a mistake and has no spaces on their post? I don't see it happening though

**Comment by pthoma14** [comment]
@idjevm agreed. We should definitely fix this bug, but it's not critical for Soft Launch.

**Comment by joshmorel** [comment]
A good first F/E issue but agreed, not critical for soft launch. See: https://css-tricks.com/almanac/properties/o/overflow-wrap/

**Comment by BMariscal** [comment]
@idjevm I can take of this. easy fix.

**Comment by idjevm** [comment]
Sounds good BRI :D yes it is just a css issue :D

**Comment by sheeba1** [comment]
@idjevm @BMariscal The issue is resolved .Working fine for individual and organization posts, but not Fixed for  Mobile. 

So wondering fix has to be applied for mobile too.Please advise.

**Comment by sheeba1** [comment]
Working fine for mobile too! Thanks.Closing the bug
