### ISSUE TITLE
User Profile:My Profile should have the comment element highlighted along with number of comments , if user's post has comments added

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#931]
Objective: An user should be notified if someone comments on his post. Right now, the user can go to My Profile to see the comments for his posts. If his post has comments added, the comment element should be Highlighted so that the user notices it conveniently. Right now it does not show comment element highlighted. The snippet below (picture 1) is from user profile. The post has 2 comments(refer picture 2). 

Expected behavior: In user profile , if user's post has comments added, the comment icon/element should be highlighted along with number of comments.  ( ex:1 Comment, 2 comments)

Picture 1.

![image](https://user-images.githubusercontent.com/65972693/86202572-703e6280-bb17-11ea-9fda-bcd1910571df.png)

if I click on the comment only, comment is highlighted

Picture 2
![image](https://user-images.githubusercontent.com/65972693/86202888-58b3a980-bb18-11ea-9d1f-b6322d471027.png)

Steps:

1. User A Login to staging and create a post(individual/organisation).
2. logout.
3.User B Logs in as a different registered user.
4. User B Add Comments to the post created by User A.
5.Now User A's My  profile section should have the comment element highlighted for this post, along with number of comments

**Comment by vikjoshi** [comment]
Reassigning to @ppagarawal . @ppagarawal , how are we handling post notifications currently?

**Comment by vikjoshi** [comment]
We should follow what we are doing for Likes on the Profile page. The Likes icon is highlighted on the profile page when there is a new like- same should be the case for Comment. If we can also show the new number of comments, that would be great as well

**Comment by pthoma14** [comment]
@vikjoshi is this issue a MVP-Critical issue? Could this be an MVP-Release 1 issue?

**Comment by vikjoshi** [comment]
@pthoma14 , I believe this is somewhat necessary to fix prior to MVP launch because otherwise the poster has no indication when there are new comments on their post. If we need to launch without it, we probably can but would be good to have this functionality in place a few days after initial launch. 

@tr1503 , how is the issue coming along? Is it looking difficult?

**Comment by pthoma14** [comment]
@vikjoshi Got it 👍 That makes sense

**Comment by tr1503** [comment]
@vikjoshi It is more difficult than what I thought. But I already found some clues to do it and I think I can complete it these two days.

**Comment by vikjoshi** [comment]
Thanks @tr1503 ! Keep me updated on your status with this- if you are able to get this fixed before code freeze in the next couple days, then we can include it in the soft launch

**Comment by sheeba1** [comment]
Verified on mobile desktop
