### ISSUE TITLE
Add video to About us page and validate for spacing

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#932]
As a user, I want to know more about FightPandemics culture, so that I can know more about FightPandemics

Design: https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5edd9fc31fa688993818434a

Link to the video: https://www.youtube.com/watch?v=d1mgFeH8l_4

Acceptance Criteria
- [ ] Insert the video in the about us page
- [ ] The video should be playable on the about us page. No redirection to website outside FightPandemics
- [ ] The video size must adjust to the screen size
- [ ] Changes must reflect both in desktop and mobile
- [ ] Validate the spacing between different sections and maintain uniform space between them

**Comment by idjevm** [comment]
will close this for now since we are not asking for a video anymore. @ppagarawal please contact @manualzuru  and @tingtingandrea to ask for specifications / design for the image that we want to put there.
