### ISSUE TITLE
[Mobile Web] Feed | Country code covered by post info

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#933]
env: staging

Steps: 
1. Open Feed page
2. Filter by Location: Deutschland
3. First post is displayed incorrectly.
4. Feed post information covers country code:
![Screenshot_2020-06-30-11-32-47-567_com android chrome 2](https://user-images.githubusercontent.com/21987083/86242677-5c414200-bba5-11ea-80c5-01ce27054db6.jpg)

**Comment by doheekim93** [comment]
Hi @galeza, I believe this is a duplicate of #701
