### ISSUE TITLE
[Desktop] Feed | View Result button invisible

### ISSUE THREAD

**Issue by galeza** [FightPandemics/FightPandemics#934]
env: staging

1. Open Feed screen
2. Open Filters on the Feed screen
2. View Result button for Filters is not visible
![Feed Buttons](https://user-images.githubusercontent.com/21987083/86243065-fbfed000-bba5-11ea-8272-9be9d211f9de.gif)

**Comment by idjevm** [comment]
Closing this as this is a duplicate of #910. @adisen is currently working on a fix for these styles.

**Comment by idjevm** [comment]
@galeza if you see anything funky with styles, please refer it and add it to #910, all the buttons across the platform got messed up but are being fix at the moment.
