### ISSUE TITLE
Post description -Text is less then 120 signs -> no View More link

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#939]
The Picture Below displays a Post description text = 118, but view less,view more link

![image](https://user-images.githubusercontent.com/65972693/86265801-225a4680-bb79-11ea-9519-1616a6a29347.png)

**Comment by BMariscal** [comment]
hello @sheeba1  the limit is set to 120 characters, not letters. The example you posted has 214 characters.

**Comment by BMariscal** [comment]
@sheeba1  is this still an issue in mobile? Can you show me an example if so. Thanks!

**Comment by sheeba1** [comment]
@BMariscal ,Sent in flowdock screen shots of Post behaviour(View more) on Desktop version . would like to get your feed back .Thanks!

**Comment by sheeba1** [comment]
@BMariscal Thank you for all clarifications regarding the requirements.
@BMariscal @doheekim93 Tested on desktop and mobile. 'View more' starts after 123 characters. Let me know if any change is needed.

**Comment by doheekim93** [comment]
@sheeba1 Hey Sheeba, could you remind me -- is this still an issue or can we close it? Thanks!

**Comment by sheeba1** [comment]
@doheekim93  , you may close this one. thx!

**Comment by doheekim93** [comment]
@sheeba1 Thanks Sheeba!
