### ISSUE TITLE
Feeds -> Filters-> "Quit Filter & View Result" buttons visibility is fluctuating

### ISSUE THREAD

**Issue by rabbi08** [FightPandemics/FightPandemics#941]
1. Open "https://staging.fightpandemics.work"
2. Navigate to Feed -> Filters 

You will observe that 'Quit Filter' is displayed and when scroll around, "View Result" button shows up.
hence the the visibility of filter buttons is fluctuating.

Refer attached GIF.
https://share.getcloudapp.com/qGuKxXED

**Comment by idjevm** [comment]
This is a duplicate issue! Please review that there are not issues already open regarding to styles. This is being resolved by #910. I have mentioned this on slack as well :)

**Comment by rabbi08** [comment]
> This is a duplicate issue! Please review that there are not issues already open regarding to styles. This is being resolved by #910. I have mentioned this on slack as well :)

Oh, I did try to search, but can't find specific terms of the issue, looking for. hence I logged. and might missed the part on slack too.
