### ISSUE TITLE
Post comment feature- 'Comment/s' label  and number of comments should be present

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#954]
Expected Behaviour:

For the post comments, there should be a   label, **Comment/Comments** along with **number** of comments. It is applicable to posts on Feed and post details page as well. (only required for Desktop)

Current behaviour is shown below:
On Feed
![image](https://user-images.githubusercontent.com/65972693/86291162-737f3000-bba3-11ea-91f3-1c52ab070c0e.png)

Post details page 

![image](https://user-images.githubusercontent.com/65972693/86291305-a88b8280-bba3-11ea-9d57-cb2e695c9f3e.png)

**Comment by idjevm** [comment]
This was resolved with #1052! Thanks @sheeba1  for pointing this out :)

**Comment by sheeba1** [comment]
verified
