### ISSUE TITLE
Text Overlapping in login page while using android mobile devices

### ISSUE THREAD

**Issue by nivetheatha** [FightPandemics/FightPandemics#970]
-Go to sign in page .
-There is text overlapping while providing Email address.
![Screenshot_20200702-154256_Samsung Internet](https://user-images.githubusercontent.com/41587211/86404796-40f63580-bc7e-11ea-8dfa-6a00ef14c26a.jpg)

**Comment by omarzoghayyer** [comment]
Hi @nivetheatha - I was wondering what browser are you using? I am using chrome and it seems to have no issues with overlapping.

<img width="312" alt="Screen Shot 2020-07-03 at 5 35 14 PM" src="https://user-images.githubusercontent.com/49251966/86502030-905a6580-bd53-11ea-88b5-dbc3b2ed2c15.png">

**Comment by omarzoghayyer** [comment]
@nivetheatha I will open a PR and please let me know if that is enough padding from top.

**Comment by nivetheatha** [comment]
Try to give email...the text will overlap..I am using chrome browser .

**Comment by nivetheatha** [comment]
Hope it will resolve..kindly letme know..once you fixed the issue.
