### ISSUE TITLE
Update texts

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#973]
The following pages have texts that require changes
1. Nav Bar (for users _not_ signed in)
2. Nav Bar (for users signed in)
3. Home Page
4. Sign In Page
5. Join Now Page
6. Help Board Page

### Changes needed for each page:
**1. Nav Bar (for users _not_ signed in)**

Desktop:
Feed --> Help Board
Login --> Sign In
Register --> Join Now
<kbd>
    <img width="1440" alt="Screen Shot 2020-07-02 at 4 18 06 PM" src="https://user-images.githubusercontent.com/66695502/86412163-0394a680-bc84-11ea-8350-03d05461d782.png">
</kbd>

Mobile:
Login --> Sign In
Register --> Join Now
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86413010-cb8e6300-bc85-11ea-8240-284ba6a9230f.jpg">
</kbd>

\
**2. Nav Bar (for users _signed in_)**

Desktop:
Feed --> Help Board
<kbd>
    <img width="1440" alt="Screen Shot 2020-07-02 at 5 09 28 PM" src="https://user-images.githubusercontent.com/66695502/86413468-e6ada280-bc86-11ea-9901-dfa47928dc79.png">
</kbd>

Logout --> Sign Out
<kbd>
    <img width="321" alt="Screen Shot 2020-07-02 at 4 21 59 PM" src="https://user-images.githubusercontent.com/66695502/86413842-e661d700-bc87-11ea-9fdb-abb6ab3bc154.png">
</kbd>

Mobile:
Feed --> Help Board
Logout --> Sign Out
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86413541-1197f680-bc87-11ea-895e-174a4ad60d32.jpg">
</kbd>

\
**3. Home Page**

Desktop:
View Community Postings --> View Help Board
<kbd>
    <img width="700" alt="Screen Shot 2020-07-02 at 4 19 51 PM" src="https://user-images.githubusercontent.com/66695502/86414081-959eae00-bc88-11ea-80e2-c77c8cbc3d93.png">
</kbd>

Mobile:
View Community Postings --> View Help Board
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86414241-fd54f900-bc88-11ea-82a8-f15f7debcb99.jpg">
</kbd>

\
**4. Sign In Page**

Desktop:
Sign Up --> Join Now
Log In --> Sign In
<kbd>
    <img width="700" alt="Screen Shot 2020-07-02 at 4 20 19 PM" src="https://user-images.githubusercontent.com/66695502/86414382-5de43600-bc89-11ea-9e8e-ca7f21d663dc.png">
</kbd>

Mobile:
Sign Up --> Join Now
Log In --> Sign In
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86414441-8a984d80-bc89-11ea-9b59-70aebd4cc898.jpg">
</kbd>

\
**5. Join Now Page**

Desktop:
Sign Up --> Join Now (3 instances)
<kbd>
    <img width="700" alt="Screen Shot 2020-07-02 at 4 20 47 PM" src="https://user-images.githubusercontent.com/66695502/86414480-a0a60e00-bc89-11ea-9c64-a25d8063fb20.png">
</kbd>

Mobile:
Sign Up --> Join Now (3 instances)
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86414528-bfa4a000-bc89-11ea-8832-f4f825400773.jpg">
</kbd>

\
**6. Help Board Page**

Desktop:
Feed --> Help Board
<kbd>
    <img width="700" alt="Screen Shot 2020-07-02 at 4 11 25 PM" src="https://user-images.githubusercontent.com/66695502/86414560-dea33200-bc89-11ea-9021-7e45b077abb3.png">
</kbd>

Mobile:
Feed --> Help Board
<kbd>
    <img width="200" src="https://user-images.githubusercontent.com/66695502/86414586-f7abe300-bc89-11ea-97a2-c0fd4c173bb8.jpg">
</kbd>

**Comment by pthoma14** [comment]
Hi @doheekim93, 

I believe we spoke about these text changes awhile ago and I'm not sure how much of an impact it will be development-wise. 

For example, **Feed --> Help Board**, this name change would have to be updated and would propagate throughout the entire codebase for consistency. Which  you could imagine would be extremely timely and wouldn't make sense for Soft Launch. 

We need to verify if this is the case. Indira thoughts?

Cc: @indirabhowmick
