### ISSUE TITLE
Feed [Mobile - IOS] - Under "Sourced by FightPandemics" the blue dot for "US" is collapsing with "Community"

### ISSUE THREAD

**Issue by dabartlett** [FightPandemics/FightPandemics#978]
Under "Sourced by FightPandemics" the blue dot for "US" is collapsing with "Community"

Steps to Reproduce:

1 - Using Mobile IOS (I used Iphone 6s) > Be on Feed page (staging)
2 - scroll down to  "Sourced by FightPandemics"

Current Results: The blue dot for "US" is collapsing with "Community"
Expected: The blue dot should be moved below the community

*** Sorry can't paste image here*****

**Comment by idjevm** [comment]
You actually can paste an image, anyhow if you prefer to use a different tool, think of using this one -> https://www.getcloudapp.com/

**Comment by idjevm** [comment]
Also please refer to this page, in how to properly create issues. https://www.notion.so/fightpandemics/How-to-create-a-ticket-or-a-pull-request-on-GitHub-3ee2abb2d7f24b90ac35553dd0a117c4

**Comment by dabartlett** [comment]
![image](https://user-images.githubusercontent.com/67716598/86440388-30b27a80-bcbf-11ea-9491-79471dc641b6.png)

**Comment by dabartlett** [comment]
![image](https://user-images.githubusercontent.com/67716598/86440872-19c05800-bcc0-11ea-9c93-9a0caf40b724.png)

**Comment by idjevm** [comment]
please @dabartlett give a read to this document -> https://www.notion.so/fightpandemics/How-to-create-a-ticket-new-issue-on-GitHub-4405fe4ef57e4875b18fce25043d3d6a 

There are a few more things that we need to add to a new issue / labels, linking the project, assigning the proper PM...

**Comment by dabartlett** [comment]
Thank you, I will revise it again - I have been able to add the image for now, but I think a permission may be missing to edit and add the labels.
![image](https://user-images.githubusercontent.com/67716598/86441307-db776880-bcc0-11ea-9a9d-1d7dbc63f3d2.png)

**Comment by nivetheatha** [comment]
It's happening for android devices as well.

**Comment by rabbi08** [comment]
This issue also exist for Android, as the company location is overlapped by the company type as shown in below screenshot:

![image](https://user-images.githubusercontent.com/67168400/86827912-9193d700-c060-11ea-85da-5dc49192704f.png)

**Comment by galeza** [comment]
As per @ppagarawal request I'm adding this comment.
Please get a line space between the footer and the last text on the Feed page

**Comment by doheekim93** [comment]
@dabartlett @rabbi08 Hey guys, we had another issue for this (#701). Do you guys still see this issue?

**Comment by rabbi08** [comment]
This issue is fixed now. Please see #1366. There were various issues related to the UI. This one is last merged for post UI issue fix.

**Comment by doheekim93** [comment]
@rabbi08 Okay, I will close this issue for now. If you see this happen again, please either reopen this ticket or open a new one! Thanks :)
