### ISSUE TITLE
Home Page and Nav Bar: Add ID attribute for elements on these pages

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics#988]
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

Please also note, when assigning id attribute, to assign it to the area that encompasses the entire button or element.
Example: not just the text "Next", but the entire button (including Next and arrow symbol)
<img width="150" alt="Screen Shot 2020-07-03 at 6 43 37 PM" src="https://user-images.githubusercontent.com/66695502/86501298-437b8c80-bd5d-11ea-929d-bffb689f5fc0.png">

Why we need to assign unique IDs: [https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/#:~:text=You%20will%20need%20this%20'id,not%20contain%20any%20white%20space.](url)

## Home Page
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Request Help Button | HP_RE |
| 2. | Offer Help Button | HP_OF |
| 3. | "View Community Posting" Button | HP_VHB |

|Desktop |  Mobile |
| --- | --- |
| ![](https://user-images.githubusercontent.com/66695502/86500288-af59f700-bd55-11ea-94da-966c02f2eaf3.png)  |  ![](https://user-images.githubusercontent.com/66695502/86519452-6743de80-be00-11ea-974c-eb558b38f4aa.jpg) |

## Nav Bar
**For users _NOT_ signed in:**
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 4. | "About Us" Button | NAV_AU |
| 5. | "Feed" Button | NAV_HB |
| 6. | "Login" Button | NAV_SI |
| 7. | "Register" Button | NAV_JN |
| 8. | Feedback Icon | NAV_FDB |

|Desktop |  Mobile |
| --- | --- |
| ![](https://user-images.githubusercontent.com/66695502/86500726-bf270a80-bd58-11ea-92d5-60042a169370.png)  |  ![](https://user-images.githubusercontent.com/66695502/86519509-0d8fe400-be01-11ea-8153-2740347013d1.jpg) |

\
**For users signed in:**
_Please note:_ The buttons "About Us" and "Feed" here should have the same 'id' attributes as the above.
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 9. | "Add Organisation" Button | NAV_ADO |

|Desktop |  Mobile |
| --- | --- |
| ![](https://user-images.githubusercontent.com/66695502/86500827-82a7de80-bd59-11ea-89a1-a382b7e0fe9c.png)  |  ![](https://user-images.githubusercontent.com/66695502/86519513-1385c500-be01-11ea-9e90-c0a7c21a513b.jpg) |

**Comment by jyclam** [comment]
@doheekim93 Just wanted to confirm that the Login / Register button gets **one** tag: `NAV_SI`

**Comment by doheekim93** [comment]
@jyclam Hi, yes for the mobile version, Login/Register gets **one** tag NAV_SI (the text links to the sign in page only).

**Comment by jyclam** [comment]
Perfect, thanks for confirming.
