### ISSUE TITLE
Filter's "View Result" and "Quit Filters" button has the wrong styles.

### ISSUE THREAD

**Issue by silenceway** [FightPandemics/FightPandemics#994]
After changing the `BaseButton` from antd-mobile Button to antd Button, the "View Results" button in filters has issues with the background, and the "Quit Filters" button has issues in hover state.

Expected:

![Captura de Pantalla 2020-07-03 a la(s) 11 03 59 p  m](https://user-images.githubusercontent.com/877561/86504758-5c4a6900-bd82-11ea-9d42-40148d85e365.png)

Current:

![Captura de Pantalla 2020-07-03 a la(s) 11 04 50 p  m](https://user-images.githubusercontent.com/877561/86504764-666c6780-bd82-11ea-86fc-3a25ccf5b380.png)

It can be tested here: https://staging.fightpandemics.work/feed and open "Filters".

**Comment by idjevm** [comment]
This is already being resolved with #910. There was a PR that was merged that I sadly I didn't get on time to review and broke some styling across the platform.
