### ISSUE TITLE
Change in the hompepage verbiage

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#995]
Current text:
"A place to offer and receive help"

![image](https://user-images.githubusercontent.com/6276256/86508119-21384c00-bdfb-11ea-91c6-83b3f9ba4efb.png)

Desirable text on homepage:
"A place to offer and request help"

**Comment by ppagarawal** [comment]
So quick @idjevm ! :)

**Comment by idjevm** [comment]
Yeah I mean these are small fixes so they can be done quickly to let other engineers focus on a bit bigger tasks x)
