### ISSUE TITLE
Post tags,Post title, and description should be left aligned with name

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#999]
Issue: Feed Posts are not left aligned on staging(Refer Figure 1)
Expected Result:   Post tags,Post title, and description should be left aligned with name. It is applicable to Feed->Posts,post details for both desktop and mobile

Figure1:
![image](https://user-images.githubusercontent.com/65972693/86517805-95192b00-bde0-11ea-9f0c-f6f9026a64f6.png)

**Comment by dabartlett** [comment]
There are others places os mobile (IOS and android) where needs alignment: https://staging.fightpandemics.work/organization/5f04a4a9e2ee740013423bac

![image](https://user-images.githubusercontent.com/67716598/86813935-9abb7e80-c035-11ea-9242-a275e0f1e331.png)

https://staging.fightpandemics.work/
![image](https://user-images.githubusercontent.com/67716598/86814348-2503e280-c036-11ea-95bb-8b87801c1202.png)

https://staging.fightpandemics.work/offer-help
![image](https://user-images.githubusercontent.com/67716598/86814515-60061600-c036-11ea-9d61-700fb6b7e275.png)
